# coding: utf8


shortcuts = {
    "Google Chrome":{ #https://support.google.com/chrome/answer/157179?hl=en
        "Open a new window":"⌘n",
        "Open a new window in Incognito mode":"⌘t",
        "Open a new tab, and jump to it":"⌘t",
        "Reopen the last closed tab, and jump to it":"⌘⇧t",
        "Jump to the next open tab":"⌘⌥→",
        "Jump to the previous open tab":"⌘⌥←",
        "Jump to a specific tab (1-9)":"⌘[NUM]",
        "Jump to the last tab":"⌘9",
        "Open the previous page in your browsing history for the current tab":"⌘[ or ⌘←",
        "Open the next page in your browsing history for the current tab":"⌘] or ⌘→",
        "Close the current tab or pop-up":"⌘w",
        "Close all open tabs and the browser":"⌘⇧w",
        "Minimize the window":"⌘m",
        "Hide Google Chrome":"⌘h",
        "Quit Google Chrome":"⌘q",
        "Developer Tools":"⌘⌥i",
        "View Source":"⌘⌥U",
        "Always show toolbar in full screen":"⌘⇧F",
        "Show or hide the Bookmarks Bar":"⌘⇧b",
        "Open the Bookmark Manager:":"⌘⌥b",
        "Open the Settings page in a new tab":"⌘,",
        "Open the History page in a new tab":"⌘y",
        "Open the Downloads page in a new tab":"⌘⇧j",
        "Open the Find Bar to search the current page":"⌘f",
        "Jump to the next match to your Find Bar search":"⌘g",
        "Jump to the previous match to your Find Bar search":"⌘⇧g",
        "When Find Bar is open, search for selected text":"⌘e",
        "Open the Clear Browsing Data options":"⌘⇧⌫",
        "Log in as a different user or browse as a Guest":"⌘⇧m",
        "Search with your default search engine":"Type a search term + ↩",
        "Search using a different search engine":"Type a search engine name + Tab",
        "Add www. and .com to a site name, and open it in the current tab":"Type a site name + ⌃↩",
        "Add www. and .com to a site name, and open it in a new tab":"Type a site name + ⌃⇧↩",
        "Open the website in a new background tab":"Type a web address + ⌘↩",
        "Jump to the address bar":"⌘l",
        "Remove predictions from your address bar":"↓ to highlight + ⇧fn⌫",
        "Open options to print the current page":"⌘p",
        "Open options to save the current page":"⌘s",
        "Open the Page Setup dialog ":"⌘⌥p",
        "Email your current page":"⌘⇧i",
        "Reload your current page":"⌘r",
        "Reload your current page, ignoring cached content":"⌘⇧r",
        "Stop the page loading":"Esc",
        "Browse clickable items moving forward":"Tab",
        "Browse clickable items moving backward":"⇧Tab",
        "Open a file from your computer in Google Chrome":"⌘o + Select a file",
        "Display non-editable HTML source code for the current page":"⌘⌥u",
        "Open the JavaScript Console":"⌘⌥j",
        "Save your current webpage as a bookmark":"⌘d",
        "Save all open tabs as bookmarks in a new folder":"⌘⇧d",
        "Turn full-screen mode on or off":"⌘⌃f",
        "Make everything on the page bigger - zoom in":"⌘+",
        "Make everything on the page smaller - zoom out":"⌘-",
        "Return everything on the page to the default size":"⌘0",
        "Scroll down a webpage, a screen at a time":"Space",
        "Scroll up a webpage, a screen at a time":"⇧Space",
        "Search the web":"⌘⌥f",
        "Move your cursor to the front of the previous word in a text field ":"⌥←",
        "Move your cursor to the back of the next word in a text field":"⌥→",
        "Delete the previous word in a text field":"⌥⌫",
        "Open your home page in the current tab":"⌘⇧h",
        "Open a link in a current tab (mouse only)":"Drag a link to a tab",
        "Open a link in new background tab":"⌘ + Click a link",
        "Open a link, and jump to it":"⌘⇧ + Click a link",
        "Open a link, and jump to it (mouse only)":"Drag a link to a blank area of the tab strip",
        "Open a link in a new window":"⇧ + Click a link",
        "Open a tab in a new window (mouse only)":"Drag the tab out of the tab strip",
        "Move a tab to a current window (mouse only)":"Drag the tab into an existing window",
        "Return a tab to its original position":"Press Esc while dragging",
        "Save the current webpage as a bookmark":"Drag the web address to the Bookmarks Bar",
        "Download the target of a link":"⌥ + Click a link",
        "Display your browsing history":"Right-click Back ⇦ or Next ⇨, or click & hold Back ⇦ or Next ⇨",
        "Increase the window to full height":"Double-click a blank area of the tab strip"
    },
    "Reddit Enhancement Suite":{ #⇧/
        "Show help for keyboard shortcuts":"⇧/",
        "Launch RES command line":"/",
        "Launch filter command line":"H",
        "Move up to the previous link or comment in flat lists":"K",
        "Move down to the next link or comment in flat lists":"J",
        "Move to top of list (on link pages)":"⇧K",
        "Move to bottom of list (on link pages)":"⇧J",
        "Follow link (link pages only)":"↩",
        "Follow link in new tab (link pages only)":"⇧↩",
        "Toggle expando (image/text/video)":"X",
        "Increase the size of image(s) in the highlighted post area":"=",
        "Decrease the size of image(s) in the highlighted post area":"-",
        "Increase the size of image(s) in the highlighted post area (finer control)":"⇧=",
        "Decrease the size of image(s) in the highlighted post area (finer control)":"⇧-",
        "Removes the height restriction of image(s) in the highlighted post area":"⇧→",
        "Move the image(s) in the highlighted post area up":"⌃↑",
        "Move the image(s) in the highlighted post area down":"Move the image(s) in the highlighted post area down.",
        "Move the image(s) in the highlighted post area left":"⌃← ",
        "Move the image(s) in the highlighted post area right":"⌃→",
        "View the previous image of an inline gallery":"[",
        "View the next image of an inline gallery":"]",
        "Toggle 'show images' button":"⇧X",
        "View comments for link (shift opens them in a new tab)":"C",
        "View comments for link in a new tab":"⇧C",
        "View link and comments in new tabs.":"L",
        "View link and comments in new background tabs.":"⇧L",
        "Upvote selected link or comment (or remove the upvote).":"A",
        "Downvote selected link or comment (or remove the downvote).":"Z",
        "Upvote selected link or comment (but don't remove the upvote).":"⇧A",
        "Downvote selected link or comment (but don't remove the downvote).":"⇧Z",
        "Save the current post to your reddit account (not preserved if deleted or edited)":"S",
        "Save the current comment with RES (preserved locally)":"S",
        "Go to subreddit of selected link (link pages only)":"R",
        "Go to subreddit of selected link in a new tab (link pages only).":"⇧R ",
        "Enter 'goMode' (before using 'go to' shortcuts).":"G",
        "Go to inbox":"G then I",
        "Go to inbox in a new tab.":"G then ⇧I",
        "Go to modmail.":"G then M",
        "Go to modmail in a new tab.":"G then ⇧M",
        "Go to profile.":"G then U",
        "Go to profile in a new tab.":"G then ⇧U",
        "Go to front page.":"G then F ",
        "Go to /r/all.":"⌥A",
        "Go to subreddit front page.":"⇧F",
        "Go to a random subreddit.":"⌥Y",
        "Go to next page (link list pages only).":"G then N",
        "Go to previous page (link list pages only).":"G then P",
        "Focuses the cursor in the search box.":"⌥/",
    },
    "Sublime Text":{ #http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html
        "Command Pallete":"⌘⇧P",
        "Python Console":"⌃`",
        "Toggle Sidebar":"⌘K, ⌘B",
        "Toggle Full­scr­een":"⌃⌘F",
        "Toggle Dist­raction Free Mode":"⌃⇧⌘F",
        "Show scope in status bar":"⌃⇧P",
        "Cut line":"⌘X",
        "Insert line after":"⌘↩",
        "Insert line before":"⌘⇧↩",
        "Move line/selection up":"⌘⌃↑",
        "Move line/selection down":"⌘⌃↓",
        "Select line - Repeat to select next lines":"⌘L",
        "Select word - Repeat to select next occurrence":"⌘D",
        "Select all occurrences of current selection":"⌃⌘G",
        "Extra cursor on the line above":"⌃⇧↑",
        "Extra cursor on the line below":"⌃⇧↓",
        "Jump to closing parentheses Repeat to jump to opening parentheses":"⌃M",
        "Select all contents of the current parentheses":"⌃⇧M",
        "Move to beginning of line":"⌃A",
        "Move to beginning of text on line":"⌘Left",
        "Move to end of line":"⌃E, ⌘Right",
        "Delete from cursor to end of line":"⌘K, ⌘K",
        "Delete from cursor to start of line":"⌘K⌫",
        "Indent current line(s)":"⌘]",
        "Un-indent current line(s)":"⌘[",
        "Duplicate line(s)":"⌘⇧D",
        "Join line below to the end of the current line":"⌘J",
        "Comment/un-comment current line":"⌘/",
        "Block comment current selection":"⌘⌥/",
        "Redo, or repeat last keyboard shortcut command":"⌘Y",
        "Paste and indent correctly":"⌘⇧V",
        "Select next auto-complete suggestion":"⌃Space",
        "Soft undo; jumps to your last change before undoing change when repeated":"⌃U",
        "Column selection up":"⌃⇧↑",
        "Column selection down":"⌃⇧↓",
        "Wrap Selection in html tag":"⌃⇧W",
        "Delete current line of cursor":"⌃⇧K",
        "Quick-open files by name":"⌘P or ⌘T",
        "Goto symbol":"⌘R",
        "Goto line in current file":"⌃G",
        "Goto word in current file":"",
        "Find":"⌘F",
        "Replace":"⌘⌥F",
        "Find in files":"⌘⇧F",
        "Scroll down one page":"⌃V",
        "Center current line vertically in page":"⌃L",
        "Scroll to end of file":"⌘↓",
        "Scroll to start of file":"⌘↑",
        "Open last closed tab":"⌘⇧t",
        "Jump to tab in current group where num is 1-9":"⌘[NUM]",
        "Jump to 10th tab in current group":"⌘0",
        "Cycle left through tabs":"⌘⇧[",
        "Cycle right through tabs":"⌘⇧]",
        "Cycle up through recent tabs":"^Tab",
        "Cycle down through recent tabs":"⇧^Tab",
        "Revert view to single column":"⌘⌥1",
        "Split view into two columns":"⌘⌥2",
        "Split view into three columns":"⌘⌥3",
        "Split view into four columns":"⌘⌥4",
        "Set view to grid (4 groups)":"⌘⌥5",
        "Jump to group where num is 1-4":"⌃[NUM]",
        "Move file to specified group where num is 1-4":"⌃⇧[NUM]",
        "Toggle bookmark":"⌘F2",
        "Next bookmark":"F2",
        "Previous bookmark":"⇧F2",
        "Clear bookmarks":"⇧⌘F2",
        "Transform to Uppercase":"⌘K, ⌘U",
        "Clip text upwards / downwards":"⌘⌃↑, ⌘⌃↓",
    },
    "Vintage Sublime":{ #https://github.com/sublimehq/Vintage/blob/master/Default%20(OSX).sublime-keymap
        "Exit insert mode":"⌃c or Esc",
        "Exit visual mode":"⌃c or Esc",
        "Vi Cancel current action":"⌃c",
        "Move back to beginning of word":"⌥←",
        "Move back to end of word":"⌃←",
        "Move forward to beginning of word":"⌥→",
        "Move forward to end of word":"⌃→",
        "up":"k",
        "down":"j",
        "left":"h",
        "right":"l",
        "Move cursor to end of line":"⌘right",
        "Move cursor to first non-white space char":"⌘left",
        "Move to beginning of file":"⌘↑",
        "Move to end of file":"⌘↓",
        "page up":"⌃↑",
        "page down":"⌃↓",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "replace a single character":"r",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":"."
    },
    "Vim":{ #https://vim.rtorr.com/
        "open help for keyword":":help keyword",
        "open file":":o file",
        "save file as":":saveas file",
        "close current pane":":close",
        "open man page for word under the cursor":"K",
        "move cursor left":"h",
        "move cursor down":"j",
        "move cursor up":"k",
        "move cursor right":"l",
        "move to top of screen":"H",
        "move to middle of screen":"M",
        "move to bottom of screen":"L",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "jump backwards to the start of a word":"b",
        "jump backwards to the start of a word (words can contain punctuation)":"B",
        "move to matching character (default supported pairs: '()', '{}', '[]')":"%",
        "jump to the start of the line":"0",
        "jump to the first non-blank character of the line":"^",
        "jump to the end of the line":"$",
        "jump to the end of the line":"$",
        "jump to the last non-blank character of the line":"g_",
        "go to the first line of the document":"gg",
        "go to the last line of the document":"G",
        "go to line 5":"5G",
        "jump to next occurrence of character x":"fx",
        "jump to before next occurrence of character x":"tx",
        "jump to previous occurence of character x":"Fx",
        "jump to after previous occurence of character x":"Tx",
        "repeat previous f, t, F or T movement":";",
        "repeat previous f, t, F or T movement, backwards":",",
        "jump to next paragraph (or function/block, when editing code)":"}",
        "jump to previous paragraph (or function/block, when editing code)":"{",
        "center cursor on screen":"zz",
        "move back one full screen":"⌃b",
        "move forward one full screen":"⌃f",
        "move forward 1/2 a screen":"⌃d",
        "move back 1/2 a screen":"⌃u",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "insert (append) at the end of the word":"ea",
        "exit insert/visual mode":"Esc",
        "replace a single character":"r",
        "join line below to the current one":"J",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "transpose two letters (delete and paste)":"xp",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":".",
        #Marking text (visual mode) stopped at
        "start visual mode, mark lines, then do a command (like y-yank)":"v",
        "start linewise visual mode":"V",
        "visual - move to other end of marked area":"o",
        "start visual block mode":"^v",
        "visual - move to other corner of block":"O",
        "visual - mark a word":"aw",
        "visual - a block with ()":"ab",
        "visual - inner block with ()":"ib",
        "visual - inner block with {}":"iB",
        "shift text right":">",
        "shift text left":"<",
        "yank (copy) marked text":"y",
        "delete marked text":"d",
        "switch case":"~",
        "show registers content":":reg",
        "yank into register x":"\"xy",
        "paste contents of register x":"\"xp",
        "list of marks":":marks",
        "set current position for mark A":"ma",
        "jump to position of mark A":"'a",
        "yank text to position of mark A":"y`a",
        "record macro a":"qa",
        "stop recording macro":"q",
        "run macro a":"@a",
        "rerun last run macro":"@@",
        "yank (copy) a line":"yy",
        "yank (copy) 2 lines":"2yy",
        "yank (copy) the characters of the word from the cursor position to the start of the next word":"yw",
        "yank (copy) to end of line":"y$",
        "put (paste) the clipboard after cursor":"p",
        "put (paste) before cursor":"P",
        "delete (cut) a line":"dd",
        "delete (cut) 2 lines":"2dd",
        "delete (cut) the characters of the word from the cursor position to the start of the next word":"dw",
        "delete (cut) to the end of the line":"D",
        "delete (cut) to the end of the line":"d$",
        "delete (cut) character":"x",
        "write (save) the file, but don't exit":":w",
        "write out the current file using sudo":":w !sudo tee %",
        "write (save) and quit":":wq or :x or ZZ",
        "quit (fails if there are unsaved changes)":":q",
        "quit and throw away unsaved changes":":q! or ZQ",
        "write (save) and quit on all tabs":":wqa",
        "search for pattern in multiple files":":vimgrep /pattern/ {file}",
        "search - jump to the next match":":cn",
        "search - jump to the previous match":":cp",
        "search - open a window containing the list of matches":":copen",
        "edit a file in a new buffer":":e file",
        "go to the next buffer":":bnext or :bn",
        "go to the previous buffer":":bprev or :bp",
        "delete a buffer (close a file)":":bd",
        "list all open buffers":":ls",
        "open a file in a new buffer and split window":":sp file",
        "open a file in a new buffer and vertically split window":":vsp file",
        "split window":"Ctrl + ws",
        "switch windows":"Ctrl + ww",
        "quit a window":"Ctrl + wq",
        "split window vertically":"Ctrl + wv",
        "move cursor to the left window (vertical split)":"Ctrl + wh",
        "move cursor to the right window (vertical split)":"Ctrl + wl",
        "move cursor to the window below (horizontal split)":"Ctrl + wj",
        "move cursor to the window above (horizontal split)":"Ctrl + wk",
        "open a file in a new tab":":tabnew or :tabnew file",
        "move the current split window into its own tab":"Ctrl + wT",
        "move to the next tab":"gt or :tabnext or :tabn",
        "move to the previous tab":"gT or :tabprev or :tabp",
        "move to tab number #":"#gt",
        "move current tab to the #th position (indexed from 0)":":tabmove #",
        "close the current tab and all its windows":":tabclose or :tabc",
        "close all tabs except for the current one":":tabonly or :tabo",
        "command - run the command on all tabs (e.g. :tabdo q - closes all opened tabs)":":tabdo"
    },
    "iTerm2":{

    },
    "Mac OSX":{

    },
    "Firefox":{

    }
}

# test = {
#     "chrome":{
#         "Open a new window":"⌘ + n",
#         "Open a new window in Incognito mode":"⌘ + t",
#     },
#     "RES":{
#         "Show help for keyboard shortcuts":"shift + /",
#         "Launch RES command line.":"/",
#         "Move up in posts":"j"
#     }
# }

import collections

def convert(data):
    if isinstance(data, basestring):
        return data.decode('utf-8').strip()
    elif isinstance(data, collections.Mapping):
        return dict(map(convert, data.iteritems()))
    elif isinstance(data, collections.Iterable):
        return type(data)(map(convert, data))
    else:
        return data

shortcuts = convert(shortcuts)


# print test
# print convert(test)


