# coding: utf8


shortcuts = {
    "Google Chrome":{ #https://support.google.com/chrome/answer/157179?hl=en
        "Open a new window":"⌘n",
        "Open a new window in Incognito mode":"⌘t",
        "Open a new tab, and jump to it":"⌘t",
        "Reopen the last closed tab, and jump to it":"⌘⇧t",
        "Jump to the next open tab":"⌘⌥→",
        "Jump to the previous open tab":"⌘⌥←",
        "Jump to a specific tab (1-9)":"⌘[NUM]",
        "Jump to the last tab":"⌘9",
        "Open the previous page in your browsing history for the current tab":"⌘[ or ⌘←",
        "Open the next page in your browsing history for the current tab":"⌘] or ⌘→",
        "Close the current tab or pop-up":"⌘w",
        "Close all open tabs and the browser":"⌘⇧w",
        "Minimize the window":"⌘m",
        "Hide Google Chrome":"⌘h",
        "Quit Google Chrome":"⌘q",
        "Developer Tools":"⌘⌥i",
        "View Source":"⌘⌥U",
        "Always show toolbar in full screen":"⌘⇧F",
        "Show or hide the Bookmarks Bar":"⌘⇧b",
        "Open the Bookmark Manager:":"⌘⌥b",
        "Open the Settings page in a new tab":"⌘,",
        "Open the History page in a new tab":"⌘y",
        "Open the Downloads page in a new tab":"⌘⇧j",
        "Open the Find Bar to search the current page":"⌘f",
        "Jump to the next match to your Find Bar search":"⌘g",
        "Jump to the previous match to your Find Bar search":"⌘⇧g",
        "When Find Bar is open, search for selected text":"⌘e",
        "Open the Clear Browsing Data options":"⌘⇧⌫",
        "Log in as a different user or browse as a Guest":"⌘⇧m",
        "Search with your default search engine":"Type a search term + ↩",
        "Search using a different search engine":"Type a search engine name + Tab",
        "Add www. and .com to a site name, and open it in the current tab":"Type a site name + ⌃↩",
        "Add www. and .com to a site name, and open it in a new tab":"Type a site name + ⌃⇧↩",
        "Open the website in a new background tab":"Type a web address + ⌘↩",
        "Jump to the address bar":"⌘l",
        "Remove predictions from your address bar":"↓ to highlight + ⇧fn⌫",
        "Open options to print the current page":"⌘p",
        "Open options to save the current page":"⌘s",
        "Open the Page Setup dialog ":"⌘⌥p",
        "Email your current page":"⌘⇧i",
        "Reload your current page":"⌘r",
        "Reload your current page, ignoring cached content":"⌘⇧r",
        "Stop the page loading":"Esc",
        "Browse clickable items moving forward":"Tab",
        "Browse clickable items moving backward":"⇧Tab",
        "Open a file from your computer in Google Chrome":"⌘o + Select a file",
        "Display non-editable HTML source code for the current page":"⌘⌥u",
        "Open the JavaScript Console":"⌘⌥j",
        "Save your current webpage as a bookmark":"⌘d",
        "Save all open tabs as bookmarks in a new folder":"⌘⇧d",
        "Turn full-screen mode on or off":"⌘⌃f",
        "Make everything on the page bigger - zoom in":"⌘+",
        "Make everything on the page smaller - zoom out":"⌘-",
        "Return everything on the page to the default size":"⌘0",
        "Scroll down a webpage, a screen at a time":"Space",
        "Scroll up a webpage, a screen at a time":"⇧Space",
        "Search the web":"⌘⌥f",
        "Move your cursor to the front of the previous word in a text field ":"⌥←",
        "Move your cursor to the back of the next word in a text field":"⌥→",
        "Delete the previous word in a text field":"⌥⌫",
        "Open your home page in the current tab":"⌘⇧h",
        "Open a link in a current tab (mouse only)":"Drag a link to a tab",
        "Open a link in new background tab":"⌘ + Click a link",
        "Open a link, and jump to it":"⌘⇧ + Click a link",
        "Open a link, and jump to it (mouse only)":"Drag a link to a blank area of the tab strip",
        "Open a link in a new window":"⇧ + Click a link",
        "Open a tab in a new window (mouse only)":"Drag the tab out of the tab strip",
        "Move a tab to a current window (mouse only)":"Drag the tab into an existing window",
        "Return a tab to its original position":"Press Esc while dragging",
        "Save the current webpage as a bookmark":"Drag the web address to the Bookmarks Bar",
        "Download the target of a link":"⌥ + Click a link",
        "Display your browsing history":"Right-click Back ⇦ or Next ⇨, or click & hold Back ⇦ or Next ⇨",
        "Increase the window to full height":"Double-click a blank area of the tab strip"
    },
    "Reddit Enhancement Suite":{ #⇧/
        "Show help for keyboard shortcuts":"⇧/",
        "Launch RES command line":"/",
        "Launch filter command line":"H",
        "Move up to the previous link or comment in flat lists":"K",
        "Move down to the next link or comment in flat lists":"J",
        "Move to top of list (on link pages)":"⇧K",
        "Move to bottom of list (on link pages)":"⇧J",
        "Follow link (link pages only)":"↩",
        "Follow link in new tab (link pages only)":"⇧↩",
        "Toggle expando (image/text/video)":"X",
        "Increase the size of image(s) in the highlighted post area":"=",
        "Decrease the size of image(s) in the highlighted post area":"-",
        "Increase the size of image(s) in the highlighted post area (finer control)":"⇧=",
        "Decrease the size of image(s) in the highlighted post area (finer control)":"⇧-",
        "Removes the height restriction of image(s) in the highlighted post area":"⇧→",
        "Move the image(s) in the highlighted post area up":"⌃↑",
        "Move the image(s) in the highlighted post area down":"Move the image(s) in the highlighted post area down.",
        "Move the image(s) in the highlighted post area left":"⌃← ",
        "Move the image(s) in the highlighted post area right":"⌃→",
        "View the previous image of an inline gallery":"[",
        "View the next image of an inline gallery":"]",
        "Toggle 'show images' button":"⇧X",
        "View comments for link (⇧ opens them in a new tab)":"C",
        "View comments for link in a new tab":"⇧C",
        "View link and comments in new tabs.":"L",
        "View link and comments in new background tabs.":"⇧L",
        "Upvote selected link or comment (or remove the upvote).":"A",
        "Downvote selected link or comment (or remove the downvote).":"Z",
        "Upvote selected link or comment (but don't remove the upvote).":"⇧A",
        "Downvote selected link or comment (but don't remove the downvote).":"⇧Z",
        "Save the current post to your reddit account (not preserved if deleted or edited)":"S",
        "Save the current comment with RES (preserved locally)":"S",
        "Go to subreddit of selected link (link pages only)":"R",
        "Go to subreddit of selected link in a new tab (link pages only).":"⇧R ",
        "Enter 'goMode' (before using 'go to' shortcuts).":"G",
        "Go to inbox":"G then I",
        "Go to inbox in a new tab.":"G then ⇧I",
        "Go to modmail.":"G then M",
        "Go to modmail in a new tab.":"G then ⇧M",
        "Go to profile.":"G then U",
        "Go to profile in a new tab.":"G then ⇧U",
        "Go to front page.":"G then F ",
        "Go to /r/all.":"⌥A",
        "Go to subreddit front page.":"⇧F",
        "Go to a random subreddit.":"⌥Y",
        "Go to next page (link list pages only).":"G then N",
        "Go to previous page (link list pages only).":"G then P",
        "Focuses the cursor in the search box.":"⌥/",
    },
    "Sublime Text":{ #http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html
        "Command Pallete":"⌘⇧P",
        "Python Console":"⌃`",
        "Toggle Sidebar":"⌘K, ⌘B",
        "Toggle Full­scr­een":"⌃⌘F",
        "Toggle Dist­raction Free Mode":"⌃⇧⌘F",
        "Show scope in status bar":"⌃⇧P",
        "Cut line":"⌘X",
        "Insert line after":"⌘↩",
        "Insert line before":"⌘⇧↩",
        "Move line/selection up":"⌘⌃↑",
        "Move line/selection down":"⌘⌃↓",
        "Select line - Repeat to select next lines":"⌘L",
        "Select word - Repeat to select next occurrence":"⌘D",
        "Select all occurrences of current selection":"⌃⌘G",
        "Extra cursor on the line above":"⌃⇧↑",
        "Extra cursor on the line below":"⌃⇧↓",
        "Jump to closing parentheses Repeat to jump to opening parentheses":"⌃M",
        "Select all contents of the current parentheses":"⌃⇧M",
        "Move to beginning of line":"⌃A",
        "Move to beginning of text on line":"⌘Left",
        "Move to end of line":"⌃E, ⌘Right",
        "Delete from cursor to end of line":"⌘K, ⌘K",
        "Delete from cursor to start of line":"⌘K⌫",
        "Indent current line(s)":"⌘]",
        "Un-indent current line(s)":"⌘[",
        "Duplicate line(s)":"⌘⇧D",
        "Join line below to the end of the current line":"⌘J",
        "Comment/un-comment current line":"⌘/",
        "Block comment current selection":"⌘⌥/",
        "Redo, or repeat last keyboard shortcut command":"⌘Y",
        "Paste and indent correctly":"⌘⇧V",
        "Select next auto-complete suggestion":"⌃Space",
        "Soft undo; jumps to your last change before undoing change when repeated":"⌃U",
        "Column selection up":"⌃⇧↑",
        "Column selection down":"⌃⇧↓",
        "Wrap Selection in html tag":"⌃⇧W",
        "Delete current line of cursor":"⌃⇧K",
        "Quick-open files by name":"⌘P or ⌘T",
        "Goto symbol":"⌘R",
        "Goto line in current file":"⌃G",
        "Goto word in current file":"",
        "Find":"⌘F",
        "Replace":"⌘⌥F",
        "Find in files":"⌘⇧F",
        "Scroll down one page":"⌃V",
        "Center current line vertically in page":"⌃L",
        "Scroll to end of file":"⌘↓",
        "Scroll to start of file":"⌘↑",
        "Open last closed tab":"⌘⇧t",
        "Jump to tab in current group where num is 1-9":"⌘[NUM]",
        "Jump to 10th tab in current group":"⌘0",
        "Cycle left through tabs":"⌘⇧[",
        "Cycle right through tabs":"⌘⇧]",
        "Cycle up through recent tabs":"^Tab",
        "Cycle down through recent tabs":"⇧^Tab",
        "Revert view to single column":"⌘⌥1",
        "Split view into two columns":"⌘⌥2",
        "Split view into three columns":"⌘⌥3",
        "Split view into four columns":"⌘⌥4",
        "Set view to grid (4 groups)":"⌘⌥5",
        "Jump to group where num is 1-4":"⌃[NUM]",
        "Move file to specified group where num is 1-4":"⌃⇧[NUM]",
        "Toggle bookmark":"⌘F2",
        "Next bookmark":"F2",
        "Previous bookmark":"⇧F2",
        "Clear bookmarks":"⇧⌘F2",
        "Transform to Uppercase":"⌘K, ⌘U",
        "Clip text upwards / downwards":"⌘⌃↑, ⌘⌃↓",
    },
    "Vintage Sublime":{ #https://github.com/sublimehq/Vintage/blob/master/Default%20(OSX).sublime-keymap
        "Exit insert mode":"⌃c or Esc",
        "Exit visual mode":"⌃c or Esc",
        "Vi Cancel current action":"⌃c",
        "Move back to beginning of word":"⌥←",
        "Move back to end of word":"⌃←",
        "Move forward to beginning of word":"⌥→",
        "Move forward to end of word":"⌃→",
        "up":"k",
        "down":"j",
        "left":"h",
        "right":"l",
        "Move cursor to end of line":"⌘right",
        "Move cursor to first non-white space char":"⌘left",
        "Move to beginning of file":"⌘↑",
        "Move to end of file":"⌘↓",
        "page up":"⌃↑",
        "page down":"⌃↓",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "replace a single character":"r",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":"."
    },
    "Vim":{ #https://vim.rtorr.com/
        "open help for keyword":":help keyword",
        "open file":":o file",
        "save file as":":saveas file",
        "close current pane":":close",
        "open man page for word under the cursor":"K",
        "move cursor left":"h",
        "move cursor down":"j",
        "move cursor up":"k",
        "move cursor right":"l",
        "move to top of screen":"H",
        "move to middle of screen":"M",
        "move to bottom of screen":"L",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "jump backwards to the start of a word":"b",
        "jump backwards to the start of a word (words can contain punctuation)":"B",
        "move to matching character (default supported pairs: '()', '{}', '[]')":"%",
        "jump to the start of the line":"0",
        "jump to the first non-blank character of the line":"^",
        "jump to the end of the line":"$",
        "jump to the end of the line":"$",
        "jump to the last non-blank character of the line":"g_",
        "go to the first line of the document":"gg",
        "go to the last line of the document":"G",
        "go to line 5":"5G",
        "jump to next occurrence of character x":"fx",
        "jump to before next occurrence of character x":"tx",
        "jump to previous occurence of character x":"Fx",
        "jump to after previous occurence of character x":"Tx",
        "repeat previous f, t, F or T movement":";",
        "repeat previous f, t, F or T movement, backwards":",",
        "jump to next paragraph (or function/block, when editing code)":"}",
        "jump to previous paragraph (or function/block, when editing code)":"{",
        "center cursor on screen":"zz",
        "move back one full screen":"⌃b",
        "move forward one full screen":"⌃f",
        "move forward 1/2 a screen":"⌃d",
        "move back 1/2 a screen":"⌃u",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "insert (append) at the end of the word":"ea",
        "exit insert/visual mode":"Esc",
        "replace a single character":"r",
        "join line below to the current one":"J",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "transpose two letters (delete and paste)":"xp",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":".",
        #Marking text (visual mode) stopped at
        "start visual mode, mark lines, then do a command (like y-yank)":"v",
        "start linewise visual mode":"V",
        "visual - move to other end of marked area":"o",
        "start visual block mode":"^v",
        "visual - move to other corner of block":"O",
        "visual - mark a word":"aw",
        "visual - a block with ()":"ab",
        "visual - inner block with ()":"ib",
        "visual - inner block with {}":"iB",
        "shift text right":">",
        "shift text left":"<",
        "yank (copy) marked text":"y",
        "delete marked text":"d",
        "switch case":"~",
        "show registers content":":reg",
        "yank into register x":"\"xy",
        "paste contents of register x":"\"xp",
        "list of marks":":marks",
        "set current position for mark A":"ma",
        "jump to position of mark A":"'a",
        "yank text to position of mark A":"y`a",
        "record macro a":"qa",
        "stop recording macro":"q",
        "run macro a":"@a",
        "rerun last run macro":"@@",
        "yank (copy) a line":"yy",
        "yank (copy) 2 lines":"2yy",
        "yank (copy) the characters of the word from the cursor position to the start of the next word":"yw",
        "yank (copy) to end of line":"y$",
        "put (paste) the clipboard after cursor":"p",
        "put (paste) before cursor":"P",
        "delete (cut) a line":"dd",
        "delete (cut) 2 lines":"2dd",
        "delete (cut) the characters of the word from the cursor position to the start of the next word":"dw",
        "delete (cut) to the end of the line":"D",
        "delete (cut) to the end of the line":"d$",
        "delete (cut) character":"x",
        "write (save) the file, but don't exit":":w",
        "write out the current file using sudo":":w !sudo tee %",
        "write (save) and quit":":wq or :x or ZZ",
        "quit (fails if there are unsaved changes)":":q",
        "quit and throw away unsaved changes":":q! or ZQ",
        "write (save) and quit on all tabs":":wqa",
        "search for pattern in multiple files":":vimgrep /pattern/ {file}",
        "search - jump to the next match":":cn",
        "search - jump to the previous match":":cp",
        "search - open a window containing the list of matches":":copen",
        "edit a file in a new buffer":":e file",
        "go to the next buffer":":bnext or :bn",
        "go to the previous buffer":":bprev or :bp",
        "delete a buffer (close a file)":":bd",
        "list all open buffers":":ls",
        "open a file in a new buffer and split window":":sp file",
        "open a file in a new buffer and vertically split window":":vsp file",
        "split window":"Ctrl + ws",
        "switch windows":"Ctrl + ww",
        "quit a window":"Ctrl + wq",
        "split window vertically":"Ctrl + wv",
        "move cursor to the left window (vertical split)":"Ctrl + wh",
        "move cursor to the right window (vertical split)":"Ctrl + wl",
        "move cursor to the window below (horizontal split)":"Ctrl + wj",
        "move cursor to the window above (horizontal split)":"Ctrl + wk",
        "open a file in a new tab":":tabnew or :tabnew file",
        "move the current split window into its own tab":"Ctrl + wT",
        "move to the next tab":"gt or :tabnext or :tabn",
        "move to the previous tab":"gT or :tabprev or :tabp",
        "move to tab number #":"#gt",
        "move current tab to the #th position (indexed from 0)":":tabmove #",
        "close the current tab and all its windows":":tabclose or :tabc",
        "close all tabs except for the current one":":tabonly or :tabo",
        "command - run the command on all tabs (e.g. :tabdo q - closes all opened tabs)":":tabdo"
    },
    "iTerm2":{
        #factory default key mappings in preferences
        #http://www.ifdattic.com/iterm-shortcut-keys/
        "New Tab":"⌘T",
        "Previous Tab":"⌘←",
        "Next Tab":"⌘→",
        "Close Tab":"⌘w",
        "Move Tab Right":"⇧⌘→",
        "Move Tab Left":"⇧⌘←",
        "Split Vertically with Current Profile":"⌘D",
        "Split Horizontally with Current Profile":"⇧⌘D",
        "Next Pane":"⌘]",
        "Previous Pane":"⌘[",
        "Select Pane Above":"⌥⌘↑",
        "Select Pane Below":"⌥⌘↓",
        "Select Pane Left":"⌥⌘←",
        "Select Pane Right":"⌥⌘→",
        "Clear Window":"^L",
        "Clear buffer":"⌘K",
        "Scroll One Line Up":"⌘↑",
        "Scroll One Line Down":"⌘↓",
        "Find":"⌘F",
        "Make Text Bigger":"⌘+",
        "Make Text Normal Size":"⌘0",
        "Make Text Smaller":"⌘-",
        "Go Left One Word":"⌥←",
        "Go Right One Word":"⌥→",
        "Clear line":"^u",
        "Highlight cursour":"⌘/",
        "Scroll To Top":"⌘Home",
        "Scroll To End":"⌘End",
        "Scroll One Page Up":"⌘Page Up or ⇧Page Up",
        "Scroll One Page Down":"⌘Page Down or ⇧Page Down",
    },
    "zshell":{
        #https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet
        "Create a new tab in the current directory (macOS - requires enabling access for assistive devices under System Preferences).":"tabs",
        "Create a new directory and change to it, will create intermediate directories as required.":"take",
        "Extract an archive (supported types: tar.{bz2,gz,xz,lzma}, bz2, rar, gz, tar, tbz2, tgz, zip, Z, 7z).":"x / extract",
        "Get a list of the top 20 commands and how many times they have been run.":"zsh_stats",
        "Uninstall Oh-my-zsh.":"uninstall_oh_my_zsh",
        "Upgrade Oh-my-zsh.":"upgrade_oh_my_zsh",
        "Uptake new changes":"source ~/.zshrc",
        "list all aliases":"alias",
        "cd ..":"..",
        "cd ../..":"...",
        "cd ../../..":"....",
        "cd ../../../..":".....",
        "cd /":"/",
        "cd ~":"~",
        "switch to directory number n (2-9)":"cd +n",
        "tab-completeion ls":"ls (tab)",
        "tab-completeion cap":"cap (tab)",
        "tab-completeion rake":"rake (tab)",
        "tab-completeion ssh":"ssh (tab)",
        "tab-completeion sudo unmount":"sudo unmount(tab)",
        "tab-completeion kill":"kill (tab)",
        "tab-completeion unrar":"unrar (tab)",
        "Dynamic access to current branch name with the current_branch function":"git pull origin $(current_branch)",
        "Dynamic access to current branch name with the current_branch function":"grb publish $(current_branch) origin",
        "git":"g",
        "git add":"ga",
        "git add --all":"gaa",
        "git add --patch":"gapa",
        "git branch":"gb",
        "git branch -a":"gba",
        "git branch -d":"gbd",
        "git blame -b -w":"gbl",
        "git branch --no-merged":"gbnm",
        "git branch --remote":"gbr",
        "git bisect":"gbs",
        "git bisect bad":"gbsb",
        "git bisect good":"gbsg",
        "git bisect reset":"gbsr",
        "git bisect start":"gbss",
        "git commit -v":"gc",
        "git commit -v --amend":"gc!",
        "git commit -v -a":"gca",
        "git commit -v -a --amend":"gca!",
        "git commit -v -a --no-edit --amend":"gcan!",
        "git commit -v -a -s --no-edit --amend":"gcans!",
        "git commit -a -m":"gcam",
        "git commit -s -m":"gcsm",
        "git checkout -b":"gcb",
        "git config --list":"gcf",
        "git clone --recursive":"gcl",
        "git clean -fd":"gclean",
        "git reset --hard ^^ git clean dfx":"gpristine",
        "git checkout master":"gcm",
        "git checkout develop":"gcd",
        "git commit -m":"gcmsg",
        "git checkout":"gco",
        "git shortlog -sn":"gcount",
        "git cherry-pick":"gcp",
        "git cherry-pick --abort":"gcpa",
        "git cherry-pick --continue":"gcpc",
        "git commit -S":"gcs",
        "git diff":"gd",
        "git diff --cached":"gdca",
        "git describe --tags `git rev-list --tags --max-count=1`":"gdct",
        "git diff-tree --no-commit-id --name-only -r":"gdt",
        "git diff --word-diff":"gdw",
        "git fetch":"gf",
        "git fetch --all --prune":"gfa",
        "git fetch origin":"gfo",
        "git gui citool":"gg",
        "git gui citool --amend":"gga",
        "git pull origin $(current_branch) && git push origin $(current_branch)":"ggpnp",
        "git pull origin $(current_branch)":"ggpull",
        "git pull origin $(current_branch)":"ggl",
        "git pull --rebase origin $(current_branch)":"ggpur",
        "git pull upstream master":"glum",
        "git push origin $(current_branch)":"ggpush",
        "git push origin $(current_branch)":"ggp",
        "git branch --set-upstream-to=origin/$(current_branch)":"ggsup",
        "git update-index --assume-unchanged":"gignore",
        "git ls-files -v | grep \"^[[:lower:]]\"":"gignored",
        "git svn dcommit && git push github master:svntrunk":"git-svn-dcommit-push",
        "gitk --all --branches":"gk",
        "git pull":"gl",
        "git log --stat --max-count = 10":"glg",
        "git log --graph --max-count = 10":"glgg",
        "git log --graph --decorate --all":"glgga",
        "git log --oneline --decorate --color":"glo",
        "git log --oneline --decorate --color --graph":"glog",
        "_git_log_prettily (git log --pretty=$1)":"glp",
        "git merge":"gm",
        "git mergetool --no-prompt":"gmt",
        "git push":"gp",
        "git push origin --all && git push origin --tags":"gpoat",
        "git remote":"gr",
        "git rebase --abort":"grba",
        "git rebase --continue":"grbc",
        "git rebase --skip":"grbs",
        "git rebase -i":"grbi",
        "git reset HEAD":"grh",
        "git reset HEAD --hard":"grhh",
        "git remote rename":"grmv",
        "git remote remove":"grrm",
        "git remote set-url":"grset",
        "cd $(git rev-parse --show-toplevel || echo \".\")":"grt",
        "git remote update":"grup",
        "git remote -v":"grv",
        "git svn dcommit":"gsd",
        "git show --pretty = short --show-signature":"gsps",
        "git svn rebase":"gsr",
        "git status -s":"gss",
        "git status":"gst",
        "git stash save":"gsta",
        "git stash apply":"gstaa",
        "git stash drop":"gstd",
        "git stash list":"gstl",
        "git stash pop":"gstp",
        "git stash show --text":"gsts",
        "git tag -s":"gts",
        "git update-index --no-assume-unchanged":"gunignore",
        "git log -n 1 | grep -q -c \"--wip--\" && git reset HEAD~1":"gunwip",
        "git pull --rebase":"gup",
        "git verify-tag":"gvt",
        "git whatchanged -p --abbrev-commit --pretty = medium":"gwch",
        "git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m \"--wip--\"":"gwip",
        "(When using sublime plugin) Open current directory in Sublime Text 2/3":"stt",
        "(When using vi-mode plugin) Edit current command line in Vim":"v",
        "Symfony2 - php ./app/console":"sf",
        "Symfony2 - php app/console cache:clear":"sfcl",
        "Symfony2 - sf debug:container":"sfcontainer",
        "Symfony2 - sf cache:warmup":"sfcw",
        "Symfony2 - sf generate:bundle":"sfgb",
        "Symfony2 - sf debug:router":"sfroute",
        "Symfony2 - sf server:run -vvv":"sfsr",
        "tmux attach -t":"ta",
        "tmux attach -d -t":'tad',
        "tmux new-session -s":"ts",
        "tmux list-sessions":"tl",
        "tmux kill-server":"tksv",
        "tmux kill-session -t":"tkss",
        "show the status of the NAME process":"sc-status NAME",
        "show the NAME systemd .service file" :"sc-show NAME",
        "start the NAME process" : "sc-start NAME",
        "stop the NAME process" : "sc-stop NAME",
        "restart the NAME process" : "sc-restart NAME",
        "enable the NAME process to start at boot" : "sc-enable NAME",
        "disable the NAME process at boot" : "sc-disable NAME",
    },
    "Mac OSX":{
        "application preferences":"⌘,",
        "toggle full screen":"⌘^f"
    },
    "Firefox":{

    },
    "Youtube.com":{
        #http://www.hongkiat.com/blog/useful-youtube-keyboard-shortcuts-to-know/
        #shift + /
        "Pause/Play video (player)":"Spacebar",
        "Pause/Play video":"k",
        "Keyboard shortcuts":"⇧/",
        "Previous video":"⇧p",
        "Next video":"⇧n",
        "Rewind 10 seconds":"j",
        "Fastfoward 10 seconds":"l",
        "Toggle Mute":"m",
        "Seek backwards by smallest amount possible, when video is paused":",",
        "Seek forwards by smallest amount possible, when video is paused":".",
        "Decrease playback rate":"< (^,)",
        "Increase playback rate":"> (^.)",
        "Toggle full screen":"f",
        "Seek backwards by 5 seconds (player)":"←",
        "Seek forwards by 5 seconds":"→",
        "Increase the volume by 5%":"UP",
        "Decrease the volume by 5%":"DOWN",
        "Close the current dialog or similar dialogs (share panel)":"ESCAPE",
        "Seek to the beginning of the video":"HOME",
        "Seek to the end of the video":"END",
        "If the video supports captions, toggle captions ON/OFF":"c",
        "Rotate through different text opacity levels":"o",
        "Rotate through different window opacity levels":"w",
        "Rotate through font sizes (increasing)":"+",
        "Rotate through font sizes (decreasing)":"-",
        "Seek to specific point in the video (7 advances to 70% of duration)":"0..9",
        "When viewing a spherical video, pan up":"w",
        "When viewing a spherical video, pan left":"a",

    },
    "AutoMute Chrome extension":{
        "Toggle mute current app":"⌥⇧m",
        "Mute all tabs":"⌥⇧l",
        "Mute other tabs":"⌥⇧o"
    },
    "GitHub.com":{
    #https://help.github.com/articles/using-keyboard-shortcuts/
        "Focus the search bar":"s",
        "Go to your notifications":"g then n",
        "Go to the Code tab":"g then c",
        "Go to the Issues tab":"g then i",
        "Go to the Pull reuests tab":"g then p",
        "Go to the Projects tab":"g then b",
        "Go to the Wiki tab":"g then w",
        "Code editing - Start searching in file editor":"⌘f",
        "Code editing - Find next":"⌘g",
        "Code editing - Find previous":"⌘⇧g",
        "Code editing - Replace":"⌘⌥f",
        "Code editing - Replace All":"⇧⌘⌥f",
        "Code editing - Jump to line":"⌥g",
        "Code editing - Undo":"⌘z",
        "Code editing - Redo":"⌘y",
        "Code browsing - Activates the file finder":"t",
        "Code browsing - Jump to a line in your code":"l",
        "Code browsing - Switch to a new branch or tag":"w",
        "Code browsing - Expand a URL to its canonical form":"y",
        "Code browsing - Show or hide comments on diffs":"i",
        "Code browsing - Open blame view":"b",
        "Comments - Markdown to bold text":"⌘b",
        "Comments - Markdown to italicize text":"⌘i",
        "Comments - Markdown to create a link":"⌘k",
        "Comments - Toggles between the Write and Preview comment tabs":"⌘⇧p",
        "Comments - Submits a comment":"^⏎",
        "Issue/PR lists - Create an issue":"c",
        "Issue/PR lists - Focus the issues search bar":"/",
        "Issue/PR lists - Filter by author":"u",
        "Issue/PR lists - Filter by or edit labels":"l",
        "Issue/PR lists - Filter by or edit milestones":"m",
        "Issue/PR lists - Filter by or edit assignee":"a",
        "Issue/PR lists - Quote the selected text in your reply":"r",
        "Issue/PR lists - Open issue":"o or ⏎",
        "Issue/PR - Request a reviewer":"q",
        "Issue/PR - Set a milestone":"m",
        "Issue/PR - Apply a label":"l",
        "Issue/PR - Set an assignee":"a",
        "PR changes - Open the list of commits in the PR":"c",
        "PR changes - Open the list of changed files in the pull request":"t",
        "PR changes - Move selection down in the list":"j",
        "PR changes - Move selection up in the list":"k",
        "Notifications - Mark as read":"e or l or y",
        "Notifications - Mute thread":"⇧m",
        "Network Graph - Scroll left":"← or h",
        "Network Graph - Scroll right":"→ or l",
        "Network Graph - Scroll up":"↑ or k",
        "Network Graph - Scroll down":"↓ or j",
        "Network Graph - Scroll all the way left":"⇧← or ⇧h",
        "Network Graph - Scroll all the way right":"⇧→ or ⇧l",
        "Network Graph - Scroll all the way up":"⇧↑ or ⇧k",
        "Network Graph - Scroll all the way down":"⇧↓ or ⇧j",
        "Project boards - Moving a column - Start moving the focused column":"⏎ or Space",
        "Project boards - Moving a column - Cancel the move in progress":"Esc",
        "Project boards - Moving a column - Complete the move in progress":"⏎",
        "Project boards - Moving a column - Move column to the left":"← or h",
        "Project boards - Moving a column - Move column to the leftmost postition":"⌘← or ⌘h",
        "Project boards - Moving a column - Move column to the right":"→ or l",
        "Project boards - Moving a column - Move column to the rightmost postition":"⌘→ or ⌘l",
        "Project boards - Moving a card - Start moving the focused card":"⏎ or Space",
        "Project boards - Moving a card - Cancel the move in progress":"Esc",
        "Project boards - Moving a card - Complete the move in progress":"⏎",
        "Project boards - Moving a card - Move card down":"↓ or j",
        "Project boards - Moving a card - Move card to the bottom of the column":"⌘↓ or ⌘j",
        "Project boards - Moving a card - Move card up":"↑ or k",
        "Project boards - Moving a card - Move card to the top of the column":"⌘↑ or ⌘k",
        "Project boards - Moving a card - Move card to the bottom of the column on the left":"← or h",
        "Project boards - Moving a card - Move card to the top of the column on the left":"⇧← or ⇧h",
        "Project boards - Moving a card - Move card to the bottom of the leftmost column":"⌘← or ⌘h",
        "Project boards - Moving a card - Move card to the top of the leftmost column":"⌘⇧← or ⌘⇧h",
        "Project boards - Moving a card - Move card to the bottom of the column on the right":"→ or l",
        "Project boards - Moving a card - Move card to the top of the column on the right":"⇧→ or ⇧l",
        "Project boards - Moving a card - Move card to the bottom of the rightmost column":"⌘→ or ⌘l",
        "Project boards - Moving a card - Move card to the top of the rightmost column":"⌘⇧→ or ⌘⇧l"
    },
    "Outlook":{ #https://support.office.com/en-us/article/Keyboard-shortcuts-for-Outlook-for-Mac-07ae68c8-b7af-4010-b225-324c04ac7335?ui=en-US&rs=en-US&ad=US
        "Archive message":"^e",
        "Previous message":"^[",
        "Next message":"^]",
        "Save an item":"⌘S",
        "Print an item":"⌘P",
        "Undo the last action":"⌘Z",
        "Redo the last action":"⌘Y",
        "Minimize the active window":"⌘M",
        "Create a new folder in the navigation pane":"⌘⇧N",
        "Create new email (in Mail view)":"⌘N",
        "Hide the reading pane or show it on the right":"⌘\\",
        "Hide the reading pane or show it below":"⇧ ⌘\\ )",
        "Move the selected item to a different folder":"⇧ ⌘M",
        "Copy the selected item to a different folder":"⇧ ⌘C",
        "Select all items in the item list, if the item list is the active pane":"⌘A",
        "Minimize or expand the ribbon":"⌘⌥R",
        "Hide Outlook":"⌘H",
        "Quit Outlook":"⌘Q",
        "Start dictation":"FnFn",
        "Insert emoji":"⌘^Space",
        "Go to Mail view":"⌘1",
        "Go to Calendar view":"⌘2",
        "Go to Contacts view":"⌘3",
        "Go to Tasks view":"⌘4",
        "Go to Notes view":"⌘5",
        "Open the Sync Status window or make it the active window":"⌘7",
        "Open the Sync Errors or make it the active window":"⌘8",
        "Open the Contacts Search window":"⌘0",
        "Open the Outlook Preferences dialog box":"⌘,",
        "Cycle forward through open windows":"⌘~",
        "Cycle back through open windows":"⇧ ⌘~",
        "Close the active window":"⌘W",
        "Open the selected item":"⌘O",
        "Move forward through controls in a window":"Tab",
        "Move back through controls in a window":"⇧Tab",
        "Search current folder":"⌥ ⌘F",
        "Do an advanced search in Outlook (add Item Contains filter for searching)":"⇧ ⌘F",
        "Find text within an item - search":"⌘F",
        "Find the next instance of the text you searched for in an item":"⌘G",
        "Find the previous instance of the text you searched for in an item":"⌘⇧G",
        "Create a new message":"⌘N",
        "Send the open message":"⌘Return",
        "Send all messages in the Outbox and receive all incoming messages":"⌘K",
        "Send all the messages in the Outbox":"⇧ ⌘K",
        "Save the open message and store it in the Drafts folder":"⌘S",
        "Add an attachment to the open message":"⌘E",
        "Open the Spelling and Grammar dialog box":"⌘:",
        "Check recipient names in the open messages":"^ ⌘C",
        "Reply to the sender of the message or, if the message is from a mailing list, reply to the mailing list":"⌘R",
        "Reply to all":"⇧+  ⌘R",
        "Forward the message":"⌘J",
        "Open the selected message in a separate window":"⌘O",
        "Clear the flag for the selected message":"⌥ ⌘'",
        "Mark the selected message as junk mail":"⌘⇧J",
        "Mark the selected message as not junk mail":"⌘⇧⌥J",
        "Display the previous message":"[",
        "Display the next message":"]",
        "Navigate to the previous pane in the Mail view":"⇧[",
        "Navigate to the next pane in the Mail view":"⇧]",
        "Move the selected message to a folder":"⇧ ⌘M",
        "Decrease the display size of text in an open message or in the reading pane":"⌘-",
        "Increase the display size of text in an open message or in the reading pane":"⌘+",
        "Scroll down to the next screen of text or, if you are at the end of a message, display the next message":"Spacebar",
        "Scroll up to the previous screen of text or, if you are at the beginning of a message, display the previous message":"⇧+ Spacebar",
        "Delete the selected message":"Delete",
        "Permanently delete the selected message":"⇧Delete",
        "Delete the current message, and, if the message window is open, close it":"⌘Delete",
        "Mark selected messages as read":"⌘T",
        "Mark selected messages as unread":"⇧ ⌘T",
        "Mark all messages in a folder as read":"⌥ ⌘T",
        "Open the Calendar window":"⌘2",
        "Create a new appointment":"⌘N",
        "Open the selected calendar event":"⌘O",
        "Delete the calendar event":"Delete",
        "Switch the view to include today":"⌘T",
        "In Day view, move to the previous day. In Week and Work Week views, move to the previous week. In Month view, move to the previous month.":"⌘←",
        "In Day view, move to the next day. In Week and Work Week views, move to the next week. In Month view, move to the next month.":"⌘→",
        "Navigate to the previous pane in the Calendar view":"⇧[",
        "Navigate to the next pane in the Calendar view":"⇧]",
        "Create a new contact":"⌘N",
        "Open the selected contact":"⌘O",
        "Delete the contact":"Delete",
        "Close the current open contact and open the previous contact":"[",
        "Close the current open contact and open the next contact":"]",
        "Navigate to the previous pane in the People view":"⇧+ [",
        "Navigate to the next pane in the People view":"⇧]",
        "Move to the Task window":"⌘4",
        "Create a new task":"⌘N",
        "Open the selected task":"⌘O",
        "Delete the task":"Delete",
        "Close the current open task and open the previous task in the Tasks list":"[",
        "Close the current open task and open the next task in the Tasks list":"]",
        "Navigate to the previous pane in the Tasks view":"⇧[",
        "Navigate to the next pane in the Tasks view":"⇧]",
        "Move to the Notes window":"⌘5",
        "Create a new note":"⌘N",
        "Open the selected note":"⌘O",
        "Delete the note":"Delete",
        "Close the current open note and open the previous note in the Notes list":"[",
        "Close the current open note and open the next note in the Notes list":"]",
        "Navigate to the previous pane in the Notes view":"⇧[",
        "Navigate to the next pane in the Notes view":"⇧]",
        "Send a note as an email":"⌘J",
        "Send a note as an HTML attachment to an email":"^ ⌘J [First place the focus on the note in the list of notes]",
        "Cut the selected text to the clipboard":"⌘X",
        "Copy a selection to the clipboard":"⌘C",
        "Paste a selection from the clipboard":"⌘V",
        "Paste a selection from the clipboard and match the destination style":"⇧⌥ ⌘V",
        "Make the selected text bold":"⌘B",
        "Make the selected text italic":"⌘I",
        "Underline the selected text":"⌘U",
        "Strike through the selected text":"⇧ ⌘X",
        "Insert a hyperlink":"^ ⌘K",
        "Move the cursor left one character":"←",
        "Move the cursor right one character":"→",
        "Move the cursor up one line":"↑",
        "Move the cursor down one line":"↓",
        "Move the cursor to the beginning of the current paragraph":"⌥↑",
        "Move the cursor to the end of the current paragraph":"⌥↓",
        "Move the cursor to the beginning of the current word":"⌥←",
        "Move the cursor to the end of the current word":"⌥→",
        "Decrease indent":"{",
        "Increase indent":"}",
        "Delete the character to the left of the cursor, or delete the selected text":"Delete",
        "Delete the character to the right side of the cursor, or delete the selected text":"Delete [If your keyboard doesn't have a  Delete key, use FNDelete]",
        "Insert a tab stop":"Tab",
        "Move the cursor to the beginning of the line":"⌘←",
        "Move the cursor to the end of the line":"⌘→",
        "Move the cursor to the top of the message body":"⌘↑",
        "Move the cursor to the bottom of the message body":"⌘↓",
        "Move the cursor to the beginning of the selected text":"⌘Home",
        "Move the cursor to the end of the selected text":"⌘End",
        "Scroll up":"Page up",
        "Scroll down":"Page down",
        "Flag the selected item for follow up, with Today as Due Date":"^1",
        "Flag the selected item for follow up, with Tomorrow as Due Date":"^2",
        "Flag the selected item for follow up, with This Week as Due Date":"^3",
        "Flag the selected item for follow up, with Next Week as Due Date":"^4",
        "Flag the selected item for follow up, with No Due Date":"^5",
        "Flag the selected item for follow up, and add a custom Due Date":"^6",
        "Flag the selected item for follow up, and add a reminder":"^=",
        "Mark the selected item as Complete":"^0",
        "Clear the selected item's follow-up flag":"⌥⌘'"
    },
    "Video Speed Controller chrome extension":{
    #settings
        "Rewind":"Z",
        "Advance":"X",
        "Reset speed":"R",
        "Decrease speed":"S",
        "Increase speed":"D",
        "Preferred speed":"G",
        "Show/hide controller":"V"
    },
    "inbox.google.com":{
        #⇧?
        "Everywhere - Toggle and view keyboard shortcuts":"⇧?",
        "Everywhere - Compose":"c",
        "Everywhere - Search":"/",
        "Everywhere - Go to inbox":"i",
        "Everywhere - Open Hangouts and focus the conversation list":"h",
        "Everywhere - Open Hangouts and focus the search box":"q",
        "Everywhere - Create reminder":"t",
        "Everywhere - Focus on notification":"Shift b",
        "Everywhere - Open main menu":"Shift m",
        "Everywhere - Undo last action":"z",

    },
    "trello":{

    },
    "Alfred":{
    #https://www.alfredapp.com/help/getting-started/cheatsheet/

    },
    "Terminal":{
    #https://github.com/0nn0/terminal-mac-cheatsheet

    },
}

import collections

def convert(data):
    if isinstance(data, basestring):
        return data.decode('utf-8').strip()
    elif isinstance(data, collections.Mapping):
        return dict(map(convert, data.iteritems()))
    elif isinstance(data, collections.Iterable):
        return type(data)(map(convert, data))
    else:
        return data

shortcuts = convert(shortcuts)