# coding: utf8
shortcuts = {
    "Airmail":{
    #https://help.airmailapp.com/en-us/article/keyboard-shortcuts-airmail-for-macos-hzjy9n/
        "Label": "L",
        "V": "L",
        "Move to": "L",
        "S or ⇧⌘S": "L",
        "Mark as star": "L",
        "C or ⌘N": "L",
        "New Message": "L",
        "N": "L",
        "Select Next Conversation": "L",
        "P": "L",
        "Select Previous Conversation": "L",
        "R or ⌘R": "L",
        "Reply": "L",
        "A or ⌘⇧R": "L",
        "Reply All": "L",
        "E": "L",
        "Archive": "L",
        "0": "L",
        "Show All / Remove all filters": "L",
        "1": "L",
        "Show Unread": "L",
        "2": "L",
        "Show Starred": "L",
        "3": "L",
        "Show Attachments": "L",
        "4": "L",
        "Show Conversations": "L",
        "5": "L",
        "Sort by Sender": "L",
        "6": "L",
        "Sort by Subject": "L",
        "7": "L",
        "Sort by Replied": "L",
        "8": "L",
        "Sort by Unread": "L",
        "9": "L",
        "Sort by Date": "L",
        "#": "L",
        "Move to trash": "L",
        "=": "L",
        "Select mails for same Sender/Receiver": "L",
        "+ or ⌘⇧I": "L",
        "Mark as Important": "L",
        "- or ⌘⇧I": "L",
        "Mark as Not Important": "L",
        "⌘⌥R": "L",
        "Refresh / Get Messages": "L",
        "⌘.": "L",
        "Cancel or Extend View": "L",
        "⌘↖": "L",
        "Go to First": "L",
        "⌘↘": "L",
        "Go to Last": "L",
        "⌘F": "L",
        "Search all messages": "L",
        "⌘+": "L",
        "Zoom in": "L",
        "⌘-": "L",
        "Zoom out": "L",
        "⌘0": "L",
        "Reset zoom": "L",
        "⌘E": "L",
        "Quick Reply": "L",
        "⌘O Open message in separate preview window": "L",
        "D": "L",
        "Send Again": "L",
        "⌥⌘B": "L",
        "To Do": "L",
        "⌥⌘N": "L",
        "Memo": "L",
        "⌥⌘M": "L",
        "Done": "L",
        "⌥J": "L",
        "Load Image": "L",
        "⌥⇧⌘F": "L",
        "Reveal hidden folder": "L",
        "⌥⇧⌘F": "L",
        "Hide hidden folders": "L",
        "⌥⌘E": "L",
        "Export to email": "L",
        "⌥⇧⌘V": "L",
        "Paste and match style": "L",
        "⌥⌘F": "L",
        "Find in messages": "L",
        "⌥⌘I": "L",
        "Quote Selection": "L",
        "⌥⇧⌘I": "L",
        "Reverse Order": "L",
        "⌥⌘U": "L",
        "Show Raw Source": "L",
        "^⌘A": "L",
        "Convert to `Reply All` while replying": "L",
        "^⌘S": "L",
        "Next sender while composing": "L",
        "^⌥⌘R": "L",
        "Redirect": "L",
        "^⌘I": "L",
        "Next signature while composing": "L",
        "^1,2,3,4…": "L",
        "Switch Account": "L",
        "^T": "L",
        "Operations": "L",
        "^⌥⌘V": "L",
        "Switch to plain text": "L",
        "^F": "L",
        "Show messages from the same sender": "L",
        "^⌥F": "L",
        "Show/Hide Filter": "L",
        "^⌥⌘C": "L",
        "Copy message link": "L",
        "^⌥C": "L",
        "Calendar": "L",
        "^⌥R": "L",
        "Reminders": "L",
        "^⌥Y": "L",
        "BusyCal": "L",
        "^⌥F": "L",
        "Fantastical": "L",
        "^⌥S": "L",
        "Fantastical2": "L",
        "^⌥O": "L",
        "Omnifocus": "L",
        "^⌥T": "L",
        "Things": "L",
        "^⌥H": "L",
        "2Do": "L",
        "^⌘L": "L",
        "Show folder filter": "L",
        "^⌥⌘Delete": "L",
        "Empty trash": "L",
        "^⌘P": "L",
        "Show Plugins Folders": "L",
        "^⌘R": "L",
        "Rules": "L",
        "⇧⌘N": "L",
        "New Folder": "L",
        "⇧U or ⌘⇧U": "L",
        "Mark as unread": "L",
        "⇧I or ⌘⇧U": "L",
        "Mark as read": "L",
        "⇧⌘L": "L",
        "Find all folders": "L",
        "⇧⌘A": "L",
        "Attach": "L",
        "⇧⌘E": "L",
        "Quick reply all": "L",
        "⇧⌘V": "L",
        "Paste text only": "L",
        "⇧⌘T": "L",
        "Plain text composer": "L",
        "⇧⌘↑": "L",
        "All inboxes": "L",
        "^⌘→": "L",
        "Next account": "L",
        "^⌘←": "L",
        "Previous account": "L",
        "⌥⌘↓": "L",
        "Show/Hide Accounts": "L",
        "⌥⌘←": "L",
        "Hide folders": "L",
        "⌥⌘→": "L",
        "Show folders": "L",
        "⌘←": "L",
        "Hide Message Detail": "L",
        "⌘→": "L",
        "Show Message Detail": "L",
        "⌘←": "L",
        "Hide Message Preview Pane": "L",
        "⌘→": "L",
        "Show Message Preview Pane": "L"
    }
}