# coding: utf8

shortcuts = {
    "Alfred App": {
        "Show Alfred": "⌥ spacebar",
        "Select the next item in the list": "↓",
        "Select the previous item in the list": "↑",
        "Action the currently selected item": "↩",
        "Action the # item directly [1-9]": "⌘ #",
        "Open file or application in default application": "⌘ o",
        "Open Alfred Preferences": "⌘ ,",
        "Search the currently typed query in Finder": "⌥ ↩",
        "Search the currently typed query in default web search": "⌃ ↩",
        "Reveal in Finder (if the result is a local file)": "⌘ ↩",
        "Show list of available Actions for selection": "⌥ ⌘ \\",
        "Preview in Quick Look": "⇧ / ⌘Y",
        "Hide Alfred, or go back if in a stacked view": "⎋",
        "Hide Alfred, ignoring stacked views": "⌘ ⎋",
        "Dynamically toggle maximum height in select views, such as the Grid View": "⌘ 0",
        "Zoom In in select views, such as the PDF View": "⌘ +",
        "Zoom Out in select views, such as the PDF View": "⌘ -",
        "Go to last browsed path in the File System Navigation": "⌥ ⌘ /",
        "Show list of available Actions for selected item in File System Navigation": "→ / fn / ⌃",
        "Browse selected folder in File System Navigation": "⌘ ↓",
        "Enter a folder in File System Navigation": "↩",
        "Go up a folder in File System Navigation": "backspace",
        "Autocomplete": "⇥",
        "Show hidden files in File System Navigation": ".",
        "Add to the File Buffer and move to the next item": "⌥ ↓",
        "Add or remove item from the File Buffer": "⌥ ↑",
        "Remove last item from the File Buffer": "⌥ ←",
        "Action all items in the File Buffer": "⌥ →",
        "Open Clipboard History viewer": "⌥ ⌘ c",
        "Copy selected clip to current Clipboard": "⌘ c",
        "While in Clipboard Viewer, save current clip as a snippet": "⌘ s",
        "Delete the selected entry": "Fn Backspace",
        "Show the Music Mini Player": "⌃ ⌘ ↩",
        "Play / Pause": "⌃ ⌘ ↓",
        "Next Track": "⌃ ⌘ →",
        "Back Track": "⌃ ⌘ ←",
        "Play Random Album": "⌃ ⌘ ↑",
        "Rate currently playing song from 0 to 5 stars": "⌃ ⌘ [0-5]",
    }
}

page_url = "https://www.alfredapp.com/help/getting-started/cheatsheet/"