# coding: utf8

shortcuts = {
    "Google Chrome":{ #https://support.google.com/chrome/answer/157179?hl=en
        "Open a new window":"⌘n",
        "Open a new window in Incognito mode":"⌘t",
        "Open a new tab, and jump to it":"⌘t",
        "Reopen the last closed tab, and jump to it":"⌘⇧t",
        "Jump to the next open tab":"⌘⌥→",
        "Jump to the previous open tab":"⌘⌥←",
        "Jump to a specific tab (1-9)":"⌘[NUM]",
        "Jump to the last tab":"⌘9",
        "Open the previous page in your browsing history for the current tab":"⌘[ or ⌘←",
        "Open the next page in your browsing history for the current tab":"⌘] or ⌘→",
        "Close the current tab or pop-up":"⌘w",
        "Close all open tabs and the browser":"⌘⇧w",
        "Minimize the window":"⌘m",
        "Hide Google Chrome":"⌘h",
        "Quit Google Chrome":"⌘q",
        "Developer Tools":"⌘⌥i",
        "View Source":"⌘⌥U",
        "Always show toolbar in full screen":"⌘⇧F",
        "Show or hide the Bookmarks Bar":"⌘⇧b",
        "Open the Bookmark Manager:":"⌘⌥b",
        "Open the Settings page in a new tab":"⌘,",
        "Open the History page in a new tab":"⌘y",
        "Open the Downloads page in a new tab":"⌘⇧j",
        "Open the Find Bar to search the current page":"⌘f",
        "Jump to the next match to your Find Bar search":"⌘g",
        "Jump to the previous match to your Find Bar search":"⌘⇧g",
        "When Find Bar is open, search for selected text":"⌘e",
        "Open the Clear Browsing Data options":"⌘⇧⌫",
        "Log in as a different user or browse as a Guest":"⌘⇧m",
        "Search with your default search engine":"Type a search term + ↩",
        "Search using a different search engine":"Type a search engine name + Tab",
        "Add www. and .com to a site name, and open it in the current tab":"Type a site name + ⌃↩",
        "Add www. and .com to a site name, and open it in a new tab":"Type a site name + ⌃⇧↩",
        "Open the website in a new background tab":"Type a web address + ⌘↩",
        "Jump to the address bar":"⌘l",
        "Delete all words in address bar before cursor":"⌘⌫",
        "Delete one word in address bar before cursor":"⌥⌫",
        "Remove predictions from your address bar":"↓ to highlight + ⇧fn⌫",
        "Open options to print the current page":"⌘p",
        "Open options to save the current page":"⌘s",
        "Open the Page Setup dialog ":"⌘⌥p",
        "Email your current page":"⌘⇧i",
        "Reload your current page":"⌘r",
        "Reload your current page, ignoring cached content":"⌘⇧r",
        "Stop the page loading":"Esc",
        "Browse clickable items moving forward":"Tab",
        "Browse clickable items moving backward":"⇧Tab",
        "Open a file from your computer in Google Chrome":"⌘o + Select a file",
        "Display non-editable HTML source code for the current page":"⌘⌥u",
        "Open the JavaScript Console":"⌘⌥j",
        "Save your current webpage as a bookmark":"⌘d",
        "Save all open tabs as bookmarks in a new folder":"⌘⇧d",
        "Turn full-screen mode on or off":"⌘⌃f",
        "Make everything on the page bigger - zoom in":"⌘+",
        "Make everything on the page smaller - zoom out":"⌘-",
        "Return everything on the page to the default size":"⌘0",
        "Scroll down a webpage, a screen at a time":"Space",
        "Scroll up a webpage, a screen at a time":"⇧Space",
        "Search the web":"⌘⌥f",
        "Move your cursor to the front of the previous word in a text field ":"⌥←",
        "Move your cursor to the back of the next word in a text field":"⌥→",
        "Delete the previous word in a text field":"⌥⌫",
        "Open your home page in the current tab":"⌘⇧h",
        "Open a link in a current tab (mouse only)":"Drag a link to a tab",
        "Open a link in new background tab":"⌘ + Click a link",
        "Open a link, and jump to it":"⌘⇧ + Click a link",
        "Open a link, and jump to it (mouse only)":"Drag a link to a blank area of the tab strip",
        "Open a link in a new window":"⇧ + Click a link",
        "Open a tab in a new window (mouse only)":"Drag the tab out of the tab strip",
        "Move a tab to a current window (mouse only)":"Drag the tab into an existing window",
        "Return a tab to its original position":"Press Esc while dragging",
        "Save the current webpage as a bookmark":"Drag the web address to the Bookmarks Bar",
        "Download the target of a link":"⌥ + Click a link",
        "Display your browsing history":"Right-click Back ⇦ or Next ⇨, or click & hold Back ⇦ or Next ⇨",
        "Increase the window to full height":"Double-click a blank area of the tab strip"
    }
}