# coding: utf8

shortcuts = {
    "Google Chrome Mac Keyboard Shortcuts": {
        "Tab & Window Shortcuts": {
            "Open a new window": "⌘ + n",
            "Open a new window in Incognito mode": "⌘ + Shift + n",
            "Open a new tab, and jump to it": "⌘ + t",
            "Reopen previously closed tabs in the order they were closed": "⌘ + Shift + t",
            "Jump to the next open tab": "⌘ + Option + Right arrow",
            "Jump to the previous open tab": "⌘ + Option + Left arrow",
            "Jump to a specific tab": "⌘ + 1 through ⌘ + 8",
            "Jump to the last tab": "⌘ + 9",
            "Open the previous page in your browsing history for the current tab": "⌘ + [ or ⌘ + Left arrow",
            "Open the next page in your browsing history for the current tab": "⌘ + ] or ⌘ + Right arrow",
            "Close the current tab or pop-up": "⌘ + w",
            "Close the current window": "⌘ + Shift + w",
            "Minimize the window": "⌘ + m",
            "Hide Google Chrome": "⌘ + h",
            "Quit Google Chrome": "⌘ + q",
            "Move tabs right or left": "Ctrl + Shift + PgUp or Ctrl + Shift + PgDn",
            "Turn on full-screen mode": "Fn + f",
            "Turn off full-screen mode": "Fn + f or press and hold Esc",
        },
        "Tab Group Shortcuts": {
            "Collapse or expand a tab group": "Switch focus to tab group header, then press Space bar or Enter",
            "Move a tab or tab group": "Switch focus to tab or group, then press Ctrl + Left arrow or Ctrl + Right arrow",
        },
        "Google Chrome Feature Shortcuts": {
            "Show or hide the Bookmarks Bar": "⌘ + Shift + b",
            "Open the Bookmark Manager": "⌘ + Option + b",
            "Open the Settings page in a new tab": "⌘ + ,",
            "Open the History page in a new tab": "⌘ + y",
            "Open the Downloads page in a new tab": "⌘ + Shift + j",
            "Open the Find Bar to search the current page": "⌘ + f",
            "Jump to the next match to your Find Bar search": "⌘ + g",
            "Jump to the previous match to your Find Bar search": "⌘ + Shift + g",
            "When Find Bar is open, search for selected text": "⌘ + e",
            "Open Developer Tools": "⌘ + Option + i",
            "Open the Delete Browsing Data options": "⌘ + Shift + Delete",
            "Log in as a different user, browse as a Guest, or access payment and password info": "⌘ + Shift + m",
            "Jump to the main menu bar": "Control + F2",
            "Cycle focus to unfocused dialog (if showing) and all toolbars": "⌘ + Option + Up arrow or Down arrow",
            "Open a feedback form": "⌘ + Option + Shift + i",
            "Turn on caret browsing": "F7",
            "Focus on inactive dialogs": "⌘ + Option + Shift + a",
        },
        "Address Bar Shortcuts": {
            "Search with your default search engine": "Type a search term + Return",
            "Search using a different search engine": "Type a search engine name + press Tab",
            "Add www. and .com to a site name, open in current tab": "Type a site name + Ctrl + Return",
            "Add www. and .com to a site name, open in a new window": "Type a site name + Ctrl + Shift + Return",
            "Open the website in a new background tab": "Type a web address + ⌘ + Return",
            "Jump to the address bar": "⌘ + l",
            "Remove predictions from your address bar": "Down arrow to highlight + Shift + fn + Delete",
            "Forward Delete or fn-Delete (on a laptop)": "Forward Delete or fn-Delete (on a laptop)",
            "Move cursor to the address bar": "Ctrl + F5",
        },
        "Webpage Shortcuts": {
            "Compose a new email message with a link to the current page": "⌘ + Shift + i",
            "Open options to print the current page": "⌘ + p",
            "Open options to save the current page": "⌘ + s",
            "Open the Page Setup dialog": "⌘ + Option + p",
            "Reload current page ignoring cached content": "⌘ + Shift + r",
            "Stop the page loading": "Esc",
            "Browse clickable items moving forward": "Tab",
            "Browse clickable items moving backward": "Shift + Tab",
            "Open a file from your computer in Chrome": "⌘ + o",
            "Display non-editable HTML source code for current page": "⌘ + Option + u",
            "Open the JavaScript Console": "⌘ + Option + j",
            "Save current webpage as a bookmark": "⌘ + d",
            "Save all open tabs as bookmarks in a new folder": "⌘ + Shift + d",
            "Make everything on the page bigger": "⌘ and +",
            "Make everything on the page smaller": "⌘ and -",
            "Return everything on the page to default size": "⌘ + 0",
            "Scroll down a webpage a screen at a time": "Space",
            "Scroll up a webpage a screen at a time": "Shift + Space",
            "Search the web": "⌘ + Option + f",
            "Move cursor to beginning of previous word in a text field": "Option + Left arrow",
            "Move cursor to back of next word in a text field": "Option + Right arrow",
            "Delete previous word in a text field": "Option + Delete",
            "Open your home page in the current tab": "⌘ + Shift + h",
        },
        "Mouse Shortcuts": {
            "Open a link in a new background tab": "⌘ + Click a link",
            "Open a link, and jump to it": "⌘ + Shift + Click a link",
            "Open a link in a new window": "Shift + Click a link",
            "Return a tab to its original position": "Press Esc while dragging",
            "Save the current webpage as a bookmark": "Drag the web address to the Bookmarks Bar",
            "Download the target of a link": "Option + Click a link",
        },
        "Other": {
            "Right-click Back": "[no shortcut specified]",
            "Right-click Next": "[no shortcut specified]",
            "Increase the window to full height": "Double-click a blank area of the tab strip",
        },
    },
    "Page URL": "https://support.google.com/chrome/answer/157179?hl=en"
}