# coding: utf8

shortcuts = { #https://docs.databricks.com/notebooks/notebooks-use.html
    "Databricks": {
        "Switch to Command Mode": "Esc",
        "Find and Replace": "Ctrl ⌥ F",
        "Run command and move to next cell": "⇧⏎",
        "Run command and insert new cell below": "⌥ ⏎",
        "Run command": "Ctrl ⏎",
        "Run all above commands (exclusive)": "⇧⌥ Up",
        "Run all below commands (inclusive)": "⇧⌥ Down",
        "Move to previous/next cell": "⌥ Up/Down",
        "Insert a cell above": "Ctrl ⌥ P",
        "Insert a cell below": "Ctrl ⌥ N",
        "Split a cell at cursor": "Ctrl ⌥ -",
        "Move a cell up": "Ctrl ⌥ Up",
        "Move a cell down": "Ctrl ⌥ Down",
        "Toggle comments panel": "Ctrl ⌥ M",
        "Copy current cell": "Ctrl ⌥ C",
        "Cut current cell": "Ctrl ⌥ X",
        "Paste cell below": "Ctrl ⌥ V",
        "Delete current cell": "Ctrl ⌥ D",
        "Move up or to previous cell": "Up",
        "Move down or to next cell": "Down",
        "Autocomplete, indent selection": "Tab",
        "Unindent selection": "⇧Tab",
        "Indent/Unindent selection": "⌘ ]/[",
        "Undo typing": "⌘ Z",
        "Redo typing": "⌘ ⇧Z",
        "Toggle line comment": "⌘ /",
        "Select multiple cells": "⌘ Click",
        "Switch to Edit Mode": "⏎",
        "Find and Replace": "Ctrl⌥F",
        "Run command and move to next cell": "⇧⏎",
        "Run command": "Ctrl ⏎",
        "Run all above commands (exclusive)": "⇧⌥ ↑",
        "Run all below commands (inclusive)": "⇧⌥ ↓",
        "Delete current cell": "DD",
        "Delete current cell (skip prompt)": "⇧DD",
        "Go to first cell": "GG",
        "Go to last cell": "⇧G",
        "Undo delete cells": "Z",
        "Cut current cell": "X",
        "Copy current cell": "C",
        "Paste cell below": "V",
        "Paste cell above": "⇧V",
        "Insert a cell above": "A",
        "Insert a cell below": "B",
        "Toggle cell output": "O",
        "Scroll down": "Space",
        "Scroll up": "⇧Space",
        "Toggle keyboard shortcuts menu": "H",
        "Merge with cell below": "⇧M",
        "Move to previous cell": "↑/P/K"
    }
}