# coding: utf8
shortcuts = {
    "Default Folder X":{ #https://forum.keyboardmaestro.com/t/tip-be-aware-of-default-folder-x-shortcuts/6667
        "Open in Finder": "optioncommandF",
        "New Folder": "shiftcommandN",
        "Rename": "optioncommandR",
        "Copy": "optioncommandC",
        "Move": "optioncommandM",
        "Get Info": "commandI",
        "Show in Finder": "commandR",
        "Move To Trash": "commandT",
        "Desktop": "commandD",
        "Home": "shiftcommandH",
        "iCloud": "shiftcommandI",
        "Go to Default Folder": "commandU",
        "Previous Finder Window": "optionshift↑",
        "Next Finder Window": "optionshift↓",
        "Show Menu - Finder": "^optioncommandM",
        "Copy Folder Path to Clipboard": "Not set",
        "Copy Folder Name to Clipboard": "Not set",
        "Duplicate": "Not set",
        "Copy Selected Path to Clipboard": "Not set",
        "Copy Selected Name to Clipboard": "Not set",
        "Compress": "Not set",
        "Uncompres": "Not set",
        "Quicklook": "Not set",
        "Preferences": "Not set",
        "Add to Favorites": "Not set",
        "Remove From Favorites": "Not set",
        "Set Default Folder for Application": "Not set",
        "Set Default Folder for Application & File Type": "Not set",
        "Previous Recent Folder": "Not set",
        "Next Recent Folder": "Not set",
        "Show Utility Menu": "Not set",
        "Show Computer Menu": "Not set",
        "Show Favorites Menu": "Not set",
        "Show Recent Folder Menu": "Not set",
        "Show Finder Window Menu": "Not set",
        "Show / Hide Toolbar": "Not set",
        "Add to Favorites": "Not set",
        "Remove from Favorites": "Not set",
        "Previous Recent Folder": "Not set",
        "Next Recent Folder": "Not set",
        "Previous Finder Window": "Not set",
        "Next Finder Window": "Not set",
        "Show / Hide Finder Drawer": "Not set",
        "Switch to Previous Folder Set - System": "Not set",
        "Switch to Next Folder Set - System": "Not set",
        "Show Menu - System": "Not set"
        }
    }