# coding: utf8

#https://help.evernote.com/hc/en-us/articles/208313358-Keyboard-shortcuts-in-Evernote-for-Mac
shortcuts = {
    "Evernote": {
        "Global - Quick Note": "^⌘N",
        "Global - New Note Window": "^⌥⌘N  ",
        "Global - Paste to Evernote": "^⌘V    ",
        "Global - Clip Rectangle or Window": "^⌘C    ",
        "Global - Search in Evernote": "^⌘E    ",
        "New Note": "⌘N",
        "New Chat": "⌥⇧⌘N",
        "New Notebook": "⇧⌘N   ",
        "New Tag": "^⌘T    ",
        "New Window": "⌥⌘N   ",
        "New Tab": "⌘T ",
        "Sync": "^⌘S    ",
        "Close": "⌘W ",
        "Save": "⌘S ",
        "Quick Look Attachments": "⌘Y ",
        "Print": "⌘P ",
        "Show/Hide Toolbar": "⌥⌘T   ",
        "Show/Hide Sidebar": "⌥⌘S   ",
        "Work Chat": "⌥⌘0   ",
        "Notes": "⌥⌘1   ",
        "Notebooks": "⌥⌘2   ",
        "Tags": "⌥⌘3   ",
        "Atlas / Business Home (Evernote Business only)": "⌥⌘4   ",
        "Atlas (Evernote Business only)": "⌥⌘5   ",
        "Announcements (Evernote Business only)": "⌥⌘6   ",
        "Announcements (Evernote Business only)": "⌥⌘7   ",
        "Show All Notes": "⇧⌘A   ",
        "Jump to Notebook": "⌘J ",
        "Jump to Tag": "⇧⌘J   ",
        "Select Note List": "⌘| ",
        "Back": "⌘[ ",
        "Forward": "⌘] ",
        "Enter Full Screen": "^⌘F    ",
        "Go to Shortcuts 1-9": "⌘1-9   ",
        "Preferences": "⌘, ",
        "Switch User": "^⌘A    ",
        "Hide Evernote": "⌘H ",
        "Hide Others": "⌥⌘H   ",
        "Quit Evernote": "⌘Q ",
        "Minimize": "⌘M ",
        "Zoom": "/   ",
        "Undo": "⌘Z ",
        "Redo": "⇧⌘Z   ",
        "Cut": "⌘X ",
        "Copy": "⌘C ",
        "Paste": "⌘V ",
        "Paste and Match Style": "⇧⌘V   ",
        "Select All": "⌘A ",
        "Encrypt Selected Text": "⇧⌘X   ",
        "Search Notes": "⌥⌘F   ",
        "Reset Search": "⌘R ",
        "Find Within Note": "⌘F ",
        "Find Next": "⌘G ",
        "Find Previous": "⇧⌘G   ",
        "Show Spelling and Grammar": "⌘: ",
        "Check Document Now": "⌘; ",
        "Start Dictation": "fn fn   ",
        "Emoji & Symbols": "^⌘Space    ",
        "Copy Public Link": "⌘/ ",
        "Present": "⌘↩ ",
        "Present on Another Screen": "⌥⌘↩   ",
        "Edit Note Title": "⌘L ",
        "Edit Tags": "⌘' ",
        "Show/Hide Note Info": "⇧⌘I   ",
        "Copy Note Link": "^⌥⌘C  ",
        "Move To Notebook": "^⌘M    ",
        "Merge Notes": "⇧⌘M   ",
        "Show Colors": "⇧⌘C   ",
        "Align Left": "⌥⌘{   ",
        "Center": "⌥⌘|   ",
        "Align Right": "⌥⌘}   ",
        "Increase Indent Level": "⇧⌘]   ",
        "Decrease Indent Level": "⇧⌘[   ",
        "Toggle Bulleted List": "⇧⌘U   ",
        "Toggle Numbered List": "⇧⌘O   ",
        "Increase List Level": "Tab   ",
        "Decrease List Level": "⇧⇤ ",
        "Insert Table": "⇧⌘L   ",
        "Add Link": "⌘K ",
        "Remove Link": "⇧⌘K   ",
        "Bold": "⌘B ",
        "Italic": "⌘I ",
        "Underline": "⌘U ",
        "Strikethrough": "^⌘K    ",
        "Highlight": "^⌘H    ",
        "Superscript": "^⌘+    ",
        "Subscript": "^⌘-    ",
        "Bigger": "⌘+ ",
        "Smaller": "⌘- ",
        "Insert To-do": "⇧⌘T   ",
        "Insert Horizontal Rule": "⇧⌘H   ",
        "Insert Date": "⇧⌘D   ",
        "Insert Time": "⌥⇧⌘D ",
        "Simplify Formatting": "⇧⌘F   "
    }
}