# coding: utf8
shortcuts = {
    "Finder":{
        # https://support.apple.com/en-jo/HT201236
        "Duplicate the selected files.": "Command-D",
        "Eject the selected disk or volume.": "Command-E",
        "Start a Spotlight search in the Finder window.": "Command-F",
        "Show the Get Info window for a selected file.": "Command-I",
        "Open the Computer window.": "Shift-Command-C",
        "Open the desktop folder.": "Shift-Command-D",
        "Open the All My Files window.": "Shift-Command-F (Opens Recents, replaces All My Files)",
        "Open a Go to Folder window.": "Shift-Command-G",
        "Open the Home folder of the current macOS user account.": "Shift-Command-H",
        "Open iCloud Drive.": "Shift-Command-I",
        "Open the Network window.": "Shift-Command-K",
        "Open the Downloads folder.": "Option-Command-L",
        "Open the Documents folder.": "Shift-Command-O",
        "Open the AirDrop window.": "Shift-Command-R",
        "Add selected Finder item to the Dock (OS X Mountain Lion or earlier).": "Control-Shift-Command-T",
        "Add selected Finder item to the Dock (OS X Mavericks or later).": "Control-Shift-Command-T",
        "Open the Utilities folder.": "Shift-Command-U",
        "Show or hide the Dock. This often works even when you're not in the Finder.": "Option-Command-D",
        "Add the selected item to the sidebar (OS X Mavericks or later).": "Control-Command-T",
        "Hide or show the path bar in Finder windows.": "Option-Command-P",
        "Hide or show the Sidebar in Finder windows.": "Option-Command-S",
        "Hide or show the status bar in Finder windows.": "Command-/",
        "Show View Options.": "Command-J",
        "Open the Connect to Server window.": "Command-K",
        "Make an alias of the selected item.": "Control-Command-A",
        "Open a new Finder window.": "Command-N",
        "Create a new folder.": "Shift-Command-N",
        "Create a new Smart Folder.": "Option-Command-N",
        "Show the original file for the selected alias.": "Command-R",
        "Show or hide the tab bar when a single tab is open in the current Finder window.": "Command-T",
        "Show or hide a Finder tab.": "Shift-Command-T",
        "Show or hide the toolbar when a single tab is open in the current Finder window.": "Option-Command-T",
        "Move: Move the files in the Clipboard from their original location to the current location.": "Option-Command-V",
        "View a Quick Look slideshow of the selected files.": "Option-Command-Y",
        "Use Quick Look to preview the selected files.": "Command-Y",
        "View the items in the Finder window as icons.": "Command-1",
        "View the items in a Finder window as a list.": "Command-2",
        "View the items in a Finder window in columns.": "Command-3",
        "View the items in a Finder window with Cover Flow (Gallery view in newer macOS).": "Command-4",
        "Go to the previous folder.": "Command-[",
        "Go to the next folder.": "Command-]",
        "Open the folder that contains the current folder.": "Command-Up Arrow",
        "Open the folder that contains the current folder in a new window.": "Control-Command-Up Arrow",
        "Open the selected item.": "Command-Down Arrow",
        "Show the desktop. This works even when you're not in the Finder.": "Command + Mission Control (F3)",
        "Turn Target Display Mode on or off.": "Command + Brightness Up",
        "Turn display mirroring on or off when your Mac is connected to more than one display.": "Command + Brightness Down",
        "Open the selected folder (list view).": "Right Arrow",
        "Close the selected folder (list view).": "Left Arrow",
        "Open a folder in a separate window and close the current window.": "Option + double-click",
        "Open a folder in a separate tab or window.": "Command + double-click",
        "Move the selected item to the Trash.": "Command-Delete",
        "Empty the Trash.": "Shift-Command-Delete",
        "Empty the Trash without confirmation dialog.": "Option-Shift-Command-Delete",
        "Use Quick Look to preview the files.": "Command-Y",
        "Open Displays preferences. This works with either Brightness key.": "Option-Brightness Up",
        "Open Mission Control preferences.": "Option-Mission Control",
        "Open Sound preferences.": "Option-Volume Up or any volume key",
        "Move the dragged item to another volume or location.": "Command (while dragging)",
        "Copy the dragged item.": "Option (while dragging)",
        "Make an alias of the dragged item.": "Option-Command (while dragging)",
        "Open all folders within the selected folder (list view).": "Option-click a disclosure triangle",
        "See the folders that contain the current folder.": "Command-click a window title"
    },
    "General": {
        "Cut": "Command-X",
        "Copy": "Command-C",
        "Paste": "Command-V",
        "Undo": "Command-Z",
        "Redo": "Shift-Command-Z",
        "Select All": "Command-A",
        "Find": "Command-F",
        "Find Again (next occurrence)": "Command-G",
        "Find the previous occurrence": "Shift-Command-G",
        "Hide the windows of the front app": "Command-H",
        "View the front app but hide others": "Option-Command-H",
        "Minimize the front window to the Dock": "Command-M",
        "Minimize all windows of the front app": "Option-Command-M",
        "Open the selected item or dialog": "Command-O",
        "Open a print dialog": "Command-P",
        "Quit the current app": "Command-Q",
        "Save the current document": "Command-S",
        "Open a new tab": "Command-T",
        "Close the front window": "Command-W",
        "Close all windows of the app": "Option-Command-W",
        "Force quit an app": "Option-Command-Esc",
        "Show or hide Spotlight": "Command-Space bar",
        "Spotlight search from Finder": "Command-Option-Space bar",
        "Show the Character Viewer": "Control-Command-Space bar or Fn-E",
        "Use or stop full screen": "Control-Command-F",
        "Use Quick Look to preview": "Space bar",
        "Switch to next most recently used app": "Command-Tab",
        "Switch between windows of the current app": "Command-Grave accent (`)",
        "Screenshot or screen recording": "Shift-Command-5",
        "Screenshots": "Shift-Command-3 or Shift-Command-4",
        "Create a Quick Note": "Fn-Q"
    },
    "Sleep, log out, and shut down shortcuts": {
        "Turn on Mac, wake from sleep, or put to sleep (press and hold 1.5 sec)": "Power button",
        "Put to sleep": "Option-Command-Power button or Option-Command-Media Eject",
        "Put displays to sleep": "Control-Shift-Power button or Control-Shift-Media Eject",
        "Show restart/sleep/shutdown dialog": "Control-Power button or Control-Media Eject",
        "Force restart": "Control-Command-Power button",
        "Quit all apps then restart": "Control-Command-Media Eject",
        "Quit all apps then shut down": "Control-Option-Command-Power button or Control-Option-Command-Media Eject",
        "Immediately lock screen": "Control-Command-Q",
        "Log out": "Shift-Command-Q",
        "Log out immediately": "Option-Shift-Command-Q",
        "Skip confirmation dialog when choosing Log Out, Shut Down, or Restart": "Hold Option key"
    }
}

# Reference page:
page_url = "https://support.apple.com/en-jo/HT201236"