# coding: utf8

shortcuts = {
    "Finder": {
        # https://support.apple.com/en-jo/HT201236
        "Duplicate the selected files.": "Command-D",
        "Eject the selected disk or volume.": "Command-E",
        "Start a Spotlight search in the Finder window.": "Command-F",
        "Show the Get Info window for a selected file.": "Command-I",
        "Open the Computer window.": "Shift-Command-C",
        "Open the desktop folder.": "Shift-Command-D",
        "Open the All My Files window.": "Shift-Command-F",
        "Open a Go to Folder window.": "Shift-Command-G",
        "Open the Home folder of the current macOS user account.": "Shift-Command-H",
        "Open iCloud Drive.": "Shift-Command-I",
        "Open the Network window.": "Shift-Command-K",
        "Open the Downloads folder.": "Option-Command-L",
        "Open the Documents folder.": "Shift-Command-O",
        "Open the AirDrop window.": "Shift-Command-R",
        "Add selected Finder item to the Dock (OS X Mavericks or later).": "Control-Shift-Command-T",
        "Open the Utilities folder.": "Shift-Command-U",
        "Show or hide the Dock.": "Option-Command-D",
        "Add the selected item to the sidebar (OS X Mavericks or later).": "Control-Command-T",
        "Hide or show the path bar in Finder windows.": "Option-Command-P",
        "Hide or show the Sidebar in Finder windows.": "Option-Command-S",
        "Hide or show the status bar in Finder windows.": "Command-/",
        "Show View Options.": "Command-J",
        "Open the Connect to Server window.": "Command-K",
        "Make an alias of the selected item.": "Control-Command-A",
        "Open a new Finder window.": "Command-N",
        "Create a new folder.": "Shift-Command-N",
        "Create a new Smart Folder.": "Option-Command-N",
        "Show the original file for the selected alias.": "Command-R",
        "Show or hide the tab bar when a single tab is open in the current Finder window.": "Command-T",
        "Show or hide a Finder tab.": "Shift-Command-T",
        "Show or hide the toolbar when a single tab is open in the current Finder window.": "Option-Command-T",
        "Move: Move the files in the Clipboard from their original location to the current location.": "Option-Command-V",
        "View a Quick Look slideshow of the selected files.": "Option-Command-Y",
        "Use Quick Look to preview the selected files.": "Command-Y",
        "View the items in the Finder window as icons.": "Command-1",
        "View the items in a Finder window as a list.": "Command-2",
        "View the items in a Finder window in columns.": "Command-3",
        "View the items in a Finder window with Cover Flow (or Gallery).": "Command-4",
        "Go to the previous folder.": "Command-[",
        "Go to the next folder.": "Command-]",
        "Open the folder that contains the current folder.": "Command-Up Arrow",
        "Open the folder that contains the current folder in a new window.": "Control-Command-Up Arrow",
        "Open the selected item.": "Command-Down Arrow",
        "Open the selected folder (list view only).": "Right Arrow",
        "Close the selected folder (list view only).": "Left Arrow",
        "Open a folder in a separate window and close the current window.": "Option double-click folder",
        "Open a folder in a separate tab or window.": "Command double-click folder",
        "Move the selected item to the Trash.": "Command-Delete",
        "Empty the Trash.": "Shift-Command-Delete",
        "Empty the Trash without confirmation dialog.": "Option-Shift-Command-Delete",
        "Open Displays preferences.": "Option-Brightness Up",
        "Turn display mirroring on or off when your Mac is connected to more than one display.": "Command-Brightness Down",
        "Turn Target Display Mode on or off.": "Command-Brightness Up",
        "Open Mission Control preferences.": "Option-Mission Control",
        "Show the desktop.": "Command-Mission Control or Fn-H or Fn-F11",
        "Open Mission Control.": "Control-Up Arrow",
        "Open Sound preferences.": "Option-Volume Up",
        "Move the dragged item to another volume or location.": "Command while dragging",
        "Copy the dragged item.": "Option while dragging",
        "Make an alias of the dragged item.": "Option-Command while dragging",
        "Open all folders within the selected folder (list view).": "Option-click a disclosure triangle",
        "See the folders that contain the current folder.": "Command-click a window title",
    },

    "Common": {
        "Cut the selected item and copy it to the Clipboard.": "Command-X",
        "Copy the selected item to the Clipboard.": "Command-C",
        "Paste the contents of the Clipboard.": "Command-V",
        "Undo the previous command.": "Command-Z",
        "Redo the undone command.": "Shift-Command-Z",
        "Select all items.": "Command-A",
        "Find items.": "Command-F",
        "Find next occurrence.": "Command-G",
        "Find previous occurrence.": "Shift-Command-G",
        "Hide front app windows.": "Command-H",
        "Hide other apps.": "Option-Command-H",
        "Minimize front window.": "Command-M",
        "Minimize all windows of front app.": "Option-Command-M",
        "Open selected item.": "Command-O",
        "Print current document.": "Command-P",
        "Quit current app.": "Command-Q",
        "Save current document.": "Command-S",
        "Open new tab.": "Command-T",
        "Close front window.": "Command-W",
        "Close all windows of the app.": "Option-Command-W",
        "Force quit an app.": "Option-Command-Esc",
        "Show/hide Spotlight search field.": "Command-Space bar",
        "Spotlight search from Finder window.": "Command-Option-Space bar",
        "Show Character Viewer.": "Control-Command-Space bar or Fn-E",
        "Toggle full screen mode.": "Control-Command-F",
        "Use Quick Look to preview selected item.": "Space bar",
        "Switch to next most recently used app.": "Command-Tab",
        "Switch between windows of current app.": "Command-Grave accent (`)",
        "Take screenshot or make screen recording.": "Shift-Command-5",
        "Screenshots.": "Shift-Command-3 or Shift-Command-4",
        "Create new empty folder in Finder.": "Shift-Command-N",
        "Create new folder containing selected items.": "Control-Command-N",
        "Open preferences for front app.": "Command-Comma (,)",
        "Create a Quick Note.": "Fn-Q",
    },

    "SleepAndShutdown": {
        "Turn on or wake Mac / press and hold for sleep / force turn off.": "Power button",
        "Put Mac to sleep.": "Option-Command-Power button or Option-Command-Media Eject",
        "Put displays to sleep.": "Control-Shift-Power button or Control-Shift-Media Eject",
        "Show restart/sleep/shut down dialog.": "Control-Power button or Control-Media Eject",
        "Force restart Mac.": "Control-Command-Power button",
        "Quit apps and restart Mac.": "Control-Command-Media Eject",
        "Quit apps and shut down Mac.": "Control-Option-Command-Power button or Media Eject",
        "Immediately lock screen.": "Control-Command-Q",
        "Log out with confirmation.": "Shift-Command-Q",
        "Log out immediately without confirmation.": "Option-Shift-Command-Q",
        "Complete action without confirmation when choosing Log Out, Shut Down, or Restart.": "Option key while choosing action"
    }
}

# Source URL:
# https://support.apple.com/en-jo/HT201236