# coding: utf8

shortcuts = {
    "Mac Keyboard Shortcuts": {
        "Cut, copy, paste, and other common shortcuts": {
            "Cut the selected item and copy it to the Clipboard": "Command-X",
            "Copy the selected item to the Clipboard": "Command-C",
            "Paste the contents of the Clipboard into the current document or app": "Command-V",
            "Undo the previous command": "Command-Z",
            "Redo the undo command": "Shift-Command-Z",
            "Select All items": "Command-A",
            "Find items in a document or open a Find window": "Command-F",
            "Find Again the next occurrence": "Command-G",
            "Find Again the previous occurrence": "Shift-Command-G",
            "Hide the windows of the front app": "Command-H",
            "Hide all other apps": "Option-Command-H",
            "Minimize the front window": "Command-M",
            "Minimize all windows": "Option-Command-M",
            "Open the selected item or file dialog": "Command-O",
            "Open print dialog": "Command-P",
            "Quit the current app": "Command-Q",
            "Save the current document": "Command-S",
            "Open a new tab": "Command-T",
            "Close the front window": "Command-W",
            "Close all windows": "Option-Command-W",
            "Force quit an app": "Option-Command-Esc",
            "Show or hide Spotlight search field": "Command–Space bar",
            "Spotlight search from Finder window": "Command–Option–Space bar",
            "Show Character Viewer": "Control–Command–Space bar or Fn-E",
            "Toggle full screen mode": "Control-Command-F",
            "Quick Look preview": "Space bar",
            "Switch to next most recently used app": "Command-Tab",
            "Switch between windows of the app": "Command–Grave accent (`)",
            "Screenshot or screen recording": "Shift-Command-5",
            "Screenshots": "Shift-Command-3 or Shift-Command-4",
            "Create new folder in Finder": "Shift-Command-N",
            "Create new folder containing selected items": "Control-Command-N",
            "Open settings/preferences for front app": "Command-Comma (,)",
            "Create a Quick Note": "Fn-Q"
        },
        "Sleep, log out, and shut down shortcuts": {
            "Press power button to turn on or wake Mac; hold 1.5s to sleep; continue holding to force off": "Power button",
            "Put Mac to sleep": "Option–Command–Power button or Option-Command-Media Eject",
            "Put displays to sleep": "Control–Shift–Power button or Control-Shift-Media Eject",
            "Show restart/sleep/shutdown dialog": "Control–Power button or Control-Media Eject",
            "Force restart Mac without prompt": "Control–Command–Power button",
            "Quit apps then restart Mac": "Control-Command-Media Eject",
            "Quit apps then shut down Mac": "Control–Option–Command–Power button or Control-option-Command-Media Eject",
            "Immediately lock screen": "Control-Command-Q",
            "Log out with confirmation": "Shift-Command-Q",
            "Log out immediately": "Option-Shift-Command-Q"
        },
        "Finder and system shortcuts": {
            "Duplicate selected files": "Command-D",
            "Eject disk or volume": "Command-E",
            "Start Spotlight search in Finder window": "Command-F",
            "Show Get Info window": "Command-I",
            "Show original file for alias, refresh page, or check software updates": "Command-R",
            "Open Computer window": "Shift-Command-C",
            "Open desktop folder": "Shift-Command-D",
            "Open Recents window": "Shift-Command-F",
            "Open Go to Folder window": "Shift-Command-G",
            "Open Home folder": "Shift-Command-H",
            "Open iCloud Drive": "Shift-Command-I",
            "Open Network window": "Shift-Command-K",
            "Open Downloads folder": "Option-Command-L",
            "New folder": "Shift-Command-N",
            "Open Documents folder": "Shift-Command-O",
            "Show/hide Preview pane in Finder": "Shift-Command-P",
            "Open AirDrop window": "Shift-Command-R",
            "Show/hide tab bar in Finder": "Shift-Command-T",
            "Add selected Finder item to Dock": "Control-Shift-Command-T",
            "Press and hold to use/stop Dock magnification": "Control-Shift",
            "Open Utilities folder": "Shift-Command-U",
            "Show/hide the Dock": "Option-Command-D",
            "Add selected item to sidebar": "Control-Command-T",
            "Hide/show path bar in Finder": "Option-Command-P",
            "Hide/show Sidebar in Finder": "Option-Command-S",
            "Hide/show status bar in Finder": "Command–Slash (/)",
            "Show View Options": "Command-J",
            "Open Connect to Server window": "Command-K",
            "Make alias of selected item": "Control-Command-A",
            "Open new Finder window": "Command-N",
            "Create new Smart Folder": "Option-Command-N",
            "Show/hide tab bar when a single tab is open in Finder": "Command-T",
            "Show/hide toolbar when single tab is open in Finder": "Option-Command-T",
            "Move files in Clipboard to current location": "Option-Command-V",
            "Quick Look preview of selected files": "Command-Y",
            "Quick Look slideshow": "Option-Command-Y",
            "Change Finder view (icons/list/columns/gallery)": "Command-1/2/3/4",
            "Go to previous folder": "Command–Left Bracket ([)",
            "Go to next folder": "Command–Right Bracket (])",
            "Open folder containing current folder": "Command–Up Arrow",
            "Open folder containing current folder in new window": "Control–Command–Up Arrow",
            "Open selected item": "Command–Down Arrow",
            "Open selected folder (list view)": "Right Arrow",
            "Close selected folder (list view)": "Left Arrow",
            "Move selected item to Trash": "Command-Delete",
            "Empty Trash": "Shift-Command-Delete",
            "Empty Trash without confirmation": "Option-Shift-Command-Delete",
            "Toggle video mirroring": "Command–Brightness Down",
            "Open Displays settings": "Option–Brightness Up",
            "Change external display brightness": "Control–Brightness Up/Down",
            "Adjust display brightness in smaller steps": "Option–Shift–Brightness Up/Down",
            "Open Mission Control settings": "Option–Mission Control",
            "Show desktop": "Command–Mission Control or Fn-H or Fn-F11",
            "Open Mission Control": "Control–Up Arrow",
            "Show all windows of front app": "Control–Down Arrow",
            "Open Sound settings": "Option–Volume Up",
            "Adjust sound volume in smaller steps": "Option–Shift–Volume Up/Down",
            "Open Keyboard settings": "Option–Keyboard Brightness Up",
            "Adjust keyboard brightness in smaller steps": "Option–Shift–Keyboard Brightness Up/Down",
            "Open item in separate window then close original": "Option key while double-clicking",
            "Open folder in separate tab or window": "Command key while double-clicking",
            "Move dragged item to other volume": "Command key while dragging to another volume",
            "Copy dragged item": "Option key while dragging",
            "Make alias of dragged item": "Option-Command while dragging",
            "Open all folders within selected folder (list view)": "Option-click a disclosure triangle",
            "See containing folders": "Command-click a window title",
            "Select multiple items": "Command or Shift while selecting item",
            "Show or hide Dock": "Fn-A",
            "Show or hide Control Center": "Fn-C",
            "Start or stop dictation": "Fn-D",
            "Show or hide Notification Center": "Fn-N",
            "Show or hide Launchpad": "Fn-Shift-A",
            "Open Character Viewer": "Fn-Fn",
            "Open or close Type to Siri (press Command twice)": "Command + Command (press twice)",
            "Select previous input source when using multiple input sources": "Control–Space bar",
            "Select next input source when using multiple input sources": "Control–Option–Space bar"
        },
        "Text-editing shortcuts": {
            "Boldface text": "Command-B",
            "Italicize text": "Command-I",
            "Add web link": "Command-K",
            "Underline text": "Command-U",
            "Show/hide Fonts window": "Command-T",
            "Select Desktop folder in Open/Save dialog": "Command-D",
            "Show/hide definition of selected word": "Control-Command-D",
            "Show Spelling and Grammar window": "Shift-Command-Colon (:)",
            "Find misspelled words": "Command-Semicolon (;)",
            "Delete word to left": "Option-Delete",
            "Delete character to left": "Control-H",
            "Delete character to right": "Control-D",
            "Forward delete on keyboards without Forward Delete key": "Fn-Delete",
            "Delete text to end of line or paragraph": "Control-K",
            "Page Up": "Fn–Up Arrow",
            "Page Down": "Fn–Down Arrow",
            "Home (start of document)": "Fn–Left Arrow",
            "End (end of document)": "Fn–Right Arrow",
            "Move insertion point to start of document": "Command–Up Arrow",
            "Move insertion point to end of document": "Command–Down Arrow",
            "Move insertion point to beginning of line": "Command–Left Arrow",
            "Move insertion point to end of line": "Command–Right Arrow",
            "Move insertion point to beginning of previous word": "Option–Left Arrow",
            "Move insertion point to end of next word": "Option–Right Arrow",
            "Select text to beginning of document": "Shift–Command–Up Arrow",
            "Select text to end of document": "Shift–Command–Down Arrow",
            "Select text to beginning of line": "Shift–Command–Left Arrow",
            "Select text to end of line": "Shift–Command–Right Arrow",
            "Extend text selection by characters or lines": "Shift–Up/Down/Left/Right Arrow",
            "Extend selection by paragraph or word boundaries": "Option–Shift–Up/Down/Left/Right Arrow",
            "Various cursor and text manipulation controls": "Control-A/E/F/B/L/P/N/O/T",
            "Left align": "Command–Left Curly Bracket ({)",
            "Right align": "Command–Right Curly Bracket (})",
            "Center align": "Shift–Command–Vertical bar (|)",
            "Go to search field": "Option-Command-F",
            "Show/hide toolbar": "Option-Command-T",
            "Copy style": "Option-Command-C",
            "Paste style": "Option-Command-V",
            "Paste and match style": "Option-Shift-Command-V",
            "Show/hide inspector window": "Option-Command-I",
            "Page setup": "Shift-Command-P",
            "Show Save As dialog or duplicate document": "Shift-Command-S",
            "Decrease size of selected item": "Shift–Command–Minus (-)",
            "Increase size of selected item": "Shift–Command–Plus (+) or Command–Equal (=)",
            "Open Help menu": "Shift–Command–Question mark (?)"
        },
        "Accessibility shortcuts": {
            "Invert colors": "Control-Option-Command-8",
            "Reduce contrast": "Control-Option-Command-Comma (,)",
            "Increase contrast": "Control-Option-Command-Period (.)",
            "Move focus to menu bar": "Control-F2 or Fn-Control-F2",
            "Move focus to Dock": "Control-F3 or Fn-Control-F3",
            "Focus active window or next window": "Control-F4 or Fn-Control-F4",
            "Focus window toolbar": "Control-F5 or Fn-Control-F5",
            "Focus floating window": "Control-F6 or Fn-Control-F6",
            "Focus previous panel": "Control-Shift-F6",
            "Toggle Tab moves focus behavior": "Control-F7 or Fn-Control-F7",
            "Focus status menu in menu bar": "Control-F8 or Fn-Control-F8",
            "Activate next open window": "Command–Grave accent (`)",
            "Activate previous open window": "Shift–Command–Grave accent (`)",
            "Move focus to window drawer": "Option–Command–Grave accent (`)",
            "Move to next control": "Tab",
            "Move to previous control": "Shift-Tab",
            "Move to next control in text fields": "Control-Tab",
            "Move to previous control grouping": "Control-Shift-Tab",
            "Navigate lists/tabs/menus; adjust sliders": "Arrow keys",
            "Move to control adjacent to text field": "Control–Arrow keys",
            "Show Accessibility Shortcuts panel": "Option-Command-F5 or triple-press Touch ID"
        },
        "App-specific shortcuts": "Links provided for shortcuts of Apple TV, App Store, Calendar, Contacts, Disk Utility, Find My, iMovie, Keynote, Mail, Maps, Messages, Music, News, Notes, Numbers, Pages, Photos, Podcasts, Reminders, Preview, Safari, Spotlight, Terminal, Voice Memos apps."
    },
    "page_url": "https://support.apple.com/en-jo/HT201236"
}