# coding: utf8
shortcuts = {
    "Firefox":{
        #https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
        #https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/Keyboard_shortcuts
        "Navigation - Back    ":"command + ← or command + [ or Delete",
        "Navigation - Forward ":"command + → or command + ] or Shift + Delete",
        "Navigation - Home   ":"option + home",
        "Navigation - Open File   ":"command + O",
        "Navigation - Reload  ":"F5 or command + R",
        "Navigation - Reload (override cache) ":"command + shift + R",
        "Navigation - Stop    ":"Esc  or command + .",
        "Current Page - Go Down a Screen    ":"fn + ↓",
        "Current Page - Go Up a Screen  ":"fn + ↑ or Shift + Space bar",
        "Current Page - Go to Bottom of Page    ":"End or command + ↓",
        "Current Page - Go to Top of Page   ":"Home or command + ↑",
        "Current Page - Move to Next Frame  ":"F6",
        "Current Page - Move to Previous Frame  ":"Shift + F6",
        "Current Page - Print   ":"command + P",
        "Current Page - Save Page As    ":"command + S",
        "Current Page - Zoom In ":"command + +",
        "Current Page - Zoom Out    ":"command + -",
        "Current Page - Zoom Reset  ":"command + 0",
        "Editing - Copy    ":"command + C",
        "Editing - Cut ":"command + X",
        "Editing - Delete  ":"delete",
        "Editing - Paste  ":"command + V",
        "Editing - Paste (as plain text)   ":"command + shift + V",
        "Editing - Redo    ":"command + shift + Z",
        "Editing - Select All  ":"command + A",
        "Editing - Undo    ":"command + Z",
        "Search - Find    ":"command + F ",
        "Search - Find Again  ":"F3 or command + G ",
        "Search - Find Previous   ":"Shift + F3 or command + shift + G ",
        "Search - Quick Find within link-text only    ":"'   ",
        "Search - Quick Find  ":"/   ",
        "Search - Close the Find or Quick Find bar    ":"Esc - when the Find or Quick Find bar is focused",
        "Search - Focus Search bar    ":"command + K or command + option + F    ",
        "Search - Quickly switch between search engines   ":"command + ↑ or command + ↓ - when Search Bar is focused",
        "Search - View menu to switch, add or manage search engines":"option + ↑ or option + ↓  - when Search Bar is focused",
        "Windows/tabs - Close Tab   ":"command + W - except for App Tabs",
        "Windows/tabs - Close Window    ":"command + shift + W ",
        "Windows/tabs - Move Tab in focus Left  ":"Ctrl + Shift + Page Up  ",
        "Windows/tabs - Move Tab in focus ":"Right Ctrl + Shift + Page Down    ",
        "Windows/tabs - Move Tab in focus to start  ":"command + home  ",
        "Windows/tabs - Move Tab in focus to end    ":"command + end   ",
        "Windows/tabs - Mute/Unmute Audio   ":"Ctrl + M    ",
        "Windows/tabs - New Tab ":"command + T ",
        "Windows/tabs - New Window  ":"command + N ",
        "Windows/tabs - New Private Window  ":"command + shift + P ",
        "Windows/tabs - Next Tab    ":"control + tab or control + page down or command + option + →    ",
        "Windows/tabs - Open Address in New Tab ":"option + return - from Location Bar or Search Bar",
        "Windows/tabs - Previous Tab    ":"control + shift + tab or control + page up or command + option + ←    ",
        "Windows/tabs - Undo Close Tab  ":"command + shift + T ",
        "Windows/tabs - Undo Close Window   ":"command + shift + N ",
        "Windows/tabs - Select Tab 1 to 8   ":"command + 1to8  ",
        "Windows/tabs - Select Last Tab ":"command + 9",
        "History - History sidebar ":"command + shift + H",
        "History - Clear Recent History    ":"command + shift + delete",
        "Bookmarks - Bookmark All Tabs   ":"command + shift + D",
        "Bookmarks - Bookmark This Page  ":"command + D",
        "Bookmarks - Bookmarks sidebar   ":"command + B",
        "Bookmarks - Library window  ":"command + shift + B",
        "Tools - Downloads   ":"command + J",
        "Tools - Add-ons ":"command + shift + A",
        "Tools - Toggle Developer Tools  ":"F12 or command + alt + I",
        "Tools - Web Console ":"command + alt + K",
        "Tools - Inspector   ":"command + alt + C",
        "Tools - Debugger    ":"command + alt + S",
        "Tools - Style Editor    ":"Shift + F7",
        "Tools - Profiler    ":"Shift + F5",
        "Tools - Network ":"command + alt + Q",
        "Tools - Developer Toolbar   ":"Shift + F2",
        "Tools - Responsive Design View  ":"command + alt + M",
        "Tools - Scratchpad  ":"Shift + F4",
        "Tools - Page Source ":"command + U",
        "Tools - Browser Console ":"command + shift + J",
        "Tools - Page Info   ":"command + I",
        "PDF Viewer - Next page   ":"N or J or →",
        "PDF Viewer - Previous page   ":"P or K or ←",
        "PDF Viewer - Zoom in ":"command + +",
        "PDF Viewer - Zoom out    ":"command + -",
        "PDF Viewer - Automatic Zoom  ":"command + 0",
        "PDF Viewer - Rotate the document clockwise   ":"R",
        "PDF Viewer - Rotate counterclockwise ":"Shift + R",
        "PDF Viewer - Switch to Presentation Mode ":"command + Alt + P",
        "PDF Viewer - Toggle Hand Tool    ":"H",
        "PDF Viewer - Focus the Page Number input box ":"command + Alt + G",
        "Complete .com Address   ":"command + return",
        "Complete .net Address   ":"shift + return",
        "Complete .org Address   ":"command + shift + return",
        "Delete Selected Autocomplete Entry  ":"shift + delete",
        "Toggle Full Screen  ":"command+Shift+F",
        "Toggle Reader Mode  ":"command+option+R",
        "Caret Browsing  ":"F7",
        "Select Location Bar ":"F6 or command + L",
        "Media - Toggle Play / Pause ":"Space bar",
        "Media - Decrease volume ":"↓",
        "Media - Increase volume ":"↑",
        "Media - Mute audio  ":"command + ↓",
        "Media - Unmute audio    ":"command + ↑",
        "Media - Seek back 15 seconds    ":"←",
        "Media - Seek back 10 %  ":"command + ←",
        "Media - Seek forward 15 seconds ":"→",
        "Media - Seek forward 10 %   ":"command + →",
        "Media - Seek to the beginning   ":"Home",
        "Media - Seek to the end ":"End",
        "Inspect Element":"Cmd + Opt + C",
        "Node picker - Select the element under the mouse and cancel picker mode   ":"Click",
        "Node picker - Select the element under the mouse and stay in picker mode   ":"Shift+Click ",
        "HTML pane - Delete the selected node    ":"Delete",
        "HTML pane - Undo delete of a node   ":"Cmd + Z",
        "HTML pane - Redo delete of a node   ":"Cmd + Shift + Z / Cmd + Y",
        "HTML pane - Move to next node (expanded nodes only) ":"Down arrow",
        "HTML pane - Move to previous node   ":"Up arrow",
        "HTML pane - Expand currently selected node  ":"Right arrow",
        "HTML pane - Collapse currently selected node    ":"Right arrow",
        "HTML pane - Step forward through the attributes of a node   ":"Tab",
        "HTML pane - Step backward through the attributes of a node  ":"Shift + Tab",
        "HTML pane - Start editing the selected attribute    ":"Enter",
        "HTML pane - Hide/show the selected node ":"H   ",
        "HTML pane - Focus on the search box in the HTML pane    ":"Cmd + F",
        "HTML pane - Edit as HTML    ":"F2",
        "HTML pane - Stop editing HTML   ":"F2 / Ctrl +Enter",
        "HTML pane - Copy the selected node's outer HTML  ":"Cmd + C",
        "HTML pane - Scroll the selected node into view   ":"S",
        "HTML pane - Find the next match in the markup, when searching is active ":"Enter",
        "HTML pane - Find the previous match in the markup, when searching is active  ":"Shift + Enter",
        "Breadcrumbs bar - Move to the previous element in the breadcrumbs bar     ":"Left arrow",
        "Breadcrumbs bar - Move to the next element in the breadcrumbs bar     ":"Right arrow",
        "Breadcrumbs bar - Focus the HTML pane ":"Shift + Tab",
        "Focus the CSS pane  ":"Tab",
        "CSS pane - Focus on the search box in the CSS pane ":"Cmd + F",
        "CSS pane - Clear search box content (only when the search box is focused, and content has been entered)    ":"Esc",
        "CSS pane - Step forward through properties and values  ":"Tab",
        "CSS pane - Step backward through properties and values ":"Shift + Tab",
        "CSS pane - Start editing property or value (Rules view only, when a property or value is selected, but not already being edited)   ":"Enter or Space",
        "CSS pane - Cycle up and down through auto-complete suggestions (Rules view only, when a property or value is being edited) ":"Up arrow , Down arrow",
        "CSS pane - Choose current auto-complete suggestion (Rules view only, when a property or value is being edited) ":"Enter or Tab",
        "CSS pane - Increment selected value by 1   ":"Up arrow",
        "CSS pane - Decrement selected value by 1   ":"Down arrow",
        "CSS pane - Increment selected value by 100 ":"Shift + Page Up",
        "CSS pane - Decrement selected value by 100 ":"Shift + Page Down",
        "CSS pane - Increment selected value by 10  ":"Shift + Up arrow",
        "CSS pane - Decrement selected value by 10  ":"Shift + Down arrow",
        "CSS pane - Increment selected value by 0.1 ":"Opt + Up arrow",
        "CSS pane - Decrement selected value by 0.1 ":"Opt + Down arrow",
        "CSS pane - Show/hide more information about current property (Computed view only, when a property is selected)  ":"Return or Space",
        "CSS pane - Open MDN reference page about current property (Computed view only, when a property is selected) ":"F1",
        "CSS pane - Open current CSS file in Style Editor (Computed view only, when more information is shown for a property and a CSS file reference is focused)    ":"Enter",
        "Increase font size  ":"Cmd +",
        "Decrease font size  ":"Cmd + -",
        "Reset font size ":"Cmd + 0"
    }
}