# coding: utf8

shortcuts = {
    "Gmail": # https://support.google.com/mail/answer/6594?hl=en
      {
		"Previous message in an open conversation": "p",
		"Next message in an open conversation": "n",
		"Focus main window": "⇧Esc",
		"Focus latest chat or compose": "Esc",
		"Advance to the next chat or compose": "Ctrl + .",
		"Advance to previous chat or compose": "Ctrl + ,",
		"Send": "⌘Enter",
		"Add cc recipients": "⌘⇧c",
		"Add bcc recipients": "⌘⇧b",
		"Access custom from": "⌘⇧f",
		"Insert a link": "⌘k",
		"Go to next misspelled word (Mac only)": "⌘;",
		"Open spelling suggestions": "⌘m",
		"Previous font": "⌘⇧5",
		"Next font": "⌘⇧6",
		"Decrease text size": "⌘⇧-",
		"Increase text size": "⌘⇧+",
		"Bold": "⌘b",
		"Italics": "⌘i",
		"Underline": "⌘u",
		"Numbered list": "⌘⇧7",
		"Bulleted list": "⌘⇧8",
		"Quote": "⌘⇧9",
		"Indent less": "⌘[",
		"Indent more": "⌘]",
		"Align left": "⌘⇧l",
		"Align center": "⌘⇧e",
		"Align right": "⌘⇧r",
		"Remove formatting": "⌘\\",
		"Move focus to toolbar": ",",
		"Select conversation": "x",
		"Toggle star/rotate among superstars": "s",
		"Archive": "e",
		"Mute conversation": "m",
		"Report as spam": "!",
		"Delete": "#",
		"Reply": "r",
		"Reply in a new window": "⇧r",
		"Reply all": "a",
		"Reply all in a new window": "⇧a",
		"Forward": "f",
		"Forward in a new window": "⇧f",
		"Update conversation": "⇧n",
		"Archive conversation and go previous/next": "] or [",
		"Undo last action": "z",
		"Mark as read": "⇧i",
		"Mark as unread": "⇧u",
		"Mark unread from the selected message": "_",
		"Mark as important": "+ or =",
		"Mark as not important": "-",
		"Snooze": "b",
		"Expand entire conversation": ";",
		"Collapse entire conversation": ":",
		"Add conversation to Tasks": "⇧t",
		"Compose": "c",
		"Compose in a new tab": "d",
		"Search mail": "/",
		"Search chat contacts": "g",
		"Open 'more actions' menu": ".",
		"Open 'move to' menu": "v",
		"Open 'label as' menu": "l",
		"Open keyboard shortcut help": "?",
		"Go to next page": "g + n",
		"Go to previous page": "g + p",
		"Back to threadlist": "u",
		"Newer conversation": "k",
		"Older conversation": "j",
		"Open conversation": "o or Enter",
		"Go to next Inbox section": "`",
		"Go to previous Inbox section": "~",
		"Select all conversations": "* + a",
		"Deselect all conversations": "* + n",
		"Select read conversations": "* + r",
		"Select unread conversations": "* + u",
		"Select starred conversations": "* + s",
		"Select unstarred conversations": "* + t",
		"Go to Inbox": "g + i",
		"Go to Starred conversations": "g + s",
		"Go to Snoozed conversations": "g + b",
		"Go to Sent messages": "g + t",
		"Go to Drafts": "g + d",
		"Go to All mail": "g + a",
		"Switch between sidebar and your inbox.": "⌘Alt + ,  and ⌘Alt + .",
		"Go to Tasks": "g + k",
		"Go to label": "g + l",
		"Hangouts - Show menu": "h + m",
		"Show archived hangouts": "h + a",
		"Show Hangout requests": "h + i",
		"Focus on the conversation list": "h + c",
		"Hangouts - Open phone": "h + p"
	}
}

