# coding: utf8

shortcuts = {
    "Gmail": # https://support.google.com/mail/answer/6594?hl=en
      {
		"Previous message in an open conversation": "p",
		"Next message in an open conversation": "n",
		"Focus main window": "Shift + Esc",
		"Focus latest chat or compose": "Esc",
		"Advance to the next chat or compose": "Ctrl + .",
		"Advance to previous chat or compose": "Ctrl + ,",
		"Send": "⌘/Ctrl + Enter",
		"Add cc recipients": "⌘/Ctrl + Shift + c",
		"Add bcc recipients": "⌘/Ctrl + Shift + b",
		"Access custom from": "⌘/Ctrl + Shift + f",
		"Insert a link": "⌘/Ctrl + k",
		"Go to next misspelled word (Mac only)": "⌘ + ;",
		"Open spelling suggestions": "⌘/Ctrl + m",
		"Previous font": "⌘/Ctrl + Shift + 5",
		"Next font": "⌘/Ctrl + Shift + 6",
		"Decrease text size": "⌘/Ctrl + Shift + -",
		"Increase text size": "⌘/Ctrl + Shift and +",
		"Bold": "⌘/Ctrl + b",
		"Italics": "⌘/Ctrl + i",
		"Underline": "⌘/Ctrl + u",
		"Numbered list": "⌘/Ctrl + Shift + 7",
		"Bulleted list": "⌘/Ctrl + Shift + 8",
		"Quote": "⌘/Ctrl + Shift + 9",
		"Indent less": "⌘/Ctrl + [",
		"Indent more": "⌘/Ctrl + ]",
		"Align left": "⌘/Ctrl + Shift + l",
		"Align center": "⌘/Ctrl + Shift + e",
		"Align right": "⌘/Ctrl + Shift + r",
		"Remove formatting": "⌘/Ctrl + \\",
		"Move focus to toolbar": ",",
		"Select conversation": "x",
		"Toggle star/rotate among superstars": "s",
		"Archive": "e",
		"Mute conversation": "m",
		"Report as spam": "!",
		"Delete": "#",
		"Reply": "r",
		"Reply in a new window": "Shift + r",
		"Reply all": "a",
		"Reply all in a new window": "Shift + a",
		"Forward": "f",
		"Forward in a new window": "Shift + f",
		"Update conversation": "Shift + n",
		"Archive conversation and go previous/next": "] or [",
		"Undo last action": "z",
		"Mark as read": "Shift + i",
		"Mark as unread": "Shift + u",
		"Mark unread from the selected message": "_",
		"Mark as important": "+ or =",
		"Mark as not important": "-",
		"Snooze": "b",
		"Expand entire conversation": ";",
		"Collapse entire conversation": ":",
		"Add conversation to Tasks": "Shift + t",
		"Compose": "c",
		"Compose in a new tab": "d",
		"Search mail": "/",
		"Search chat contacts": "g",
		"Open 'more actions' menu": ".",
		"Open 'move to' menu": "v",
		"Open 'label as' menu": "l",
		"Open keyboard shortcut help": "?",
		"Go to next page": "g + n",
		"Go to previous page": "g + p",
		"Back to threadlist": "u",
		"Newer conversation": "k",
		"Older conversation": "j",
		"Open conversation": "o or Enter",
		"Go to next Inbox section": "`",
		"Go to previous Inbox section": "~",
		"Select all conversations": "* + a",
		"Deselect all conversations": "* + n",
		"Select read conversations": "* + r",
		"Select unread conversations": "* + u",
		"Select starred conversations": "* + s",
		"Select unstarred conversations": "* + t",
		"Go to Inbox": "g + i",
		"Go to Starred conversations": "g + s",
		"Go to Snoozed conversations": "g + b",
		"Go to Sent messages": "g + t",
		"Go to Drafts": "g + d",
		"Go to All mail": "g + a",
		"Switch between sidebar and your inbox.": "⌘/Ctrl + Alt + ,  and ⌘/Ctrl + Alt + .",
		"Go to Tasks": "g + k",
		"Go to label": "g + l",
		"Hangouts - Show menu": "h + m",
		"Show archived hangouts": "h + a",
		"Show Hangout requests": "h + i",
		"Focus on the conversation list": "h + c",
		"Hangouts - Open phone": "h + p"
	}
}

