# coding: utf8

shortcuts = {
    "Google Sheets Mac Shortcuts": {
        "Page URL": "https://support.google.com/docs/answer/181110",
        "Common actions": {
            "Select column": "Ctrl + Space",
            "Select row": "Shift + Space",
            "Select all": "⌘ + a",
            "Select all (alternative to shift select entire row/col)": "⌘ + Shift + Space",
            "Undo": "⌘ + z",
            "Redo": ["⌘ + y", "⌘ + Shift + z", "Fn + F4"],
            "Find": "⌘ + f",
            "Find and replace": "⌘ + Shift + h",
            "Fill range": "⌘ + Enter",
            "Fill down": "⌘ + d",
            "Fill right": "⌘ + r",
            "Save": "⌘ + s",
            "Open": "⌘ + o",
            "Print": "⌘ + p",
            "Copy": "⌘ + c",
            "Cut": "⌘ + x",
            "Paste": "⌘ + v",
            "Paste values only": "⌘ + Shift + v",
            "Show common keyboard shortcuts": "⌘ + /",
            "Insert new sheet": "Shift + Fn + F11",
            "Compact controls": "Ctrl + Shift + f",
            "Input tools on/off": "⌘ + Shift + k",
            "Select input tools": "⌘ + Option + Shift + k",
            "Tool finder (formerly Search the menus)": "Option + /",
            "Select current region around selected cell": "⌘ + Shift + *",
            "Displays or hides the menus": "Ctrl + Shift + *",
            "Show/hide menus": "⌘ + Option + R",
            "Convert range to table": "⌘ + Alt + T"
        },
        "Format cells": {
            "Bold": ["⌘ + b", "⌘ + 2", "Ctrl + 2"],
            "Underline": ["⌘ + u", "⌘ + 4", "Ctrl + 4"],
            "Italic": ["⌘ + i", "⌘ + 3", "Ctrl + 3"],
            "Strikethrough": ["⌘ + Shift + x", "⌘ + 5", "Ctrl + 5"],
            "Center align": "⌘ + Shift + e",
            "Left align": "⌘ + Shift + l",
            "Right align": "⌘ + Shift + r",
            "Apply top border": "Option + Shift + 1",
            "Apply right border": "Option + Shift + 2",
            "Apply bottom border": "Option + Shift + 3",
            "Apply left border": "Option + Shift + 4",
            "Remove borders": "Option + Shift + 6",
            "Apply outer border": ["Option + Shift + 7", "⌘ + Shift + 7", "Ctrl + Shift + 7"],
            "Insert link": "⌘ + k",
            "Insert time": "⌘ + Shift + ;",
            "Insert date": "⌘ + ;",
            "Insert date and time": "⌘ + Option + Shift + ;",
            "Format as decimal": "Ctrl + Shift + 1",
            "Format as time": "Ctrl + Shift + 2",
            "Format as date": "Ctrl + Shift + 3",
            "Format as currency": "Ctrl + Shift + 4",
            "Format as percentage": "Ctrl + Shift + 5",
            "Format as exponent": "Ctrl + Shift + 6",
            "Clear formatting": "⌘ + \\"
        },
        "Navigate spreadsheet": {
            "Move to beginning of row": "Fn + Left Arrow",
            "Move to beginning of sheet": "⌘ + Fn + Left Arrow",
            "Move to end of row": "Fn + Right Arrow",
            "Move to end of sheet": "⌘ + Fn + Right Arrow",
            "Scroll to active cell": "⌘ + Backspace",
            "Move to next sheet": "Option + Down Arrow (MacBook: Option + Right Arrow)",
            "Move to previous sheet": "Option + Up Arrow (MacBook: Option + Left Arrow)",
            "Display list of sheets": "Option + Shift + k",
            "Open hyperlink": "Option + Enter",
            "Open Explore": "⌘ + Option + Shift + i",
            "Go to side panel": "⌘ + Option + .",
            "Move focus out of spreadsheet": "⌘ + Option + ,",
            "Move to quicksum (when a range of cells is selected)": "Option + Shift + q",
            "Move focus to popup (for links, bookmarks, images)": "holding Ctrl + ⌘, press e then p",
            "Open drop-down menu on filtered cell": "Ctrl + ⌘ + r",
            "Open revision history": "⌘ + Option + Shift + h",
            "Close drawing editor": ["⌘ + Esc", "Shift + Esc"],
            "Show \"Go to range\" dialog": "Ctrl + G",
            "Find and replace with Find tab selected": "Ctrl + F"
        },
        "Edit notes and comments": {
            "Insert/edit note": "Shift + F2",
            "Insert/edit comment": "⌘ + Option + m",
            "Open comment discussion thread": "⌘ + Option + Shift + a",
            "Enter current comment": "holding Ctrl + ⌘, press e then c",
            "Move to next comment": "holding Ctrl + ⌘, press n then c",
            "Move to previous comment": "holding Ctrl + ⌘, press p then c",
            "Reply to current comment": "R",
            "Move to next comment (keyboard shortcuts on selected comments)": "J",
            "Move to previous comment (keyboard shortcuts on selected comments)": "K",
            "Resolve current comment": "E",
            "Exit current comment": "U"
        },
        "Open a menu": {
            "File menu": "Ctrl + Option + f",
            "Edit menu": "Ctrl + Option + e",
            "View menu": "Ctrl + Option + v",
            "Insert menu": "Ctrl + Option + i",
            "Format menu": "Ctrl + Option + o",
            "Data menu": "Ctrl + Option + d",
            "Tools menu": "Ctrl + Option + t",
            "Open insert menu (with cells selected)": "⌘ + Option + =",
            "Open delete menu (with cells selected)": "⌘ + Option + -",
            "Form menu (when spreadsheet connected to a form)": "Ctrl + Option + m",
            "Add-ons menu": "Ctrl + Option + n",
            "Help menu": "Ctrl + Option + h",
            "Accessibility menu (screen reader support enabled)": "Ctrl + Option + a",
            "Sheet menu (copy, delete, other sheet actions)": "Option + Shift + s",
            "Context menu": ["⌘ + Shift + \\", "Shift + F10"],
            "Table column menu": "⌘ + Option + \\"
        },
        "Add or change rows and columns": {
            "Insert rows above": ["⌘ + Option + = (with rows selected)", "Ctrl + Option + i, then r, then r"],
            "Insert rows below": "Ctrl + Option + i, then r, then b",
            "Insert columns to the left": ["⌘ + Option + = (with columns selected)", "Ctrl + Option + i, then c, then c"],
            "Insert columns to the right": "Ctrl + Option + i, then c, then o",
            "Delete rows": ["⌘ + Option + - (with rows selected)", "Ctrl + Option + e, then d, then d"],
            "Delete columns": ["⌘ + Option + - (with columns selected)", "Ctrl + Option + e, then d, then e"],
            "Hide row": "⌘ + Option + 9",
            "Unhide row": "⌘ + Shift + 9",
            "Hide column": "⌘ + Option + 0",
            "Unhide column": "⌘ + Shift + 0",
            "Group rows or columns": "Option + Shift + Right Arrow",
            "Ungroup rows or columns": "Option + Shift + Left Arrow",
            "Expand grouped rows or columns": "Option + Shift + Down Arrow",
            "Collapse grouped rows or columns": "Option + Shift + Up Arrow"
        },
        "Use formulas": {
            "Show all formulas": "Ctrl + ~",
            "Insert array formula": "⌘ + Shift + Enter",
            "Collapse an expanded array formula": "⌘ + e",
            "Show/hide formula help (when entering formula)": "Shift + Fn + F1",
            "Full/compact formula help (when entering formula)": "Fn + F1",
            "Absolute/relative references (when entering formula)": "Fn + F4",
            "Toggle formula result previews (when entering formula)": "Fn + F9",
            "Resize formula bar (move up or down)": ["Ctrl + Option + Up", "Ctrl + Option + Down"],
            "Toggle formula range selection (when entering formula)": ["F2", "Ctrl + e"]
        },
        "Help for screen readers": {
            "Turn on screen reader support": "⌘ + Option + z",
            "Enable braille support": "⌘ + Option + h",
            "Read column": "⌘ + Option + Shift + c",
            "Read row": "⌘ + Option + Shift + r"
        }
    }
}