# coding: utf8

shortcuts = {
    "Google Docs": #https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en
      {
          "Copy": "⌘c",
          "Cut": "⌘x",
          "Paste": "⌘v",
          "Paste without formatting": "⌘⇧v",
          "Undo": "⌘z",
          "Redo": "⌘⇧z",
          "Insert or edit link": "⌘k",
          "Open link": "⌥⏎",
          "Show common keyboard shortcuts": "⌘/",
          "Every change is automatically saved in Drive": "⌘s",
          "Print": "⌘p",
          "Open": "⌘o",
          "Find": "⌘f",
          "Find and replace": "⌘⇧h",
          "Find again": "⌘g",
          "Find previous": "⌘⇧g",
          "Hide the menus (compact mode)": "Ctrl ⇧f",
          "Insert page break": "⌘⏎",
          "Search the menus": "⌥/ or Ctrl ⌥z",
          "Repeat last action": "⌘y",
          "Bold": "⌘b",
          "Italicize": "⌘i",
          "Underline": "⌘u",
          "Strikethrough": "⌘⇧x",
          "Superscript": "⌘.",
          "Subscript": "⌘,",
          "Copy text formatting": "⌘⌥c",
          "Paste text formatting": "⌘⌥v",
          "Clear text formatting": "⌘\\",
          "Increase font size": "⌘⇧>",
          "Decrease font size": "⌘⇧<",
          "Increase paragraph indentation": "⌘]",
          "Decrease paragraph indentation": "⌘[",
          "Apply normal text style": "⌘⌥0",
          "Apply heading style [1-6]": "⌘⌥[1-6]",
          "Left align": "⌘⇧l",
          "Center align": "⌘⇧e",
          "Right align": "⌘⇧r",
          "Justify": "⌘⇧j",
          "Numbered list": "⌘⇧7",
          "Bulleted list": "⌘⇧8",
          "Move paragraph up/down": "Ctrl ⇧↑ or Ctrl ⇧↓",
          "Alt text": "⌘⌥y",
          "Resize larger": "⌘Ctrl k",
          "Resize larger horizontally": "⌘Ctrl b",
          "Resize larger vertically": "⌘Ctrl i",
          "Resize smaller": "⌘Ctrl j",
          "Resize smaller horizontally": "⌘Ctrl w",
          "Resize smaller vertically": "⌘Ctrl q",
          "Rotate clockwise by 15°": "⌥→",
          "Rotate counterclockwise by 15°": "⌥←",
          "Rotate counterclockwise by 1°": "⌥⇧←",
          "Rotate clockwise by 1°": "⌥⇧→",
          "Close drawing editor": "⌘Esc or ⇧Esc",
          "Insert comment": "⌘⌥m",
          "Open discussion thread": "⌘⌥⇧a",
          "Enter current comment": "Ctrl ⏎",
          "Insert footnote": "⌘⌥f",
          "Context (right-click) menu": "⌘⇧\\",
          "File menu": "Ctrl ⌥f",
          "Edit menu": "Ctrl ⌥e",
          "View menu": "Ctrl ⌥v",
          "Insert menu": "Ctrl ⌥i",
          "Format menu": "Ctrl ⌥o",
          "Tools menu": "Ctrl ⌥t",
          "Help menu": "Ctrl ⌥h",
          "Accessibility menu": "Ctrl ⌥a",
          "Input tools menu": "⌘⌥⇧k",
          "Toggle input controls": "⌘⇧k",
          "Show your browser's context menu": "⇧ right-click",
          "Select all": "⌘a",
          "Extend selection one character": "⇧← or ⇧→",
          "Extend selection one line": "⇧↑ or ⇧↓",
          "Extend selection to the beginning of the line": "⇧Fn←",
          "Extend selection one paragraph": "⌥⇧↑ or ⌥⇧↓",
          "Extend selection to the end of the line": "⇧Fn→",
          "Extend selection to the beginning of the document": "⌘⇧↑",
          "Extend selection to the end of the document": "⌘⇧↓",
          "Move to current footnote": "holding Ctrl ⌘, press e then f",
          "Move to next footnote": "holding Ctrl ⌘, press n then f",
          "Move to previous footnote": "holding Ctrl ⌘, press p then f",
          "Select current list item": "holding Ctrl ⌘⇧, press e then i",
          "Select all list items at current level": "holding Ctrl ⌘⇧, press e then o",
          "Select word": "Double-click",
          "Extend selection one word at a time": "Double-click + drag",
          "Select paragraph": "Triple-click",
          "Extend selection one paragraph at a time": "Triple-click + drag",
          "Show document outline": "holding Ctrl + ⌘, press a then h",
          "Move to next heading": "holding Ctrl + ⌘, press n then h",
          "Move to previous heading": "holding Ctrl + ⌘, press p then h",
          "Move to next heading [1-6]": "holding Ctrl + ⌘, press n then [1-6]",
          "Move to previous heading [1-6]": "holding Ctrl + ⌘, press p then [1-6]",
          "Move to next media (image or drawing)": "holding Ctrl + ⌘, press n then g",
          "Move to previous media (image or drawing)": "holding Ctrl + ⌘, press p then g",
          "Move to next list": "holding Ctrl + ⌘, press n then o",
          "Move to previous list": "holding Ctrl + ⌘, press p then o",
          "Move to next item in the current list": "holding Ctrl + ⌘, press n then i",
          "Move to previous item in the current list": "holding Ctrl + ⌘, press p then i",
          "Move to next link": "holding Ctrl + ⌘, press n then l",
          "Move to previous link": "holding Ctrl + ⌘, press p then l",
          "Move to next bookmark": "holding Ctrl + ⌘, press n then b",
          "Move to previous bookmark": "holding Ctrl + ⌘, press p then b",
          "Move to next formatting change": "holding Ctrl + ⌘, press n then w",
          "Move to previous formatting change": "holding Ctrl + ⌘, press p then w",
          "Move to the next edit (while viewing revision history or new changes)": "holding Ctrl + ⌘, press n then r",
          "Move to the previous edit (while viewing revision history or new changes)": "holding Ctrl + ⌘, press p then r",
          "Move to the start of the table": "holding Ctrl + ⌘ + Shift, press t then s",
          "Move to the end of the table": "holding Ctrl + ⌘ + Shift, press t then d",
          "Move to the start of the table column": "holding Ctrl + ⌘ + Shift, press t then i",
          "Move to the end of the table column": "holding Ctrl + ⌘ + Shift, press t then k",
          "Move to the next table column": "holding Ctrl + ⌘ + Shift, press t then b",
          "Move to the previous table column": "holding Ctrl + ⌘ + Shift, press t then v",
          "Move to the start of the table row": "holding Ctrl + ⌘ + Shift, press t then j",
          "Move to the end of the table row": "holding Ctrl + ⌘ + Shift, press t then l",
          "Move to the next table row": "holding Ctrl + ⌘ + Shift, press t then m",
          "Move to the previous table row": "holding Ctrl + ⌘ + Shift, press t then g",
          "Exit table": "holding Ctrl + ⌘ + Shift, press t then e",
          "Move to the next table": "holding Ctrl + ⌘ + Shift, press n then t",
          "Move to the previous table": "holding Ctrl + ⌘ + Shift, press p then t",
          "Insert or move to header": "holding Ctrl + ⌘, press o then h",
          "Insert or move to footer": "holding Ctrl + ⌘, press o then f",
          "Move focus to popup (for links, bookmarks, and images)": "holding Ctrl + ⌘, press e then p",
          "Open revision history": "⌘ + Option + Shift + h",
          "Open Explore tool": "⌘ + Option + Shift + i",
          "Open spelling/grammar": "⌘ + Option + x or Fn + F7",
          "Open dictionary": "⌘ + Shift + y",
          "Word count": "⌘ + Shift + c",
          "Start voice typing (in Chrome)": "⌘ + Shift + s",
          "Go to side panel": "⌘ + Option + . or ⌘ + Option + ,",
          "Page up": "Fn + Up arrow",
          "Page down": "Fn + Down arrow",
          "Move to next misspelling": "⌘ + '",
          "Move to previous misspelling": "⌘ + ;",
          "Move focus out of document text": "⌘ + Option + Shift + m",
          "Return focus to document text": "Esc"
      }
  }