# coding: utf8

shortcuts = {
    "Google Docs Mac Shortcuts": {
        "Common actions": {
            "Copy": "⌘ + c",
            "Cut": "⌘ + x",
            "Paste": "⌘ + v",
            "Paste without formatting": "⌘ + Shift + v",
            "Undo": "⌘ + z",
            "Redo": "⌘ + Shift + z",
            "Insert or edit link": "⌘ + k",
            "Open link": "Option + Enter",
            "Show common keyboard shortcuts": "⌘ + /",
            "Save (changes automatically saved)": "⌘ + s",
            "Print": "⌘ + p",
            "Open": "⌘ + o",
            "Find": "⌘ + f",
            "Find and replace": "⌘ + Shift + h",
            "Find again": "⌘ + g",
            "Find previous": "⌘ + Shift + g",
            "Hide the menus (compact mode)": "Ctrl + Shift + f",
            "Insert page break": "⌘ + Enter",
            "Tool finder (formerly Search the menus)": "Option + /",
            "Repeat last action": "Ctrl + Option + z",
            "Switch to editing": "⌘ + y",
            "Switch to suggesting": "⌘ + Option + Shift + z",
            "Switch to viewing": "⌘ + Option + Shift + x",
            "Zoom in": "⌘ + +",
            "Zoom out": "⌘ + -",
            "Zoom 100%": "⌘ + 0"
        },
        "Text formatting": {
            "Bold": "⌘ + b",
            "Italicize": "⌘ + i",
            "Underline": "⌘ + u",
            "Strikethrough": "⌘ + Shift + x",
            "Superscript": "⌘ + .",
            "Subscript": "⌘ + ,",
            "Copy text formatting": "⌘ + Option + c",
            "Paste text formatting": "⌘ + Option + v",
            "Clear text formatting": "⌘ + \\",
            "Increase font size": "⌘ + Shift + .",
            "Decrease font size": "⌘ + Shift + ,"
        },
        "Paragraph formatting": {
            "Increase paragraph indentation": "⌘ + ]",
            "Decrease paragraph indentation": "⌘ + [",
            "Apply normal text style": "⌘ + Option + 0",
            "Apply heading style [1-6]": "⌘ + Option + [1-6]",
            "Left align": "⌘ + Shift + l",
            "Center align": "⌘ + Shift + e",
            "Right align": "⌘ + Shift + r",
            "Justify": "⌘ + Shift + j",
            "Numbered list": "⌘ + Shift + 7",
            "Bulleted list": "⌘ + Shift + 8",
            "Checklist": "⌘ + Shift + 9",
            "Move paragraph up/down": "Ctrl + Shift + Up/down arrow"
        },
        "Images and drawings": {
            "Alt text": "⌘ + Option + y",
            "Resize larger": "⌘ + Ctrl + k",
            "Resize larger horizontally": "⌘ + Ctrl + b",
            "Resize larger vertically": "⌘ + Ctrl + i",
            "Resize smaller": "⌘ + Ctrl + j",
            "Resize smaller horizontally": "⌘ + Ctrl + w",
            "Resize smaller vertically": "⌘ + Ctrl + q",
            "Rotate clockwise by 15°": "Option + Right arrow",
            "Rotate counterclockwise by 15°": "Option + Left arrow",
            "Rotate counterclockwise by 1°": "Option + Shift + Left arrow",
            "Rotate clockwise by 1°": "Option + Shift + Right arrow",
            "Close drawing editor": "⌘ + Esc or Shift + Esc"
        },
        "Comments and footnotes": {
            "Insert comment": "⌘ + Option + m",
            "Open discussion thread": "⌘ + Option + Shift + a",
            "Enter current comment (Ctrl + ⌘, press e then c)": "Ctrl + ⌘, e then c",
            "Insert footnote": "⌘ + Option + f",
            "Move to current footnote (Ctrl + ⌘, press e then f)": "Ctrl + ⌘, e then f",
            "Move to next footnote (Ctrl + ⌘, press n then f)": "Ctrl + ⌘, n then f",
            "Move to previous footnote (Ctrl + ⌘, press p then f)": "Ctrl + ⌘, p then f",
            "Move to next suggestion (Ctrl + ⌘, press n then u)": "Ctrl + ⌘, n then u",
            "Move to previous suggestion (Ctrl + ⌘, press p then u)": "Ctrl + ⌘, p then u",
            "Review suggested edits (Ctrl + ⌘, press o then u)": "Ctrl + ⌘, o then u",
            "Move to next comment (Ctrl + ⌘, press n then c)": "Ctrl + ⌘, n then c",
            "Move to previous comment (Ctrl + ⌘, press p then c)": "Ctrl + ⌘, p then c",
            "Open comment history": "⌘ + Option + Shift + a"
        },
        "Use keyboard shortcuts on selected comments": {
            "Reply to current comment": "R",
            "Move to next comment": "J",
            "Move to previous comment": "K",
            "Resolve current comment": "E",
            "Exit current comment": "U"
        },
        "Menus": {
            "Context (right-click) menu": "⌘ + Shift + \\ or Shift + F10",
            "File menu": "Ctrl + Option + f",
            "Edit menu": "Ctrl + Option + e",
            "View menu": "Ctrl + Option + v",
            "Insert menu": "Ctrl + Option + i",
            "Format menu": "Ctrl + Option + o",
            "Tools menu": "Ctrl + Option + t",
            "Help menu": "Ctrl + Option + h",
            "Accessibility menu (screen reader support enabled)": "Ctrl + Option + a",
            "Input Tools menu (non-Latin languages)": "⌘ + Option + Shift + k",
            "Toggle input controls (non-Latin languages)": "⌘ + Shift + k",
            "Show your browser's context menu": "Shift + right-click"
        },
        "Text selection with keyboard": {
            "Select all": "⌘ + a",
            "Select none (Ctrl + ⌘, press u then a)": "Ctrl + ⌘, u then a",
            "Extend selection one character": "Shift + Left/right arrow",
            "Extend selection one line": "Shift + Up/down arrow",
            "Extend selection to beginning of the line": "Shift + Fn + Left arrow",
            "Extend selection one paragraph": "Option + Shift + Up/Down arrow",
            "Extend selection to end of the line": "Shift + Fn + Right arrow",
            "Extend selection to beginning of the document": "⌘ + Shift + Up arrow",
            "Extend selection to end of the document": "⌘ + Shift + Down arrow",
            "Select current list item (Ctrl + ⌘ + Shift, press e then i)": "Ctrl + ⌘ + Shift, e then i",
            "Select all list items at current level (Ctrl + ⌘ + Shift, press e then o)": "Ctrl + ⌘ + Shift, e then o",
            "Select multiple sections of text": "After selecting one section, Ctrl + ⌘ + Shift + Left/right arrow"
        },
        "Text selection with mouse": {
            "Select word": "Double-click",
            "Extend selection one word at a time": "Double-click + drag",
            "Select paragraph": "Triple-click",
            "Extend selection one paragraph at a time": "Triple-click + drag"
        },
        "Screen reader shortcuts": {
            "Enable screen reader support": "Option + ⌘ + z",
            "Enable braille support": "⌘ + Option + h",
            "Verbalize selection (Ctrl + ⌘, press a then x)": "Ctrl + ⌘, a then x",
            "Verbalize from cursor location (Ctrl + ⌘, press a then r)": "Ctrl + ⌘, a then r",
            "Announce cursor location (Ctrl + ⌘, press a then l)": "Ctrl + ⌘, a then l",
            "Announce formatting at cursor location (Ctrl + ⌘, press a then f)": "Ctrl + ⌘, a then f",
            "Verbalize table row and column headers (Ctrl + ⌘ + Shift, press t then h)": "Ctrl + ⌘ + Shift, t then h",
            "Verbalize table cell location (Ctrl + ⌘ + Shift, press t then n)": "Ctrl + ⌘ + Shift, t then n",
            "Verbalize table row header (Ctrl + ⌘ + Shift, press t then r)": "Ctrl + ⌘ + Shift, t then r",
            "Verbalize table column header (Ctrl + ⌘ + Shift, press t then c)": "Ctrl + ⌘ + Shift, t then c",
            "Show live edits": "⌘ + Option + Shift + r",
            "Verbalize comment (Ctrl + ⌘, press a then c)": "Ctrl + ⌘, a then c",
            "Verbalize comment anchor (Ctrl + ⌘, press a then a)": "Ctrl + ⌘, a then a",
            "Verbalize selection formatting (Ctrl + ⌘, press a then s)": "Ctrl + ⌘, a then s",
            "Verbalize cursor location (Ctrl + ⌘, press A then L)": "Ctrl + ⌘, A then L",
            "Verbalize word count (Ctrl + ⌘, press A then W)": "Ctrl + ⌘, A then W"
        },
        "Navigation shortcuts - Document navigation": {
            "Show outline (Ctrl + ⌘, press a then h)": "Ctrl + ⌘, a then h",
            "Move to next heading (Ctrl + ⌘, press n then h)": "Ctrl + ⌘, n then h",
            "Move to previous heading (Ctrl + ⌘, press p then h)": "Ctrl + ⌘, p then h",
            "Move to next heading [1-6] (Ctrl + ⌘, press n then [1-6])": "Ctrl + ⌘, n then [1-6]",
            "Move to previous heading [1-6] (Ctrl + ⌘, press p then [1-6])": "Ctrl + ⌘, p then [1-6]",
            "Move to next media (image or drawing) (Ctrl + ⌘, press n then g)": "Ctrl + ⌘, n then g",
            "Move to previous media (image or drawing) (Ctrl + ⌘, press p then g)": "Ctrl + ⌘, p then g",
            "Move to next list (Ctrl + ⌘, press n then o)": "Ctrl + ⌘, n then o",
            "Move to previous list (Ctrl + ⌘, press p then o)": "Ctrl + ⌘, p then o",
            "Move to next item in current list (Ctrl + ⌘, press n then i)": "Ctrl + ⌘, n then i",
            "Move to previous item in current list (Ctrl + ⌘, press p then i)": "Ctrl + ⌘, p then i",
            "Move to next link (Ctrl + ⌘, press n then l)": "Ctrl + ⌘, n then l",
            "Move to previous link (Ctrl + ⌘, press p then l)": "Ctrl + ⌘, p then l",
            "Move to next bookmark (Ctrl + ⌘, press n then b)": "Ctrl + ⌘, n then b",
            "Move to previous bookmark (Ctrl + ⌘, press p then b)": "Ctrl + ⌘, p then b",
            "Move to next formatting change (Ctrl + ⌘, press n then w)": "Ctrl + ⌘, n then w",
            "Move to previous formatting change (Ctrl + ⌘, press p then w)": "Ctrl + ⌘, p then w",
            "Move to next edit (Ctrl + ⌘, press n then r)": "Ctrl + ⌘, n then r",
            "Move to previous edit (Ctrl + ⌘, press p then r)": "Ctrl + ⌘, p then r"
        },
        "Navigation shortcuts - Table navigation": {
            "Move to start of table (Ctrl + ⌘ + Shift, press t then s)": "Ctrl + ⌘ + Shift, t then s",
            "Move to end of table (Ctrl + ⌘ + Shift, press t then d)": "Ctrl + ⌘ + Shift, t then d",
            "Move to start of table column (Ctrl + ⌘ + Shift, press t then i)": "Ctrl + ⌘ + Shift, t then i",
            "Move to end of table column (Ctrl + ⌘ + Shift, press t then k)": "Ctrl + ⌘ + Shift, t then k",
            "Move to next table column (Ctrl + ⌘ + Shift, press t then b)": "Ctrl + ⌘ + Shift, t then b",
            "Move to previous table column (Ctrl + ⌘ + Shift, press t then v)": "Ctrl + ⌘ + Shift, t then v",
            "Move to start of table row (Ctrl + ⌘ + Shift, press t then j)": "Ctrl + ⌘ + Shift, t then j",
            "Move to end of table row (Ctrl + ⌘ + Shift, press t then l)": "Ctrl + ⌘ + Shift, t then l",
            "Move to next table row (Ctrl + ⌘ + Shift, press t then m)": "Ctrl + ⌘ + Shift, t then m",
            "Move to previous table row (Ctrl + ⌘ + Shift, press t then g)": "Ctrl + ⌘ + Shift, t then g",
            "Exit table (Ctrl + ⌘ + Shift, press t then e)": "Ctrl + ⌘ + Shift, t then e",
            "Move to next table (Ctrl + ⌘ + Shift, press n then t)": "Ctrl + ⌘ + Shift, n then t",
            "Move to previous table (Ctrl + ⌘ + Shift, press p then t)": "Ctrl + ⌘ + Shift, p then t"
        },
        "Other tools and navigation": {
            "Open revision history": "⌘ + Option + Shift + h",
            "Open Explore tool": "⌘ + Option + Shift + i",
            "Open spelling/grammar": "⌘ + Option + x",
            "Open dictionary": "Fn + F7 or ⌘ + Shift + y",
            "Word count": "⌘ + Shift + c",
            "Start voice typing (Chrome)": "⌘ + Shift + s",
            "Go to side panel": "⌘ + Option + . or ⌘ + Option + ,",
            "Page up": "Fn + Up arrow",
            "Page down": "Fn + Down arrow",
            "Move to next misspelling": "⌘ + '",
            "Move to previous misspelling": "⌘ + ;",
            "Insert or move to header (Ctrl + ⌘, press o then h)": "Ctrl + ⌘, o then h",
            "Insert or move to footer (Ctrl + ⌘, press o then f)": "Ctrl + ⌘, o then f",
            "Move focus to popup (links, bookmarks, images) (Ctrl + ⌘, press e then p)": "Ctrl + ⌘, e then p",
            "Move focus out of document text": "⌘ + Option + Shift + m",
            "Return focus to document text": "Esc",
            "Show person or group info": "Option + Right arrow",
            "Toggle a checkbox": "Command + Option + Enter"
        }
    },
    "URL": "https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en"
}