# coding: utf8
shortcuts = {
    #https://support.google.com/docs/answer/181110
    "Google Sheets" : {

        "Select column" : "Ctrl + Space",
        "Select row" : "Shift + Space",
        "Select all" : "⌘ + a or ⌘ + Shift + Space",
        "Undo" : "⌘ + z",
        "Redo" : "⌘ + y or ⌘ + Shift + z or Fn + F4",
        "Find" : "⌘ + f",
        "Find and replace" : "⌘ + Shift + h",
        "Fill range" : "⌘ + Enter",
        "Fill down" : "⌘ + d",
        "Fill right" : "⌘ + r",
        "Save" : "⌘ + s",
        "Open" : "⌘ + o",
        "Print" : "⌘ + p",
        "Copy" : "⌘ + c",
        "Cut" : "⌘ + x",
        "Paste" : "⌘ + v",
        "Paste values only" : "⌘ + Shift + v",
        "Show common keyboard shortcuts" : "⌘ + /",
        "Compact controls" : "Ctrl + Shift + f",
        "Input tools on/off" : "⌘ + Shift + k",
        "Select input tools" : "⌘ + Option + Shift + k",

        "Bold" : "⌘ + b",
        "Underline" : "⌘ + u",
        "Italic" : "⌘ + i",
        "Strikethrough" : "Option + Shift + 5",
        "Center align" : "⌘ + Shift + e",
        "Left align" : "⌘ + Shift + l",
        "Right align" : "⌘ + Shift + r",
        "Apply top border" : "Option + Shift + 1",
        "Apply right border" : "Option + Shift + 2",
        "Apply bottom border" : "Option + Shift + 3",
        "Apply left border" : "Option + Shift + 4",
        "Remove borders" : "Option + Shift + 6",
        "Apply outer border" : "Option + Shift + 7 or ⌘ + Shift + 7",

        "Insert link" : "⌘ + k",
        "Insert time" : "⌘ + Shift + ;",
        "Insert date" : "⌘ + ;",
        "Insert date and time" : "⌘ + Option + Shift + ;",
        "Format as decimal" : "Ctrl + Shift + 1",
        "Format as time" : "Ctrl + Shift + 2",
        "Format as date" : "Ctrl + Shift + 3",
        "Format as currency" : "Ctrl + Shift + 4",
        "Format as percentage" : "Ctrl + Shift + 5",
        "Format as exponent" : "Ctrl + Shift + 6",
        "Clear formatting" : "⌘ + \\",

        "Move to beginning of row" : "Fn + Left arrow",
        "Move to beginning of sheet" : "⌘ + Fn + Left arrow",
        "Move to end of row" : "Fn + Right arrow",
        "Move to end of sheet" : "⌘ + Fn + Right arrow",
        "Scroll to active cell" : "⌘ + Backspace",
        "Move to next sheet" : "⌘ + Shift + Fn + Down arrow",
        "Move to previous sheet" : "⌘ + Shift + Fn + Up arrow",
        "Display list of sheets" : "Option + Shift + k",
        "Open hyperlink" : "Option + Enter",
        "Open Explore" : "Option + Shift + x",
        "Move focus out of spreadsheet" : "Ctrl + ⌘ + Shift + m",
        "Move to quicksum (when a range of cells is selected)" : "Option + Shift + q",
        "Move focus to popup (for links, bookmarks, and images)" : "holding Ctrl + ⌘, press e then p",
        "Open drop-down menu on filtered cell" : "Ctrl + ⌘ + r",
        "Open revision history" : "⌘ + Option + Shift + h",
        "Open chat inside the spreadsheet" : "Shift + Esc",
        "Close drawing editor" : "⌘ + Esc or Shift + Esc",

        "Insert/edit note" : "Shift + F2",
        "Insert/edit comment" : "⌘ + Option + m",
        "Open comment discussion thread" : "⌘ + Option + Shift + a",
        "Enter current comment" : "holding Ctrl + ⌘, press e then c",
        "Move to next comment" : "holding Ctrl + ⌘, press n then c",
        "Move to previous comment" : "holding Ctrl + ⌘, press p then c",

        "File menu" : "Ctrl + Option + f",
        "Edit menu" : "Ctrl + Option + e",
        "View menu" : "Ctrl + Option + v",
        "Insert menu" : "Ctrl + Option + i",
        "Format menu" : "Ctrl + Option + o",
        "Data menu" : "Ctrl + Option + d",
        "Tools menu" : "Ctrl + Option + t",
        "Open insert menu" : "⌘ + Option + = (with cells selected)",
        "Open delete menu" : "⌘ + Option + - (with cells selected)",
        "Form menu" : "Ctrl + Option + m",
        "Add-ons menu" : "Ctrl + Option + n",
        "Help menu" : "Ctrl + Option + h",
        "Accessibility menu" : "Ctrl + Option + a",
        "Sheet menu (copy, delete, and other sheet actions)" : "Option + Shift + s",
        "Context menu" : "⌘ + Shift + \\",

        "Insert rows above" : "⌘ + Option + = (with rows selected) OR Ctrl + Option + i, then r",
        "Insert rows below" : "Ctrl + Option + i, then b",
        "Insert columns to the left" : "⌘ + Option + = (with columns selected) OR Ctrl + Option + i, then c",
        "Insert columns to the right" : "Ctrl + Option + i, then o",
        "Delete rows" : "⌘ + Option + - (with rows selected) OR Ctrl + Option + e, then d",
        "Delete columns" : "⌘ + Option + - (with columns selected) OR Ctrl + Option + e, then e",
        "Hide row" : "⌘ + Option + 9",
        "Hide column" : "⌘ + Option + 0",
        "Group rows or columns" : "Option + Shift + Right arrow",
        "Ungroup rows or columns" : "Option + Shift + Left arrow",
        "Expand grouped rows or columns" : "Option + Shift + Down arrow ",
        "Collapse grouped rows or columns" : "Option + Shift + Up arrow ",

        "Show all formulas" : "Ctrl + ~",
        "Insert array formula" : "⌘ + Shift + Enter",
        "Collapse an expanded array formula" : "⌘ + e",
        "Show/hide formula help (when entering a formula)" : "Shift + Fn + F1",
        "Full/compact formula help (when entering a formula)" : "Fn + F1",
        "Absolute/relative references (when entering a formula)" : "Fn + F4",
        "Toggle formula result previews (when entering a formula)" : "Fn + F9",
        "Resize formula bar (move up or down)" : "Ctrl + Option + Up and Ctrl + Option + Down",

        "Turn on screen reader support" : "⌘ + Option + z",
        "Read column" : "⌘ + Option + Shift + c",
        "Read row" : "⌘ + Option + Shift + r"
    }
}