# coding: utf8

shortcuts = {
    "Adobe Illustrator Mac Default Keyboard Shortcuts": {
        "Popular Shortcuts": {
            "Undo": "Command + Z",
            "Redo": "Shift + Command + Z",
            "Cut": "Command + X",
            "Copy": "Command + C",
            "Paste": "Command + V",
            "Paste in front": "Command + F",
            "Paste at back": "Command + B",
            "Paste in place": "Shift + Command + V",
            "Paste on all artboards": "Option + Shift + Command + V",
            "Check spelling": "Command + I",
            "Open the Color Settings dialog box": "Shift + Command + K",
            "Open the Keyboard Shortcuts dialog box": "Option + Shift + Command + K",
            "Open the Preferences dialog box": "Command + K"
        },
        "Work with Documents": {
            "Create a document": "Command + N",
            "Create a document from a template": "Shift + Command + N",
            "Create a document without opening dialog": "Option + Command + N",
            "Open a document": "Command + O",
            "Place a file": "Shift + Command + P",
            "Open the File Information dialog box": "Option + Shift + Command + I",
            "Open the Document Setup dialog box": "Option + Command + P",
            "Browse in Adobe Bridge": "Option + Command + O",
            "Close document window": "Command + W",
            "Save changes to document": "Command + S",
            "Open Save As dialog box": "Shift + Command + S",
            "Save a copy of the document": "Option + Command + S",
            "Save as script files": "Command + F12",
            "Open Export for screens dialog box": "Option + Command + E",
            "Open Save For Web dialog box": "Option + Shift + Command + S",
            "Package the document": "Option + Shift + Command + P",
            "Print": "Command + P",
            "Exit the application": "Command + Q"
        },
        "Select Tools": {
            "Artboard tool": "Shift + O",
            "Selection tool": "V",
            "Direct Selection tool": "A",
            "Magic Wand tool": "Y",
            "Lasso tool": "Q",
            "Pen tool": "P",
            "Curvature tool": "Shift + ~",
            "Blob Brush tool": "Shift + B",
            "Add Anchor Point tool": "+ (plus)",
            "Delete Anchor Point tool": "- (minus)",
            "Switch to Anchor Point tool": "Shift + C",
            "Type tool": "T",
            "Touch Type tool": "Shift + T",
            "Line Segment tool": "\\ (backslash)",
            "Rectangle tool": "M",
            "Ellipse tool": "L",
            "Paintbrush tool": "B",
            "Pencil tool": "N",
            "Shaper tool": "Shift + N",
            "Rotate tool": "R",
            "Reflect tool": "O",
            "Scale tool": "S",
            "Warp tool": "Shift + R",
            "Width Tool": "Shift + W",
            "Free Transform tool": "E",
            "Shape Builder Tool": "Shift + M",
            "Perspective Grid Tool": "Shift + P",
            "Perspective Selection Tool": "Shift + V",
            "Symbol Sprayer tool": "Shift + S",
            "Column Graph tool": "J",
            "Mesh tool": "U",
            "Gradient tool": "G",
            "Eyedropper tool": "I",
            "Blend tool": "W",
            "Live Paint Bucket tool": "K",
            "Live Paint Selection tool": "Shift + L",
            "Slice tool": "Shift + K",
            "Eraser tool": "Shift + E",
            "Scissors tool": "C",
            "Hand tool": "H",
            "Zoom tool": "Z",
            "Switch to Smooth tool while using Blob Brush tool": "Press Option"
        },
        "View Artwork": {
            "Toggle between screen modes": "F",
            "Fit imageable area": "Double-click Hand tool",
            "Magnify 100%": "Double-click Zoom tool or press Command + 1",
            "Switch to Hand tool": "Spacebar",
            "Switch to Zoom tool in magnify mode": "Spacebar + Command",
            "Switch to Zoom tool in reduce mode": "Spacebar + Command + Option",
            "Move Zoom marquee while dragging": "Spacebar",
            "Hide bounding box": "Shift + Command + B",
            "Hide unselected artwork": "Command + Option + Shift + 3",
            "Convert between horizontal and vertical guides": "Option-drag guide",
            "Release guide": "Command + Shift-double-click guide",
            "Show document template": "Command + H",
            "Show/Hide artboards": "Command + Shift + H",
            "Show/Hide artboard rulers": "Command + Option + R",
            "Show transparency grid": "Shift + Command + D",
            "View all artboards": "Command + Option + 0 (zero)",
            "Paste in place on active artboard": "Command + Shift + V",
            "Exit Artboard tool mode": "Esc",
            "Create artboard inside another": "Shift-drag",
            "Select multiple artboards in Artboards panel": "Command + click",
            "Navigate to next document": "Command + F6",
            "Navigate to previous document": "Command + Shift + F6",
            "Navigate to next document group": "Command + Option + F6",
            "Navigate to previous document group": "Command + Option + Shift + F6",
            "Toggle between Outline and GPU Preview": "Command + Y",
            "Toggle between GPU and CPU Preview": "Command + E",
            "View in Overprint Preview mode": "Option + Shift + Command + Y",
            "View in Pixel Preview mode": "Option + Command + Y",
            "Exit Full Screen mode": "Esc",
            "Zoom in": "Command + =",
            "Zoom out": "Command + -",
            "Hide guides": "Command + ;",
            "Lock guides": "Option + Command + ;",
            "Make guides": "Command + 5",
            "Release guides": "Option + Ctrl + 5",  # Note from original content about possible error remains.
            "Show/ Hide smart guides": "Command + U",
            "Show/ hide perspective grid": "Command + Shift + I",
            "Show grid": "Command + '",
            "Snap to grid": "Shift + Command + '",
            "Snap to point": "Option + Command + '"
        },
        "Work with Selections": {
            "Switch to last-used selection tool": "Command + `",
            "Switch between Direct Selection and Group Selection tools": "Option",
            "Add to selection": "Shift-click",
            "Subtract from selection": "Shift-click",
            "Subtract from selection with Magic Wand": "Option-click",
            "Add to selection with Lasso tool": "Shift-drag",
            "Subtract from selection with Lasso tool": "Option-drag",
            "Change pointer to cross hair with Lasso": "Caps Lock",
            "Select artwork in active artboard": "Command + Option + A",
            "Select all": "Command + A",
            "Deselect": "Shift + Command + A",
            "Reselect": "Command + 6",
            "Select the object above current selection": "Option + Command + ]",
            "Select the object below current selection": "Option + Command + [",
            "Select behind an object": "Press Command + click twice",
            "Select behind in isolation mode": "Command + click twice",
            "Group selected artwork": "Command + G",
            "Ungroup selected artwork": "Shift + Command + G",
            "Lock a selection": "Command + 2",
            "Unlock a selection": "Option + Command + 2",
            "Hide a selection": "Command + 3",
            "Show all selections": "Option + Command + 3",
            "Move selection in user-defined increments": "Arrow keys",
            "Move selection in 10x increments": "Shift + Arrow keys",
            "Lock all deselected artwork": "Command + Option + Shift + 2",
            "Constrain movement to 45° angle": "Hold Shift",
            "Bring selection forward": "Command + ]",
            "Move selection to front": "Shift + Command + ]",
            "Send selection backward": "Command + [",
            "Move selection to back": "Shift + Command + [",
            "Select only objects completely inside marquee": "Press E while dragging marquee"
        },
        "Draw": {
            "Constrain shape proportions or orientation": "Shift-drag",
            "Move shape while drawing": "Spacebar-drag",
            "Draw from center": "Option-drag",
            "Increase or decrease polygon sides etc": "Press Up or Down Arrow during drag",
            "Keep inner radius of star constant": "Hold Command during drag",
            "Keep sides of star straight": "Option-drag",
            "Switch between open and closed arc": "Hold C during drag",
            "Flip arc": "Hold Shift + F during drag",
            "Add or subtract spiral winds": "Option-drag during drag",
            "Change decay rate of spiral": "Command-drag during drag",
            "Add/remove horizontal lines in grids": "Press Up/Down Arrow during drag",
            "Add/remove vertical lines in grids": "Press Right/Left Arrow during drag",
            "Decrease/increase skew values": "Press F/V/X/C during drag (various)",
            "Increase size of Blob Brush": "] (right square bracket)",
            "Decrease size of Blob Brush": "[ (left square bracket)",
            "Constrain Blob Brush path horizontally or vertically": "Shift",
            "Switch through drawing modes": "Shift + D",
            "Join two or more paths": "Command + J",
            "Average two or more paths": "Option + Command + J",
            "Create corner or smooth join": "Shift + Command + Option + J",
            "Create a compound path": "Command + 8",
            "Release compound path": "Option + Shift + Command + 8",
            "Edit pattern": "Shift + Command + F8"
        },
        "Edit Shapes": {
            "Switch Pen tool to Convert Anchor Point tool": "Option",
            "Switch between Add Anchor Point and Delete Anchor Point tools": "Option",
            "Switch Scissors tool to Add Anchor Point tool": "Option",
            "Switch Pencil tool to Smooth tool": "Option (enable Option key toggles)",
            "Move current anchor point while drawing with Pen tool": "Spacebar-drag",
            "Cut a straight line with Knife tool": "Option-drag",
            "Cut at 45° or 90° with Knife tool": "Shift + Option-drag",
            "Use shape mode buttons in Pathfinder to create compound paths": "Option + Shape mode",
            "Erase unwanted closed regions using Shape Builder tool": "Option-click closed region",
            "Select Shape Builder tool": "Shift + M",
            "Display rectangular marquee with Shape Builder tool": "Shift + click + drag",
            "Increase/decrease intensity of symbols": "Shift + } or Shift + {",
            "Blend objects": "Option + Command + B",
            "Finish adding objects to blend": "Option + Shift + Command + B",
            "Warp-shaped envelope distortion": "Option + Command + Shift + W",
            "Mesh-shaped envelope distortion": "Option + Command + M",
            "Use another object as envelope shape": "Option + Command + C"
        },
        "Result Commands": {
            "Toggle between fill and stroke": "X",
            "Set fill and stroke to default": "D",
            "Swap fill and stroke": "Shift + X",
            "Select gradient fill mode": ">",
            "Hide gradient annotator": "Option + Command + G",
            "Select color fill mode": "<",
            "Select no stroke/fill mode": "/ (forward slash)",
            "Sample color from image or gradient": "Shift + Eyedropper tool",
            "Sample style and append appearance": "Option + Shift-click Eyedropper tool",
            "Add new fill": "Command + / (forward slash)",
            "Add new stroke": "Command + Option + / (forward slash)",
            "Reset gradient to black and white": "Command-click gradient button",
            "Make Live Paint": "Option + Command + X",
            "Decrease Bristle brush size": "[",
            "Increase Bristle brush size": "]"
        },
        "Work with Live Paint Groups": {
            "Switch to Eyedropper and sample fill/stroke": "Option-click + Live Paint Bucket tool",
            "Switch to Eyedropper and sample color from image or gradient": "Option + Shift-click + Live Paint Bucket tool",
            "Switch Live Paint Bucket tool options": "Shift + Live Paint Bucket tool",
            "Fill across unstroked edges": "Double-click + Live Paint Bucket tool",
            "Fill all faces/edges with same fill/stroke": "Triple-click + Live Paint Bucket tool",
            "Switch to Eyedropper and sample fill/stroke": "Option-click + Live Paint Selection tool",
            "Switch to Eyedropper and sample color": "Option + Shift-click + Live Paint Selection tool",
            "Add to/subtract from selection": "Shift-click + Live Paint Selection tool",
            "Select all connected faces/edges with same fill/stroke": "Double-click + Live Paint Selection tool",
            "Select all faces/edges with same fill/stroke": "Triple-click + Live Paint Selection tool"
        },
        "Work with Objects": {
            "Set origin point and open dialog with Rotate, Scale, Reflect, Shear tools": "Option-click",
            "Duplicate and transform selection using Selection, Scale, Reflect, Shear tools": "Option-drag",
            "Transform pattern": "Backquote (`)-drag",
            "Reapply transformation": "Command + D",
            "Apply last pathfinder effect": "Command + 4",
            "Move object": "Shift + Command + M",
            "Open Transform Each dialog": "Option + Shift + Command + D",
            "Make clipping mask": "Command + 7",
            "Release clipping mask": "Option + Command + 7",
            "Toggle fill and stroke": "X",
            "Set fill and stroke to default": "D",
            "Swap fill and stroke": "Shift + X",
            "Select gradient fill mode": ">",
            "Hide gradient annotator": "Option + Command + G",
            "Select color fill mode": "<",
            "Select no stroke/fill mode": "/",
            "Sample color": "Shift + Eyedropper tool",
            "Sample style and append appearance": "Option + Shift-click Eyedropper tool",
            "Add new fill": "Command + /",
            "Add new stroke": "Command + Option + /",
            "Reset gradient to black and white": "Command-click gradient button",
            "Make Live Paint": "Option + Command + X",
            "Decrease bristle brush size": "[",
            "Increase bristle brush size": "]"
        },
        "Create Variable Width Points": {
            "Select multiple width points": "Shift + click",
            "Create non-uniform widths": "Option + drag",
            "Create copy of width point": "Option + drag width point",
            "Change position of multiple width points": "Shift + drag",
            "Delete selected width point": "Delete",
            "Deselect width point": "Esc"
        },
        "Work with Type": {
            "Bold": "Shift + Command + B",
            "Italic": "Shift + Command + I",
            "Underline": "Shift + Command + U",
            "Move one character right/left": "Right or Left Arrow",
            "Move up or down one line": "Up or Down Arrow",
            "Move one word right or left": "Command + Right or Left Arrow",
            "Move up or down one paragraph": "Command + Up or Down Arrow",
            "Select one word right or left": "Shift + Command + Right or Left Arrow",
            "Select one paragraph up/down": "Shift + Command + Up or Down Arrow",
            "Extend existing selection": "Shift-click",
            "Align paragraph left/right/center": "Command + Shift + L, R, or C",
            "Justify text left": "Command + Shift + J",
            "Justify all lines": "Shift + Command + F",
            "Toggle line composer": "Option + Shift + Command + +",
            "Insert soft return": "Shift + Return",
            "Highlight kerning": "Command + Option + K",
            "Reset horizontal scale to 100%": "Command + Shift + X",
            "Increase/decrease font size": "Command + Shift + . or ,",
            "Increase/decrease font size by steps": "Option + Command + Shift + . or ,",
            "Increase/decrease leading": "Option + Up/Down (horizontal text) or Right/Left (vertical text)",
            "Select tracking value": "Option + Command + K",
            "Reset tracking/kerning": "Command + Option + Q",
            "Increase/decrease kerning and tracking": "Option + Right/Left (horizontal text) or Up/Down (vertical text)",
            "Increase/decrease by 5x": "Command + Option + Right/Left or Up/Down",
            "Increase/decrease baseline shift": "Option + Shift + Up/Down or Right/Left",
            "Switch between Type and Vertical Type tools": "Shift",
            "Switch between Area Type and Path Type tools": "Option",
            "Create outlines": "Shift + Command + O",
            "Open Character panel": "Command + T",
            "Open Paragraph panel": "Option + Command + T",
            "Open Tabs panel": "Shift + Command + T",
            "Open OpenType panel": "Option + Shift + Command + T",
            "Insert bullets": "Option + 8",
            "Insert copyright symbol": "Option + G",
            "Insert ellipsis": "Option + ;",
            "Insert paragraph symbol": "Option + 7",
            "Insert section symbol": "Option + 6",
            "Insert trademark symbol": "Option + 2",
            "Insert registered trademark symbol": "Option + R",
            "Superscript": "Shift + Command + =",
            "Subscript": "Option + Shift + Command + =",
            "Insert em dash": "Option + Shift + -",
            "Insert en dash": "Option + -",
            "Insert discretionary hyphen": "Shift + Command + -",
            "Toggle auto-hyphenation": "Option + Shift + Command + H",
            "Insert double left quotation marks": "Option + [",
            "Insert double right quotation marks": "Option + Shift + [",
            "Insert single left quotation marks": "Option + ]",
            "Insert single right quotation marks": "Option + Shift + ]",
            "Insert em space": "Shift + Command + M",
            "Insert en space": "Shift + Command + N",
            "Insert thin space": "Option + Shift + Command + M",
            "Show hidden characters": "Option + Command + I"
        }
    },
    "Page URL": "https://helpx.adobe.com/illustrator/using/default-keyboard-shortcuts.html"
}