# coding: utf8

shortcuts = {
    "Adobe Illustrator": #https://helpx.adobe.com/illustrator/using/default-keyboard-shortcuts.html
        {
            "Undo": "⌘ + Z",
            "Redo": "⇧ + ⌘ + Z",
            "Cut": "⌘ + X",
            "Copy": "⌘ + C",
            "Paste": "⌘ + V",
            "Paste in front": "⌘ + F",
            "Paste at back": "⌘ + B",
            "Paste in place": "⇧ + ⌘ + B",
            "Paste on all artboards": "⌥ + ⇧ + ⌘ + B",
            "Check spelling": "⌘ + I",
            "Open the Color Settings dialog box": "⇧ + ⌘ + K",
            "Open the Keyboard Shortcuts dialog box": "⌥ + ⇧ + ⌘ + K",
            "Open the Preferences dialog box": "⌘ + K",
            "Create a document": "⌘ + N",
            "Create a document from a template": "⇧ + ⌘ + N",
            "Create a document without opening the New Document dialog box": "⌥ + ⌘ + N",
            "Open a document": "⌘ + O",
            "Place a file in the document": "⇧ + ⌘ + P",
            "Open the File Information dialog box": "⌥ + ⇧ + ⌘ + I",
            "Open the Document Setup dialog box": "⌥ + ⌘ + P",
            "Browse in Adobe Bridge": "⌥ + ⌘ + O",
            "Close the document window": "⌘ + W",
            "Save changes made to the document": "⌘ &nbsp;+ S",
            "Open the Save As dialog box": "⇧ + ⌘ + S",
            "Save a copy of the document": "⌥ + ⌘ + S",
            "Save the document as script files": "⌘ + F12",
            "Open the Export for screens dialog box": "⌥ + ⌘ + E",
            "Open the Save For Web dialog box": "⌥ + ⇧ + ⌘ + S",
            "Package the document": "⌥ + ⇧ + ⌘ + P",
            "Print": "⌘ + P",
            "Exit the application": "⌘ + Q",
            "Artboard tool": "⇧ + O",
            "Selection tool": "V",
            "Direct Selection tool": "A",
            "Magic Wand too    ": "Y",
            "Lasso tool": "Q",
            "Pen tool": "P",
            "Curvature tool": "⇧ + ~",
            "Blob Brush tool": "⇧ + B",
            "Add Anchor Point tool": "+ (plus)",
            "Delete Anchor Point tool": "- (minus)",
            "Switch to Anchor Point tool": "⇧ + C",
            "Type tool": "T",
            "Touch Type tool": "⇧ + T",
            "Line Segment tool": "\ (backslash)",
            "Rectangle tool": "M",
            "Ellipse tool": "L",
            "Paintbrush tool": "B",
            "Pencil tool": "N",
            "Shaper tool": "⇧ + N",
            "Rotate tool": "R",
            "Reflect tool": "O",
            "Scale tool": "S",
            "Warp tool": "⇧ + R",
            "Width Tool": "⇧ +W",
            "Free Transform tool": "E",
            "Shape Builder Tool": "⇧ +M",
            "Perspective Grid Tool": "⇧ +P",
            "Perspective Selection Tool": "⇧ +V",
            "Symbol Sprayer tool": "⇧ + S",
            "Column Graph tool": "J",
            "Mesh tool": "U",
            "Gradient tool": "G",
            "Eyedropper tool": "I",
            "Blend tool": "W",
            "Live Paint Bucket tool": "K",
            "Live Paint Selection tool": "⇧ + L",
            "Slice tool": "⇧ + K",
            "Eraser tool": "⇧ + E",
            "Scissors tool": "C",
            "Hand tool": "H",
            "Zoom tool": "Z",
            "Switch to Smooth tool while using Blob Brush tool": "Press ⌥",
            "Toggle between screen modes: Normal Screen Mode, Full Screen Mode with Menu Bar, Full Screen Mode": "F",
            "Fit imageable area in window": "Double-click Hand tool",
            "Magnify 100%": "Double-click Zoom tool or press ⌘ + 1",
            "Switch to Hand tool (when not in text-edit mode)": "Spacebar",
            "Switch to Zoom tool in magnify mode": "Spacebar + ⌘",
            "Switch to Zoom tool in reduce mode": "Spacebar + ⌘ + ⌥",
            "Move Zoom marquee while dragging with the Zoom tool": "Spacebar",
            "Hide bounding box": "⇧ + Control + B",
            "Hide unselected artwork": "⌘ + ⌥ + ⇧ + 3",
            "Convert between horizontal and vertical guide": "⌥ + drag guide",
            "Release guide": "⌘ + ⇧ + double-click guide",
            "Show document template": "⌘ + H",
            "Show/Hide artboards": "⌘ + ⇧ + H",
            "Show/Hide artboard rulers": "⌘ + ⌥ + R",
            "Show transparency grid": "⇧ + ⌘ + D",
            "View all artboards in window": "⌘ + ⌥ + 0 (zero)",
            "Paste in place on the active artboard": "⌘ + ⇧ + V",
            "Exit Artboard tool mode": "Esc",
            "Create artboard inside another artboard": "⇧ + drag",
            "Select multiple artboards in the Artboards panel": "⌘ + click",
            "Navigate to next document": "⌘ + F6",
            "Navigate to previous document": "⌘ + ⇧ + F6",
            "Navigate to next document group": "⌘ + ⌥ + F6",
            "Navigate to previous document group": "⌘ + ⌥ + ⇧ + F6",
            "Toggle between Outline and GPU Preview of the document": "⌘ + Y",
            "Toggle between GPU and CPU Preview of the document": "⌘ + E",
            "View the document in Overprint Preview mode": "⌥ + ⇧ + ⌘ + Y",
            "View the document in Pixel Preview mode": "⌥ + ⌘ + Y",
            "Exit Full Screen mode": "Esc",
            "Zoom in": "⌘ + =",
            "Zoom out": "⌘ + -",
            "Hide guides": "⌘ + ;",
            "Lock guides": "⌥ + ⌘ + ;",
            "Make guides": "⌘ + 5",
            "Release guides": "⌥ + Ctrl + 5",
            "Show/ hide smart guides": "⌘ + U",
            "Show/ hide perspective grid": "⌘ + ⇧ + I",
            "Show grid": "⌘ + '",
            "Snap to grid&nbsp;": "⇧ + ⌘ + '",
            "Snap to point": "⌥ + ⌘ + '",
            "Switch to last-used selection tool (Selection tool, Direct Selection tool, or Group Selection tool)": "⌘ + `",
            "Switch between Direct Selection tool and Group Selection tool": "⌥",
            "Subtract a selection with Selection tool, Direct Selection tool, Group Selection tool, or LIve Paint Selection tool": "⇧ + click",
            "Subtract from selection with Magic Wand tool": "⌥ + click",
            "Add to selection with Lasso tool": "⇧ + drag",
            "Subtract from selection with Lasso tool": "⌥ + drag",
            "Change pointer to cross hair for Lasso tool": "Caps Lock",
            "Select artwork in active artboard": "⌘ + ⌥ + A",
            "Create crop marks around selected object": "&nbsp;",
            "Select all": "⌘ + A",
            "Deselect": "⇧ + ⌘ + A",
            "Reselect": "⌘ + 6",
            "Select the object above the current selection&nbsp;": "⌥ + ⌘ + ]",
            "Select the object below the current selection": "⌥ + ⌘ +",
            "Select behind an object": "Press ⌘ + click twice",
            "Select behind in isolation mode": "⌘ +click twice",
            "Group the selected artwork": "⌘ + G",
            "Ungroup the selected artwork": "⇧ + ⌘ + G",
            "Lock a selection": "⌘ + 2",
            "Unlock a selection": "⌥ + ⌘ + 2",
            "Hide a selection": "⌘ + 3",
            "Show all selections": "⌥ + ⌘ + 3",
            "Move selection in user-defined increments": "Right Arrow, Left Arrow, Up Arrow, or Down Arrow<br>",
            "Move selection in 10x user-defined increments": "⇧ + Right Arrow, Left Arrow, Up Arrow, or Down Arrow",
            "Lock all deselected artwork": "⌘ + ⌥ + ⇧ + 2",
            "Constrain movement to 45° angle (except when using Reflect tool)": "Hold down ⇧",
            "Bring a selection forward": "⌘ + ]",
            "Move a selection to the front": "⇧ + ⌘ + ]",
            "Send a selection backward": "⌘ + [",
            "Move a selection to the back&nbsp;": "⇧ + ⌘ + [",
            "Constrain a shape’s proportions or orientation": "⇧ + drag",
            "Move a shape while drawing it": "spacebar-drag",
            "Draw from the center of a shape (except for polygons, stars, and flares)": "⌥ + drag",
            "Keep the inner radius of a star constant": "Start dragging, then hold down ⌘",
            "Keep the sides of a star straight": "⌥ + drag",
            "Switch between an open and closed arc": "Start dragging, then hold down C",
            "Flip an arc, keeping the reference point constant": "Start dragging, then hold down SF",
            "Add or subtract winds from a spiral while increasing the length of the spiral": "Start dragging then ⌥ + drag",
            "Change the decay rate of a spiral": "Start dragging then ⌘ + drag",
            "Decrease the skew value for horizontal dividers in a rectangular grid or radial dividers in a polar grid by 10%": "Start dragging, then press F",
            "Increase the skew value for horizontal dividers in a rectangular grid or radial dividers in a polar grid by 10%": "Start dragging, then press V",
            "Increase size of Blob Brush": "] (right square bracket)",
            "Decrease size of Blob Brush": "[ (left square bracket)",
            "Constrain Blob Brush path horizontally or vertically": "⇧",
            "Switch through drawing modes": "⇧ + D",
            "Join two or more paths": "Select the paths, then press ⌘ + J",
            "Average two or more paths": "Select the paths, then press ⌥ + ⌘ + J",
            "Create corner or smooth join": "Select the anchor point, then press ⇧ + ⌘ + ⌥ + J",
            "Create a compound path": "⌘ + 8",
            "Release a compound path": "⌥ + ⇧ + ⌘ + 8",
            "Edit a pattern": "⇧ + ⌘ +F8",
            "Perspective Grid Tool": "⇧ + P",
            "Perspective Selection Tool": "⇧ + V",
            "Perspective Grid": "⌘ + ⇧ + I",
            "Moving objects perpendicularly": "Press the number 5 key, then click and drag the object",
            "Copying objects in perspective": "⌘ + Alt + drag",
            "Repeat transforming objects in perspective": "⌘ + D",
            "Switching between drawing modes": "⇧ + D",
            "Switch Pen tool to Convert Anchor Point tool": "⌥",
            "Switch between Add Anchor Point tool and Delete Anchor Point tool": "⌥",
            "Switch Scissors tool to Add Anchor Point tool": "⌥",
            "Switch Pencil tool to Smooth tool": "⌥",
            "Move current anchor point while drawing with Pen tool": "Spacebar-drag",
            "Cut a straight line with Knife tool": "⌥ + drag",
            "Cut at 45° or 90° with Knife tool": "⇧ + ⌥ + drag",
            "Use shape mode buttons in Pathfinder panel to create compound paths": "⌥ + Shape mode",
            "Erase unwanted closed regions created using Shape Builder tool": "⌥ + click the closed region",
            "Select the Shape Builder tool": "⇧ + M",
            "Display rectangular marquee to easily merge multiple paths (when using Shape Builder tool)": "⇧ + click + drag",
            "Increase the intensity of symbols (when using Symbolism tool)": "⇧ + }",
            "Decrease the intensity of symbols (when using Symbolism tool)": "⇧ + {",
            "Blend objects": "⌥ + ⌘ + B",
            "Finish adding objects to the blend": "⌥ + ⇧ + ⌘ + B",
            "Distort objects using a warp-shaped envelope": "⌥ + ⌘ + ⇧ + W",
            "Distort objects using a mesh as the shape of the envelope": "⌥ + ⌘ + M",
            "Distort objects using another object as the shape of the envelope": "⌥ + ⌘ + C",
            "Switch to Eyedropper tool and sample fill and/or stroke": "⌥ + click + Live Paint Bucket tool",
            "Switch to Eyedropper tool and sample color from an image or intermediate color from a gradient": "⌥ + ⇧ + click + Live Paint Bucket tool",
            "Fill across unstroked edges into adjacent faces": "Double-click + Live Paint Bucket tool",
            "Fill all faces that have same fill and stroke all edges that have same stroke": "Triple-click + Live Paint Bucket tool",
            "Switch to Eyedropper tool and sample fill and/or stroke": "⌥ + click + Live Paint Selection tool",
            "Add to/subtract from a selection": "⇧ + click + Live Paint Selection tool",
            "Select all connected faces /edges with same fill/stroke": "Double-click + Live Paint Selection tool",
            "Select all faces/edges with same fill/stroke": "Triple-click + Live Paint Selection tool",
            "Set origin point and open dialog box when using Rotate tool, Scale tool, Reflect tool, or Shear tool": "⌥ + click",
            "Duplicate and transform selection when using Selection tool, Scale tool, Reflect tool, or Shear tool": "⌥ + drag",
            "Transform pattern (independent of object) when using Selection tool, Scale tool, Reflect tool, or Shear tool": "Tilde (~)-drag",
            "Reapply a transformation to an object": "⌘ + D",
            "Apply last pathfinder effect to the selected object": "⌘ + 4",
            "Move an object": "⇧ + ⌘ + M",
            "Open the Transform Each dialog box": "⌥ + ⇧ + ⌘ + D",
            "Make a clipping mask": "⌘ + 7",
            "Release a clipping mask": "⌥ + ⌘ + 7",
            "Toggle between fill and stroke": "X",
            "Set fill and stroke to default": "D",
            "Swap fill and stroke": "⇧ + X",
            "Select gradient fill mode": "&gt;",
            "Hide gradient annotator (when using the Gradient tool)": "⌥ + ⌘ + G",
            "Select color fill mode": "&lt;",
            "Select no stroke/fill mode": "/ (forward slash)",
            "Sample color from an image or intermediate color from gradient": "⇧ + Eyedropper tool",
            "Sample style and append appearance of currently selected item": "⌥ + ⇧ + click + Eyedropper tool",
            "Add new fill": "⌘ + / (forward slash)",
            "Add new stroke": "⌘ + ⌥ + / (forward slash)",
            "Reset gradient to black and white": "⌘ + click gradient button in Tools panel or Gradient panel",
            "Make Live Paint (when using the Paint Bucket tool)": "⌥ + ⌘ + X",
            "Decrease Bristle brush size": "[",
            "Increase Bristle brush size": "]",
            "Select multiple width points": "⇧ +click",
            "Create non-uniform widths": "⌥ +drag",
            "Create a copy of the width point": "⌥ +drag the width point",
            "Change the position of multiple width points": "⇧ +drag",
            "Delete selected width point": "Delete",
            "Deselect a width point": "Esc",
            "Move one character right or left": "Right Arrow or Left Arrow",
            "Move up or down one line": "Up Arrow or Down Arrow",
            "Move one word right or left": "⌘ + Right Arrow or Left Arrow",
            "Move up or down one paragraph": "⌘ + Up Arrow or Down Arrow",
            "Select one word right or left": "⇧ + ⌘ + Right Arrow or Left Arrow",
            "Select one paragraph before or after": "⇧ + ⌘ + Up Arrow or Down Arrow",
            "Extend existing selection": "⇧ + click",
            "Align paragraph left, right, or center": "⌘ + ⇧ + L, R, or C",
            "Justify text left": "⌘ + ⇧ + J",
            "Justify all lines": "⇧ + ⌘ + F",
            "Toggle line composer": "⌥ + ⇧ + ⌘ +",
            "Insert soft return": "⇧ + Return",
            "Highlight kerning": "⌘ + ⌥ + K",
            "Reset horizontal scale to 100%": "⌘ + ⇧ + X",
            "Increase or decrease font size": "⌘ + ⇧ +&nbsp;. or ,",
            "Increase or decrease font size by steps": "⌥ + ⌘ +⇧ + . or ,",
            "Increase or decrease leading": "⌥ + Up or Down Arrow (horizontal text) or Right or Left Arrow (vertical text)",
            "Select tracking value": "⌥ + ⌘ + K",
            "Reset tracking/kerning to 0": "⌘ + ⌥ + Q",
            "Increase or decrease kerning and tracking": "⌥ + Right or Left Arrow (horizontal text) or Up or Down Arrow (vertical text)",
            "Increase or decrease baseline shift": "⌥ + ⇧ + Up or Down Arrow (horizontal text) or Right or Left Arrow (vertical text)",
            "Switch between Type and Vertical Type, Area Type and Vertical Area Type, and Path Type and Vertical Path Type tools": "⇧",
            "Switch between Area Type and Path Type, Vertical Area Type and Vertical Path Type tools": "⌥",
            "Create outlines": "⇧ + ⌘ + O",
            "Open the Character panel": "⌘ + T",
            "Open the Paragraph panel": "⌥ + ⌘ + T",
            "Open the Tabs panel": "⇧ + ⌘ + T",
            "Open the OpenType panel": "⌥ + ⇧ + ⌘ + T",
            "Insert bullets": "⌥ + 8",
            "Insert copyright symbol": "⌥ + G",
            "Insert ellipsis": "⌥ + ;",
            "Insert paragraph symbol": "⌥ + 7",
            "Insert section symbol<br>": "⌥ + 6<br>",
            "Insert trademark symbol": "⌥ + 2",
            "Insert registered trademark symbol": "⌥ + R",
            "Superscript": "⇧ + ⌘ + =",
            "Subscript": "Alt + ⇧ + Ctrl + =",
            "Insert em dash": "⌥ + ⇧ + -",
            "Insert en dash": "⌥ + -",
            "Insert discretionary hyphen": "⇧ + ⌘ + -",
            "Toggle auto-hyphenation": "⌥ + ⇧ + ⌘ + H",
            "Insert double left quotation marks": "⌥ + [",
            "Insert double right quotation marks": "⌥ + ⇧ + [",
            "Insert single left quotation marks": "⌥ + ]",
            "Insert single right quotation marks": "⌥ + ⇧ + ]",
            "Insert em space": "⇧ + ⌘ + M",
            "Insert en space": "⇧ + ⌘ + N",
            "Insert thin space": "⌥ + ⇧ + ⌘ + M",
            "Show hidden characters": "⌥ + ⌘ + I",
            "Set options (except for Actions, Brushes, Swatches, and Symbols panels)": "⌥ + click New button",
            "Switch units of measurement": "⌥ + ⇧ + ⌘ + U",
            "Delete without confirmation (except for Layers panel)": "⌥ + click Delete button",
            "Apply value and keep text box active": "⇧ + Return",
            "Select range of actions, brushes, layers, links, styles, or swatches": "⇧ + click",
            "Select noncontiguous actions, brushes, layers (same level only), links, styles, or swatches": "⌘ + click",
            "Show/Hide all panels": "Tab",
            "Show/Hide all panels except the Tools panel and Control panel": "⇧ + Tab",
            "Increase/ decrease values in logical fractions of the measurement unit": "⌘ + Up or Down Arrow",
            "Increase/ decrease measurement unit by 10x": "⇧ + Up or Down Arrow",
            "Expand/Collapse entire hierarchy for action set": "⌥ + click expansion triangle",
            "Set options for action set": "Double-click folder icon",
            "Play a single command": "⌘ + click Play Current Selection button",
            "Begin recording actions without confirmation": "⌥ + click New Action button",
            "Open Brush Options dialog box": "Double-click brush",
            "Duplicate brush": "Drag brush to New Brush button",
            "Open the Character panel": "⌘ + T",
            "Open the Paragraph panel": "⌥ + ⌘ + T",
            "Increase/decrease the selected value by a small increment": "Up Arrow or Down Arrow",
            "Increase/decreases the selected value by a large increment": "⇧ + Up Arrow or Down Arrow",
            "Increase/decrease the selected value by a fraction": "⌘ + Up or Down Arrow",
            "Highlight the font name field in the Character panel": "⌘ + ⌥ + ⇧ + F",
            "Select the complement for the current color fill/stroke": "⌘ + click color bar",
            "Change the nonactive fill/stroke": "⌥ + click color bar",
            "Select the complement for the nonactive fill/stroke": "⌘ + ⌥ + click color bar",
            "Select the inverse for the current fill/stroke": "⌘ +  ⇧ + click color bar",
            "Select the inverse for the nonactive fill/stroke": "⌘ + ⇧ + ⌥ + click color bar",
            "Open Color Guide": "⇧ + F3",
            "Change the color mode": "⇧ + click color bar",
            "Move color sliders in tandem": "⇧ + drag color slider",
            "Switch between percentage and 0-255 values for RGB": "Double-click to right of a numerical field",
            "Duplicate color stops": "⌥ + drag",
            "Swap color stops": "⌥ + drag color stop onto another color stop",
            "Apply swatch color to active (or selected) color stop": "⌥ + click swatch in the Swatches panel",
            "Reset the gradient fill to default black and white linear gradient": "⌘ + click Gradient Fill box in the Gradient panel",
            "Show/Hide gradient arrow": "⌘ + ⌥ + G",
            "Modify angle and end-point together": "⌥ + drag end point of gradient annotator",
            "Constrain Gradient tool or Gradient annotator while dragging": "⇧ + drag",
            "View Gradient annotator in selected gradient filled object": "G",
            "Add a layer": "⌘ + L",
            "Add a layer while opening the New Layer dialog box": "⌥ + ⌘ + L",
            "Select all objects on the layer": "⌥ + click layer name",
            "Show/hide all layers but the selected one": "⌥ + click eye icon",
            "Select Outline/Preview view for the selected layer": "⌘ + click eye icon",
            "Selects Outline/Preview view for all other layers": "⌘ + ⌥ + click eye icon",
            "Lock/unlock all other layers": "⌥ + click lock icon",
            "Expand all sublayers to display entire hierarchy": "⌥ + click expansion triangle",
            "Set options as you create new layer": "⌥ + click New Layer button",
            "Set options as you create new sublayer": "⌥ + click New Sublayer button",
            "Place new sublayer at bottom of layer list": "⌘ + ⌥ + click New Sublayer button",
            "Place layer at top of layer list": "⌘ + click New Layer button",
            "Place layer below selected layer": "⌘ + ⌥ + click New Layer button",
            "Copy the selection to a layer, sublayer, or group": "⌥ + drag selection",
            "Create new spot color": "⌘ + click New Swatch button",
            "Create new global process color": "⌘ + ⇧ + click New Swatch button",
            "Replace swatch with another": "⌥ + drag a swatch over another",
            "Apply a value and keep focus in edit field": "⇧ + Return",
            "Apply a value and copy object": "⌥ + Return",
            "Apply a value and scale option proportionately for width or height": "⌘ + Return",
            "Apply last effect to the selected object": "⇧ + ⌘ + E",
            "Apply last effect to the selected object by adjusting the values in the effects dialog box": "⌥ + ⇧ + ⌘ + E",
            "Change mask to grayscale image for editing": "⌥ + click on mask thumbnail",
            "Disable opacity mask": "⇧ + click on mask thumbnail",
            "Re-enable opacity mask": "⇧ + click on disabled mask thumbnail",
            "Increase/decrease opacity in 1% increments": "Click opacity field + Up Arrow or Down Arrow",
            "Increase/decrease opacity in 10% increments": "⇧ + click opacity field + Up Arrow or Down Arrow",
            "Invoke Help": "F1",
            "Cut": "F2",
            "Copy": "F3",
            "Paste": "F4",
            "Show/hide Brushes panel": "F5",
            "Show/hide Color panel": "F6",
            "Show/hide Layers panel": "F7",
            "Create new symbol": "F8",
            "Show/hide Info panel": "⌘ + F8",
            "Show/hide Gradient panel": "⌘ + F9",
            "Show/hide Stroke panel": "⌘ + F10",
            "Show/hide Attributes panel": "⌘ + F11",
            "Revert": "F12",
            "Show/hide Graphic Styles panel": "⇧ + F5",
            "Show/hide Appearance panel": "⇧ + F6",
            "Show/hide Align panel": "⇧ + F7",
            "Show/hide Transform panel": "⇧ + F8",
            "Show/hide Pathfinder panel": "⇧ + ⌘ + F9",
            "Show/hide Transparency panel": "⇧ + ⌘ + F10",
            "Show/hide Symbols panel": "⇧ + ⌘ + F11"
        }
    }