# coding: utf8
shortcuts = {
    "inbox.google.com":{
        #⇧?
        "Everywhere - Toggle and view keyboard shortcuts":"⇧?",
        "Everywhere - Compose":"c",
        "Everywhere - Search":"/",
        "Everywhere - Go to inbox":"i",
        "Everywhere - Open Hangouts and focus the conversation list":"h",
        "Everywhere - Open Hangouts and focus the search box":"q",
        "Everywhere - Create reminder":"t",
        "Everywhere - Focus on notification":"⇧b",
        "Everywhere - Open main menu":"⇧m",
        "Everywhere - Undo last action":"z",
        "Chat/compose - Focus latest chat or compose":"⇧Esc",
        "Chat/compose - Focus main window (while in chat or compose)":"⇧Esc",
        "Chat/compose - Advance to next chat or compose":"Ctrl .",
        "Chat/compose - Advance to previous chat or compose":"Ctrl ,",
        "Chat/compose - Bold":"⌘b",
        "Chat/compose - Italics":"⌘i",
        "Chat/compose - Underline":"⌘u",
        "Chat/compose - Insert link":"⌘k",
        "Chat/compose - Numbered list":"⌘⇧7",
        "Chat/compose - Bulleted list":"⌘⇧8",
        "Chat/compose - Remove formatting":"⌘\\",
        "Chat/compose - Send":"⌘⏎",
        "Chat/compose - Closes compose and deletes empty drafts":"Esc",
        "List - Open":"⏎ or o",
        "List - Close":"Esc or u",
        "List - Next item":"j or →",
        "List - Previous item":"k or ←",
        "List - First item":"Home",
        "List - Next message":"n",
        "List - Previous message":"p",
        "Focused item - Mark done":"e or y",
        "Focused item - Mark done and advance":"] or [",
        "Focused item - Snooze":"s",
        "Focused item - Pin":"⇧p",
        "Focused item - Reply all":"a",
        "Focused item - Reply all in a new window":"⇧a",
        "Focused item - Reply":"r",
        "Focused item - Reply in a new window":"⇧r",
        "Focused item - Forward":"f",
        "Focused item - Trash":"#",
        "Focused item - Report as spam":"!",
        "Focused item - Mute":"m",
        "Focused item - Toggle move-to menu":".",
        "Focused item - Select":"x",
        "Focused item - Select many items at once":"⇧x"
    }
}