# coding: utf8
# Intellij IDEA (default 10.5+)

shortcuts= { #help > Keymap reference
    "Intellij IDEA (default)":{
        "Editing - Basic code completion (the name of any class, method or variable)":"^Space",
        "Editing - Smart code completion (filters the list of methods and variables by expected type)":"^⇧Space",
        "Editing - Complete statement":"⌘⇧⏎",
        "Editing - Parameter info (within method call arguments)":"⌘P",
        "Editing - Quick documentation lookup":"^J or Mid.button click",
        "Editing - External Doc":"⇧F1",
        "Editing - Brief Info":"⌘ + mouse over code",
        "Editing - Show descriptions of error or warning at caret":"⌘F1",
        "Editing - Generate code... (Getters, Setters, Constructors, hashCode/equals, toString)":"⌘N or ^⏎ or ^N",
        "Editing - Override methods":"^O",
        "Editing - Implement methods":"^I",
        "Editing - Surround with... (if..else, try..catch, for, synchronized, etc.)":"⌘⌥T",
        "Editing - Comment/uncomment with line comment":"⌘/",
        "Editing - Comment/uncomment with block comment":"⌘⌥/",
        "Editing - Select successively increasing code blocks":"⌥↑",
        "Editing - Decrease current selection to previous state":"⌥↓",
        "Editing - Context info":"^⇧Q",
        "Editing - Show intention actions and quick- xes":"⌥⏎",
        "Editing - Reformat code":"⌘⌥L",
        "Editing - Optimize imports":"^⌥O",
        "Editing - Auto-indent line(s)":"^⌥I",
        "Editing - Indent/unindent selected lines":"Tab, ⇧Tab",
        "Editing - Cut current line or selected block to clipboard":"⌘X",
        "Editing - Copy current line or selected block to clipboard":"⌘C",
        "Editing - Paste from clipboard":"⌘V",
        "Editing - Paste from recent buffers...":"⌘⇧V",
        "Editing - Duplicate current line or selected block":"⌘D",
        "Editing - Delete line at caret":"⌘⌫",
        "Editing - Smart line join":"^⇧J",
        "Editing - Smart line split":"⌘⏎",
        "Editing - Start new line":"⇧⏎",
        "Editing - Toggle case for word at caret or selected block":"⌘⇧U",
        "Editing - Select till code block end/start":"⌘⇧], ⌘⇧[",
        "Editing - Delete to word end":"⌥⌦",
        "Editing - Delete to word start":"⌥⌫",
        "Editing - Expand/collapse code block":"⌘+, ⌘-",
        "Editing - Expand all":"⌘⇧+",
        "Editing - Collapse all":"⌘⇧-",
        "Editing - Close active editor tab":"⌘W",
        "Search/Replace - Search everywhere Find":"double⇧",
        "Search/Replace - Find next":"⌘G",
        "Search/Replace - Find previous":"⌘⇧G",
        "Replace":"⌘R",
        "Search/Replace - Find in path":"⌘⇧F",
        "Search/Replace - Replace in path":"⌘⇧R",
        "Search/Replace - Search structurally (Ultimate Edition only)":"⌘⇧S",
        "Search/Replace - Replace structurally (Ultimate Edition only)":"⌘⇧M",
        "Usage Search - Find usages / Find usages in file":"⌥F7/⌘F7",
        "Usage Search - Highlight usages in file":"⌘⇧F7",
        "Usage Search - Show usages":"⌘⌥F7",
        "Compile/Run - Make project (compile modifed and dependent)":"⌘F9",
        "Compile/Run - Compile selected file, package or module":"⌘⇧F9",
        "Compile/Run - Select confguration and run":"^⌥R",
        "Compile/Run - Select confguration and debug":"^⌥D",
        "Compile/Run - Run":"^R",
        "Compile/Run - Debug":"^D",
        "Compile/Run - Run context confguration from editor":"^⇧R or ^⇧D",
        "Debugging - Step over":"F8",
        "Debugging - Step into":"F7",
        "Debugging - Smart step into":"⇧F7",
        "Debugging - Step out":"⇧F8",
        "Debugging - Run to cursor":"⌥F9",
        "Debugging - Evaluate expression":"⌥F8",
        "Debugging - Resume program":"⌘⌥R",
        "Debugging - Toggle breakpoint":"⌘F8",
        "Debugging - View breakpoints":"⌘⇧F8",
        "Navigation - Go to class":"⌘O",
        "Navigation - Go to file":"⌘⇧O",
        "Navigation - Go to symbol":"⌘⌥O",
        "Navigation - Go to next/previous editor tab":"^←, ^→",
        "Navigation - Go back to previous tool window":"F12",
        "Navigation - Go to editor (from tool window)":"Esc",
        "Navigation - Hide active or last active window":"⇧Esc",
        "Navigation - Close active run/messages/find/... tab":"⌘⇧F4",
        "Navigation - Go to line":"⌘L",
        "Navigation - Recent files popup":"⌘E",
        "Navigation - Navigate back/forward":"⌘⌥←, ⌘⌥→",
        "Navigation - Navigate to last edit location":"⌘⇧⌫",
        "Navigation - Select current file or symbol in any view":"⌥F1",
        "Navigation - Go to declaration":"⌘B or ⌘Click",
        "Navigation - Go to implementation(s)":"⌘⌥B",
        "Navigation - Open quick definition lookup":"⌥Space, ⌘Y",
        "Navigation - Go to type declaration":"^⇧B",
        "Navigation - Go to super-method/super-class":"⌘U",
        "Navigation - Go to previous/next method":"^↑, ^↓",
        "Navigation - Move to code block end/start":"⌘], ⌘[",
        "Navigation - File structure popup":"⌘F12",
        "Navigation - Type hierarchy":"^H",
        "Navigation - Method hierarchy":"⌘⇧H",
        "Navigation - Call hierarchy":"^⌥H",
        "Navigation - Next/previous highlighted error":"F2, ⇧F2",
        "Navigation - Edit source / View source":"F4/⌘↓",
        "Navigation - Show navigation bar":"⌥Home",
        "Navigation - Toggle bookmark":"F3",
        "Navigation - Toggle bookmark with mnemonic":"⌥F3",
        "Navigation - Go to numbered bookmark":"^[NUM]",
        "Navigation - Show bookmarks":"⌘F3",
        "Refactoring - Copy":"F5",
        "Refactoring - Move":"F6",
        "Refactoring - Safe Delete":"⌘Delete",
        "Refactoring - Rename":"⇧F6",
        "Refactoring - Change Signature":"⌘F6",
        "Refactoring - Inline":"⌘⌥N",
        "Refactoring - Extract Method":"⌘⌥M",
        "Refactoring - Extract Variable":"⌘⌥V",
        "Refactoring - Extract Field":"⌘⌥F",
        "Refactoring - Extract Constant":"⌘⌥C",
        "Refactoring - Extract Parameter":"⌘⌥P",
        "VCS/Local History - Commit project to VCS":"⌘K",
        "VCS/Local History - Update project from VCS":"⌘T",
        "VCS/Local History - View recent changes":"⌥⇧C",
        "VCS/Local History - VCS quick popup":"^V",
        "Surround with Live Template":"⌘⌥J",
        "Insert Live Template":"⌘J",
        "General - Open corresponding tool window":"⌘[NUM]",
        "General - Save all":"⌘S",
        "General - Synchronize":"⌘⌥Y",
        "General - Toggle full screen mode":"^⌘F",
        "General - Toggle maximizing editor":"⌘⇧F12",
        "General - Add to Favorites":"⌥⇧F",
        "General - Inspect current file with current profile":"⌥⇧I",
        "General - Quick switch current scheme":"^§ or ^`",
        "General - Open Settings dialog":"⌘,",
        "General - Open Project Structure dialog":"⌘;",
        "General - Find Action":"⇧⌘A",
        "General - Switch between tabs and tool window":"^Tab"
    }
}
