# coding: utf8

shortcuts = {
    #https://confluence.atlassian.com/agile066/jira-agile-user-s-guide/using-keyboard-shortcuts#UsingKeyboardShortcuts-modifierkeys
    "Jira" : {
        "Go to Dashboard": "g then d",
        "Browse to a Project": "g then p",
        "Go to Agile": "g then a OR g then h",
        "Go to Issue Navigator": "g then i",
        "Opens the Administration Search dialog box.": "g then g",
        "Quick Search": "/",
        "Create an Issue": "c",
        "Open shortcut help": "?",
        "Dashboards drop-down menu": "Ctrl (+ alt for Safari) + d",
        "Projects drop-down menu": "Ctrl (+ alt for Safari) + p",
        "Issues drop-down menu": "Ctrl (+ alt for Safari) + i",
        "Agile drop-down menu": "Ctrl (+ alt for Safari) + g ",
        "Form Submit": "Ctrl (+ alt for Safari) + s ",
        "Cancel Form ": "Ctrl (+ alt for Safari) + `",
        "Next Issue": "j",
        "Previous Issue": "k",
        "Next Column": "n",
        "Previous Column": "p",
        "Expand/Collapse All Swimlanes ": "t",
        "View Issue": "o   ",
        "Add a New Line": "Enter",
        "Submit changes": "Enter",
        "Cancel changes": "Esc ",
        "Assign to Me": "i",
        "Send to Top": "s + t",
        "Send to Bottom": "s + b ",
        "Edit Issue": "e",
        "Projector Mode": "z   ",
        "View selected Issue": "o or Enter",
        "Next Issue": "j",
        "Previous Issue": "k",
        "Back to the Navigator": "u",
        "Hide/Show Left Section": "[",
        "Next Activity": "n",
        "Previous Activity": "p",
        "Focus search field": "f",
        "Escape field": "Esc",
        "Edit Issue": "e",
        "Assign Issue": "a",
        "Comment on Issue": "m",
        "Edit Issue Labels": "l",
        "Share Issue": "s",
        "Operations dialog box": "."
    }
}