# coding: utf8
shortcuts = {
    "Mac OSX":{
        #https://support.apple.com/en-us/HT201236
        "Create a new folder": "⇧⌘N",
        "Open preferences for the front app": "⌘,",
        "Cut": "⌘X",
        "Copy": "⌘C",
        "Paste": "⌘V",
        "Undo the previous command": "⌘Z",
        "Redo": "⇧⌘Z",
        "Select All items": "⌘A",
        "Find items in a document": "⌘F",
        "Open a Find window": "⌘F",
        "Find next": "⌘G",
        "Find previous": "⇧⌘G",
        "Hide the windows of the front app": "⌘H",
        "View the front app but hide all other apps": "⌥⌘H",
        "Minimize the front window to the Dock. ": "⌘M",
        "Minimize all windows of the front app": "⌥⌘M",
        "Open the selected item": "⌘O",
        "Open a dialog to select a file to open": "⌘O",
        "Print the current document": "⌘P",
        "Save the current document": "⌘S",
        "Open a new tab": "⌘T",
        "Close the front window": "⌘W",
        "To close all windows of the app": "⌥⌘W",
        "Force quit an app": "⌥⌘Esc",
        "Show or hide the Spotlight search field": "⌘Space bar",
        "Spotlight search from a Finder window": "⌘⌥Space bar",
        "Show the Character Viewer (emojis)": "CTRL ⌘Space bar",
        "Use the app in full screen": "Control-⌘F",
        "Use Quick Look to preview the selected item": "Space bar",
        "Switch to the next most recently used app among your open apps": "⌘Tab",
        "Take a screenshot or make a screen recording": "⇧⌘5",
        "Take a full screenshot": "⇧⌘3",
        "Take a partial screenshot": "⇧⌘4",
        "Turn on mac or wake it from sleep": "Power button",
        "Put Mac to sleep": "Press and hold Power Button for 1.5 seconds",
        "Force mac to turn off": "Press and hold power button",
        "Put your Mac to sleep": "⌥⌘Power button or ⌥⌘Media Eject",
        "Put your displays to sleep": "CTRL SHIFT Power button or CTRL SHIFT Media Eject",
        "Display a dialog asking to restart, sleep, or shut down": "CTRL Power button or CTRL Media Eject",
        "Force your Mac to restart": "CTRL ⌘Power button",
        "Quit all apps, then restart": "CTRL ⌘Media Eject",
        "Quit all apps, then shut down": "CTRL ⌥⌘ Power button or CTRL ⌥⌘ Media Eject",
        "Immediately lock your screen": "Control-⌘Q",
        "Log out of your macOS user account": "⇧⌘Q",
        "Log out immediately": "⌥⇧⌘Q",
        "Duplicate the selected files": "⌘D",
        "Eject the selected disk or volume": "⌘E",
        "Start a Spotlight search in the Finder window": "⌘F",
        "Show the Get Info window for a selected file": "⌘I",
        "Open the Computer window": "⇧⌘C",
        "Open the desktop folder": "⇧⌘D",
        "Open the Recents window, showing all of the files you viewed or changed recently": "⇧⌘F",
        "Open a Go to Folder window": "⇧⌘G",
        "Open the Home folder of the current macOS user account": "⇧⌘H",
        "Open iCloud Drive": "⇧⌘I",
        "Open the Network window": "⇧⌘K",
        "Open the Downloads folder": "⌥⌘L",
        "Create a new folder": "⇧⌘N",
        "Open the Documents folder": "⇧⌘O",
        "Show or hide the Preview pane in Finder windows": "⇧⌘P",
        "Open the AirDrop window": "⇧⌘R",
        "Show or hide the tab bar in Finder windows. ": "⇧⌘T",
        "Add selected Finder item to the Dock (OS X Mavericks or later)": "Control-⇧⌘T",
        "Open the Utilities folder": "⇧⌘U",
        "Show or hide the Dock. ": "⌥⌘D",
        "Add the selected item to the sidebar (OS X Mavericks or later)": "Control-⌘T",
        "Hide or show the path bar in Finder windows": "⌥⌘P",
        "Hide or show the Sidebar in Finder windows": "⌥⌘S",
        "Hide or show the status bar in Finder windows": "⌘Slash (/)",
        "Show View Options": "⌘J",
        "Open the Connect to Server window": "⌘K",
        "Make an alias of the selected item": "Control-⌘A",
        "Open a new Finder window": "⌘N",
        "Create a new Smart Folder": "⌥⌘N",
        "Show or hide the tab bar when a single tab is open in the current Finder window": "⌘T",
        "Show or hide the toolbar when a single tab is open in the current Finder window": "⌥⌘T",
        "Move the files in the Clipboard from their original location to the current location": "⌥⌘V",
        "Use Quick Look to preview the selected files": "⌘Y",
        "View a Quick Look slideshow of the selected files": "⌥⌘Y",
        "View the items in the Finder window as icons": "⌘1",
        "View the items in a Finder window as a list": "⌘2",
        "View the items in a Finder window in columns. ": "⌘3",
        "View the items in a Finder window in a gallery": "⌘4",
        "Go to the previous folder": "⌘[",
        "Go to the next folder": "⌘]",
        "Open the folder that contains the current folder": "⌘Up Arrow",
        "Open the folder that contains the current folder in a new window": "⌘CTRL Up Arrow",
        "Open the selected item": "⌘Down Arrow",
        "Open the selected folder. This works only when in list view": "Right Arrow",
        "Close the selected folder. This works only when in list view": "Left Arrow",
        "Move the selected item to the Trash": "⌘Delete",
        "Empty the Trash": "⇧⌘Delete",
        "Empty the Trash without confirmation dialog": "⌥⇧⌘Delete",
        "Turn target display mode on or off": "⌘Brightness Up",
        "Turn video mirroring on or off when your Mac is connected to more than one display": "⌘Brightness Down",
        "Open Displays preferences. This works with either Brightness key": "⌥Brightness Up",
        "Change the brightness of your external display, if supported by your display": "CTRL Brightness Up or CTRL Brightness Down",
        "Adjust the display brightness in smaller steps": "⌥SHIFT Brightness Up or ⌥SHIFT Brightness Down",
        "Open Mission Control preferences": "⌥Mission Control",
        "Show the desktop. ": "⌘Mission Control",
        "Show all windows of the front app": "CTRL Down Arrow",
        "Open Sound preferences": "⌥Volume Up",
        "Adjust the sound volume in smaller steps": "⌥SHIFT Volume Up or ⌥SHIFT Volume Down",
        "Open Keyboard preferences. This works with either Keyboard Brightness key": "⌥Keyboard Brightness Up",
        "Adjust the keyboard brightness in smaller steps": "⌥SHIFT Keyboard Brightness Up or ⌥SHIFT Keyboard Brightness Down",
        "Open the item in a separate window, then close the original window": "Option key while double-clicking",
        "Open a folder in a separate tab or window": "Command key while double-clicking",
        "Move the dragged item to the other volume, instead of copying it. ": "Command key while dragging to another volume",
        "Copy the dragged item. The pointer changes while you drag the item": "Option key while dragging",
        "Make an alias of the dragged item. The pointer changes while you drag the item": "⌥Command while dragging",
        "Open all folders within the selected folder. This works only when in list view": "⌥click a disclosure triangle",
        "See the folders that contain the current folder": "⌘click a window title",
        "Open Spotlight to start a search": "⌘Space bar",
        "Complete Spotlight search using the suggested result": "Right Arrow",
        "Move to the next Spotlight result": "Down Arrow",
        "Move to the previous Spotlight result": "Up Arrow",
        "Move to the first Spotlight result in the next category": "⌘Down Arrow",
        "Move to the first Spotlight result in the previous category": "⌘Up Arrow",
        "Show the path of a Spotlight result (such as a file) on your Mac": "Command",
        "Zoom in on an image preview in Spotlight": "Control (then move two fingers on the trackpad to move the image around in the preview)",
        "Open the selected Spotlight result": "Return key",
        "Spotlight - See a file in an app or the Finder": "⌘R or ⌘Double-click",
        "Open a Finder window with the Spotlight search field selected": "⌥⌘Space bar"
    }
}