# coding: utf8

shortcuts = {
    "Mac Keyboard Shortcuts": {
        # CUT, COPY, PASTE, AND OTHER COMMON SHORTCUTS
        "Cut the selected item and copy it to the Clipboard": "Command-X",
        "Copy the selected item to the Clipboard": "Command-C",
        "Paste the contents of Clipboard": "Command-V",
        "Undo previous command": "Command-Z",
        "Redo the undo command": "Shift-Command-Z",
        "Select all items": "Command-A",
        "Find items or open Find window": "Command-F",
        "Find again (next occurrence)": "Command-G",
        "Find previous occurrence": "Shift-Command-G",
        "Hide windows of front app": "Command-H",
        "View front app but hide others": "Option-Command-H",
        "Minimize front window to Dock": "Command-M",
        "Minimize all front app windows": "Option-Command-M",
        "Open selected item or open dialog": "Command-O",
        "Open print dialog": "Command-P",
        "Quit current app": "Command-Q",
        "Save current document": "Command-S",
        "Open new tab": "Command-T",
        "Close front window": "Command-W",
        "Close all windows of app": "Option-Command-W",
        "Force quit an app": "Option-Command-Esc",
        "Show or hide Spotlight search": "Command–Space bar",
        "Spotlight search from Finder window": "Command–Option–Space bar",
        "Show Character Viewer (emoji & symbols)": "Control–Command–Space bar or Fn-E",
        "Toggle full screen mode in app": "Control-Command-F",
        "Quick Look preview selected item": "Space bar",
        "Switch to next most recently used open app": "Command-Tab",
        "Switch between windows of current app": "Command–Grave accent (`)",
        "Take screenshot or screen recording": "Shift-Command-5",
        "Screenshot": "Shift-Command-3",
        "Screenshot (selection)": "Shift-Command-4",
        "Create new empty folder in Finder": "Shift-Command-N",
        "Create new folder containing selected items": "Control-Command-N",
        "Open settings/preferences for front app": "Command-Comma (,)",
        "Create a Quick Note": "Fn-Q",

        # SLEEP, LOG OUT, AND SHUT DOWN SHORTCUTS
        "Press to turn on or wake Mac; Hold 1.5 sec to sleep; Hold longer to force power off": "Power button",
        "Put Mac to sleep": "Option–Command–Power button or Option-Command-Media Eject",
        "Put displays to sleep": "Control–Shift–Power button or Control-Shift-Media Eject",
        "Show dialog to restart, sleep, or shut down": "Control–Power button or Control-Media Eject",
        "Force restart Mac without saving documents": "Control–Command–Power button",
        "Quit apps and restart Mac, ask to save unsaved docs": "Control-Command-Media Eject",
        "Quit apps and shut down Mac, ask to save unsaved docs": "Control–Option–Command–Power button or Control-option-Command-Media Eject",
        "Immediately lock screen": "Control-Command-Q",
        "Log out, confirmation asked": "Shift-Command-Q",
        "Log out immediately without confirmation": "Option-Shift-Command-Q",
        "Complete Log Out/Shut Down/Restart without confirmation dialog with Option key": "Option key while choosing Log Out/Shut Down/Restart from Apple menu",

        # FINDER AND SYSTEM SHORTCUTS
        "Duplicate selected files": "Command-D",
        "Eject selected disk or volume": "Command-E",
        "Start Spotlight search in Finder window": "Command-F",
        "Show Get Info window for selected file": "Command-I",
        "Show original for alias or reload page or check software updates": "Command-R",
        "Open Computer window": "Shift-Command-C",
        "Open desktop folder": "Shift-Command-D",
        "Open Recents window": "Shift-Command-F",
        "Open Go to Folder window": "Shift-Command-G",
        "Open Home folder": "Shift-Command-H",
        "Open iCloud Drive": "Shift-Command-I",
        "Open Network window": "Shift-Command-K",
        "Open Downloads folder": "Option-Command-L",
        "Create new folder": "Shift-Command-N",
        "Open Documents folder": "Shift-Command-O",
        "Show/hide Preview pane in Finder windows": "Shift-Command-P",
        "Open AirDrop window": "Shift-Command-R",
        "Show/hide tab bar in Finder windows": "Shift-Command-T",
        "Add selected Finder item to Dock": "Control-Shift-Command-T",
        "Hold Control-Shift while accessing Dock to toggle magnification": "Control-Shift",
        "Open Utilities folder": "Shift-Command-U",
        "Show/hide Dock": "Option-Command-D",
        "Add selected item to sidebar": "Control-Command-T",
        "Hide/show path bar in Finder windows": "Option-Command-P",
        "Hide/show Sidebar in Finder windows": "Option-Command-S",
        "Hide/show status bar in Finder windows": "Command–Slash (/)",
        "Show View Options": "Command-J",
        "Open Connect to Server window": "Command-K",
        "Make alias of selected item": "Control-Command-A",
        "Open new Finder window": "Command-N",
        "Create new Smart Folder": "Option-Command-N",
        "Show/hide tab bar when single tab open in Finder window": "Command-T",
        "Show/hide toolbar when single tab open in Finder window": "Option-Command-T",
        "Move files in Clipboard (cut-paste) in Finder": "Option-Command-V",
        "Quick Look preview selected files": "Command-Y",
        "Quick Look slideshow of selected files": "Option-Command-Y",
        "Change Finder view (icons, list, columns, gallery)": "Command-1 to Command-4",
        "Go to previous folder": "Command–Left Bracket ([)",
        "Go to next folder": "Command–Right Bracket (])",
        "Open folder that contains current folder": "Command–Up Arrow",
        "Open containing folder in new window": "Control–Command–Up Arrow",
        "Open selected item": "Command–Down Arrow",
        "Open selected folder (list view only)": "Right Arrow",
        "Close selected folder (list view only)": "Left Arrow",
        "Move selected item to Trash": "Command-Delete",
        "Empty Trash": "Shift-Command-Delete",
        "Empty Trash without confirmation": "Option-Shift-Command-Delete",
        "Turn video mirroring on/off with multiple displays": "Command–Brightness Down",
        "Open Displays settings": "Option–Brightness Up",
        "Change external display brightness": "Control–Brightness Up/Down",
        "Adjust brightness in smaller steps; add Control for external display": "Option–Shift–Brightness Up/Down",
        "Open Mission Control settings": "Option–Mission Control",
        "Show desktop": "Command–Mission Control or Fn-H or Fn-F11",
        "Open Mission Control": "Control–Up Arrow",
        "Show all windows of front app": "Control–Down Arrow",
        "Open Sound settings": "Option–Volume Up",
        "Adjust sound volume in smaller steps": "Option–Shift–Volume Up/Down",
        "Open Keyboard settings": "Option–Keyboard Brightness Up",
        "Adjust keyboard brightness in smaller steps": "Option–Shift–Keyboard Brightness Up/Down",
        "Open item in separate window then close original with Option key while double-clicking": "Option key while double-clicking",
        "Open folder in separate tab/window with Command key while double-clicking": "Command key while double-clicking",
        "Move rather than copy when dragging to another volume with Command key": "Command key while dragging to another volume",
        "Copy item when dragging with Option key (pointer changes)": "Option key while dragging",
        "Make alias of dragged item with Option-Command while dragging (pointer changes)": "Option-Command while dragging",
        "Open all folders within folder (list view) by Option-clicking a disclosure triangle": "Option-click a disclosure triangle",
        "See folders containing current folder by Command-clicking a window title": "Command-click a window title",
        "Select multiple items in Finder while holding Command or Shift": "Command or Shift while selecting",
        "Show/hide Dock": "Fn-A",
        "Show/hide Control Center": "Fn-C",
        "Start/stop dictation": "Fn-D",
        "Show/hide Notification Center": "Fn-N",
        "Show/hide Launchpad": "Fn-Shift-A",
        "Open Character Viewer": "Fn-Fn",
        "Open/close Type to Siri (press Command twice)": "Command + Command (press twice)",
        "Select previous input source": "Control–Space bar",
        "Select next input source": "Control–Option–Space bar",

        # TEXT-EDITING SHORTCUTS
        "Bold selected text toggle": "Command-B",
        "Italicize selected text toggle": "Command-I",
        "Add web link": "Command-K",
        "Underline selected text toggle": "Command-U",
        "Show/hide Fonts window": "Command-T",
        "Select Desktop folder in Open/Save dialog": "Command-D",
        "Show/hide definition of selected word": "Control-Command-D",
        "Show Spelling and Grammar window": "Shift-Command-Colon (:)",
        "Find misspelled words": "Command-Semicolon (;)",
        "Delete word to left": "Option-Delete",
        "Delete character to left": "Control-H",
        "Delete character to right": "Control-D",
        "Forward delete on keyboards lacking Forward Delete key": "Fn-Delete",
        "Delete text between insertion point and end of line/paragraph": "Control-K",
        "Page Up": "Fn–Up Arrow",
        "Page Down": "Fn–Down Arrow",
        "Home (beginning of document)": "Fn–Left Arrow",
        "End (end of document)": "Fn–Right Arrow",
        "Move insertion to beginning of document": "Command–Up Arrow",
        "Move insertion to end of document": "Command–Down Arrow",
        "Move insertion to beginning of current line": "Command–Left Arrow",
        "Move insertion to end of current line": "Command–Right Arrow",
        "Move insertion to beginning of previous word": "Option–Left Arrow",
        "Move insertion to end of next word": "Option–Right Arrow",
        "Select up to beginning of document": "Shift–Command–Up Arrow",
        "Select up to end of document": "Shift–Command–Down Arrow",
        "Select to beginning of line": "Shift–Command–Left Arrow",
        "Select to end of line": "Shift–Command–Right Arrow",
        "Extend selection one line up": "Shift–Up Arrow",
        "Extend selection one line down": "Shift–Down Arrow",
        "Extend selection one character left": "Shift–Left Arrow",
        "Extend selection one character right": "Shift–Right Arrow",
        "Extend selection to paragraph beginning (repeated presses)": "Option–Shift–Up Arrow",
        "Extend selection to paragraph end (repeated presses)": "Option–Shift–Down Arrow",
        "Extend selection to word beginning (repeated presses)": "Option–Shift–Left Arrow",
        "Extend selection to word end (repeated presses)": "Option–Shift–Right Arrow",
        "Move to beginning of line or paragraph": "Control-A",
        "Move to end of line or paragraph": "Control-E",
        "Move one character forward": "Control-F",
        "Move one character backward": "Control-B",
        "Center cursor/selection": "Control-L",
        "Move up one line": "Control-P",
        "Move down one line": "Control-N",
        "Insert new line after insertion point": "Control-O",
        "Swap characters around insertion point": "Control-T",
        "Left align": "Command–Left Curly Bracket ({)",
        "Right align": "Command–Right Curly Bracket (})",
        "Center align": "Shift–Command–Vertical bar (|)",
        "Go to search field": "Option-Command-F",
        "Show/hide toolbar in app": "Option-Command-T",
        "Copy style to Clipboard": "Option-Command-C",
        "Paste style from Clipboard": "Option-Command-V",
        "Paste and match style": "Option-Shift-Command-V",
        "Show/hide inspector window": "Option-Command-I",
        "Page setup": "Shift-Command-P",
        "Show Save As dialog or duplicate document": "Shift-Command-S",
        "Decrease size of selected item": "Shift–Command–Minus sign (-)",
        "Increase size of selected item": "Shift–Command–Plus sign (+) or Command–Equal sign (=)",
        "Open Help menu": "Shift–Command–Question mark (?)",

        # VISION SHORTCUTS
        "Invert colors": "Control-Option-Command-8",
        "Reduce contrast": "Control-Option-Command-Comma (,)",
        "Increase contrast": "Control-Option-Command-Period (.)",

        # KEYBOARD FOCUS SHORTCUTS
        "Move focus to menu bar": "Control-F2 or Fn-Control-F2",
        "Move focus to Dock": "Control-F3 or Fn-Control-F3",
        "Move focus to active or next window": "Control-F4 or Fn-Control-F4",
        "Move focus to window toolbar": "Control-F5 or Fn-Control-F5",
        "Move focus to floating window": "Control-F6 or Fn-Control-F6",
        "Move focus to previous panel": "Control-Shift-F6",
        "Change Tab focus behavior": "Control-F7 or Fn-Control-F7",
        "Move focus to status menu in menu bar": "Control-F8 or Fn-Control-F8",
        "Activate next open window in front app": "Command–Grave accent (`)",
        "Activate previous open window": "Shift–Command–Grave accent (`)",
        "Move focus to window drawer": "Option–Command–Grave accent (`)",
        "Move to next control": "Tab",
        "Move to previous control": "Shift-Tab",
        "Move to next control in text field": "Control-Tab",
        "Move to previous grouping of controls": "Control-Shift-Tab",
        "Move to adjacent item or adjust sliders": "Arrow keys",
        "Move to control adjacent to text field": "Control–Arrow keys",

        # OTHER ACCESSIBILITY SHORTCUTS
        "Show Accessibility Shortcuts panel": "Option-Command-F5 or triple-press Touch ID"
    },

    "Page URL": "https://support.apple.com/en-us/HT201236"
}