# coding: utf8

shortcuts = {
    "Word for Mac": {
        "Undo": "Command+Z or F1",
        "Redo": "Command+Y",
        "Cut": "Command+X or F2",
        "Copy": "Command+C or F3",
        "Paste": "Command+V or F4",
        "Paste text only": "Cmd+Shift+V",
        "Zoom in": "Cmd+Plus (+)",
        "Zoom out": "Cmd+Minus (-)",
        "Return to 100% zoom": "Cmd+0",
        "Zoom in/out with mouse": "Cmd+Scroll",
        "Display shortcut menu for selected item": "Shift+F10",
        "Display Go To dialog box": "Command+Option+G or F5",
        "Display Spelling and Grammar dialog box": "Command+Option+L or F7",
        "Enable extended selection mode": "F8",
        "Switch to next window": "Command+Grave accent (`)",
        "Switch to previous window": "Command+Shift+Grave accent (`)",
        "Display Save As dialog box": "Command+Shift+S",
        "Find text (move focus to Search in Document box)": "Command+F",
        "Display Find and Replace pane": "Control+H",
        "Display Print dialog box": "Command+P",
        "Close current document": "Command+F4",
        "Expand or minimize ribbon": "Command+Option+R",
        "Find next spelling/grammatical error": "Option+F7",
        "Open Dictionary": "Option+Shift+F7",
        
        # Navigate the Document
        "Move cursor one word left": "Option+Left arrow key",
        "Move cursor one word right": "Option+Right arrow key",
        "Move cursor up one paragraph": "Command+Up arrow key",
        "Move cursor down one paragraph": "Command+Down arrow key",
        "Move cursor to beginning of line": "Command+Left arrow",
        "Move cursor to end of line": "Command+Right arrow key",
        "Move cursor to top of previous page": "Command+Page up or Command+Fn+Up arrow key (MacBook)",
        "Move cursor to top of next page": "Command+Page down or Command+Fn+Down arrow key (MacBook)",
        "Move cursor to beginning of document": "Command+Home or Command+Fn+Left arrow key (MacBook)",
        "Move cursor to end of document": "Command+End or Command+Fn+Right arrow key (MacBook)",
        "Move cursor to previous insertion point": "Shift+F5",
        "Page up/down scroll view": "Page up / Page down",

        # Select Text and Graphics
        "Select multiple non-adjacent items": "Hold Command and click",
        "Select text": "Shift+Arrow keys",
        "Select word to left": "Shift+Option+Left arrow key",
        "Select word to right": "Shift+Option+Right arrow key",
        "Select to beginning of line": "Command+Shift+Left arrow key or Shift+Home",
        "Select to end of line": "Command+Shift+Right arrow key or Shift+End",
        "Select to beginning of paragraph": "Command+Shift+Up arrow key",
        "Select to end of paragraph": "Command+Shift+Down arrow key",
        "Select to top of screen": "Shift+Page up",
        "Select to bottom of screen": "Shift+Page down",
        "Select to beginning of document": "Command+Shift+Home",
        "Select to end of document": "Command+Shift+End",
        "Select to bottom of window": "Command+Shift+Option+Page down",
        "Select all content": "Command+A",

        # Extend a Selection
        "Start extending selection": "F8",
        "Select nearest character left/right": "F8 + Left/Right arrow key",
        "Expand selection (repeat F8 to expand to word, sentence, paragraph...)": "F8 repeatedly",
        "Reduce selection": "Shift+F8",
        "Select vertical block of text": "Command+Shift+F8 + arrow keys",
        "Stop extending selection": "Esc",

        # Edit Text and Graphics
        "Cut": "Command+X (F2)",
        "Copy": "Command+C (F3)",
        "Paste": "Command+V (F4)",
        "Paste special dialog": "Command+Control+V",
        "Cut to Spike": "Command+F3",
        "Paste from Spike": "Command+Shift+F3",
        "Copy text formatting": "Command+Option+C",
        "Paste text formatting": "Command+Option+V",
        "Paste text only": "Command+Shift+V",
        "Create AutoText entry": "Option+F3",
        "Display Font dialog": "Command+D",
        "Apply bold": "Command+B",
        "Apply italics": "Command+I",
        "Apply underline": "Command+U",
        "Apply underline (words only)": "Command+Shift+W",
        "Apply double underline": "Command+Shift+D",
        "Apply small caps": "Command+Shift+K",
        "Apply strike-through": "Command+Shift+X",
        "Apply subscript": "Command+Shift+Minus (-)",
        "Insert empty field": "Command+F9",
        "Insert line break": "Shift+Return",
        "Insert page break": "Command+Return",
        "Insert column break": "Command+Shift+Return",
        "Insert optional hyphen": "Command+Option+Minus (-)",
        "Insert nonbreaking hyphen": "Shift+Option+Minus (-)",
        "Insert copyright symbol": "(, C, )",
        "Insert registered trademark symbol": "Option+R",
        "Insert trademark symbol": "Option+2",

        # Align and Format Paragraphs
        "Center paragraph": "Command+E",
        "Justify paragraph": "Command+J",
        "Align left": "Command+L",
        "Align right": "Command+R",
        "Indent paragraph": "Control+Shift+M",
        "Remove indent": "Command+Shift+M",
        "Hanging indent": "Command+T",
        "Remove hanging indent": "Command+Shift+T",
        "Single spacing": "Command+1",
        "Double spacing": "Command+2",
        "1.5 line spacing": "Command+5",
        "Enable AutoFormat": "Command+Option+K",
        "Apply Normal style": "Command+Shift+N",
        "Apply Heading 1 style": "Command+Option+1",
        "Apply Heading 2 style": "Command+Option+2",
        "Apply Heading 3 style": "Command+Option+3",
        "Insert nonbreaking space": "Option+Spacebar",

        # Work with Tables
        "Insert a row": "Command+Control+I",

        # Work With Document Views
        "Switch to Read mode": "Command+Option+R",

        # Work with Right-to-Left Languages
        "Switch writing direction to RTL": "Control+Command+Left arrow",
        "Switch writing direction to LTR": "Control+Command+Right arrow",

        # Function Keys for Word for Mac
        "F1": "Undo previous action",
        "F2": "Cut",
        "Shift+F2": "Copy selected text",
        "F3": "Copy selected content",
        "Shift+F3": "Change case toggle",
        "Command+F3": "Cut to Spike",
        "Command+Shift+F3": "Paste from Spike",
        "Option+F3": "Create AutoText entry",
        "F4": "Paste",
        "Shift+F4": "Repeat last find or Go To",
        "Command+F4": "Close document",
        "F5": "Go To dialog",
        "Shift+F5": "Move cursor to last change",
        "Command+Shift+F5": "Display Bookmark dialog",
        "F6": "Switch between document, task pane, status bar, ribbon",
        "Shift+F6": "Switch between document, ribbon, status bar, task pane",
        "Command+F6": "Switch to next document window",
        "Command+Shift+F6": "Switch to previous document window",
        "F7": "Spelling and Grammar dialog",
        "Shift+F7": "Thesaurus",
        "Option+F7": "Find next spelling or grammatical error",
        "Option+Shift+F7": "Dictionary",
        "F8": "Extend selection mode",
        "Shift+F8": "Reduce selection",
        "Command+Shift+F8": "Toggle extend selection mode",
        "Option+F8": "Macro dialog",
        "F9": "Update fields",
        "Shift+F9": "Toggle field code & result display",
        "Command+F9": "Insert empty field",
        "Command+Shift+F9": "Unlink field",
        "Option+F9": "Toggle all field codes/results",
        "Option+Shift+F9": "Run GOTOBUTTON or MACROBUTTON",
        "Shift+F10": "Shortcut menu",
        "F11": "Move to next field",
        "Shift+F11": "Move to previous field",
        "Command+F11": "Lock field",
        "Command+Shift+F11": "Unlock field",
        "Option+F11": "Open VBA editor",
        "F12": "Save As dialog",
        "Shift+F12": "Save",
        "Command+F12": "Open dialog",
        "Command+Shift+F12": "Print tab in Backstage",
        "Option+Shift+F12": "Select Table of Contents button",

        # Word for iOS Mac Shortcuts (external keyboard)
        "Save (iOS)": "Command+S",
        "Print (iOS)": "Command+P",
        "Close (iOS)": "Command+W",
        "Find (iOS)": "Command+F",
        "Find next (iOS)": "Command+G",
        "Find previous (iOS)": "Shift+Command+G",
        "Select all (iOS)": "Command+A",
        "Undo (iOS)": "Command+Z",
        "Redo (iOS)": "Command+Y",
        "Cut (iOS)": "Command+X",
        "Copy (iOS)": "Command+C",
        "Paste (iOS)": "Command+V",
        "Bold (iOS)": "Command+B",
        "Italic (iOS)": "Command+I",
        "Underline (iOS)": "Command+U",
        "Underline words only (iOS)": "Command+Shift+W",
        "Change to Normal style (iOS)": "Option+Command+N",
        "Hyperlink (iOS)": "Command+K",
        "Small caps (iOS)": "Shift+Command+K",
        "All caps (iOS)": "Shift+Command+A",
        "Center paragraph (iOS)": "Command+E",
        "Justify paragraph (iOS)": "Command+J",
        "Align left (iOS)": "Command+L",
        "Align right (iOS)": "Command+R",
        "Indent paragraph (iOS)": "Control+Shift+M",
        "Remove indent (iOS)": "Shift+Command+M",
        "Hanging indent (iOS)": "Command+T",
        "Apply formatting from copied text (iOS)": "Shift+Command+V",
        "Add comment (iOS)": "Option+Command+A",
        "Find/replace (iOS)": "Control+H",
        "Toggle revision marks (iOS)": "Shift+Command+E",
    }
}

page_url = "https://support.office.com/en-us/article/Keyboard-shortcuts-in-Word-for-Mac-3256d48a-7967-475d-be81-a6e3e1284b25"