# coding: utf8
shortcuts = {
    # https://support.office.com/en-us/article/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f?ui=en-US&rs=en-US&ad=US
    "Microsoft Excel": {
        "Create new workbook": "⌘N",
        "Open workbook": "⌘O",
        "Save workbook": "⌘S",
        "Save as": "⌘⇧S",
        "Print file": "⌘P",
        "Close current workbook": "⌘W",
        "Close Excel": "⌘Q",
        "Expand or collapse ribbon": "⌘⌥R",
        "Move to next ribbon control": "Tab",
        "Activate or open selected control": "Space",
        "Confirm control change": "Return",
        "Open help": "F1",
        "Undo last action": "⌘Z",
        "Redo last action": "⌘Y",
        "Copy selected cells": "⌘C",
        "Repeat last action": "⌘Y",
        "Cut selected cells": "⌘X",
        "Paste content from clipboard": "⌘V",
        "Display the Paste Special dialog box": "⌃⌘V",
        "Display find and replace": "⌘F",
        "Display find and replace, replace selected": "⌃H",
        "Find next match": "⌘G",
        "Find previous match": "⌘⇧G",
        "Create embedded chart": "Fn⌥F1",
        "Create chart in new worksheet": "FnF11",
        "Insert table": "⌃T",
        "Toggle Autofilter": "⌘⇧F",
        "Activate filter": "⌥↓",
        "Select table row": "⇧Space",
        "Select table column": "⌃Space",
        "Select table": "⌘A",
        "Clear slicer filter": "⌥C",
        "Toggle table total row": "⌘⇧T",
        "Drag and cut": "drag",
        "Drag and copy": "⌥drag",
        "Drag and insert": "⇧drag",
        "Drag and insert copy": "⌥⇧drag",
        "Drag to worksheet": "⌘drag",
        "Drag to duplicate worksheet": "⌥drag",
        "Move one cell right": "→",
        "Move one cell left": "←",
        "Move one cell up": "↑",
        "Move one cell down": "↓",
        "Move one screen right": "Fn⌥↓",
        "Move one screen left": "Fn⌥↑",
        "Move one screen up": "Fn↑",
        "Move one screen down": "Fn↓",
        "Move to right edge of data region": "⌃→",
        "Move to left edge of data region": "⌃←",
        "Move to top edge of data region": "⌃↑",
        "Move to bottom edge of data region": "⌃↓",
        "Move to beginning of row": "Fn←",
        "Move to last cell in worksheet": "Fn⌃→",
        "Move to first cell in worksheet": "Fn⌃←",
        "Turn End mode on": "Fn→",
        "Go back to hyperlink": "⌃GReturn",
        "Select entire row": "⇧Space",
        "Select entire column": "⌃Space",
        "⌃Space": "Select entire worksheet",
        "Select entire worksheet": "⌘A",
        "Add adjacent cells to selection": "⇧Click",
        "Add non-adjacent cells to selection": "⌘Click",
        "Same selection in next column": "⌥Tab",
        "Same selection in previous column": "⌥⇧Tab",
        "Move right between non-adjacent selections": "⌃⌥→",
        "Move left between non-adjacent selections": "⌃⌥←",
        "Toggle add to selection mode": "Fn⇧F8",
        "Cancel selection": "Esc",
        "Select active cell only": "⇧Delete",
        "Show the active cell on worksheet": "⌘Delete",
        "Move active cell clockwise in selection": "⌃.",
        "Move active cell down in selection": "Return",
        "Move active cell up in selection": "⇧Return",
        "Move active cell right in a selection": "Tab",
        "Move active cell left in a selection": "⇧Tab",
        "Extend selection by one cell right": "⇧→",
        "Extend selection by one cell left": "⇧←",
        "Extend selection by one cell up": "⇧↑",
        "Extend selection by one cell down": "⇧↓",
        "Extend the selection to the last cell right": "⌃⇧→",
        "Extend the selection to the last cell left": "⌃⇧←",
        "Extend the selection to the last cell up": "CtrlShift↑",
        "Extend the selection to the last cell down": "⌃⇧↓",
        "Extend selection up one screen": "Fn⇧↑",
        "Extend selection down one screen": "Fn⇧↓",
        "Extend selection right one screen": "Fn⇧⌘↓",
        "Extend selection left one screen": "Fn⇧⌘↑",
        "Extend selection to start of row": "Fn⇧←",
        "Extend selection to first cell in worksheet": "Fn⌃⇧←",
        "Extend selection to last cell in worksheet": "Fn⌃⇧→",
        "Toggle extend selection mode": "FnF8",
        "Display 'Go To' dialog box": "⌃G",
        "Select cells with comments": "Fn⌃⇧O",
        "Select current region around active cell": "⇧⌃Space",
        "Select current region": "⌘A",
        "Select current array": "⌃/",
        "Select row differences": "⌃\\",
        "Select column differences": "⌃⇧|",
        "Select direct precedents": "⌃[",
        "Select all precedents": "⌃⇧{",
        "Select direct dependents": "Ctrl]",
        "Select all dependents": "⌃⇧}",
        "Select visible cells only": "⌘⇧Z",
        "Edit the active cell": "⌃U",
        "Insert or edit comment": "Fn⇧F2",
        "Cancel entry": "Esc",
        "Select one character right": "⇧→",
        "Select one character left": "⇧←",
        "Move one word right": "⌃→",
        "Move one word left": "⌃←",
        "Select one word right": "⌃⇧→",
        "Select one word left": "⌃⇧←",
        "Select to beginning of cell": "Fn⇧←",
        "Select to end of cell": "Fn⇧→",
        "Delete to end of line": "⌃Delete",
        "Delete character to the left of cursor": "Delete",
        "Delete character to the right of cursor": "FnDelete",
        "Start a new line in the same cell": "⌃⌥Return",
        "Enter and move down": "Return",
        "Enter and move up": "⇧Return",
        "Enter and move right": "Tab",
        "Enter and move left": "⇧Tab",
        "Complete entry and stay in same cell": "⌃Return",
        "Enter same data in multiple cells": "⌃Return",
        "Insert current date": "⌃;",
        "Insert current time": "⌃⇧:",
        "Fill down from cell above": "⌃D",
        "Fill right from cell left": "⌃R",
        "Copy formula from cell above": "⌃'",
        "Copy value from cell above": "⌃⇧\"",
        "Add hyperlink": "⌘K",
        "Display AutoComplete list": "⌥↓",
        "Format (almost) anything": "⌘1",
        "Display Format Cells with Font tab selected": "⌃⇧F",
        "Apply or remove bold formatting": "⌘B",
        "Apply or remove italic formatting": "⌘I",
        "Apply or remove underscoring": "⌘U",
        "Apply or remove strikethrough formatting": "⌘⇧X",
        "Add or remove the shadow font style": "⌘⇧W",
        "Add or remove the outline font style": "⌘⇧D",
        "Align center": "⌘E",
        "Align left": "⌘L",
        "Align right": "⌘R",
        "Indent": "⌃⌥Tab",
        "Remove indent": "⌃⌥⇧Tab",
        "Increase font size one step": "⌘⇧>",
        "Decrease font size one step": "⌘⇧<",
        "Apply general format": "⌃⇧~",
        "Apply currency format": "⌃⇧$",
        "Apply percentage format": "⌃⇧%",
        "Apply scientific format": "⌃⇧^",
        "Apply date format": "⌃⇧#",
        "Apply time format": "⌃⇧@",
        "Apply number format": "⌃⇧!",
        "Add border outline": "⌘⌥0",
        "Add or remove border right": "⌘⌥→",
        "Add or remove border left": "⌘⌥←",
        "Add or remove border top": "⌘⌥↑",
        "Add or remove border bottom": "⌘⌥↓",
        "Remove borders": "⌘⌥_",
        "Toggle absolute and relative references": "⌘T",
        "Open the Insert Function Dialog Box": "Fn⇧F3",
        "Autosum selected cells": "⌘⇧T",
        "Toggle formulas on and off": "⌃`",
        "Insert function arguments": "⌃⇧A",
        "Enter array formula": "⌃⇧Return",
        "Calculate worksheets": "FnF9",
        "Calculate active worksheet": "Fn⇧F9",
        "Evaluate part of a formula": "FnF9",
        "Expand or collapse the formula bar": "⌃⇧U",
        "Display function arguments dialog box": "⌃A",
        "Define name": "Fn⌃F3",
        "Define name using row and column labels": "Fn⌃⇧F3",
        "Accept function with autocomplete": "↓Tab",
        "Display Insert Dialog box": "⌃I",
        "Insert rows": "⌃I",
        "Insert columns": "⌃I",
        "Display Delete dialog box": "⌃-",
        "Delete rows": "⌃-",
        "Delete columns": "⌃-",
        "Delete cells": "⌃-",
        "Delete contents of selected cells": "FnDelete",
        "Hide columns": "⌃0",
        "Hide rows": "⌃9",
        "Unhide rows": "⌃⇧9",
        "Unhide columns": "⌃⇧0",
        "Group rows or columns": "⌘⇧K",
        "Ungroup rows or columns": "⌘⇧J",
        "Open Group Dialog Box": "⌘⇧K",
        "Open Ungroup Dialog Box": "⌘⇧J",
        "Hide or show outline symbols": "⌃8",
        "Zoom in": "⌥⌘+",
        "Zoom out": "⌥⌘-",
        "Select entire pivot table": "⌘A",
        "Toggle pivot table field checkbox": "Space",
        "Group pivot table items": "⌘⇧K",
        "Ungroup pivot table items": "⌘⇧J",
        "Create pivot chart on new worksheet": "FnF11",
        "Open pivot table wizard": "⌘⌥P",
        "Insert new worksheet": "fn⇧F11",
        "Go to next worksheet": "Fn⌃↓",
        "Go to previous worksheet": "Fn⌃↑",
        "Move to next pane": "FnF6",
        "Move to previous pane": "Fn⇧F6",
        "Go to next workbook": "⌃Tab",
        "Go to previous workbook": "⌃⇧Tab",
        "Minimize current workbook window": "⌘M",
        "Maximize current workbook window": "fn⌃F10",
        "Select adjacent worksheets": "⇧Click",
        "Select non-adjacent worksheets": "⌘Click",
        "Toggle scroll lock": "Fn⇧F14",
        "Toggle full screen": "⌃⌘F",
        "Move to next control": "Tab",
        "Move to previous control": "⇧Tab",
        "Move to next tab": "⌃Tab",
        "Move to previous tab": "⌃⇧Tab",
        "Accept and apply": "Return",
        "Check and uncheck box": "Space",
        "Cancel and close the dialog box": "Esc",
        "Open Spelling dialog box": "FnF7",
        "Open Thesaurus dialog box": "Fn⇧F7",
        "Open Macro dialog box": "Fn⌥F8",
        "Open VBA Editor": "Fn⌥F11",
        "Duplicate object": "⌘D",
        "Snap to grid": "⌘",
        "Hide or show objects": "⌃6",
        "Display Modify Cell Style dialog box": "⌘⇧L",
        "Display right-click menu": "Fn⇧F10",
        "Delete comment": "fnShiftF10",
        "Display control menu": "?"
    }
}
