# coding: utf8

shortcuts = {
    "Excel for Mac": {
        "Paste selection": "Cmd+V or Control+V",
        "Copy selection": "Cmd+C or Control+C",
        "Clear selection": "Delete",
        "Save workbook": "Cmd+S or Control+S",
        "Undo action": "Cmd+Z or Control+Z",
        "Redo action": "Cmd+Y or Control+Y or Cmd+Shift+Z",
        "Cut selection": "Cmd+X or Control+X or Shift+Mac Delete",
        "Apply bold formatting": "Cmd+B or Control+B",
        "Print workbook": "Cmd+P or Control+P",
        "Open Visual Basic": "Option+F11",
        "Fill cells down": "Cmd+D or Control+D",
        "Fill cells right": "Cmd+R or Control+R",
        "Insert cells": "Control+Shift+=",
        "Delete cells": "Cmd+Hyphen (-) or Control+Hyphen (-)",
        "Calculate all open workbooks": "Cmd+= or F9",
        "Close window": "Cmd+W or Control+W",
        "Quit Excel": "Cmd+Q",
        "Display Go To dialog box": "Control+G or F5",
        "Display Format Cells dialog box": "Cmd+1 or Control+1",
        "Display Replace dialog box": "Control+H or Cmd+Shift+H",
        "Use Paste Special": "Cmd+Control+V or Control+Option+V or Cmd+Option+V",
        "Apply underline formatting": "Cmd+U",
        "Apply italic formatting": "Cmd+I or Control+I",
        "Open a new blank workbook": "Cmd+N or Control+N",
        "Create new workbook from template": "Cmd+Shift+P",
        "Display Save As dialog box": "Cmd+Shift+S or F12",
        "Display Help window": "F1 or Cmd+Forward slash (/)",
        "Select all": "Cmd+A or Cmd+Shift+Spacebar",
        "Add or remove a filter": "Cmd+Shift+F or Control+Shift+L",
        "Minimize/maximize ribbon tabs": "Cmd+Option+R",
        "Display Open dialog box": "Cmd+O or Control+O",
        "Check spelling": "F7",
        "Open thesaurus": "Shift+F7",
        "Display Formula Builder": "Shift+F3",
        "Open Define Name dialog box": "Cmd+F3",
        "Insert/reply to threaded comment": "Cmd+Return",
        "Open Create names dialog box": "Cmd+Shift+F3",
        "Insert a new sheet": "Shift+F11",
        "Print preview": "Cmd+P or Control+P",

        # Work in Windows & Dialog Boxes
        "Expand/minimize ribbon": "Cmd+Option+R",
        "Switch to full screen view": "Cmd+Control+F",
        "Switch to next app": "Cmd+Tab",
        "Switch to previous app": "Shift+Cmd+Tab",
        "Close active workbook window": "Cmd+W",
        "Take screenshot and save to desktop": "Shift+Cmd+3",
        "Minimize active window": "Control+F9",
        "Maximize/restore active window": "Control+F10 or Cmd+F10",
        "Hide Excel": "Cmd+H",
        "Move to next box, option, control, or command": "Tab",
        "Move to previous box, option, control, or command": "Shift+Tab",
        "Exit dialog or cancel action": "Esc",
        "Perform default button action": "Return",
        "Cancel command and close": "Esc",

        # Move and Scroll in Sheet/Workbook
        "Move one cell up/down/left/right": "Arrow keys",
        "Move to edge of current data region": "Cmd+Arrow key",
        "Move to beginning of row": "Home (MacBook: Fn+Left arrow)",
        "Move to beginning of sheet": "Control+Home (MacBook: Control+Fn+Left arrow)",
        "Move to last cell in use": "Control+End (MacBook: Control+Fn+Right arrow)",
        "Move down one screen": "Page Down (MacBook: Fn+Down arrow)",
        "Move up one screen": "Page Up (MacBook: Fn+Up arrow)",
        "Move one screen right": "Option+Page Down (MacBook: Fn+Option+Down arrow)",
        "Move one screen left": "Option+Page Up (MacBook: Fn+Option+Up arrow)",
        "Move to next sheet": "Control+Page Down or Option+Right arrow",
        "Move to previous sheet": "Control+Page Up or Option+Left arrow",
        "Scroll to display active cell": "Control+Delete",
        "Display Go To dialog box": "Control+G",
        "Display Find dialog box": "Control+F or Shift+F5",
        "Access search (in cell or selection)": "Cmd+F",

        # Enter Data on Sheet
        "Edit selected cell": "F2",
        "Complete entry and move forward": "Return",
        "Start new line in same cell": "Option+Return or Control+Option+Return",
        "Fill selected range with text": "Cmd+Return or Control+Return",
        "Complete entry and move up": "Shift+Return",
        "Complete entry and move right": "Tab",
        "Complete entry and move left": "Shift+Tab",
        "Cancel cell entry": "Esc",
        "Delete char to left": "Delete",
        "Delete char to right": "Mac Delete button or Fn+Delete on MacBook",
        "Delete text to end of line": "Control+Mac Delete button or Control+Fn+Delete on MacBook",
        "Move one char up/down/left/right": "Arrow keys",
        "Move to beginning of line": "Home (MacBook: Fn+Left arrow)",

        # Work in Cells or Formula Bar
        "Turn on/off tooltips": "Control+Option+P",
        "Edit selected cell": "F2",
        "Expand/collapse formula bar": "Control+Shift+U",
        "Delete preceding char when editing": "Delete",
        "Complete cell entry": "Return",
        "Enter formula as array formula": "Shift+Cmd+Return or Control+Shift+Return",
        "Cancel entry": "Esc",
        "Display Formula Builder after typing function": "Control+A",
        "Insert hyperlink": "Cmd+K or Control+K",
        "Edit active cell and move insertion point to end": "Control+U",
        "Open Formula Builder": "Shift+F3",
        "Calculate active sheet": "Shift+F9",
        "Display context menu": "Shift+F10",
        "Start a formula": "Equal sign (=)",
        "Toggle formula reference style": "Cmd+T or F4",
        "Insert AutoSum formula": "Shift+Cmd+T",
        "Enter date": "Control+Semicolon (;)",
        "Enter time": "Cmd+Semicolon (;)",
        "Copy value from cell above": "Control+Shift+\"",
        "Alternate between displaying values/formulas": "Control+Grave accent (`)",
        "Display AutoComplete list": "Option+Down arrow",
        "Define name": "Control+L",
        "Open Smart Lookup pane": "Control+Option+Cmd+L",
        "Calculate all worksheets": "Control+Option+F9",
        "Check dependent formulas & calculate all": "Control+Option+Shift+F9",

        # Format and Edit Data
        "Create table": "Cmd+T or Control+T",
        "Insert line break in cell": "Cmd+Option+Return or Control+Option+Return",
        "Insert special characters": "Control+Cmd+Spacebar",
        "Increase font size": "Shift+Cmd+>",
        "Decrease font size": "Shift+Cmd+<",
        "Align center": "Cmd+E",
        "Align left": "Cmd+L",
        "Display Modify Cell Style dialog": "Shift+Cmd+L",
        "Display Format Cells dialog": "Cmd+1",
        "Apply general number format": "Control+Shift+Tilde (~)",
        "Apply currency format": "Control+Shift+Dollar sign ($)",
        "Apply percentage format": "Control+Shift+Percent sign (%)",
        "Apply exponential format": "Control+Shift+Caret (^)",
        "Apply date format": "Control+Shift+Number sign (#)",
        "Apply time format": "Control+Shift+At symbol (@)",
        "Apply number format": "Control+Shift+Exclamation point (!)",
        "Apply outline border": "Cmd+Option+0",
        "Add outline border to right": "Cmd+Option+Right arrow",
        "Add outline border to left": "Cmd+Option+Left arrow",
        "Add outline border to top": "Cmd+Option+Up arrow",
        "Add outline border to bottom": "Cmd+Option+Down arrow",
        "Remove outline borders": "Cmd+Option+Hyphen",
        "Apply/remove bold": "Cmd+B",
        "Apply/remove italic": "Cmd+I",
        "Apply/remove underline": "Cmd+U",
        "Apply/remove strikethrough": "Shift+Cmd+X",
        "Hide/unhide column or row using Cmd or Control with parentheses keys": "Cmd/Control +( or )",

        # Select Cells, Columns, or Rows
        "Extend selection by one cell": "Shift+Arrow",
        "Extend selection to last nonblank cell": "Shift+Cmd+Arrow",
        "Extend selection to beginning of row": "Shift+Home (MacBook: Shift+Fn+Left)",
        "Extend selection to beginning of sheet": "Control+Shift+Home (MacBook: Control+Shift+Fn+Left)",
        "Extend selection to last cell used": "Control+Shift+End (MacBook: Control+Shift+Fn+Right)",
        "Select entire column": "Control+Spacebar",
        "Select entire row": "Shift+Spacebar",
        "Select current region or entire sheet": "Cmd+A",
        "Select only visible cells": "Shift+Cmd+Asterisk (*)",
        "Select only active cell when multiple selected": "Shift+Delete (not forward Delete)",
        "Extend selection down/up one screen": "Shift+Page down/up (MacBook: Shift+Fn+Down/Up)",
        "Alternate hiding/displaying objects": "Control+6",
        "Turn on extend mode": "F8",
        "Add another range to selection": "Shift+F8",
        "Select current array": "Control+Forward slash (/)",
        "Select row cells not matching active cell": "Control+Backward slash (\\)",
        "Select only cells referred by formulas": "Control+Shift+Left bracket ([)",
        "Select cells referred directly or indirectly": "Control+Shift+Left brace ({)",
        "Select cells referring directly": "Control+Right bracket (])",
        "Select cells referring directly or indirectly": "Control+Shift+Right brace (})",

        # Work with a Selection
        "Copy selection": "Cmd+C or Control+V",
        "Paste selection": "Cmd+V or Control+V",
        "Cut selection": "Cmd+X or Control+X",
        "Clear selection": "Delete",
        "Delete selection": "Control+Hyphen",
        "Undo last action": "Cmd+Z",
        "Hide/unhide columns or rows with Cmd/Control + parentheses": "Cmd/Control +( or )",
        "Move selected rows, columns, or cells": "Hold Shift while dragging",

        # Use Charts
        "Insert new chart sheet": "F11",
        "Cycle chart selection": "Arrow keys",

        # Sort, Filter, PivotTable
        "Open Sort dialog": "Cmd+Shift+R",
        "Add/remove filter": "Cmd+Shift+F or Control+Shift+L",
        "Display Filter list or PivotTable field menu": "Option+Down arrow",

        # Outline Data
        "Display/hide outline symbols": "Control+8",
        "Hide/unhide selected rows/columns": "Control+9 / Control+Shift+( or Control+0 / Control+Shift+)",

        # Function Key Shortcuts
        "Help": "F1",
        "Edit cell": "F2",
        "Insert note": "Shift+F2",
        "Threaded comment": "Cmd+Shift+F2",
        "Save dialog": "Option+F2",
        "Formula Builder": "Shift+F3",
        "Define Name": "Cmd+F3",
        "Close window/dialog": "Cmd+F4",
        "Go To": "F5",
        "Find": "Shift+F5",
        "Search Sheet dialog": "Control+F5",
        "Switch focus worksheet/ribbon/task pane/status bar": "F6 or Shift+F6",
        "Check Spelling": "F7",
        "Thesaurus": "Shift+F7 or Control+Option+Cmd+R",
        "Extend selection": "F8",
        "Add to selection": "Shift+F8",
        "Macro dialog": "Option+F8",
        "Calculate all open workbooks": "F9",
        "Calculate active sheet": "Shift+F9",
        "Minimize active window": "Control+F9",
        "Context menu": "Shift+F10",
        "Pop-up menu on object": "Option+Shift+F10",
        "Maximize/restore active window": "Control+F10 or Cmd+F10",
        "Insert new chart sheet": "F11",
        "Insert new sheet": "Shift+F11",
        "Insert Excel 4.0 macro sheet": "Cmd+F11",
        "Open Visual Basic": "Option+F11",
        "Display Save As dialog": "F12",
        "Display Open dialog": "Cmd+F12",
        "Open Power Query Editor": "Option+F12",

        # Drawing
        "Toggle Drawing mode": "Cmd+Control+Z"
    },
    "Page URL": "https://support.office.com/en-us/article/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f?ui=en-US&rs=en-US&ad=US"
}