# coding: utf8
shortcuts = {
    "Microsoft Word":{
        # https://support.office.com/en-us/article/Keyboard-shortcuts-in-Word-for-Mac-3256d48a-7967-475d-be81-a6e3e1284b25
        "Undo the last action":"⌘Z or ^Z",
        "Cut selected text or graphics":"⌘X or ^X",
        "Copy selected text or graphics to the Clipboard":"⌘C or ^C",
        "Paste the Clipboard contents":"⌘V or ^V",
        "Choose the Go To command (Edit menu)":"⌥⌘G",
        "Open the Spelling and Grammar dialog box":"⌥⌘L",
        "Extend a selection":"F8",
        "Go to the next window":"⌘`",
        "Choose the Save As command (File menu).":"⌘⇧S",
        "Copy selected text":"⇧F2",
        "Change letters to uppercase, lowercase, or mixed case":"⇧F3",
        "Find (focus on search bar)":"^F",
        "Find and Replace":"^H",
        "Print a document":"⌘P or ^P",
        "Move to the previous insertion point":"⇧F5",
        "Go to the previous window":"⌘⇧`",
        "Open the Thesaurus pane":"⇧F7",
        "Shrink a selection":"⇧F8",
        "Switch between a field code and its result":"⇧F9",
        "Cut the selection to the Spike":"⌘F3",
        "Close the window":"⌘F4",
        "Expand or minimize the ribbon":"⌥⌘R",
        "Edit a bookmark":"⌘⇧F5",
        "Find the next misspelling or grammatical error.":"⌥F7",
        "Look up selected text on the Internet":"⌘⇧L",
        "Cursor - Move one character to the left":"←",
        "Cursor - Move one character to the right":"→",
        "Cursor - Move one word to the left":"⌥←",
        "Cursor - Move one word to the right":"⌥→",
        "Cursor - Move one paragraph up":"⌘↑",
        "Cursor - Move one paragraph down":"⌘↓",
        "Cursor - Move one cell to the left (in a table)":"⇧Tab",
        "Cursor - Move one cell to the right (in a table)":"Tab",
        "Cursor - Move up one line":"↑",
        "Cursor - Move down one line":"↓",
        "Cursor - Move to the end of a line":"⌘→ or End",
        "Cursor - Move to the beginning of a line":"⌘← or Home",
        "Cursor - Move up one screen (scrolling)":"Page Up",
        "Cursor - Move down one screen (scrolling)":"Page Down",
        "Cursor - Move to the top of the next page":"⌘Page Down",
        "Cursor - Move to the top of the previous page":"⌘Page Up",
        "Cursor - To the end of a document":"⌘End",
        "Cursor - On a MacBook keyboard:":"⌘Fn→",
        "Cursor - To the beginning of a document":"⌘Home",
        "Cursor - On a MacBook keyboard:":"⌘Fn←",
        "Cursor - To the previous insertion point":"⇧F5",
        "Select multiple items not next to each other":"Select first item, hold down ⌘, and then select any additional items",
        "Select one character to the right":"⇧→",
        "Select one character to the left":"⇧←",
        "Select one word to the right":"⇧⌥→",
        "Select one word to the left":"⇧⌥←",
        "Select to the end of a line":"⌘⇧→ or ⇧End",
        "Select to the beginning of a line":"⌘⇧← or ⇧Home",
        "Select one line down":"⇧↓",
        "Select one line up":"⇧↑",
        "Select to the end of a paragraph":"⌘⇧↓",
        "Select to the beginning of a paragraph":"⌘⇧↑",
        "Select one screen down":"⇧Page Down",
        "Select one screen up":"⇧Page Up",
        "Select to the beginning of a document":"⌘⇧Home",
        "Select to the end of a document":"⌘⇧End",
        "Select to the end of a window":"⌥⌘⇧Page Down",
        "Select to select the entire document":"⌘A",
        "Select to a vertical block of text":"⌘⇧F8, and then use the arrow keys",
        "Select to a specific location in a document":"F8, and then use the arrow keys",
        "Select the next cell's contents":"Tab",
        "Select the preceding cell's contents":"⇧Tab",
        "Extend a selection to adjacent cells":"Hold down ⇧ and press an arrow key repeatedly",
        "Select a column":"Click in the column's top or bottom cell. Hold down ⇧ and press the ↑ or ↓ key repeatedly",
        "Extend a selection (or block)":"⌘⇧F8, and then use the arrow keys",
        "Reduce the selection size":"⇧F8",
        "Select multiple cells, columns, or rows that are not next to each other":"Select first item, hold down  ⌘, and then select any additional items",
        "Extend select - Turn on extend mode":"F8",
        "Extend select - Select the nearest character to the left":"F8, ←",
        "Extend select - Select the nearest character to the right":"F8, →",
        "Extend select - Expand a selection":"Press F8 repeatedly.",
        "Extend select - Reduce the size of a selection":"⇧F8",
        "Extend select - Turn off extend mode":"Esc",
        "Edit - Copy text or graphics":"⌘C or F3",
        "Edit - Copy a style":"⌘⇧C",
        "Edit - Paste a style":"⌘⇧V",
        "Edit - Copy text or graphics to the Scrapbook":"^⌥C",
        "Edit - Cut selected text to the clipboard":"⌘X or F2",
        "Edit - Move text or graphics":"⌘X or F2 (then move the cursor and press ⌘V or F4)",
        "Edit - Create AutoText":"⌥F3",
        "Edit - Insert AutoText":"⌘⌥⇧V",
        "Edit - Paste the Clipboard contents":"⌘V or F4",
        "Edit - Paste special":"⌘^V",
        "Edit - Paste and match the formatting of the surrounding text":"⌘⌥⇧V",
        "Edit - Paste the Spike  contents":"⌘⇧F3",
        "Edit - Delete one character to the left":"Delete",
        "Edit - Delete one word to the left":"⌘Delete",
        "Edit - Delete one character to the right":"⌘ or Clear",
        "Edit - Delete one word to the right":"⌘ ⌘",
        "Edit - Cut selected text to the Clipboard":"⌘X or F2",
        "Edit - Undo the last action":"⌘Z",
        "Edit - Redo the last action":"⌘Y",
        "Edit - Cut to the Spike":"⌘F3",
        "Center a paragraph":"⌘E",
        "Justify a paragraph":"⌘J",
        "Left-align a paragraph":"⌘L",
        "Right-align a paragraph":"⌘R",
        "Indent a paragraph from the left":"^⇧M",
        "Remove a paragraph indent from the left":"⌘⇧M",
        "Create a hanging indent":"⌘T",
        "Remove a hanging indent":"⌘⇧T",
        "Start AutoFormat":"⌘⌥K",
        "Apply the Normal style":"⌘⇧N",
        "Apply the Heading 1 style":"⌘⌥1",
        "Apply the Heading 2 style":"⌘⌥2",
        "Apply the Heading 3 style":"⌘⌥3",
        "Apply the List style when the cursor is at the beginning of a line":"⌘⇧L",
        "Insert a nonbreaking space":"⌥Space",
        "Set lines as single-spaced":"⌘1",
        "Set lines as double-spaced":"⌘2",
        "Set lines as 1.5-line spacing":"⌘5",
        "Add or remove one line of space directly preceding a paragraph":"⌘0",
        "Format - Change the font":"⌘⇧F",
        "Format - Increase the font size":"⌘⇧>",
        "Format - Decrease the font size":"⌘⇧<",
        "Format - Increase the font size by 1 point":"⌘]",
        "Format - Decrease the font size by 1 point":"⌘[",
        "Format - Change the formatting of characters (Font command, Format menu)":"⌘D",
        "Format - Change the case of letters":"⇧F3",
        "Format - Format in all capital letters":"⌘⇧A",
        "Format - Apply bold formatting":"⌘B",
        "Format - Apply an underline":"⌘U",
        "Format - Underline words but not spaces":"⌘⇧W",
        "Format - Double-underline text":"⌘⇧D",
        "Format - Apply italic formatting":"⌘I",
        "Format - Format in all small capital letters":"⌘⇧K",
        "Format - Apply subscript formatting (automatic spacing)":"⌘=",
        "Format - Apply superscript formatting (automatic spacing)":"⌘⇧+",
        "Format - Apply strike-through formatting":"⌘⇧X",
        "Insert an empty field":"⌘F9",
        "Special Chars - Insert a line break":"⇧⏎",
        "Special Chars - Insert a page break":"⌘⏎",
        "Special Chars - Insert a column break":"⌘⇧⏎",
        "Special Chars - Insert a nonbreaking hyphen":"⌘⇧-",
        "Special Chars - Insert the copyright symbol":"⌥G",
        "Special Chars - Insert the registered trademark symbol":"⌥R",
        "Special Chars - Insert the trademark symbol":"⌥2",
        "Special Chars - Insert an ellipsis":"⌥;",
        "Special Chars - Insert a DATE field":"^⇧D",
        "Special Chars - Insert a LISTNUM field":"⌘⌥⇧L",
        "Special Chars - Insert a PAGE field":"^⇧P",
        "Special Chars - Insert a TIME field":"^⇧T",
        "Special Chars - Insert an empty field":"⌘F9",
        "Fields - Update selected fields":"F9",
        "Fields - Unlink a field":"⌘⇧F9",
        "Fields - Switch between a field code and its result":"⇧F9",
        "Fields - Switch between all field codes and their results":"⌥F9",
        "Fields - Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"⌥⇧F9",
        "Fields - Go to the next field":"F11",
        "Fields - Go to the previous field":"⇧F11",
        "Fields - Lock a field":"⌘F11",
        "Fields - Unlock a field":"⌘⇧F11",
        "Outline - Promote a paragraph":"^⇧←",
        "Outline - Demote a paragraph":"^⇧→",
        "Outline - Demote to body text":"⌘⇧N",
        "Outline - Move selected paragraphs up":"^⇧↑",
        "Outline - Move selected paragraphs down":"^⇧↓",
        "Outline - Expand text under a heading":"^⇧+",
        "Outline - Collapse text under a heading":"^⇧-",
        "Outline - Expand all body text and headings or collapse all body text":"^⇧A",
        "Outline - Show the first line of body text or all body text":"^⇧L",
        "Outline - Show all headings with the specified heading level":"^⇧ +<Heading level>",
        "Review - Insert a comment":"⌘⌥A",
        "Review - Turn track changes on or off":"⌘⇧E",
        "Review - Go to the beginning of a comment":"Home",
        "Review - Go to the end of a comment":"End",
        "Review - Go to the beginning of the list of comments when in the Reviewing Pane":"⌘Home",
        "Review - Go to the end of the list of comments when in the Reviewing Pane":"⌘End",
        "Print a document":"⌘P",
        "Table - Move to the next cell":"Tab ",
        "Table - Add a new row (if cursor is on last row)":"Tab ",
        "Table - Move to the preceding cell":"⇧Tab",
        "Table - Move to the preceding or next row":"↑ or ↓",
        "Table - Move to the first cell in the row":"^Home",
        "Table - Move to the last cell in the row":"^End",
        "Table - Move to the first cell in the column":"^Page Up",
        "Table - Move to the last cell in the column":"^Page Down",
        "Table - Start a new paragraph":"⏎",
        "Table - Add a new row at the bottom of the table":"Tab at the end of the last row",
        "Table - Add text before a table at the beginning of a document":"⏎ at the beginning of the first cell",
        "Table - Insert a row":"⌘^I",
        "Table Resize by ruler - Move a single column line":"⇧",
        "Table Resize by ruler - Equally resize all columns to the right":"⌘⇧",
        "Table Resize by ruler - Proportionally resize all columns to the right":"⌘",
        "Table Resize directly - Move a single column line":"",
        "Table Resize directly - Retain column sizes to the right":"⇧",
        "Table Resize directly - Equally resize all columns to the right":"⌘⇧",
        "Table Resize directly - Proportionally resize all columns to the right":"⌘",
        "Table - Insert a new paragraph in a cell":"⏎",
        "Table - Insert a Tab character in a cell":"⌥Tab",
        "Insert a footnote":"⌘⌥F",
        "Insert an endnote":"⌘⌥E",
        "Paragraph direction to right to left":"^⌘←",
        "Paragraph direction to left to right":"^⌘→",
        "Undo the last action":"F1",
        "Cut selected text or graphics":"F2",
        "Copy selected text or graphics to the clipboard":"F3",
        "Paste the Clipboard contents":"F4",
        "Choose the Go To command (Edit menu)":"F5",
        "Open the Spelling and Grammar dialog box":"F7",
        "Extend a selection":"F8",
        "Update selected fields.":"F9",
        "Go to the next window":"⌘F6",
        "Copy selected text":"⇧F2",
        "Change letters to uppercase, lowercase, or mixed case":"⇧F3",
        "Repeat a Find or Go To action":"⇧F4 or ⌘⇧F4",
        "Move to the previous insertion point":"⇧F5",
        "Open the Thesaurus pane":"⇧F7",
        "Shrink a selection":"⇧F8",
        "Switch between a field code and its result.":"⇧F9",
        "Go to the previous field":"⇧F11",
        "Cut the selection to the Spike":"⌘F3",
        "Close the window":"⌘F4",
        "Go to the next window":"⌘F6",
        "Insert an empty field":"⌘F9",
        "Lock a field":"⌘F11",
        "Insert the contents of the Spike":"⌘⇧F3",
        "Edit a bookmark":"⌘⇧F5",
        "Update linked information in a Word source document":"⌘⇧F7",
        "Extend a selection as a block selection":"⌘⇧F8, an arrow key",
        "Unlink a field":"⌘⇧F9",
        "Unlock a field":"⌘⇧F11",
        "Create an AutoText entry":"⌥F3",
        "Find the next misspelling or grammatical error":"⌥F7",
        "Run a macro":"⌥F8",
        "Switch between all field codes and their results":"⌥F9",
        "Look up selected text on the Internet":"⌘⇧L",
        "Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"⌥⇧F9"
    }
}