# coding: utf8
shortcuts = {
    "Microsoft Word":{
        # https://support.office.com/en-us/article/Keyboard-shortcuts-in-Word-for-Mac-3256d48a-7967-475d-be81-a6e3e1284b25
        "Undo the last action":"COMMAND + Z or Control + Z",
        "Cut selected text or graphics":"COMMAND + X or Control + X",
        "Copy selected text or graphics to the Clipboard":"COMMAND + C or Control + C",
        "Paste the Clipboard contents":"COMMAND + V or Control + V",
        "Choose the Go To command (Edit menu)":"Option +  COMMAND + G",
        "Open the Spelling and Grammar dialog box":"Option +  COMMAND + L",
        "Extend a selection":"F8",
        "Go to the next window":"COMMAND + Grave accent ( ` )",
        "Choose the Save As command (File menu).":"COMMAND + Shift + S",
        "Copy selected text":"Shift + F2",
        "Change letters to uppercase, lowercase, or mixed case":"Shift + F3",
        "Find":"Control+F; places the focus in the Search box",
        "Find and Replace":"Control+H",
        "Print a document":"COMMAND + P or Control + P",
        "Move to the previous insertion point":"Shift + F5",
        "Go to the previous window":"COMMAND + Shift + `",
        "Open the Thesaurus pane":"Shift+ F7",
        "Shrink a selection":"Shift+ F8",
        "Switch between a field code and its result":"Shift + F9",
        "Cut the selection to the Spike":"COMMAND + F3",
        "Close the window":"COMMAND + F4",
        "Expand or minimize the ribbon":"Option +  COMMAND + R",
        "Edit a bookmark":"COMMAND + Shift + F5",
        "Find the next misspelling or grammatical error. The Check spelling as you type check box must be selected (Word menu, Preferences command, Spelling and Grammar).":"Option + F7",
        "Look up selected text on the Internet":"COMMAND + Shift + L",
        "Cursor - Move one character to the left":"Left arrow",
        "Cursor - Move one character to the right":"Right arrow",
        "Cursor - Move one word to the left":"Option + Left arrow",
        "Cursor - Move one word to the right":"Option + Right arrow",
        "Cursor - Move one paragraph up":"COMMAND + Up arrow",
        "Cursor - Move one paragraph down":"COMMAND + Down arrow",
        "Cursor - Move one cell to the left (in a table)":"Shift + Tab",
        "Cursor - Move one cell to the right (in a table)":"Tab",
        "Cursor - Move up one line":"Up arrow",
        "Cursor - Move down one line":"Down arrow",
        "Cursor - Move to the end of a line":"COMMAND + Right arrow or End",
        "Cursor - Move to the beginning of a line":"COMMAND + Left arrow or Home",
        "Cursor - Move up one screen (scrolling)":"Page Up",
        "Cursor - Move down one screen (scrolling)":"Page Down",
        "Cursor - Move to the top of the next page":"COMMAND + Page Down",
        "Cursor - Move to the top of the previous page":"COMMAND + Page Up",
        "Cursor - To the end of a document":"COMMAND + End",
        "Cursor - On a MacBook keyboard:":"COMMAND + FN + Right arrow",
        "Cursor - To the beginning of a document":"COMMAND + Home",
        "Cursor - On a MacBook keyboard:":"COMMAND + FN + Left arrow",
        "Cursor - To the previous insertion point":"Shift + F5",
        "Select multiple items not next to each other":"Select the first item that you want, hold down  COMMAND , and then select any additional items",
        "Select one character to the right":"Shift + Right arrow",
        "Select one character to the left":"Shift + Left arrow",
        "Select one word to the right":"Shift + Option + Right arrow",
        "Select one word to the left":"Shift + Option + Left arrow",
        "Select to the end of a line":"COMMAND + Shift + Right arrow or Shift + End",
        "Select to the beginning of a line":"COMMAND + Shift + Left arrow or Shift + Home",
        "Select one line down":"Shift + Down arrow",
        "Select one line up":"Shift + Up arrow",
        "Select to the end of a paragraph":"COMMAND + Shift + Down arrow",
        "Select to the beginning of a paragraph":"COMMAND + Shift + Up arrow",
        "Select one screen down":"Shift + Page Down",
        "Select one screen up":"Shift + Page Up",
        "Select to the beginning of a document":"COMMAND + Shift + Home",
        "Select to the end of a document":"COMMAND + Shift + End",
        "Select to the end of a window":"Option +  COMMAND + Shift + Page Down",
        "Select to select the entire document":"COMMAND + A",
        "Select to a vertical block of text":"COMMAND + Shift + F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Select to a specific location in a document":"F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Select the next cell's contents":"Tab",
        "Select the preceding cell's contents":"Shift + Tab",
        "Extend a selection to adjacent cells":"Hold down Shift and press an arrow key repeatedly",
        "Select a column":"Click in the column's top or bottom cell. Hold down Shift and press the Up arrow or Down arrow key repeatedly",
        "Extend a selection (or block)":"COMMAND + Shift + F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Reduce the selection size":"Shift + F8",
        "Select multiple cells, columns, or rows that are not next to each other":"Select the first item that you want, hold down  COMMAND , and then select any additional items",
        "Extend select - Turn on extend mode":"F8",
        "Extend select - Select the nearest character to the left":"F8, Left arrow",
        "Extend select - Select the nearest character to the right":"F8, Right arrow",
        "Extend select - Expand a selection":"Press F8 repeatedly to expand the selection to the entire word, sentence, paragraph, section, and document.",
        "Extend select - Reduce the size of a selection":"Shift + F8",
        "Extend select - Turn off extend mode":"Esc",
        "Edit - Copy text or graphics":"COMMAND + C or F3",
        "Edit - Copy a style":"COMMAND + Shift + C",
        "Edit - Paste a style":"COMMAND + Shift + V",
        "Edit - Copy text or graphics to the Scrapbook":"Control + Option + C",
        "Edit - Cut selected text to the clipboard":"COMMAND + X or F2",
        "Edit - Move text or graphics":"COMMAND + X or F2 (then move the cursor and press  COMMAND + V or F4 )",
        "Edit - Create AutoText":"Option + F3",
        "Edit - Insert AutoText":"COMMAND + Option + Shift + V",
        "Edit - Paste the Clipboard contents":"COMMAND + V or F4",
        "Edit - Paste special":"COMMAND + Control + V",
        "Edit - Paste and match the formatting of the surrounding text":"COMMAND + Option + Shift + V",
        "Edit - Paste the Spike  contents":"COMMAND + Shift + F3",
        "Edit - Delete one character to the left":"Delete",
        "Edit - Delete one word to the left":"COMMAND + Delete",
        "Edit - Delete one character to the right":"COMMAND or Clear",
        "Edit - Delete one word to the right":"COMMAND +  COMMAND",
        "Edit - Cut selected text to the Clipboard":"COMMAND + X or F2",
        "Edit - Undo the last action":"COMMAND + Z",
        "Edit - Redo the last action":"COMMAND + Y",
        "Edit - Cut to the Spike":"COMMAND + F3",
        "Center a paragraph":"COMMAND + E",
        "Justify a paragraph":"COMMAND + J",
        "Left-align a paragraph":"COMMAND + L",
        "Right-align a paragraph":"COMMAND + R",
        "Indent a paragraph from the left":"Control + Shift + M",
        "Remove a paragraph indent from the left":"COMMAND + Shift + M",
        "Create a hanging indent":"COMMAND + T",
        "Remove a hanging indent":"COMMAND + Shift + T",
        "Start AutoFormat":"COMMAND + Option + K",
        "Apply the Normal style":"COMMAND + Shift + N",
        "Apply the Heading 1 style":"COMMAND + Option + 1",
        "Apply the Heading 2 style":"COMMAND + Option + 2",
        "Apply the Heading 3 style":"COMMAND + Option + 3",
        "Apply the List style when the cursor is at the beginning of a line":"COMMAND + Shift + L",
        "Insert a nonbreaking space":"Option + Spacebar",
        "Set lines as single-spaced":"COMMAND + 1",
        "Set lines as double-spaced":"COMMAND + 2",
        "Set lines as 1.5-line spacing":"COMMAND + 5",
        "Add or remove one line of space directly preceding a paragraph":"COMMAND + 0 (zero)",
        "Format - Change the font":"COMMAND + Shift + F",
        "Format - Increase the font size":"COMMAND + Shift + >",
        "Format - Decrease the font size":"COMMAND + Shift + <",
        "Format - Increase the font size by 1 point":"COMMAND + ]",
        "Format - Decrease the font size by 1 point":"COMMAND + [",
        "Format - Change the formatting of characters (Font command, Format menu)":"COMMAND + D",
        "Format - Change the case of letters":"Shift + F3",
        "Format - Format in all capital letters":"COMMAND + Shift + A",
        "Format - Apply bold formatting":"COMMAND + B",
        "Format - Apply an underline":"COMMAND + U",
        "Format - Underline words but not spaces":"COMMAND + Shift + W",
        "Format - Double-underline text":"COMMAND + Shift + D",
        "Format - Apply italic formatting":"COMMAND + I",
        "Format - Format in all small capital letters":"COMMAND + Shift + K",
        "Format - Apply subscript formatting (automatic spacing)":"COMMAND + Equal sign",
        "Format - Apply superscript formatting (automatic spacing)":"COMMAND + Shift + Plus sign",
        "Format - Apply strike-through formatting":"COMMAND + Shift + X",
        "Insert an empty field":"COMMAND + F9",
        "Special Chars - Insert a line break":"Shift + Return",
        "Special Chars - Insert a page break":"COMMAND + Enter",
        "Special Chars - Insert a column break":"COMMAND + Shift + Return",
        "Special Chars - Insert a nonbreaking hyphen":"COMMAND + Shift + Hyphen",
        "Special Chars - Insert the copyright symbol":"Option + G",
        "Special Chars - Insert the registered trademark symbol":"Option + R",
        "Special Chars - Insert the trademark symbol":"Option + 2",
        "Special Chars - Insert an ellipsis":"Option + Semicolon",
        "Special Chars - Insert a DATE field":"Control + Shift + D",
        "Special Chars - Insert a LISTNUM field":"COMMAND + Option + Shift + L",
        "Special Chars - Insert a PAGE field":"Control + Shift + P",
        "Special Chars - Insert a TIME field":"Control + Shift + T",
        "Special Chars - Insert an empty field":"COMMAND + F9",
        "Fields - Update selected fields":"F9",
        "Fields - Unlink a field":"COMMAND + Shift + F9",
        "Fields - Switch between a field code and its result":"Shift + F9",
        "Fields - Switch between all field codes and their results":"Option + F9",
        "Fields - Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"Option + Shift + F9",
        "Fields - Go to the next field":"F11",
        "Fields - Go to the previous field":"Shift + F11",
        "Fields - Lock a field":"COMMAND + F11",
        "Fields - Unlock a field":"COMMAND + Shift + F11",
        "Outline - Promote a paragraph":"Control + Shift + Left arrow",
        "Outline - Demote a paragraph":"Control + Shift + Right arrow",
        "Outline - Demote to body text":"COMMAND + Shift + N",
        "Outline - Move selected paragraphs up":"This keyboard shortcut conflicts with a default Mission Control key. To use this Office keyboard shortcut, you must first change the Mission Control shortcut for this key. On the Apple menu, click System Preferences > Mission Control. Under Keyboard and Mouse, choose another shortcut for Mission Control, or choose – (minus sign) to turn it off.",
        "Outline - Control + Shift + Up arrow":"Move selected paragraphs down",
        "Outline - This keyboard shortcut conflicts with a default Mission Control key. To use this Office keyboard shortcut, you must first change the Application windows shortcut for this key. On the Apple menu, click System Preferences > Mission Control. Under Keyboard and Mouse, choose another shortcut for Application windows, or choose – (minus sign) to turn it off.":"Control + Shift + Down arrow",
        "Outline - Expand text under a heading":"Control + Shift + Plus sign",
        "Outline - Collapse text under a heading":"Control + Shift + Minus sign",
        "Outline - Expand all body text and headings or collapse all body text":"Control + Shift + A",
        "Outline - Show the first line of body text or all body text":"Control + Shift + L",
        "Outline - Show all headings with the specified heading level":"Control + Shift +<Heading level>",
        "Review - Insert a comment":"COMMAND + Option + A",
        "Review - Turn track changes on or off":"COMMAND + Shift + E",
        "Review - Go to the beginning of a comment":"Home",
        "Review - Go to the end of a comment":"End  (The End key is not available on all keyboards)",
        "Review - Go to the beginning of the list of comments when in the Reviewing Pane":"COMMAND + Home",
        "Review - Go to the end of the list of comments when in the Reviewing Pane":"COMMAND + End",
        "Print a document":"COMMAND + P",
        "Table - Move to the next cell":"Tab (If the cursor is in the last cell of a table, pressing Tab adds a new row)",
        "Table - Move to the preceding cell":"Shift + Tab",
        "Table - Move to the preceding or next row":"Up arrow or Down arrow",
        "Table - Move to the first cell in the row":"Control + Home",
        "Table - Move to the last cell in the row":"Control + End",
        "Table - Move to the first cell in the column":"Control + Page Up",
        "Table - Move to the last cell in the column":"Control + Page Down",
        "Table - Start a new paragraph":"Return",
        "Table - Add a new row at the bottom of the table":"Tab at the end of the last row",
        "Table - Add text before a table at the beginning of a document":"Return at the beginning of the first cell",
        "Table - Insert a row":"COMMAND + Control + I",
        "Table Resize by ruler - Move a single column line":"Shift",
        "Table Resize by ruler - Equally resize all columns to the right":"COMMAND + Shift",
        "Table Resize by ruler - Proportionally resize all columns to the right":"COMMAND",
        "Table Resize directly - Move a single column line":"",
        "Table Resize directly - Retain column sizes to the right":"Shift",
        "Table Resize directly - Equally resize all columns to the right":"COMMAND + Shift",
        "Table Resize directly - Proportionally resize all columns to the right":"COMMAND",
        "Table - Insert a new paragraph in a cell":"Return",
        "Table - Insert a Tab character in a cell":"Option + Tab",
        "Insert a footnote":"COMMAND + Option + F",
        "Insert an endnote":"COMMAND + Option + E",
        "Paragraph direction to right to left":"Control +  COMMAND + Left arrow",
        "Paragraph direction to left to right":"Control +  COMMAND + Right arrow",
        "Undo the last action":"F1",
        "Cut selected text or graphics":"F2",
        "Copy selected text or graphics to the clipboard":"F3",
        "Paste the Clipboard contents":"F4",
        "Choose the Go To command (Edit menu)":"F5",
        "Open the Spelling and Grammar dialog box":"F7",
        "Extend a selection":"F8",
        "Update selected fields.":"F9",
        "Go to the next window":"COMMAND + F6",
        "Copy selected text":"Shift + F2",
        "Change letters to uppercase, lowercase, or mixed case":"Shift + F3",
        "Repeat a Find or Go To action":"Shift + F4 or COMMAND + Shift + F4",
        "Move to the previous insertion point":"Shift + F5",
        "Open the Thesaurus pane":"Shift+ F7",
        "Shrink a selection":"Shift+ F8",
        "Switch between a field code and its result.":"Shift + F9",
        "Go to the previous field":"Shift + F11 (confilcts with default Mission Control key)",
        "Cut the selection to the Spike":"COMMAND + F3",
        "Close the window":"COMMAND + F4",
        "Go to the next window":"COMMAND + F6",
        "Insert an empty field":"COMMAND + F9",
        "Lock a field":"COMMAND + F11",
        "Insert the contents of the Spike":"COMMAND + Shift + F3",
        "Edit a bookmark":"COMMAND + Shift + F5",
        "Update linked information in a Word source document":"COMMAND + Shift + F7",
        "Extend a selection as a block selection":"COMMAND + Shift + F8, an arrow key",
        "Unlink a field":"COMMAND + Shift + F9",
        "Unlock a field":"COMMAND + Shift + F11",
        "Create an AutoText entry":"Option + F3",
        "Find the next misspelling or grammatical error":"Option + F7",
        "Run a macro":"Option + F8",
        "Switch between all field codes and their results":"Option + F9",
        "Look up selected text on the Internet":"COMMAND + Shift + L",
        "Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"Option + Shift + F9"
    }
}