# coding: utf8
shortcuts = {
    "Outlook":{ #https://support.office.com/en-us/article/Keyboard-shortcuts-for-Outlook-for-Mac-07ae68c8-b7af-4010-b225-324c04ac7335?ui=en-US&rs=en-US&ad=US
        "Archive message":"^e",
        "Previous message":"^[",
        "Next message":"^]",
        "Save an item":"⌘S",
        "Print an item":"⌘P",
        "Undo the last action":"⌘Z",
        "Redo the last action":"⌘Y",
        "Minimize the active window":"⌘M",
        "Create a new folder in the navigation pane":"⌘⇧N",
        "Create new email (in Mail view)":"⌘N",
        "Hide the reading pane or show it on the right":"⌘\\",
        "Hide the reading pane or show it below":"⇧ ⌘\\ )",
        "Move the selected item to a different folder":"⇧ ⌘M",
        "Copy the selected item to a different folder":"⇧ ⌘C",
        "Select all items in the item list, if the item list is the active pane":"⌘A",
        "Minimize or expand the ribbon":"⌘⌥R",
        "Hide Outlook":"⌘H",
        "Quit Outlook":"⌘Q",
        "Start dictation":"FnFn",
        "Insert emoji":"⌘^Space",
        "Go to Mail view":"⌘1",
        "Go to Calendar view":"⌘2",
        "Go to Contacts view":"⌘3",
        "Go to Tasks view":"⌘4",
        "Go to Notes view":"⌘5",
        "Open the Sync Status window or make it the active window":"⌘7",
        "Open the Sync Errors or make it the active window":"⌘8",
        "Open the Contacts Search window":"⌘0",
        "Open the Outlook Preferences dialog box":"⌘,",
        "Cycle forward through open windows":"⌘~",
        "Cycle back through open windows":"⇧ ⌘~",
        "Close the active window":"⌘W",
        "Open the selected item":"⌘O",
        "Move forward through controls in a window":"Tab",
        "Move back through controls in a window":"⇧Tab",
        "Search current folder":"⌥ ⌘F",
        "Do an advanced search in Outlook (add Item Contains filter for searching)":"⇧ ⌘F",
        "Find text within an item - search":"⌘F",
        "Find the next instance of the text you searched for in an item":"⌘G",
        "Find the previous instance of the text you searched for in an item":"⌘⇧G",
        "Create a new message":"⌘N",
        "Send the open message":"⌘Return",
        "Send all messages in the Outbox and receive all incoming messages":"⌘K",
        "Send all the messages in the Outbox":"⇧ ⌘K",
        "Save the open message and store it in the Drafts folder":"⌘S",
        "Add an attachment to the open message":"⌘E",
        "Open the Spelling and Grammar dialog box":"⌘:",
        "Check recipient names in the open messages":"^ ⌘C",
        "Reply to the sender of the message or, if the message is from a mailing list, reply to the mailing list":"⌘R",
        "Reply to all":"⇧+  ⌘R",
        "Forward the message":"⌘J",
        "Open the selected message in a separate window":"⌘O",
        "Clear the flag for the selected message":"⌥ ⌘'",
        "Mark the selected message as junk mail":"⌘⇧J",
        "Mark the selected message as not junk mail":"⌘⇧⌥J",
        "Display the previous message":"[",
        "Display the next message":"]",
        "Navigate to the previous pane in the Mail view":"⇧[",
        "Navigate to the next pane in the Mail view":"⇧]",
        "Move the selected message to a folder":"⇧ ⌘M",
        "Decrease the display size of text in an open message or in the reading pane":"⌘-",
        "Increase the display size of text in an open message or in the reading pane":"⌘+",
        "Scroll down to the next screen of text or, if you are at the end of a message, display the next message":"Spacebar",
        "Scroll up to the previous screen of text or, if you are at the beginning of a message, display the previous message":"⇧+ Spacebar",
        "Delete the selected message":"Delete",
        "Permanently delete the selected message":"⇧Delete",
        "Delete the current message, and, if the message window is open, close it":"⌘Delete",
        "Mark selected messages as read":"⌘T",
        "Mark selected messages as unread":"⇧ ⌘T",
        "Mark all messages in a folder as read":"⌥ ⌘T",
        "Open the Calendar window":"⌘2",
        "Create a new appointment":"⌘N",
        "Open the selected calendar event":"⌘O",
        "Delete the calendar event":"Delete",
        "Switch the view to include today":"⌘T",
        "In Day view, move to the previous day. In Week and Work Week views, move to the previous week. In Month view, move to the previous month.":"⌘←",
        "In Day view, move to the next day. In Week and Work Week views, move to the next week. In Month view, move to the next month.":"⌘→",
        "Navigate to the previous pane in the Calendar view":"⇧[",
        "Navigate to the next pane in the Calendar view":"⇧]",
        "Create a new contact":"⌘N",
        "Open the selected contact":"⌘O",
        "Delete the contact":"Delete",
        "Close the current open contact and open the previous contact":"[",
        "Close the current open contact and open the next contact":"]",
        "Navigate to the previous pane in the People view":"⇧+ [",
        "Navigate to the next pane in the People view":"⇧]",
        "Move to the Task window":"⌘4",
        "Create a new task":"⌘N",
        "Open the selected task":"⌘O",
        "Delete the task":"Delete",
        "Close the current open task and open the previous task in the Tasks list":"[",
        "Close the current open task and open the next task in the Tasks list":"]",
        "Navigate to the previous pane in the Tasks view":"⇧[",
        "Navigate to the next pane in the Tasks view":"⇧]",
        "Move to the Notes window":"⌘5",
        "Create a new note":"⌘N",
        "Open the selected note":"⌘O",
        "Delete the note":"Delete",
        "Close the current open note and open the previous note in the Notes list":"[",
        "Close the current open note and open the next note in the Notes list":"]",
        "Navigate to the previous pane in the Notes view":"⇧[",
        "Navigate to the next pane in the Notes view":"⇧]",
        "Send a note as an email":"⌘J",
        "Send a note as an HTML attachment to an email":"^ ⌘J [First place the focus on the note in the list of notes]",
        "Cut the selected text to the clipboard":"⌘X",
        "Copy a selection to the clipboard":"⌘C",
        "Paste a selection from the clipboard":"⌘V",
        "Paste a selection from the clipboard and match the destination style":"⇧⌥ ⌘V",
        "Make the selected text bold":"⌘B",
        "Make the selected text italic":"⌘I",
        "Underline the selected text":"⌘U",
        "Strike through the selected text":"⇧ ⌘X",
        "Insert a hyperlink":"^ ⌘K",
        "Move the cursor left one character":"←",
        "Move the cursor right one character":"→",
        "Move the cursor up one line":"↑",
        "Move the cursor down one line":"↓",
        "Move the cursor to the beginning of the current paragraph":"⌥↑",
        "Move the cursor to the end of the current paragraph":"⌥↓",
        "Move the cursor to the beginning of the current word":"⌥←",
        "Move the cursor to the end of the current word":"⌥→",
        "Decrease indent":"{",
        "Increase indent":"}",
        "Delete the character to the left of the cursor, or delete the selected text":"Delete",
        "Delete the character to the right side of the cursor, or delete the selected text":"Delete [If your keyboard doesn't have a  Delete key, use FNDelete]",
        "Insert a tab stop":"Tab",
        "Move the cursor to the beginning of the line":"⌘←",
        "Move the cursor to the end of the line":"⌘→",
        "Move the cursor to the top of the message body":"⌘↑",
        "Move the cursor to the bottom of the message body":"⌘↓",
        "Move the cursor to the beginning of the selected text":"⌘Home",
        "Move the cursor to the end of the selected text":"⌘End",
        "Scroll up":"Page up",
        "Scroll down":"Page down",
        "Flag the selected item for follow up, with Today as Due Date":"^1",
        "Flag the selected item for follow up, with Tomorrow as Due Date":"^2",
        "Flag the selected item for follow up, with This Week as Due Date":"^3",
        "Flag the selected item for follow up, with Next Week as Due Date":"^4",
        "Flag the selected item for follow up, with No Due Date":"^5",
        "Flag the selected item for follow up, and add a custom Due Date":"^6",
        "Flag the selected item for follow up, and add a reminder":"^=",
        "Mark the selected item as Complete":"^0",
        "Clear the selected item's follow-up flag":"⌥⌘'"
    }
}