# coding: utf8

shortcuts = {
    "Adobe Photoshop Mac Keyboard Shortcuts": {
        "General / Popular Shortcuts": {
            "Free Transform": "Command + T",
            "Deselect selections": "Command + D",
            "Undo last command": "Command + Z",
            "Increase Brush Size": "]",
            "Decrease Brush Size": "[",
            "Increase Brush Hardness": "}",
            "Decrease Brush Hardness": "{",
            "Rotate brush tip by 1 degree": "Left Arrow (anti-clockwise), Right Arrow (clockwise)",
            "Rotate brush tip by 15 degrees": "Shift + Left Arrow, Shift + Right Arrow",
            "Default Foreground/Background colors": "D",
            "Switch Foreground/Background colors": "X",
            "Fit layer(s) to screen": "Option-click layer",
            "New layer via copy": "Command + J",
            "New layer via cut": "Shift + Command + J",
            "Add to a selection": "Any selection tool + Shift-drag",
            "Delete brush or swatch": "Option-click brush or swatch",
            "Toggle auto-select checkbox in Options bar with Move tool selected": "Command-click",
            "Close all open documents other than current document": "Command + Option + P",
            "Cancel modal dialog window (including Start Workspace)": "Escape",
            "Select first edit field of toolbar": "Return",
            "Navigate between fields": "Tab",
            "Navigate between fields in opposite direction": "Shift + Tab",
            "Change Cancel to Reset": "Option"
        },
        "Use Function Keys": {
            "Show/Hide Actions Panel": "Option + F9"
        },
        "Selection Tools": {
            "Cycle through tools with the same shortcut key": "Shift-press shortcut key (if Use Shift Key for Tool Switch preference is selected)",
            "Cycle through hidden tools": "Option-click tool (except Add/Delete/Convert Point tools)",
            "Move tool/Artboard tool": "V",
            "Rectangular Marquee tool/Elliptical Marquee tool": "M",
            "Lasso tools": "L",
            "Object Selection/Quick Selection/Magic Wand": "W",
            "Crop tool/Perspective Crop/Slice tools": "C",
            "Eyedropper/Color Sampler/Ruler/Note tools": "I",
            "Spot Healing/Healing Brush/Patch/Content-Aware Move/Red Eye": "J",
            "Brush/Pencil/Color Replacement/Mixer Brush": "B",
            "Clone Stamp/Pattern Stamp": "S",
            "History Brush/Art History Brush": "Y",
            "Eraser tools": "E",
            "Gradient/Paint Bucket/3D Material Drop tool": "G",
            "Dodge/Burn/Sponge": "O",
            "Pen tools": "P",
            "Type tools": "T",
            "Path Selection/Direct Selection tools": "A",
            "Shape tools": "U",
            "Hand tool": "H",
            "Rotate View tool": "R",
            "Zoom tool": "Z"
        },
        "View Images": {
            "Cycle through open documents": "Control + Tab",
            "Switch to previous document": "Shift + Command + `(grave accent)",
            "Close a file in Photoshop and open Bridge": "Shift + Command + W",
            "Toggle between Standard and Quick Mask mode": "Q",
            "Toggle Standard screen mode, Full screen with menu bar, or Full screen mode": "F (Shift + F backward)",
            "Toggle canvas color": "Spacebar + F (or Control-click canvas background)",
            "Fit image in window": "Double-click Hand tool",
            "Zoom 100%": "Double-click Zoom tool or Command + 1",
            "Switch to Hand tool": "Spacebar",
            "Switch to Zoom In tool": "Command + Spacebar",
            "Switch to Zoom Out tool": "Option + Spacebar",
            "Scroll image with Hand tool": "Spacebar-drag"
        },
        "Puppet Warp (Mac shortcuts)": {
            "Free Transform": "Command + T",
            "Delete brush or swatch": "Option-click brush/swatch",
            "Fit layer(s) to screen": "Option-click layer",
            "New layer via copy": "Command + J",
            "New layer via cut": "Shift + Command + J",
            "Add to a selection": "Any selection tool + Shift-drag",
            "Toggle auto-select checkbox with Move tool selected": "Command-click",
            "Close all open docs except current": "Command + Option + P",
            "Cancel modal dialog window": "Escape",
            "Select first edit field of toolbar": "Return",
            "Navigate between fields": "Tab; reverse Shift + Tab",
            "Use black-and-white adjustment": "Shift + Command + Option + B",
            "Select all pins": "Command + A",
            "Deselect all pins": "Command + D",
            "Delete pins": "Option-click pin"
        },
        "Use Select and Mask": {
            "Select and mask": "Command + Option + R",
            "Target layer": "Command + 2",
            "Target mask": "\\ (backslash)",
            "Disable mask temporarily": "Shift-click mask",
            "Add layer mask icon": "Option-click layer mask icon",
            "Invert layer mask": "Command + I"
        },
        "Filter Gallery (Mac shortcuts)": {
            "Apply new filter on top of selected filter": "Option-click on filter",
            "Change Cancel button to default": "Command + click",
            "Step forward": "Command + Shift + Z",
            "Step backward": "Command + Option + Z"
        },
        "Liquify Filter (Mac shortcuts)": {
            "Forward Warp tool": "W",
            "Reconstruct tool": "R",
            "Twirl Clockwise tool": "C",
            "Pucker tool": "S",
            "Bloat tool": "B",
            "Push Left tool": "O",
            "Freeze Mask tool": "F",
            "Thaw Mask tool": "D",
            "Smooth tool": "E",
            "Face tool": "A",
            "Hand tool": "H",
            "Zoom tool": "Z",
            "Liquify filter open": "Shift + Command + X",
            "Reverse direction for Bloat, Pucker, and Push Left tools": "Option + tool key"
        },
        "Vanishing Point (Mac shortcuts)": {
            "Zoom 2x temporary": "X",
            "Zoom in": "Command + + (plus)",
            "Zoom out": "Command + - (hyphen)",
            "Fit in view": "Command + 0 (zero), Double-click Hand tool",
            "Rotate image left": "Command + ]",
            "Rotate image right": "Command + [",
            "Undo last action": "Command + Z",
            "Redo last action": "Command + Shift + Z",
            "Deselect all": "Command + D",
            "Hide selection and planes": "Command + H",
            "Move selection 1 pixel": "Arrow keys",
            "Move selection 10 pixels": "Shift + arrow keys",
            "Copy": "Command + C",
            "Paste": "Command + V",
            "Repeat last duplicate and move": "Command + Shift + T",
            "Cancel distortions": "Esc"
        },
        "Camera Raw Dialog Box (Mac shortcuts)": {
            "Zoom tool": "Z",
            "Hand tool": "H",
            "White Balance tool": "I",
            "Color Sampler tool": "S",
            "Crop tool": "C",
            "Straighten tool": "A",
            "Spot Removal tool": "B",
            "Red Eye Removal tool": "E",
            "Basic panel": "Command + Option + 1",
            "Tone Curve panel": "Command + Option + 2",
            "Detail panel": "Command + Option + 3",
            "HSL/Grayscale panel": "Command + Option + 4",
            "Split Toning panel": "Command + Option + 5",
            "Lens Corrections panel": "Command + Option + 6",
            "Camera Calibration panel": "Command + Option + 7",
            "Presets panel": "Command + Option + 9",
            "Open Snapshots panel": "Command + Option + 9",
            "Adjustment Brush tool": "K",
            "Graduated Filter tool": "G",
            "Increase/decrease brush size": "] / [",
            "Increase/decrease brush feather": "Shift + ] / Shift + [",
            "Temporarily switch from Add to Erase mode (Adjustment Brush tool)": "Option",
            "Increase/decrease temporary Adjustment Brush tool size": "Option + ] / Option + [",
            "Switch to New mode (Add/Erase mode)": "N",
            "Toggle Auto Mask": "M",
            "Rotate image left": "Command + ]",
            "Rotate image right": "Command + [",
            "Zoom in": "Command + + (plus)",
            "Zoom out": "Command + - (hyphen)",
            "Toggle preview": "P",
            "Full screen mode": "F",
            "Open selected images in Camera Raw from Bridge": "Command + R"
        },
        "Curves (Mac shortcuts)": {
            "Open Curves dialog box": "Command + M",
            "Deselect a point": "Command + D",
            "Move selected point 1 unit": "Arrow keys",
            "Move selected point 10 units": "Shift + Arrow keys",
            "Display highlights and shadows clipped": "Option-drag black/white sliders",
            "Set point to composite curve": "Command-click image",
            "Toggle grid size": "Option-click field",
            "Change color channels": {
                "RGB": "Option + 2",
                "Red": "Option + 3",
                "Green": "Option + 4",
                "Blue": "Option + 5"
            }
        },
        "Select and Move Objects (Mac shortcuts)": {
            "Add to selection": "Shift-drag",
            "Subtract from selection": "Option-drag",
            "Constrain marquee to square/circle": "Shift-drag",
            "Draw marquee from center": "Option-drag",
            "Switch to Move tool": "Command",
            "Move copy of selection": "Move tool + Option-drag",
            "Move selection area 1 pixel": "Any selection + Arrow keys",
            "Move selection area 10 pixels": "Shift + Arrow keys",
            "Move layer 1 pixel when nothing selected on layer": "Command + Arrow keys",
            "Accept cropping or exit cropping": "Crop tool + Return or Esc"
        },
        "Use for Painting (Mac shortcuts)": {
            "Select foreground color from color picker": "Any painting tool + Control + Option + Command + drag",
            "Select foreground color from image with Eyedropper tool": "Any painting tool + Option",
            "Select background color": "Eyedropper tool + Option-click",
            "Sets opacity, tolerance, strength, or exposure": "Any painting tool + number keys (Shift where airbrush enabled)",
            "Sets flow for painting mode": "Any painting tool + Shift + number keys",
            "Mixer Brush changes Mix setting": "Option + Shift + number",
            "Fill with foreground color": "Option + Delete",
            "Lock transparent pixels": "/ (forward slash)",
            "Connect points with straight line": "Any painting tool + Shift-click"
        },
        "Use for Blending Modes (Mac shortcuts)": {
            "Cycle through blending modes": "Shift + + (plus) or – (minus)",
            "Normal": "Shift + Option + N",
            "Dissolve": "Shift + Option + I",
            "Multiply": "Shift + Option + M",
            "Color Burn": "Shift + Option + B",
            "Screen": "Shift + Option + S",
            "Overlay": "Shift + Option + O",
            "Soft Light": "Shift + Option + F",
            "Hard Light": "Shift + Option + H",
            "Difference": "Shift + Option + E",
            "Hue": "Shift + Option + U",
            "Saturation": "Shift + Option + T",
            "Color": "Shift + Option + C",
            "Luminosity": "Shift + Option + Y"
        },
        "Select and Edit Text (Mac shortcuts)": {
            "Move type in image": "Command-drag type layer",
            "Select 1 character left/right, 1 line down/up, or 1 word": "Shift + Arrow keys or Command + Shift + Arrow keys",
            "Select characters from insertion point to mouse click": "Shift-click",
            "Show/Hide selection on selected type": "Command + H",
            "Display bounding box for transforming text": "Command",
            "Scale text within bounding box": "Command-drag bounding box handle",
            "Move text box while creating": "Spacebar-drag"
        },
        "Format Type (Mac shortcuts)": {
            "Align left, center, right": "Horizontal Type tool + Command + Shift + L/C/R",
            "Align top, center, bottom": "Vertical Type tool + Command + Shift + L/C/R",
            "Choose 100% horizontal scale": "Command + Shift + X",
            "Choose 100% vertical scale": "Command + Shift + Option + X",
            "Choose Auto leading": "Command + Shift + Option + A",
            "Choose 0 for tracking": "Command + Control + Shift + Q",
            "Justify paragraph": "Command + Shift + J or Command + Shift + F",
            "Toggle paragraph hyphenation": "Command + Control + Shift + Option + H",
            "Decrease or increase type size": "Command + Shift + < or >",
            "Decrease or increase leading": "Option + Up Arrow or Down Arrow",
            "Decrease or increase baseline shift": "Shift + Option + Up Arrow or Down Arrow",
            "Decrease or increase kerning/tracking": "Option + Left Arrow or Right Arrow"
        },
        "Use the Layers Panel (Mac shortcuts)": {
            "Load layer transparency as selection": "Command-click layer thumbnail",
            "Add to current selection": "Command + Shift-click layer thumbnail",
            "Subtract from current selection": "Command + Option-click layer thumbnail",
            "New layer": "Command + Shift + N",
            "New layer via copy": "Command + J",
            "Group layers": "Command + G",
            "Ungroup layers": "Command + Shift + G",
            "Create/release clipping mask": "Command + Option + G",
            "Select all layers": "Command + Option + A",
            "Merge visible layers": "Command + Shift + E",
            "Create new layer below target": "Command-click New Layer button",
            "Select top layer": "Option + . (period)",
            "Select bottom layer": "Option + , (comma)",
            "Add to layer selection": "Shift + Option + [ or ]",
            "Select next layer down/up": "Option + [ or ]",
            "Move target layer down/up": "Command + [ or ]",
            "Merge layers": "Highlight layers, then Command + E",
            "Show/hide this layer only": "Control-click eye icon",
            "Show/hide all other visible layers": "Option-click eye icon",
            "Toggle lock transparency": "/ (forward slash)",
            "Edit layer effect/style": "Double-click layer effect/style",
            "Hide layer effect/style": "Option-double-click layer effect/style",
            "Toggle layer mask on/off": "Shift-click layer mask thumbnail",
            "Toggle rubylith mode for layer mask": "\\ (backslash) or Shift + Option-click layer mask thumbnail"
        }
    },
    "page_url": "https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html"
}