# coding: utf8

# https://www.pixelmator.com/tutorials/resources/keyboard-shortcuts/
shortcuts = {
    "Pixelmator": {
      "Zoom in": "⌘ +",
      "Zoom out": "⌘ -",
      "Zoom to fit": "⌘0",
      "View actual size": "⌥⌘0 or ⌘1",
      "Select Zoom tool": "Z",
      "Zoom in with zoom tool": "Click",
      "Zoom out with zoom tool": "⌥click",
      "zoom in to area with zoom tool": "Drag over an area",
      "Scroll an image": "Press and hold the Space bar, then drag the image",
      "Style": "S",
      "Arrange": "V",
      "Free Selection": "L",
      "Rectangular Selection": "M",
      "Elliptical Selection": "Y",
      "Color Selection": "W",
      "Quick Selection": "Q",
      "Paint": "B",
      "Erase": "E",
      "Gradient Fill": "G",
      "Color Fill": "N",
      "Repair": "R",
      "Rectangle Shape": "U",
      "Pen": "P",
      "Type": "T",
      "Color Adjustments": "A",
      "Effects": "F",
      "Color Picker": "I",
      "Crop": "C",
      "Slice and Export for Web": "K or ⇧⌘E",
      "Create a new image": "⌘N",
      "Open an image from your Photos library": "⌥⌘N",
      "Open an image": "⌘O",
      "Save an image": "⌘S",
      "Duplicate an image": "⇧⌘S",
      "Save an existing image as a new image": "⌥⇧⌘S",
      "Export an image": "⌘E",
      "Undo last action": "⌘Z",
      "Redo last action": "⇧⌘Z",
      "Cut": "⌘X",
      "Copy": "⌘C",
      "Paste": "⌘V",
      "Paste and match style": "⌥⇧⌘V",
      "Inver the colors of an image layer": "⌘I",
      "Duplicate layer or selected area": "⇧⌘D or ⌘J",
      "Cut and paste selected area": "⇧⌘J",
      "Duplicate a layer and move it by a pixel": "⌥Arrow",
      "Duplicate a layer and move it by 10 pixels": "⌥⇧Arrow",
      "Change the size of the image": "⌥⌘I",
      "Use ML Super Resolution to increase the resolution of an image": "⌥⌘U",
      "Change the size of the image canvas": "⌥⌘C",
      "Change the color profile of the image": "⇧⌘K",
      "Create an empty new layer": "⇧⌘N",
      "Insert an image as a new layer": "⇧⌘V",
      "Replace an existing image layer with a new image": "⇧⌘R",
      "Delete selected layer(s)": "Backspace",
      "Select all layers": "⌥⌘A",
      "Merge selected layers": "⌥⌘E",
      "Merge all layers": "⌥⇧⌘E",
      "Group layers": "⌘G",
      "Ungroup layers": "⇧⌘G",
      "Lock or unlock layers": "Slash (/) key",
      "Hide or show layers": "⌥⌘, or Ctrl H",
      "Add a layer mask that hides all the contents of the layer": "⌥click Add Mask in the Layers sidebar shortcut menu",
      "Copy a layer mask": "⌥drag a layer mask from one layer to another",
      "Temporarily disable a layer mask": "⇧click a layer mask",
      "Create a clipping mask": "⌥⌘G or ⌥click between two layers in the Layers sidebar",
      "Select the next layer in the layer list": "⌥Right bracket (])",
      "Select the previous layer in the layer list": "⌥Left bracket ([)",
      "Select the top layer in the layer list": "⌥Period (.)",
      "Selecte the bottom layer in the layer list": "⌥,",
      "Bring selected layer(s) forward": "⌘Right Bracket (])",
      "Send selected layer(s) to the front": "⌥⌘Right Bracket (])",
      "Bring selected layer(s) backward": "⌘Left Bracket ([)",
      "Send selected layer(s) to the back": "⌥⌘Left Bracket ([)",
      "Move a layer while using any tool": "⌘drag the layer",
      "Cycle through blending modes": "⇧+ or ⇧-",
      "Set layer opacity": "Press a number key once or twice quickly in succession. Press the 0 key once for 100% and twice for 0%",
      "Temporarily view original layer without styles applied": "Hold O key",
      "Resize a layer": "Drag a layer handle",
      "Duplicate a layer": "⇧⌘D or ⌥drag",
      "Disable alignment guides while moving or resizing": "⌘drag",
      "Resize a layer from the center": "⌥drag a layer handle",
      "Constrain the aspect ratio when resizing a layer": "⇧drag a layer handle",
      "Constrain the aspect ratio when resizing a layer from the center": "⌥⇧drag a layer handle",
      "Open the shortcut menu for the selected layer": "Ctrl click the layer",
      "Rotate a layer": "⌘drag a layer handle",
      "Rotate a layer in 15º steps": "⇧⌘drag a layer handle",
      "Move a layer in a straight or diagonal line": "⇧drag a layer",
      "Turn on the Transform tool": "⌘T",
      "Skew the shape of a layer": "Drag a transform handle while pressing and holding the Shift and ⌘ keys",
      "Freely distort the shape of a layer": "Drag a transform handle while pressing and holding the ⌘ key",
      "Transform the perspective of a layer": "Drag a transform handle while pressing and holding the Option, Shift, and ⌘ keys",
      "Select the entire image": "⌘A",
      "Deselect an active selection": "⌘D",
      "Invert a selection": "⇧⌘I",
      "Load the outline of a layer as a selection": "⌥⌘L or ⌘click the thumbnail of a layer",
      "Turn on Refine Selection": "⌥⌘R",
      "Copy a selected area": "⌘C",
      "Cut a selected area": "⌘X",
      "Paste a selected area": "⌘V",
      "Duplicate a selected area": "⇧⌘D",
      "Constrain selection to a circle or a square": "Press and hold the Shift key after starting a selection",
      "Add to a selection": "Hold down the Shift key before starting to select",
      "Subtract from a selection": "Hold down the Option key before starting to select",
      "Intersect a selection": "Hold down the Shift and Option keys before starting to select",
      "Reset foreground and background colors to black and white": "D",
      "Switch between foreground and background color": "X",
      "Paint or erase a straight line": "Click to add the start of the line, then ⇧click the end of the line",
      "Paint or erase a vertical or horizontal line": "Press and hold the Shift key before starting to paint",
      "Open brush settings": "Double-click a brush",
      "Navigate through brushes": ", or Period (.)",
      "Increase or decrease brush size": "Right bracket (]) or Left bracket ([)",
      "Increase or decrease brush softness": "⇧Right bracket (]) or ⇧Left bracket ([)",
      "Constrain gradient angle to 15º intervals": "Press and hold the Shift key while painting a gradient",
      "Sample a color from your image as you paint": "Press and hold the Option key to activate the color picker, then ⌥click to sample a color",
      "Fill a layer with the foreground color": "⌘Backspace",
      "Fill layer with background color": "⌥Backspace",
      "Set the opacity of the Paint tool": "Press a number key once or twice quickly in succession. Press the 0 key for 100%, or 00 for 0%",
      "Cycle through blending modes": "⇧+ or ⇧-",
      "Choose the clone source": "⌥click",
      "Choose the Rectangle Shape tool": "U",
      "Unite a shape with the selected shape": "Press and hold the Shift key before starting to draw",
      "Subtract a shape from the selected shape": "Press and hold the Option key before starting to draw",
      "Intersect a shape with the selected shape": "Press and hold the Option and Shift keys before starting to draw",
      "Move a shape on the canvas while using any shape tool": "⌘drag a shape",
      "Select a different shape on the canvas while using any shape tool": "⌘click a shape",
      "Select multiple shapes on the canvas while using any shape tool": "Press and hold the Shift and ⌘ keys, then click or drag to select shapes ",
      "Move multiple shapes on the canvas while using any shape tool": "After selecting multiple shapes, press and hold the ⌘ key and drag the shapes",
      "Make a shape editable": "Return key",
      "Break apart the direction lines of a smooth anchor point": "⌥drag a direction point",
      "Rejoin the direction lines of a smooth anchor point": "⌥drag a direction point",
      "Select or deselect multiple anchor points": "⇧click an anchor point or ⇧drag to draw a selection over multiple anchor points",
      "Delete the selected anchor point(s)": "Backspace key",
      "Stop editing a shape": "Esc key",
      "Add a sharp point": "Click anywhere in the image",
      "Add a smooth point": "Drag anywhere in the image",
      "Delete the most recently added anchor point": "Backspace key",
      "Adjust the direction lines of a smooth anchor point after adding it": "⌘drag a direction line",
      "Break apart the direction lines of a smooth anchor point while adding it": "Press and hold the Option key while dragging to add an anchor point",
      "Break apart the direction lines of a smooth anchor point after adding it": "⌥drag a direction point",
      "Finish drawing a path and close it": "Return key",
      "Finish drawing a path and leave it open": "Esc key",
      "Automatically enhance the colors of an image (ML Enhance)": "⇧⌘M",
      "Automatically remove camera noise and image compression artifacts (ML Denoise)": "Ctrl ⇧D",
      "Apply the Hue &amp; Saturation adjustment": "⌘U",
      "Apply the Color Balance adjustment": "⌘B",
      "Apply the Levels adjustment": "⌘L",
      "Apply the Curves adjustment": "⌘K",
      "Temporarily view the original layer without adjustments": "Hold O key",
      "Apply the Color Fill effect": "⌥⌘F",
      "Temporarily view original layer without effects": "Hold O key",
      "Open Pixelmator Pro preferences": "⌘,",
      "Show or hide the document info window": "⇧⌥⌘I",
      "Show or hide the Info bar": "⌘/",
      "Hide or show the toolbar": "⌥⌘T",
      "Hide or show the Tools sidebar": "⌥T",
      "Show or hide the Layers sidebar": "⌥L",
      "Set the Layers sidebar to use List view": "⌥⇧L",
      "Set the Layers sidebar to use the Thumbnail view": "Ctrl ⇧L",
      "Show or hide alignment guides": "⌥⌘;",
      "Show or hide the rulers": "⌘R",
      "Show or hide the grid": "⌥⌘‘",
      "Show or hide the Colors window": "⇧⌘C",
      "Turn Soft Proof Colors on or off": "⌘Y",
      "Enter or exit fullscreen": "Ctrl ⌘F",
      "Close the active window": "⌘W",
      "Close all windows": "⌥⌘W",
      "Open the next tab": "Ctrl Tab",
      "Open the previous tab": "Ctrl ⇧Tab",
      "Show or hide the tab bar": "⇧⌘T",
      "View all open tabs": "⇧⌘\\",
      "Cycle through windows": "⌘`",
      "Minimize the active window": "⌘M",
      "Minimize all windows": "⌥⌘M",
      "Hide Pixelmator Pro": "⌘H",
      "Hide other app windows": "⌥⌘H",
      "Print": "⌘P",
      "Quit Pixelmator Pro": "⌘Q"
      }
}
