# coding: utf8

shortcuts = {
    "Reddit Enhancement Suite":{ #⇧/
        "Show help for keyboard shortcuts":"⇧/",
        "Launch RES command line":"/",
        "Launch filter command line":"H",
        "Move up to the previous link or comment in flat lists":"K",
        "Move down to the next link or comment in flat lists":"J",
        "Move to top of list (on link pages)":"⇧K",
        "Move to bottom of list (on link pages)":"⇧J",
        "Follow link (link pages only)":"↩",
        "Follow link in new tab (link pages only)":"⇧↩",
        "Toggle expando (image/text/video)":"X",
        "Increase the size of image(s) in the highlighted post area":"=",
        "Decrease the size of image(s) in the highlighted post area":"-",
        "Increase the size of image(s) in the highlighted post area (finer control)":"⇧=",
        "Decrease the size of image(s) in the highlighted post area (finer control)":"⇧-",
        "Removes the height restriction of image(s) in the highlighted post area":"⇧→",
        "Move the image(s) in the highlighted post area up":"⌃↑",
        "Move the image(s) in the highlighted post area down":"Move the image(s) in the highlighted post area down.",
        "Move the image(s) in the highlighted post area left":"⌃← ",
        "Move the image(s) in the highlighted post area right":"⌃→",
        "View the previous image of an inline gallery":"[",
        "View the next image of an inline gallery":"]",
        "Toggle 'show images' button":"⇧X",
        "View comments for link (⇧ opens them in a new tab)":"C",
        "View comments for link in a new tab":"⇧C",
        "View link and comments in new tabs.":"L",
        "View link and comments in new background tabs.":"⇧L",
        "Upvote selected link or comment (or remove the upvote).":"A",
        "Downvote selected link or comment (or remove the downvote).":"Z",
        "Upvote selected link or comment (but don't remove the upvote).":"⇧A",
        "Downvote selected link or comment (but don't remove the downvote).":"⇧Z",
        "Save the current post to your reddit account (not preserved if deleted or edited)":"S",
        "Save the current comment with RES (preserved locally)":"S",
        "Go to subreddit of selected link (link pages only)":"R",
        "Go to subreddit of selected link in a new tab (link pages only).":"⇧R ",
        "Enter 'goMode' (before using 'go to' shortcuts).":"G",
        "Go to inbox":"G then I",
        "Go to inbox in a new tab.":"G then ⇧I",
        "Go to modmail.":"G then M",
        "Go to modmail in a new tab.":"G then ⇧M",
        "Go to profile.":"G then U",
        "Go to profile in a new tab.":"G then ⇧U",
        "Go to front page.":"G then F ",
        "Go to /r/all.":"⌥A",
        "Go to subreddit front page.":"⇧F",
        "Go to a random subreddit.":"⌥Y",
        "Go to next page (link list pages only).":"G then N",
        "Go to previous page (link list pages only).":"G then P",
        "Focuses the cursor in the search box.":"⌥/",
    }
}