# coding: utf8

shortcuts = {
    "Reddit Enhancement Suite": {
        "Show help for keyboard shortcuts": "?",
        "Launch RES command line": "/",
        "Launch filter command line": "H",
        "Move up to the previous link or comment in flat lists": "K",
        "Move down to the next link or comment in flat lists": "J",
        "Move to top of list (on link pages)": "Shift+K",
        "Move to bottom of list (on link pages)": "Shift+J",
        "Follow link (link pages only)": "Enter",
        "Follow link in new tab (link pages only)": "Shift+Enter",
        "Toggle expando (image/text/video)": "X",
        "Increase the size of image(s) in the highlighted post area": "=",
        "Decrease the size of image(s) in the highlighted post area": "-",
        "Increase the size of image(s) in the highlighted post area (finer control)": "Shift+=",
        "Decrease the size of image(s) in the highlighted post area (finer control)": "Shift+-",
        "Removes the height restriction of image(s) in the highlighted post area": "Shift+Enter",
        "Move the image(s) in the highlighted post area up": "Ctrl+Up",
        "Move the image(s) in the highlighted post area down": "Ctrl+Down",
        "Move the image(s) in the highlighted post area left": "Ctrl+Left",
        "Move the image(s) in the highlighted post area right": "Ctrl+Right",
        "View the previous image of an inline gallery": "[",
        "View the next image of an inline gallery": "]",
        "Toggle 'show images' button": "Shift+X",
        "View comments for link (Shift+opens them in a new tab)": "C",
        "View comments for link in a new tab": "Shift+C",
        "View link and comments in new tabs": "L",
        "View link and comments in new background tabs": "Shift+L",
        "Upvote selected link or comment (or remove the upvote)": "A",
        "Downvote selected link or comment (or remove the downvote)": "Z",
        "Upvote selected link or comment (but don't remove the upvote)": "Shift+A",
        "Downvote selected link or comment (but don't remove the downvote)": "Shift+Z",
        "Save the current post to your reddit account (not preserved if deleted or edited)": "S",
        "Save the current comment with RES (preserved locally)": "S",
        "Go to subreddit of selected link (link pages only)": "R",
        "Go to subreddit of selected link in a new tab (link pages only)": "Shift+R",
        "Enter 'goMode' (before using 'go to' shortcuts)": "G",
        "Go to inbox": "G then I",
        "Go to inbox in a new tab": "G then Shift+I",
        "Go to modmail": "G then M",
        "Go to modmail in a new tab": "G then Shift+M",
        "Go to profile": "G then U",
        "Go to profile in a new tab": "G then Shift+U",
        "Go to front page": "G then F",
        "Go to /r/all": "Ctrl+Alt+A",
        "Go to subreddit front page": "Shift+F",
        "Go to a random subreddit": "Ctrl+Alt+Y",
        "Go to next page (link list pages only)": "G then N",
        "Go to previous page (link list pages only)": "G then P",
        "Focuses the cursor in the search box": "Ctrl+Alt+/",
    }
}

# Reference page URL:
# https://www.reddit.com/r/Enhancement/comments/shortcuts_list