# coding: utf8
shortcuts = {
    "Safari":{
        #https://support.apple.com/en-jo/guide/safari/keyboard-and-other-shortcuts-cpsh003
        #https://www.lifewire.com/keyboard-shortcuts-for-safari-in-mac-446554
        #https://support.apple.com/en-jo/guide/safari-developer/keyboard-shortcuts-reference-dev654e5967f
        "Scroll up, down, left, or right":"Press the arrow keys",
        "Scroll in larger increments":"Press Option while you press an arrow key",
        "Scroll down a screen":"Page Down or Space bar",
        "Scroll up a screen":"Page Up or Shift–Space bar",
        "Scroll to the top-left corner of the page":"Command–Up Arrow or Home",
        "Scroll to the bottom-left corner of the page":"Command–Down Arrow or End",
        "Highlight the next item on a webpage":"Tab ",
        "Highlight the same items as Tab plus all other clickable items":"Option-tab",
        "Show all tabs":"Shift-Command-\\",
        "Open a page in a new tab":"Command-click a link ",
        "Open a bookmark in a new tab":"Command-click a bookmark ",
        "Open a page in a new tab in Smart Search field":"Command-Return after typing",
        "Open a page in a new tab, and make that tab the active tab":"Shift-Command-click a link",
        "Open a bookmark in a new tab, and make that tab the active tab":"Shift-Command-click a bookmark",
        "Open a page in a new tabn Smart Search field, and make that tab the active tab":"Shift-Command-Return after typing in the Smart Search field",
        "Make the next tab the active tab":"Control-Tab or Shift-Command-]",
        "Make the previous tab the active tab":"Control-Shift-Tab or Shift-Command -[",
        "Select one of your first nine tabs":"Command-1 to Command-9",
        "Close all tabs except for one":"Option-click the close button  on the tab you want to leave open",
        "Reopen the last tab or window you closed":"Shift-Command-T",
        "See a list of your recently visited pages by name":"Hold down the Back or Forward button until the list appears",
        "See a list of your recently visited pages by web address (URL)":"Press Option and hold down the Back or Forward button until the list appears",
        "Go to your homepage":"Command-Home key",
        "While typing in the Smart Search field, restore the current webpage address":"Esc",
        "Close Reader":"Esc",
        "Exit full-screen view":"Esc",
        "Download a linked file":"Option-click a link to the file",
        "Open a downloaded file":"Double-click the file in the downloads list",
        "Zoom website content":"Press Command-Plus Sign (+) or Command-Minus Sign (-)",
        "Zoom website text":"Press Option while you choose View > Make Text Bigger or View > Make Text Smaller",
        "Show or Hide the Reading List sidebar":"Control-Command-2",
        "Add the current page":"Shift-Command-D",
        "Add a linked page":"Shift-click a link to the page",
        "Remove a page":"Control-click the page summary in the sidebar, then choose Remove Item",
        "Add a bookmark to the Favorites bar":"Click the Smart Search field to show the page’s full address and its icon, then drag the icon to the Favorites bar",
        "Open all bookmarks from a folder in the Favorites bar":"Command-click the folder in the Favorites bar",
        "Move a bookmark on the Favorites bar":"Drag the bookmark left or right",
        "Remove a bookmark from the Favorites bar":"Drag the bookmark off the top of the bar",
        "Show or Hide the Bookmarks sidebar":"Control-Command-1",
        "Select bookmarks and folders in the sidebar":"Command-click each bookmark and folder",
        "Extend selection of bookmarks and folders in the sidebar":"Shift-click",
        "Select the next bookmark or folder":"Up Arrow or Down Arrow",
        "Open the selected bookmark":"Space bar",
        "Open the selected folder":"Space bar or Right Arrow",
        "Close the selected folder":"Space bar or Left Arrow",
        "Change the name or address of a bookmark":"Select the bookmark, then press Return",
        "Cancel editing a bookmark name in the sidebar":"Esc",
        "Finish editing a bookmark name":"Return",
        "Create a folder containing the selected bookmarks and folders in bookmarks view":"Option-click the New Folder button near the top-right corner",
        "Delete a bookmark":"Select the bookmark, then press Delete",
        "Go back":"COMMAND + [ ",
        "Go forward":"COMMAND + ] ",
        "Download a file":"OPTION + Link on a web page ",
        "Select all":"COMMAND + A ",
        "Show/Hide Favorites":"COMMAND + SHIFT + B ",
        "Copy":"COMMAND + C ",
        "Add a Bookmark":"COMMAND + D ",
        "Find":"COMMAND + F ",
        "Hide Safari":"COMMAND + H ",
        "Advance to selection":"COMMAND + J ",
        "Open location":"COMMAND + L ",
        "Minimize":"COMMAND + M ",
        "Open new window":"COMMAND + N ",
        "Open file":"COMMAND + O ",
        "Print":"COMMAND + P ",
        "Quit Safari":"COMMAND + Q ",
        "Reload page":"COMMAND + R ",
        "Save As":"COMMAND + S ",
        "Open a new tab":"COMMAND + T ",
        "Paste":"COMMAND + V ",
        "Close":"COMMAND + W ",
        "Undo":"COMMAND + Z ",
        "Add To Reading List":"COMMAND + SHIFT + D ",
        "Redo":"COMMAND + SHIFT + Z ",
        "Resources":"COMMAND + OPTION + A ",
        "Show all Bookmarks":"COMMAND + OPTION + B ",
        "Google Search":"COMMAND + OPTION + F ",
        "Downloads":"COMMAND + OPTION + L ",
        "Load the nth bookmark in Bookmarks Toolbar":"COMMAND + NUM [1-9]",
        "Load Safari Help":"COMMAND + ? ",
        "Load Preferences":"COMMAND + , ",
        "Local search within the currently selected resource in the tab":"Command-F",
        "Select next in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"Shift-Command-] or Ctrl-Tab",
        "Select previous tab in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"Shift-Command-[ or Ctrl-Shift-Tab",
        "Find Next":"Command-G",
        "Find Previous":"Command-Shift-G",
        "Puts the selected text in the system search pasteboard, which is used by the Find dialog as the default search text":"Command-E",
        "Brings up the “Go To Line Number” dialog":"Control-G (in text editor)",
        "Brings up the Quick Open dialog, a feature that allows you to quickly search for a file in Web Inspector":"Command-Shift-O",
        "Zoom-in, makes Web Inspector’s interface larger":"Command-+",
        "Zoom-out, makes Web Inspector’s interface smaller":"Command- -",
        "Open Settings":"Command- ,",
        "Reset changes to Web Inspector’s interface size":"Command-0",
        "Save all console messages to a text file in the Console tab. Save current web content into a .webarchive file in the Elements tab. When showing a resource, it saves the resource to disk":"Command-S",
        "Forces the Save As… dialog":"Shift-Command-S",
        "Toggle between previous Web Inspector position, detached and docked":"Shift-Command-D",
        "Shifts focus to the search bar":"Shift-Command-F",
        "Enter element selection mode":"Shift-Command-C",
        "Focus the Split Console at the bottom of the tabs. Click again to enlarge the console":"Escape",
        "Focus on the console prompt. Unlike Esc, it does the same thing regardless of the context":"Control-~",
        "Show/Close Web Inspector":"Command-Option-I",
        "Show Error Console":"Command-Option-C",
        "Start Profiling JavaScript":"Shift-Command-Option-P",
        "Next Console Suggestion":"Tab",
        "Previous Console Suggestion":"Shift-Tab",
        "Accept Console Suggestion":"Right",
        "Previous Command/Line in Console":"Up",
        "Next Command/Line in Console":"Down",
        "Clear Console History":"Command-K (when in Console tab)",
        "Clear Network Items":"Command-K (when in Network tab)",
        "Execute Console Command in Console tab. Edit attribute in Elements Panel when element is selected":"Return",
        "Continue in Debugger":"Command-/",
        "Step Over in Debugger":"Command-’",
        "Step Into in Debugger":"Command-;",
        "Step Out in Debugger":"Shift-Command-;",
        "Show/hide status bar":"Command-/",
        "Show/hide sidebar":"Command-shift-L",
        "Enter full-screen":"Command-ctrl-f",
        "Open profiles":"Command-O",
        "Show toolbelt":"Command-shift-B",
        "Save work arrangement":"Command-shift-S",
        "Password manager":"Command-option-F",
        "Expose All Tabs":"Command-option-E",
        "Move tab right":"Command-shift-option-]",
        "Move tab left":"Command-shift-option-[",
        "Empty Caches":"Command-option-E",
        "Go to home page":"Command-shift-H",
        "Show history":"Command-Y",
        "Autofill form":"Command-shift-A",
        "Toggle page source":"Command-Shift-U",
        "Toggle web insepector":"Command-Shift-I",
        "Toggle JavaScript console":"Command-Shift-C",
        "Start/stop time line recording":"Command-shift-option-T",
        "Start/stop element selction":"Command-shift-C",
        "Open first-ninth tab":"Command-[1-9]"
    }
}