# coding: utf8
shortcuts = {
    "Safari":{
        #https://support.apple.com/en-jo/guide/safari/keyboard-and-other-shortcuts-cpsh003
        #https://www.lifewire.com/keyboard-shortcuts-for-safari-in-mac-446554
        #https://support.apple.com/en-jo/guide/safari-developer/keyboard-shortcuts-reference-dev654e5967f
        "Scroll up, down, left, or right":"↑↓→←",
        "Scroll in larger increments":"⌥↑ ⌥↓ ⌥→ ⌥←",
        "Scroll down a screen":"Page Down or Space",
        "Scroll up a screen":"Page Up or ⇧Space",
        "Scroll to the top-left corner of the page":"⌘↑ or Home",
        "Scroll to the bottom-left corner of the page":"⌘↓ or End",
        "Highlight the next item on a webpage":"Tab",
        "Highlight the same items as Tab plus all other clickable items":"⌥Tab",
        "Show all tabs":"⇧⌘\\",
        "Open a page in a new tab":"⌘click a link ",
        "Open a bookmark in a new tab":"⌘click a bookmark ",
        "Open a page in a new tab in Smart Search field":"⌘⏎ after typing",
        "Open a page in a new tab, and make that tab the active tab":"⇧⌘click a link",
        "Open a bookmark in a new tab, and make that tab the active tab":"⇧⌘click a bookmark",
        "Open a page in a new tabn Smart Search field, and make that tab the active tab":"⇧⌘⏎ after typing in the Smart Search field",
        "Make the next tab the active tab":"^Tab or ⇧⌘]",
        "Make the previous tab the active tab":"^⇧Tab or ⇧⌘[",
        "Select one of your first nine tabs":"⌘1 to ⌘9",
        "Close all tabs except for one":"⌥click the close button on the tab you want to leave open",
        "Reopen the last tab or window you closed":"⇧⌘T",
        "See a list of your recently visited pages by name":"Hold down the Back or Forward button until the list appears",
        "See a list of your recently visited pages by web address (URL)":"⌥hold down the Back or Forward button until the list appears",
        "Go to your homepage":"⌘Home",
        "While typing in the Smart Search field, restore the current webpage address":"Esc",
        "Close Reader":"Esc",
        "Exit full-screen view":"Esc",
        "Download a linked file":"⌥click a link to the file",
        "Open a downloaded file":"Double-click the file in the downloads list",
        "Zoom website content":"⌘+ or ⌘-",
        "Zoom website text":"Press ⌥ while you choose View > Make Text Bigger or View > Make Text Smaller",
        "Show or Hide the Reading List sidebar":"^⌘2",
        "Add the current page":"⇧⌘D",
        "Add a linked page":"⇧click a link to the page",
        "Remove a page":"^click the page summary in the sidebar, then choose Remove Item",
        "Add a bookmark to the Favorites bar":"Click the Smart Search field to show the page’s full address and its icon, then drag the icon to the Favorites bar",
        "Open all bookmarks from a folder in the Favorites bar":"⌘click the folder in the Favorites bar",
        "Move a bookmark on the Favorites bar":"Drag the bookmark left or right",
        "Remove a bookmark from the Favorites bar":"Drag the bookmark off the top of the bar",
        "Show or Hide the Bookmarks sidebar":"^⌘1",
        "Select bookmarks and folders in the sidebar":"⌘click each bookmark and folder",
        "Extend selection of bookmarks and folders in the sidebar":"⇧click",
        "Select the next bookmark or folder":"Up Arrow or Down Arrow",
        "Open the selected bookmark":"Space",
        "Open the selected folder":"Space or →",
        "Close the selected folder":"Space or ←",
        "Change the name or address of a bookmark":"Select the bookmark, then press ⏎",
        "Cancel editing a bookmark name in the sidebar":"Esc",
        "Finish editing a bookmark name":"⏎",
        "Create a folder containing the selected bookmarks and folders in bookmarks view":"⌥click the New Folder button near the top-right corner",
        "Delete a bookmark":"Select the bookmark, then press Delete",
        "Go back":"⌘[ ",
        "Go forward":"⌘] ",
        "Download a file":"⌥Click on link on a web page ",
        "Select all":"⌘A",
        "Show/Hide Favorites":"⌘⇧B ",
        "Copy":"⌘C ",
        "Add a Bookmark":"⌘D ",
        "Find":"⌘F ",
        "Hide Safari":"⌘H ",
        "Advance to selection":"⌘J ",
        "Open location":"⌘L ",
        "Minimize":"⌘M ",
        "Open new window":"⌘N ",
        "Open file":"⌘O ",
        "Print":"⌘P ",
        "Quit Safari":"⌘Q ",
        "Reload page":"⌘R ",
        "Save As":"⌘S ",
        "Open a new tab":"⌘T ",
        "Paste":"⌘V ",
        "Close":"⌘W ",
        "Undo":"⌘Z ",
        "Add To Reading List":"⌘⇧D ",
        "Redo":"⌘⇧Z ",
        "Resources":"⌘⌥A ",
        "Show all Bookmarks":"⌘⌥B ",
        "Google Search":"⌘⌥F ",
        "Downloads":"⌘⌥L ",
        "Load Safari Help":"⌘? ",
        "Load Preferences":"⌘, ",
        "Local search within the currently selected resource in the tab":"⌘F",
        "Select next in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"⇧⌘] or ^Tab",
        "Select previous tab in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"⇧⌘[ or ^⇧Tab",
        "Find Next":"⌘G",
        "Find Previous":"⌘⇧G",
        "Puts the selected text in the system search pasteboard, which is used by the Find dialog as the default search text":"⌘E",
        "Brings up the “Go To Line Number” dialog":"^G (in text editor)",
        "Brings up the Quick Open dialog, a feature that allows you to quickly search for a file in Web Inspector":"⌘⇧O",
        "Zoom-in, makes Web Inspector’s interface larger":"⌘+",
        "Zoom-out, makes Web Inspector’s interface smaller":"⌘ -",
        "Open Settings":"⌘ ,",
        "Reset changes to Web Inspector’s interface size":"⌘0",
        "Save all console messages to a text file in the Console tab. Save current web content into a .webarchive file in the Elements tab. When showing a resource, it saves the resource to disk":"⌘S",
        "Forces the Save As… dialog":"⇧⌘S",
        "Toggle between previous Web Inspector position, detached and docked":"⇧⌘D",
        "Shifts focus to the search bar":"⇧⌘F",
        "Enter element selection mode":"⇧⌘C",
        "Focus the Split Console at the bottom of the tabs. Click again to enlarge the console":"Esc",
        "Focus on the console prompt. Unlike Esc, it does the same thing regardless of the context":"^~",
        "Show/Close Web Inspector":"⌘⌥I",
        "Show Error Console":"⌘⌥C",
        "Start Profiling JavaScript":"⇧⌘⌥P",
        "Next Console Suggestion":"Tab",
        "Previous Console Suggestion":"⇧Tab",
        "Accept Console Suggestion":"→",
        "Previous Command/Line in Console":"↑",
        "Next Command/Line in Console":"↓",
        "Clear Console History (when in Console tab)":"⌘K",
        "Clear Network Items (when in Network tab)":"⌘K",
        "Execute Console Command in Console tab. Edit attribute in Elements Panel when element is selected":"⏎",
        "Continue in Debugger":"⌘/",
        "Step Over in Debugger":"⌘’",
        "Step Into in Debugger":"⌘;",
        "Step Out in Debugger":"⇧⌘;",
        "Show/hide status bar":"⌘/",
        "Show/hide sidebar":"⌘⇧L",
        "Enter full-screen":"⌘^f",
        "Open profiles":"⌘O",
        "Show toolbelt":"⌘⇧B",
        "Save work arrangement":"⌘⇧S",
        "Password manager":"⌘⌥F",
        "Expose All Tabs":"⌘⌥E",
        "Move tab right":"⌘⇧⌥]",
        "Move tab left":"⌘⇧⌥[",
        "Empty Caches":"⌘⌥E",
        "Go to home page":"⌘⇧H",
        "Show history":"⌘Y",
        "Autofill form":"⌘⇧A",
        "Toggle page source":"⌘⇧U",
        "Toggle web insepector":"⌘⇧I",
        "Toggle JavaScript console":"⌘⇧C",
        "Start/stop time line recording":"⌘⇧⌥T",
        "Start/stop element selction":"⌘⇧C"
    }
}