# coding: utf8

shortcuts = {
    "Sibelius G7":{ #http://www.sibelius.com/helpcenter/hintsandtips/G7Hints&Tips_Shortcuts.pdf
        "take G7 out of note entry or text entry": "Esc",
        "stop playback": "Esc",
        "select something (note, measure, text etc)": "Single-click",
        "on a staff selects the whole line of music": "Double-click",
        "on a staff selects a staff for the whole score": "Triple-click",
        "respells enharmonically (if a note is selected)": "Enter (Return)",
        "edits text (if text is selected)": "Enter",
        "forces a system break (if a barline is selected)": "Enter",
        "the note A (Shift + A to add an A to an existing selected note)": "A",
        "the note B (Shift + B to add a B to an existing selected note)": "B",
        "the note C (Shift + C to add a C to an existing selected note)": "C",
        "the note D (Shift + D to add a D to an existing selected note)": "D",
        "the note E (Shift + E to add an E to an existing selected note)": "E",
        "the note F (Shift + F to add an F to an existing selected note)": "F",
        "the note G (Shift + G to add a G to an existing selected note)": "G",
        "crescendo (Shift + H for a decrescendo)": "H",
        "instruments window": "I",
        "key signatures": "K",
        "lines menu (includes trills, first/second endings, rits, accels)": "L",
        "input note or input into tab staff": "N",
        "stops playback": "O",
        "play your music": "P",
        "clefs": "Q",
        "repeat something selected": "R",
        "slurs – use space bar to extend them": "S",
        "time signature": "T",
        "flips stems, slurs, ties and articulations": "X",
        "symbols window": "Z",
        "sixteenth note": "2 on numeric keypad",
        "eighth note value": "3 on numeric keypad",
        "quarter note value": "4 on numeric keypad",
        "half note value": "5 on numeric keypad",
        "whole note value": "6 on numeric keypad",
        "adds a natural to a selected note": "7 on numeric keypad",
        "adds a sharp to a selected note": "8 on numeric keypad",
        "adds a flat to a selected note": "9 on numeric keypad",
        "add unison to selected note": "1 on main qwerty keyboard",
        "add second above selected note": "2 on main qwerty keyboard",
        "add third above selected note": "3 on main qwerty keyboard",
        "add fourth above selected note": "4 on main qwerty keyboard",
        "add fifth above selected note": "5 on main qwerty keyboard",
        "add sixth above selected note": "6 on main qwerty keyboard",
        "add seventh above selected note": "7 on main qwerty keyboard",
        "add octave above selected note": "8 on main qwerty keyboard",
        "add second below selected note": "Shift +2 on main qwerty keyboard",
        "add third below selected note": "Shift +3 on main qwerty keyboard",
        "add fourth below selected note": "Shift +4 on main qwerty keyboard",
        "add fifth below selected note": "Shift +5 on main qwerty keyboard",
        "add sixth below selected note": "Shift +6 on main qwerty keyboard",
        "add seventh below selected note": "Shift +7 on main qwerty keyboard",
        "add octave below selected note": "Shift +8 on main qwerty keyboard",
        "chord diagram or guitar frame": "Shift +K",
        "toggles on/off Live Playback": "Shift +L",
        "transpose notes or key": "Shift +T",
        "copies whatever is selected": "⌥ + click",
        "select or change voices 1,2,3 and 4": "⌥+ 1,2,3,4 (main qwerty keyboard)",
        "select all": "⌘ + A",
        "add a bar to the end of score": "⌘ + B",
        "copy to clipboard": "⌘ + C",
        "add a dynamic to a selected note": "⌘ + E",
        "add chord symbol above a selected note": "⌘ + K",
        "add lyrics to a selected note": "⌘ + L",
        "start a new score": "⌘ + N",
        "open an existing score": "⌘ + O",
        "print": "⌘ + P",
        "quit G7": "⌘ + Q",
        "save": "⌘ + S",
        "add text to a selected note": "⌘ + T",
        "paste – good for copying between files": "⌘ + V",
        "close your score": "⌘ + W",
        "redo last action (if you’ve undone it)": "⌘ + Y",
        "undo last action (press multiple times to undo lots!)": "⌘ + Z",
        "toggles on/off the Fretboard": "⌘ + ⌥ + F",
        "toggles on/off the Keypad": "⌘ + ⌥ + K",
        "toggles on/off the Mixer": "⌘ + ⌥ + M",
        "toggles on/off the Navigator": "⌘ + ⌥ + N",
        "toggles on/off the Properties box": "⌘ + ⌥ + P",
        "add tempo or metronome mark": "⌘ + ⌥ + T",
        "select whole line of lyrics or chord symbols (if one word or chord symbol is already selected)": "⌘ + Shift A",
        "add a bar after what is currently selected": "⌘ + Shift B",
        "record in Flexi-time (Esc key or O to stop)": "⌘ + Shift F",
        "hide whatever is selected": "⌘ + Shift H",
        "reset note spacing for selected notes or score": "⌘ + Shift N",
        "Flexi-time (recording) options": "⌘ + Shift O",
        "show hidden object (opposite of hide)": "⌘ + Shift S",
        "extract parts": "⌘ + Shift X",
        "key zoom in": "⌘ and +",
        "key zoom out": "⌘ and –",
        "moves a selected note up in pitch, moves selected text up, and moves input curser up in a tab staff": "↑",
        "moves a selected note down in pitch, moves selected text down, and moves input curser down in a tab staff": "↓",
        "moves selected note(s) up an octave": "⌘ + ↑",
        "moves selected note(s) down an octave": "⌘ + ↓",
        "moves to previous note or rest": "←",
        "moves to next note or rest": "→",
        "go into create mode (note inputting) or input rest of selected value": "Spacebar",
        "select the first measure rest in a score": "Tab",
        "takes you back a page": "Home",
        "takes you forward a page": "End",
        "takes you up the page": "Page Up",
        "takes you down the page": "Page Down",
        "moves a selected note to the right or expands a selected bar": "Shift + ⌥ + →",
        "moves a selected note to the left or contracts a selected bar": "Shift + ⌥ + ←",
        "moves an individual staff up": "Shift + ⌥ + ↑",
        "moves an individual staff down": "Shift + ⌥ + ↓",
        "moves staff and rest of score down": "⌘ + ⌥ + + ↓"
    }
}