# coding: utf8
#http://www.cheetyr.com/sketch

shortcuts = {
  "Sketch": {
    "New Artboard":"A",
    "Slice":"S",
    "Rectangle":"R",
    "Rounded Rectangle":"U",
    "Oval":"O",
    "Line":"L",
    "Vector Point":"V",
    "Pencil":"P",
    "Text":"T",
    "Bold":"⌘B",
    "Italic":"⌘I",
    "Underline":"⌘U",
    "Increase font size":"⌥⌘+",
    "Decrease font size":"⌥⌘-",
    "Increase character spacing":"⌥^L",
    "Decrease character spacing":"⌥^T",
    "Change font":"⌘T",
    "Convert text to outlines":"⇧⌘O",
    "Align left":"⌘⇧{",
    "Align centre":"⌘⇧|",
    "Align right":"⌘⇧}",
    "Special characters":"^⌘Space",
    "Zoom in":"⌘+",
    "Zoom out":"⌘-",
    "Actual size":"⌘0",
    "Centre canvas":"⌘1",
    "Zoom selection":"⌘2",
    "Centre selection":"⌘3",
    "Temporary zoom to actual size":"§",
    "Focus on first input field":"⌥Tab",
    "Toggle rulers":"^R",
    "Toggle grid":"^G",
    "Toggle layer guides":"^L",
    "Toggle pixels":"^P",
    "Toggle selection handles":"^H",
    "Toggle pixel grid":"^X",
    "Toggle between documents":"⌘~",
    "Toggle layers list":"⌥⌘1",
    "Toggle inspector":"⌥⌘2",
    "Toggle layers, inspector":"⌥⌘3",
    "Toggle toolbar":"⌥⌘T",
    "Presentation mode":"⌘.",
    "Enter fullscreen":"^⌘F",
    "Keep current selection":"⌘⌥",
    "Use as mask span":"^⌘M",
    "Union":"⌥⌘U",
    "Subtract":"⌥⌘S",
    "Intersect":"⌥⌘I",
    "Difference":"⌥⌘X",
    "Change object size":"⌘ Arrows",
    "Change units by 10":"⇧⌘ Arrows",
    "Change vector point style":"1, 2, 3, 4",
    "Show distance to other layers":"⌥",
    "Show distance to other layers inside group":"⌥⌘",
    "Duplicate":"⌘D",
    "Duplicate":"⌥ Drag",
    "Copy style":"⌥⌘C",
    "Paste style":"⌥⌘V",
    "Colour picker":"^C",
    "Transform":"⌘T",
    "Rotate":"⇧⌘R",
    "Toggle Fill":"F",
    "Toggle Border":"B",
    "Move layer up":"⌥⌘↑",
    "Bring layer to front":"^⌥⌘↑",
    "Move layer down":"⌥⌘↓",
    "Bring layer to back":"^⌥⌘↓",
    "Hide layer":"⇧⌘H",
    "Lock layer":"⇧⌘L",
    "Rename layer":"⌘R",
    "Group layers":"⌘G",
    "Ungroup layers":"⇧⌘G",
    "Select layer above":"⇧Tab",
    "Select layer below":"Tab",
    "Select parent layer": "Esc",
    "Select layer one level deeper": "⏎",
    "Find layer by name":"⌘F",
    "Select page above":"Fn ↑",
    "Select page below":"Fn ↓"
  }
}
