# coding: utf8

shortcuts = {
    "Slack": #https://get.slack.help/hc/en-us/articles/201374536-Slack-keyboard-shortcuts
        {
            "Jump to a conversation": "⌘K or ⌘T",
            "Move focus to the next section": "F6",
            "Move focus to the previous section": "Shift F6",
            "Browse direct messages": "⌘Shift K",
            "Browse channels": "⌘Shift L",
            "Compose a new message": "⌘N",
            "Open the Threads view": "⌘Shift T",
            "Previous unread channel or DM": "Option Shift ↑", 
            "Next unread channel or DM": "OptionShift↓",
            "Previous channel or DM visited": "⌘[ or ⌘]",
            "Open your preferences": "⌘,",
            "Channel info pane": "⌘ShiftI",
            "Mentions & reactions": "⌘ShiftM",
            "People": "⌘ShiftE",
            "Saved items": "⌘ShiftS",
            "Set a status": "⌘ShiftY",
            "Search current channel or conversation": "⌘F",
            "Open previous search": "⌘G",
            "Toggle full-screen view": "^⌘F",
            "Collapse or open the right sidebar": "⌘.",
            "Collapse or open the left sidebar": "⌘ShiftD",
            "Open All unread view": "⌘ShiftA",
            "Mark messages as unread": "Option click a message",
            "Move between messages": "↑ or ↓",
            "Open and collapse channels": "← or →",
            "Switch to previous workspace": "⌘Shift[",
            "Switch to next workspace": "⌘Shift]",
            "Switch to a specific workspace": "⌘[number]",
            "Mark all messages in current channel or DM as read": "Esc",
            "Mark all messages as read": "Shift Esc",
            "Set a message as your oldest unread message": "Option click a message",
            "Edit your message": "E",
            "Add an emoji reaction": "R",
            "Open or reply to a thread": "T or →",
            "Pin or unpin a message": "P",
            "Share a message": "S",
            "Save a message or remove from Saved items": "A",
            "Mark as unread starting from a message": "U",
            "Delete your message": "Delete",
            "Create a reminder about a message": "M",
            "Edit your last message": "⌘↑ in empty message field",
            "Select text to beginning of current line": "Shift↑",
            "Select text to end of current line": "Shift↓",
            "Create a new line in your message": "Shift Enter",
            "Add an emoji reaction to a message": "⌘Shift\\",
            "Bold selected text": "⌘B",
            "Italicise selected text": "⌘I",
            "Cross out selected text (strikethrough)": "⌘Shift X",
            "Quote selected text": "⌘Shift9",
            "Code selected text": "⌘ShiftC",
            "Codeblock selected text": "⌘ Alt Shift C",
            "Turn selected text into a numbered list": "⌘Shift7",
            "Turn selected text into a bullet-point list": "⌘Shift8",
            "Apply formatting when you copy and paste text in markdown": "⌘ShiftF",
            "Undo message formatting": "⌘Z",
            "Upload file": "⌘U",
            "Create new snippet": "⌘Shift Enter",
            "Toggle mute on and off": "M",
            "Toggle video on and off": "V",
            "Show invitation list": "+ or A",
            "View and select an emoji reaction": "E then 1–9"
        }
    }