# coding: utf8

shortcuts = {
    "Slack": #https://get.slack.help/hc/en-us/articles/201374536-Slack-keyboard-shortcuts
        {
            "Open list of keyboard shortcuts": "⌘/",
            "Move focus to the next element  ": "Tab",
            "Move focus to the previous element  ": "⇧ Tab",
            "Move focus through messages in a channel or DM": "↑ or ↓",
            "Move focus to the next section": "^`",
            "Move focus to the previous section": "⇧^`",
            "Take action or click on buttons": "Spacebar",
            "Take action or click on links": "⏎",
            "Close windows, menus, or the message input box": "Esc",
            "Zoom in or out (increase or decrease text size)": "⌘+ or ⌘-",
            "Scroll up (toggled in Preferences)": "Fn↑ or Page Up",
            "Scroll down (toggled in Preferences)": "Fn↓ or Page Down",
            "Quick Switcher ": "⌘K or ⌘T (just for desktop)",
            "Direct messages menu": "⌘⇧K",
            "Open All Threads view": "⌘⇧T",
            "Previous channel or DM": "⌥↑",
            "Next channel or DM": "⌥↓",
            "Previous unread channel or DM": "⌥ ⇧↑",
            "Next unread channel or DM": "⌥⇧↓",
            "Previous channel or DM visited": "⌘[",
            "Next channel or DM visited  ": "⌘]",
            "Preferences (Desktop apps only.)": "⌘,",
            "Open or close right pane": "⌘.",
            "Channel info pane": "⌘⇧I",
            "Activity": "⌘⇧M",
            "Directory": "⌘⇧E",
            "Starred Items": "⌘⇧S Ctrl⇧S",
            "Search the current channel or conversation": "⌘F",
            "Toggle full screen view": "^⌘F",
            "Open All Unreads view": "⌘⇧A",
            "Mark messages as unread": "⌥ and click a message",
            "Move between channels": "→ or ←",
            "Toggle current channel read or unread": "R",
            "Switch to previous team ": "⌘⇧[",
            "Switch to next team ": "⌘⇧]",
            "Switch to a specific team (see assigned number under the team icon in your Slack app) ": "⌘[NUM]",
            "Mark all messages in current channel or DM as read": "Esc",
            "Mark all messages as read": "⇧Esc",
            "Set a message as your oldest unread message": "⌥ and click a message",
            "Edit your last message": "↑ in empty message box",
            "Select text to beginning of current line": "⇧↑",
            "Select text to end of current line": "⇧↓",
            "Create a new line in your message": "⇧⏎  ",
            "Add emoji reactions to a message": "⌘⇧\\",
            "Autocomplete @display name beginning with [character]": "[character]Tab or @[character]Tab",
            "Autocomplete channel beginning with [character]": "#[character]Tab",
            "Autocomplete emoji beginning with [character]": ":[character]Tab",
            "Upload a file": "⌘U",
            "Create a new Snippet    ": "⌘⏎⇧",
            "Toggle mute on and off": "M (hold down to talk when muted)",
            "Toggle video on and off ": "V",
            "Show the invite list    ": "+ or A",
            "View and select and emoji reactions ": "E then 1 - 9"
        }
    }