# coding: utf8

shortcuts = {
    "Slack": {
        # Slack basics
        "Compose a new message (Mac)": "⌘ + N",
        "Compose a new message (Windows/Linux)": "Ctrl + N",
        "Unsend a message (Mac)": "⌘ + Z",
        "Unsend a message (Windows/Linux)": "Ctrl + Z",
        "Set your status (Mac)": "⌘ + Shift + Y",
        "Set your status (Windows/Linux)": "Ctrl + Shift + Y",
        "Open your preferences (Mac)": "⌘ + ,",
        "Open your preferences (Windows/Linux)": "Ctrl + ,",
        "Show or hide the left sidebar (Mac)": "⌘ + Shift + D",
        "Show or hide the left sidebar (Windows/Linux)": "Ctrl + Shift + D",
        "Hide the right sidebar (Mac)": "⌘ + .",
        "Hide the right sidebar (Windows/Linux)": "Ctrl + .",
        "Create a new canvas (Mac)": "⌘ + Shift + N",
        "Create a new canvas (Windows/Linux)": "Ctrl + Shift + N",
        "Upload a file (Mac)": "⌘ + U",
        "Upload a file (Windows/Linux)": "Ctrl + U",
        "View all downloaded files (Mac)": "⌘ + Shift + J",
        "View all downloaded files (Windows/Linux)": "Ctrl + Shift + J",
        "Create a new snippet (Mac)": "⌘ + Shift + Enter",
        "Create a new snippet (Windows/Linux)": "Ctrl + Shift + Enter",
        "Add an emoji reaction to a message (Mac)": "⌘ + Shift + \\",
        "Add an emoji reaction to a message (Windows/Linux)": "Ctrl + Shift + \\",
        "Start a search (Mac)": "⌘ + G",
        "Start a search (Windows/Linux)": "Ctrl + G",
        "Search in the current conversation (Mac)": "⌘ + F",
        "Search in the current conversation (Windows/Linux)": "Ctrl + F",
        "Start, join, leave, or end a huddle (Mac)": "⌘ + Shift + H",
        "Start, join, leave, or end a huddle (Windows/Linux)": "Ctrl + Shift + H",
        "Toggle mute on a huddle (Mac)": "⌘ + Shift + Space",
        "Toggle mute on a huddle (Windows/Linux)": "Ctrl + Shift + Space",
        "Toggle full screen view (Mac)": "Ctrl + ⌘ + F",
        "Toggle full screen view (Windows/Linux)": "F11",
        "Close window (Mac)": "⌘ + W",
        "Close window (Windows/Linux)": "Ctrl + W",
        "Reopen last closed window (Mac)": "⌘ + Shift + W",
        "Reopen last closed window (Windows/Linux)": "Ctrl + Shift + W",
        "Open the People view (Mac)": "⌘ + Shift + E",
        "Open the People view (Windows/Linux)": "Ctrl + Shift + E",
        "Quit Slack (Mac)": "⌘ + Q",
        "Quit Slack (Windows/Linux)": "Ctrl + Q",

        # Navigate conversations and messages
        "Jump to a conversation (Mac)": "⌘ + K or ⌘ + T",
        "Jump to a conversation (Windows/Linux)": "Ctrl + K or Ctrl + T",
        "Jump to most recent unread message (Mac)": "⌘ + J",
        "Jump to most recent unread message (Windows/Linux)": "Ctrl + J",
        "Jump to previous unread channel or DM (Mac)": "Option + Shift + ↑",
        "Jump to next unread channel or DM (Mac)": "Option + Shift + ↓",
        "Jump to previous unread channel or DM (Windows/Linux)": "Alt + Shift + ↑",
        "Jump to next unread channel or DM (Windows/Linux)": "Alt + Shift + ↓",
        "Jump to previous channel or DM in sidebar (Mac)": "Option + ↑",
        "Jump to next channel or DM in sidebar (Mac)": "Option + ↓",
        "Jump to previous channel or DM in sidebar (Windows/Linux)": "Alt + ↑",
        "Jump to next channel or DM in sidebar (Windows/Linux)": "Alt + ↓",
        "Go back in history (Mac)": "⌘ + [",
        "Go forward in history (Mac)": "⌘ + ]",
        "Go back in history (Windows/Linux)": "Alt + ←",
        "Go forward in history (Windows/Linux)": "Alt + →",
        "Open the Home view (Windows/Linux)": "Ctrl + 1",
        "Browse DMs (Mac)": "Ctrl + 2 or ⌘ + Shift + K",
        "Browse DMs (Windows/Linux)": "Ctrl + Shift + 2 or Ctrl + Shift + K",
        "Open the Activity view (Mac)": "Ctrl + 3 or ⌘ + Shift + M",
        "Open the Activity view (Windows/Linux)": "Ctrl + Shift + 3 or Ctrl + Shift + M",
        "View items in Later (Windows/Linux)": "Ctrl + 4",
        "Open the More View (Windows/Linux)": "Ctrl + 0",
        "Open the Threads view (Mac)": "⌘ + Shift + T",
        "Open the Threads view (Windows/Linux)": "Ctrl + Shift + T",
        "Browse channels (Mac)": "⌘ + Shift + L",
        "Browse channels (Windows/Linux)": "Ctrl + Shift + L",
        "Open conversation details (Mac)": "⌘ + Shift + I",
        "Open conversation details (Windows/Linux)": "Ctrl + Shift + I",
        "Open a conversation's channel canvas (Mac)": "⌘ + Option + .",
        "Open a conversation's channel canvas (Windows/Linux)": "Ctrl + Alt + .",
        "Move focus to the next section": "F6",
        "Move focus to the previous section": "Shift + F6",

        # Mark messages read/unread
        "Mark all messages in current conversation as read": "Esc",
        "Mark all messages as read": "Shift + Esc",
        "Mark a message as unread (Mac)": "Option + Click",
        "Mark a message as unread (Windows/Linux)": "Alt + Click",

        # Navigate unread messages
        "Open the All unreads view (Mac)": "⌘ + Shift + A",
        "Open the All unreads view (Windows/Linux)": "Ctrl + Shift + A",
        "Move between messages": "↑ or ↓",
        "Mark a group of messages as unread": "Esc",
        "Open or collapse a group of messages": "← or →",

        # Switch workspaces
        "Expand or collapse the workspace switcher (Mac)": "⌘ + Shift + S",
        "Expand or collapse the workspace switcher (Windows/Linux)": "Ctrl + Shift + S",
        "Switch to previous workspace": "Ctrl + Shift + Tab",
        "Switch to next workspace": "Ctrl + Tab",
        "Switch to a specific workspace (Mac)": "⌘ + [number]",
        "Switch to a specific workspace (Windows/Linux)": "Ctrl + [number]",

        # Switch tabs
        "Switch to the previous tab": "Ctrl + Page up",
        "Switch to the next tab": "Ctrl + Page down",

        # Take actions on messages
        "Edit your message": "E",
        "Delete your message": "Delete",
        "Open or reply to a thread": "T or →",
        "Forward a message": "F",
        "Pin or unpin a message": "P",
        "Save a message or remove from Saved items": "A",
        "Mark as unread starting from a message": "U",
        "Create a reminder about a message": "M",
        "Add an emoji reaction to a message": "R",

        # Format messages (Mac)
        "Select text to beginning of current line (Mac)": "Shift + ↑",
        "Select text to end of current line (Mac)": "Shift + ↓",
        "Create a new line in your message (Mac)": "Shift + Enter",
        "Bold selected text (Mac)": "⌘ + B",
        "Italicise selected text (Mac)": "⌘ + I",
        "Cross out selected text (strikethrough) (Mac)": "⌘ + Shift + X",
        "Hyperlink selected text (Mac)": "⌘ + Shift + U",
        "Quote selected text (Mac)": "⌘ + Shift + 9",
        "Code selected text (Mac)": "⌘ + Shift + C",
        "Codeblock selected text (Mac)": "⌘ + Alt + Shift + C",
        "Turn selected text into a numbered list (Mac)": "⌘ + Shift + 7",
        "Turn selected text into a bullet-point list (Mac)": "⌘ + Shift + 8",
        "Apply formatting when you copy and paste text in markdown (Mac)": "⌘ + Shift + F",
        "Undo message formatting (Mac)": "⌘ + Z",

        # Format messages (Windows/Linux)
        "Select text to beginning of current line (Windows/Linux)": "Shift + ↑",
        "Select text to end of current line (Windows/Linux)": "Shift + ↓",
        "Create a new line in your message (Windows/Linux)": "Shift + Enter",
        "Bold selected text (Windows/Linux)": "Ctrl + B",
        "Italicise selected text (Windows/Linux)": "Ctrl + I",
        "Cross out selected text (strikethrough) (Windows/Linux)": "Ctrl + Shift + X",
        "Hyperlink selected text (Windows/Linux)": "Ctrl + Shift + U",
        "Quote selected text (Windows/Linux)": "Ctrl + Shift + 9",
        "Code selected text (Windows/Linux)": "Ctrl + Shift + C",
        "Codeblock selected text (Windows/Linux)": "Ctrl + Alt + Shift + C",
        "Turn selected text into a numbered list (Windows/Linux)": "Ctrl + Shift + 7",
        "Turn selected text into a bullet-point list (Windows/Linux)": "Ctrl + Shift + 8",
        "Apply formatting when you copy and paste text in markdown (Windows/Linux)": "Ctrl + Shift + F",
        "Undo message formatting (Windows/Linux)": "Ctrl + Z",

        # Format text in a canvas (Mac)
        "Format selected text as paragraph (Mac)": "⌘ + Option + 0",
        "Format selected text as big heading (Mac)": "⌘ + Option + 1",
        "Format selected text as medium heading (Mac)": "⌘ + Option + 2",
        "Format selected text as small heading (Mac)": "⌘ + Option + 3",
        "Format selected text as checklist (Mac)": "⌘ + Shift + 0",
        "Format selected text as bulleted list (Mac)": "⌘ + Shift + 8",
        "Format selected text as numbered list (Mac)": "⌘ + Shift + 7",
        "Toggle heading and list styles (Mac)": "Ctrl + `",

        # Format text in a canvas (Windows/Linux)
        "Format selected text as paragraph (Windows/Linux)": "Ctrl + Alt + 0",
        "Format selected text as big heading (Windows/Linux)": "Ctrl + Alt + 1",
        "Format selected text as medium heading (Windows/Linux)": "Ctrl + Alt + 2",
        "Format selected text as small heading (Windows/Linux)": "Ctrl + Alt + 3",
        "Format selected text as checklist (Windows/Linux)": "Ctrl + Shift + 0",
        "Format selected text as bulleted list (Windows/Linux)": "Ctrl + Shift + 8",
        "Format selected text as numbered list (Windows/Linux)": "Ctrl + Shift + 7",
        "Toggle heading and list styles (Windows/Linux)": "Ctrl + `",

        # Navigate a canvas (Mac)
        "View comment thread (Mac)": "⌘ + Option + T",
        "Show reader or edit view (Mac)": "⌘ + Option + R",
        "Open context menu (Mac)": "⌘ + Shift + /",
        "Find text in the canvas (Mac)": "⌘ + F",
        "Find next (Mac)": "⌘ + G",
        "Find previous (Mac)": "⌘ + Shift + G",
        "Find and replace (Mac)": "⌘ + Shift + H",
        "Copy anchor link to section (Mac)": "Ctrl + Option + Q",
        "Undo last action (Mac)": "⌘ + Z",
        "Redo last action (Mac)": "⌘ + Shift + Z",
        "Move item in a formatted list up (Mac)": "⌘ + Option + ↑",
        "Move item in a formatted list down (Mac)": "⌘ + Option + ↓",

        # Navigate a canvas (Windows/Linux)
        "View comment thread (Windows/Linux)": "Ctrl + Alt + T",
        "Show reader or edit view (Windows/Linux)": "Ctrl + Alt + R",
        "Open context menu (Windows/Linux)": "Shift + F10",
        "Find text in the canvas (Windows/Linux)": "Ctrl + F",
        "Find next (Windows/Linux)": "Ctrl + G",
        "Find previous (Windows/Linux)": "Ctrl + Shift + G",
        "Find and replace (Windows/Linux)": "Ctrl + Shift + H",
        "Copy anchor link to section (Windows/Linux)": "Ctrl + Alt + Q",
        "Undo last action (Windows/Linux)": "Ctrl + Z",
        "Redo last action (Windows/Linux)": "Ctrl + Shift + Z",
        "Move item in a formatted list up (Windows/Linux)": "Ctrl + Alt + ↑",
        "Move item in a formatted list down (Windows/Linux)": "Ctrl + Alt + ↓",
    }
}