# coding: utf8
#https://wesbos.com/sublime-text-code-folding/
#https://wesbos.com/sublime-text-code-folding/

shortcuts = {
    "Sublime Text":{
        "Command Pallete":"⌘⇧P",
        "Python Console":"⌃`",
        "Toggle Sidebar":"⌘K, ⌘B",
        "Toggle Full­scr­een":"⌃⌘F",
        "Toggle Dist­raction Free Mode":"⌃⇧⌘F",
        "Show scope in status bar":"⌃⇧P",
        "Cut line":"⌘X",
        "Insert line after":"⌘↩",
        "Insert line before":"⌘⇧↩",
        "Move line/selection up":"⌘⌃↑",
        "Move line/selection down":"⌘⌃↓",
        "Select line - Repeat to select next lines":"⌘L",
        "Select word - Repeat to select next occurrence":"⌘D",
        "Select all occurrences of current selection":"⌃⌘G",
        "Extra cursor on the line above":"⌃⇧↑",
        "Extra cursor on the line below":"⌃⇧↓",
        "Jump to closing parentheses Repeat to jump to opening parentheses":"⌃M",
        "Select all contents of the current parentheses":"⌃⇧M",
        "Move to beginning of line":"⌃A",
        "Move to beginning of text on line":"⌘Left",
        "Move to end of line":"⌃E, ⌘Right",
        "Delete from cursor to end of line":"⌘K, ⌘K",
        "Delete from cursor to start of line":"⌘K⌫",
        "Indent current line(s)":"⌘]",
        "Un-indent current line(s)":"⌘[",
        "Duplicate line(s)":"⌘⇧D",
        "Join line below to the end of the current line":"⌘J",
        "Comment/un-comment current line":"⌘/",
        "Block comment current selection":"⌘⌥/",
        "Redo, or repeat last keyboard shortcut command":"⌘Y",
        "Paste and indent correctly":"⌘⇧V",
        "Select next auto-complete suggestion":"⌃Space",
        "Soft undo; jumps to your last change before undoing change when repeated":"⌃U",
        "Column selection up":"⌃⇧↑",
        "Column selection down":"⌃⇧↓",
        "Wrap Selection in html tag":"⌃⇧W",
        "Delete current line of cursor":"⌃⇧K",
        "Quick-open files by name":"⌘P or ⌘T",
        "Goto symbol":"⌘R",
        "Goto line in current file":"⌃G",
        "Goto word in current file":"",
        "Find":"⌘F",
        "Replace":"⌘⌥F",
        "Find in files":"⌘⇧F",
        "Scroll down one page":"⌃V",
        "Center current line vertically in page":"⌃L",
        "Scroll to end of file":"⌘↓",
        "Scroll to start of file":"⌘↑",
        "Open last closed tab":"⌘⇧t",
        "Jump to tab in current group where num is 1-9":"⌘[NUM]",
        "Jump to 10th tab in current group":"⌘0",
        "Cycle left through tabs":"⌘⇧[",
        "Cycle right through tabs":"⌘⇧]",
        "Cycle up through recent tabs":"^Tab",
        "Cycle down through recent tabs":"⇧^Tab",
        "Revert view to single column":"⌘⌥1",
        "Split view into two columns":"⌘⌥2",
        "Split view into three columns":"⌘⌥3",
        "Split view into four columns":"⌘⌥4",
        "Set view to grid (4 groups)":"⌘⌥5",
        "Jump to group where num is 1-4":"⌃[NUM]",
        "Move file to specified group where num is 1-4":"⌃⇧[NUM]",
        "Toggle bookmark":"⌘F2",
        "Next bookmark":"F2",
        "Previous bookmark":"⇧F2",
        "Clear bookmarks":"⇧⌘F2",
        "Transform to Uppercase":"⌘K, ⌘U",
        "Clip text upwards / downwards":"⌘⌃↑, ⌘⌃↓",
        "Code fold":"⌘⌥[",
        "Code unfold":"⌘⌥]",
        "Code fold multiple blocks at once":"⌘k,⌘2 [fold everything beyond 2nd level]",
        "Code unfold everything":"⌘k,⌘0",
        "Code fold Html tag - show":"⌘k,⌘T",
        "Code fold Html tag - hide":"⌘k,⌘0",
    },
    "Vintage Sublime":{ #https://github.com/sublimehq/Vintage/blob/master/Default%20(OSX).sublime-keymap
        "Exit insert mode":"⌃c or Esc",
        "Exit visual mode":"⌃c or Esc",
        "Vi Cancel current action":"⌃c",
        "Move back to beginning of word":"⌥←",
        "Move back to end of word":"⌃←",
        "Move forward to beginning of word":"⌥→",
        "Move forward to end of word":"⌃→",
        "up":"k",
        "down":"j",
        "left":"h",
        "right":"l",
        "Move cursor to end of line":"⌘right",
        "Move cursor to first non-white space char":"⌘left",
        "Move to beginning of file":"⌘↑",
        "Move to end of file":"⌘↓",
        "page up":"⌃↑",
        "page down":"⌃↓",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "replace a single character":"r",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":"."
    }
}