# coding: utf8
shortcuts = {
    # https://support.culturedcode.com/customer/portal/articles/2785159
    "Things": {
        "Create a new to-do": "⌘N",
        "Create a new to-do below selection": "Space",
        "Paste plain text to create new to-dos": "⌘V",
        "Create a checklist in an open to-do": "⌘⇧C",
        "Create a new heading in a project": "⌘⇧N",
        "Create a new project": "⌘⌥N",
        "Open Quick Entry": "^Space",
        "Open Quick Entry with Autofill": "⌥^Space",
        "Open a to-do or project": "↩",
        "Save and close": "⌘↩ or Esc",
        "Duplicate a to-do or project": "⌘D",
        "Copy a to-do or project": "⌘C",
        "Paste a to-do or project": "⌘V",
        "Complete selected items": "⌘.",
        "Cancel selected items": "⌘⌥.",
        "Delete selected items": "Delete",
        "Move completed to Logbook": "⌘L",
        "Select item above": "↑",
        "Select item below": "↓",
        "Extend selection upwards": "⇧↑",
        "Extend selection downwards": "⇧↓",
        "Extend selection to the top": "⌥⇧↑",
        "Extend selection to the bottom": "⌥⇧↓",
        "Select everything": "⌘A",
        "Move selection to another list": "⌘⇧M",
        "Move copied to-dos and projects": "⌘⌥V",
        "Move selection up": "⌘↑",
        "Move selection down": "⌘↓",
        "Move selection to top of list": "⌘⌥↑",
        "Move selection to bottom of list": "⌘⌥↓",
        "Show Jump Start": "⌘S",
        "Start Today": "⌘T",
        "Start This Evening": "⌘E",
        "Start Anytime": "⌘R",
        "Start Someday": "⌘O",
        "Start date +1 day ": "^]",
        "Start date -1 day ": "^[",
        "Start date + 1 week ": "^⇧]",
        "Start date - 1 week ": "^⇧[",
        "Direct access to set a Deadline": "⌘⇧D",
        "Deadline +1 day": "^.",
        "Deadline -1 day": "^,",
        "Deadline +1 week ": "^⇧>",
        "Deadline -1 week ": "^⇧<",
        "Make to-do or project repeating": "⌘⇧R",
        "Open new window": "⌘^N",
        "Cycle through open windows": "⌘⇧`",
        "Close current window": "⌘W",
        "Close all windows": "⌘⌥W",
        "Hide or show sidebar": "⌘/",
        "Hide or show toolbar": "⌘⌥T",
        "Full screen": "⌘^F",
        "Go to Inbox": "⌘1",
        "Go to Today": "⌘2",
        "Go to Upcoming": "⌘3",
        "Go to Anytime": "⌘4",
        "Go to Someday": "⌘5",
        "Go to Logbook": "⌘6",
        "Show to-do in list": "⌘⇧L",
        "Enter a selected project": "→",
        "Return to previous list": "←",
        "Scroll to top": "⌥↑",
        "Scroll to bottom": "⌥↓",
        "Navigate up in the sidebar": "⌘⌥^↑",
        "Navigate down in the sidebar": "⌘⌥^↓",
        "Start typing to begin a search": "any key",
        "Find": "⌘F",
        "Open tag window": "⌘^T",
        "Close tag window": "Esc",
        "Direct access to add a tag": "⌘⇧T",
        "Toggle a tag for selected to-do": "^shortcut",
        "Filter for a tag": "⌥^shortcut",
        "Select multiple tags": "⌘click any tag",
        "Destroy previous filter": "^Esc",
        "Open a link": "⌘⌥↩"
    }
}
