# coding: utf8
shortcuts = {
    # https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf
    "Visual Studio Code": {
        "Show Command Palette": "⇧⌘",
        "Quick Open, Go to File…": "⌘P",
        "New window/instance": "⇧⌘",
        "Close window/instance": "⌘W",
        "User Settings": "⌘,",
        "Keyboard Shortcuts": "⌘K ⌘S",
        "Cut line (empty selection)": "⌘X",
        "Copy line (empty selection)": "⌘C",
        "Move line down/up": "⌥↓ / ⌥↑",
        "Copy line down/up": "⇧⌥↓ / ⇧⌥↑",
        "Delete line": "⇧⌘K",
        "Insert line below/above": "⌘Enter / ⇧⌘Enter",
        "Jump to matching bracket": "⇧⌘\\",
        "Indent/outdent line": "⌘] / ⌘[",
        "Go to beginning/end of line": "Home / End",
        "Go to beginning/end of file": "⌘↑ / ⌘↓",
        "Scroll line up/down": "⌃PgUp / ⌃PgDn",
        "Scroll page up/down": "⌘PgUp /⌘PgDn",
        "Fold/unfold region": "⌥⌘[ / ⌥⌘]",
        "Fold/unfold all subregions": "⌘K ⌘[ / ⌘K ⌘]",
        "Fold/unfold all regions": "⌘K ⌘0 / ⌘K ⌘J",
        "Add line comment": "⌘K ⌘C",
        "Remove line comment": "⌘K ⌘U",
        "Toggle line comment": "⌘/",
        "Toggle block comment": "⇧⌥A",
        "Toggle word wrap": "⌥Z",
        "Insert cursor": "⌥ + click",
        "Insert cursor above": "⌥⌘↑",
        "Insert cursor below": "⌥⌘↓",
        "Undo last cursor operation": "⌘U",
        "Insert cursor at end of each line selected": "⇧⌥I",
        "Select current line": "⌘L",
        "Select all occurrences of current selection": "⇧⌘L",
        "Select all occurrences of current word": "⌘F2",
        "Expand / shrink selection": "⌃⇧⌘→ / ←",
        "Column (box) selection": "⇧⌥ + drag mouse",
        "Column (box) selection up/down": "⇧⌥⌘↑ / ↓",
        "Column (box) selection left/right": "⇧⌥⌘← / →",
        "Column (box) selection page up": "⇧⌥⌘PgUp",
        "Column (box) selection page down": "⇧⌥⌘PgDn",
        "Find": "⌘F",
        "Replace": "⌥⌘F",
        "Find next/previous": "⌘G / ⇧⌘G",
        "Select all occurrences of Find match": "⌥Enter",
        "Add selection to next Find match": "⌘D",
        "Move last selection to next Find match": "⌘K ⌘D",
        "Trigger suggestion": "⌃Space",
        "Trigger parameter hints": "⇧⌘Space",
        "Format document": "⇧⌥F",
        "Format selection": "⌘K ⌘F",
        "Go to Definition": "F12",
        "Peek Definition": "⌥F12",
        "Open Definition to the side": "⌘K F12",
        "Quick Fix": "⌘.",
        "Show References": "⇧F12",
        "Rename Symbol": "F2",
        "Trim trailing whitespace": "⌘K ⌘X",
        "Change file language": "⌘K M",
        "Show all Symbols": "⌘T",
        "Go to Line...": "⌃G",
        "Go to File...": "⌘P",
        "Go to Symbol...": "⇧⌘O",
        "Show Problems panel": "⇧⌘M",
        "Go to next/previous error or warning": "F8 / ⇧F8",
        "Navigate editor group history": "⌃⇧Tab",
        "Go back/forward": "⌃- / ⌃⇧-",
        "Toggle Tab moves focus": "⌃⇧M",
        "Close editor": "⌘W",
        "Close folder": "⌘K F",
        "Split editor": "⌘\\",
        "Focus into 1st, 2nd, 3rd editor group": "⌘1 / ⌘2 / ⌘3",
        "Focus into previous/next editor group": "⌘K ⌘← / ⌘K ⌘→",
        "Move editor left/right": "⌘K ⇧⌘← / ⌘K ⇧⌘→",
        "Move active editor group": "⌘K ← / ⌘K →",
        "New File": "⌘N",
        "Open File...": "⌘O",
        "Save": "⌘S",
        "Save As...": "⇧⌘S",
        "Save All": "⌥⌘S",
        "Close": "⌘W",
        "Close All": "⌘K ⌘W",
        "Reopen closed editor": "⇧⌘T",
        "Enter Keep preview mode editor open": "⌘K",
        "Open next / previous": "⌃Tab / ⌃⇧Tab",
        "Copy path of active file": "⌘K P",
        "Reveal active file in Explorer": "⌘K R",
        "Show active file in new window/instance": "⌘K O",
        "Toggle full screen": "⌃⌘F",
        "Toggle editor layout (horizontal/vertical)": "⌥⌘0",
        "Zoom in/out": "⌘= / ⇧⌘-",
        "Toggle Sidebar visibility": "⌘B",
        "Show Explorer / Toggle focus": "⇧⌘E",
        "Show Search": "⇧⌘F",
        "Show Source Control": "⌃⇧G",
        "Show Debug": "⇧⌘D",
        "Show Extensions": "⇧⌘X",
        "Replace in files": "⇧⌘H",
        "Toggle Search details": "⇧⌘J",
        "Show Output panel": "⇧⌘U",
        "Open Markdown preview": "⇧⌘V",
        "Open Markdown preview to the side": "⌘K V",
        "Zen Mode (Esc Esc to exit)": "⌘K Z",
        "Toggle breakpoint": "F9",
        "Start/Continue": "F5",
        "Step into/ out": "F11 / ⇧F11",
        "Step over": "F10",
        "Stop": "⇧F5",
        "Show hover": "⌘K ⌘I",
        "Show integrated terminal": "⌃`",
        "Create new terminal": "⌃⇧`",
        "Copy selection": "⌘C",
        "Scroll up/down": "⌘↑ / ↓",
        "Scroll to top/bottom": "⌘Home / End"
    }
}
