# coding: utf8
shortcuts = {
    #https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/xcode_help-command_shortcuts/MenuCommands/MenuCommands014.html
    "XCode" : {
        "New Tab": "⌘T",
        "New Window": "⇧⌘T",
        "New File…": "⌘N",
        "New Target…": "not set",
        "New Project…": "⇧⌘N",
        "New Workspace": "⌃⌘N",
        "New Group": "⌥⌘N",
        "New Group from Selection": "not set",
        "Add Files…": "⌥⌘A",
        "Open…": "⌘O",
        "Open Quickly…": "⇧⌘O",
        "Close Window": "⌘W",
        "Close All Windows": "⌥⌘W",
        "Close Tab": "⇧⌘W",
        "Close Other Tabs": "⌥⇧⌘W",
        "Close Document": "⌃⌘W",
        "Close Workspace": "not set",
        "Save": "⌘S",
        "Save All": "⌥⌘S",
        "Save Multiple…": "⌥⇧⌘S",
        "Save As…": "⇧⌘S",
        "Revert…": "not set",
        "Unlock…": "not set",
        "Show in Finder": "not set",
        "Open with External Editor": "not set",
        "Workspace Settings…": "not set",
        "Commit…": "⌥⌘C",
        "Update…": "⌥⌘X",
        "Update All": "⌃⌥⌘X",
        "Merge…": "not set",
        "Discard Changes…": "not set",
        "Add": "not set",
        "Ignore": "not set",
        "Mark as Resolved": "not set",
        "Refresh Status": "not set",
        "Show Repository Status": "not set",
        "Repositories…": "not set",
        "Create Snapshot…": "⌃⌘S",
        "Page Setup…": "⇧⌘P",
        "Print…": "⌘P",
        "Undo": "⌘Z",
        "Redo": "⇧⌘Z",
        "Cut": "⌘X",
        "Copy": "⌘C",
        "Paste": "⌘V",
        "Paste Special": "⌥⌘V",
        "Paste and Match Style": "⌥⇧⌘V",
        "Duplicate": "⌘D",
        "Delete": "not set",
        "Select All": "⌘A",
        "Find in Workspace…": "⇧⌘F",
        "Find and Replace in Workspace…": "⌥⇧⌘F",
        "Find…": "⌘F",
        "Find and Replace…": "⌥⌘F",
        "Find Next": "⌘G",
        "Find Previous": "⇧⌘G",
        "Use Selection for Find": "⌘E",
        "Use Selection for Replace": "⇧⌘E",
        "Filter in Navigator": "⌥⌘J",
        "Filter in Library": "⌥⌘L",
        "Show Fonts": "⌃⇧⌘T",
        "Bold": "not set",
        "Italics": "not set",
        "Underline": "not set",
        "Show Colors": "not set",
        "Show Spelling and Grammar": "⌘:",
        "Check Document Now": "not set",
        "Check Spelling While Typing": "not set",
        "Check Grammar With Spelling": "not set",
        "Correct Spelling Automatically": "not set",
        "Show Substitutions": "not set",
        "Smart Copy/Paste": "not set",
        "Smart Quotes": "not set",
        "Smart Dashes": "not set",
        "Smart Links": "not set",
        "Data Detectors": "not set",
        "Text Replacement": "not set",
        "Make Upper Case": "not set",
        "Make Lower Case": "not set",
        "Capitalize": "not set",
        "Start Speaking": "not set",
        "Stop Speaking": "not set",
        "Rename": "not set",
        "Extract": "not set",
        "Create Superclass": "not set",
        "Move Up": "not set",
        "Move Down": "not set",
        "Encapsulate": "not set",
        "Project": "⌘1",
        "Symbol": "⌘2",
        "Search": "⌘3",
        "Issue": "⌘4",
        "Debug": "⌘5",
        "Breakpoint": "⌘6",
        "Log": "⌘7",
        "Show Navigator": "⌘0",
        "Standard": "⌘↩",
        "Assistant": "⌥⌘↩",
        "Version": "⌥⇧⌘↩",
        "Show Related Items": "⌃1",
        "Show Previous History": "⌃2",
        "Show Previous Files History": "⌃⌘2",
        "Show Next History": "⌃3",
        "Show Next Files History": "⌃⌘3",
        "Show Top Level Items": "⌃4",
        "Show Group Files": "⌃5",
        "Show Document Items": "⌃6",
        "Show Issues": "⌃7",
        "Add Assistant Editor": "not set",
        "Remove Assistant Editor": "⌃⇧⌘W",
        "Reset Editor": "⌥⇧⌘Z",
        "Assistant Editors on Right": "not set",
        "Assistant Editors on Bottom": "not set",
        "Assistant Editors on Left": "not set",
        "Assistant Editors on Top": "not set",
        "Assistant Editors Stacked Horizontally": "not set",
        "Assistant Editors Stacked Vertically": "not set",
        "Assistant Editors Stacked Horizontally Right to Left": "not set",
        "Assistant Editors Stacked Vertically Bottom to Top": "not set",
        "Show Toolbar Bar": "not set",
        "Show Tab Bar": "not set",
        "Show Debug area": "⇧⌘Y",
        "Reveal in Project Navigator": "⌘L",
        "Open in Adjacent Editor": "⌘<",
        "Go Forward": "⌃⌘⇢",
        "Go Forward in Alternate Editor": "⌃⌥⌘⇢",
        "Go Back": "⌃⌘⇠",
        "Go Back in Alternate Editor": "⌃⌥⌘⇠",
        "Jump to Selection": "⌘J",
        "Jump to Definition": "⇧⌘D",
        "Move Focus To Next Area": "⌥⌘K",
        "Move Focus To Previous Area": "⌥⇧⌘K",
        "Jump to Next Object with Clipped Content": "not set",
        "Jump to Previous Object with Clipped Content": "not set",
        "Jump to Counterpart": "⌃⌘⇡",
        "Jump To…": "⇧⌘J",
        "Jump to Next Placeholder": "⌃/",
        "Jump to Previous Placeholder": "⌃?",
        "Jump to Next Issue": "⌘'",
        "Jump and Fix Next Issue": "⌃⌘'",
        "Jump to Previous Issue": "⌘\"",
        "Jump and Fix Previous Issue": "⌃⌘\"",
        "Show Grid": "not set",
        "Show Page Breaks": "not set",
        "Add Entity": "not set",
        "Add Fetch Request": "not set",
        "Add Configuration": "not set",
        "Add Attribute": "⌃⌘A",
        "Add Fetched Property": "not set",
        "Add Relationship": "⌃⌘R",
        "Import…": "not set",
        "Create NSManagedObject subclass…": "not set",
        "Explore Documentation": "not set",
        "Search Documentation": "not set",
        "Documentation Bookmarks": "not set",
        "Zoom In": "not set",
        "Zoom Out": "not set",
        "Actual Size": "not set",
        "Add Bookmark": "not set",
        "History": "not set",
        "Show Bounds Rectangles": "not set",
        "Show Layout Rectangles": "not set",
        "Snap to Guides": "not set",
        "Live Autoresizing": "not set",
        "Align Left Edges": "⌘[",
        "Align Right Edges": "⌘]",
        "Align Top Edges": "not set",
        "Align Bottom Edges": "not set",
        "Align Horizontal Centers": "not set",
        "Align Vertical Centers": "not set",
        "Align Baselines": "not set",
        "Align Horizontal Center In Container": "not set",
        "Align Vertical Center In Container": "not set",
        "Send to Front": "not set",
        "Send to Back": "not set",
        "Send Forward": "not set",
        "Send Backward": "not set",
        "Unembed": "not set",
        "Size to Fit": "⌘=",
        "Add Horizontal Guide": "⌘_",
        "Add Vertical Guide": "⌘|",
        "Reveal in Document Structure": "not set",
        "Simulate Document": "not set",
        "Automatically Resize": "not set",
        "Zoom In": "not set",
        "Zoom Out": "not set",
        "Actual Size": "not set",
        "Single Page": "not set",
        "Single Page Continuous": "not set",
        "Two Pages": "not set",
        "Two Pages Continuous": "not set",
        "Next Page": "⌥⌘⇣",
        "Previous Page": "⌥⌘⇡",
        "Insert Page Break": "not set",
        "Insert Line Break": "not set",
        "Insert Paragraph Break": "not set",
        "Show Ruler": "not set",
        "Add Link…": "not set",
        "Allow Hyphenation": "not set",
        "Make Text Bigger": "⌘+",
        "Make Text Smaller": "⌘-",
        "Show Completions": "⌃\"",
        "Edit All in Scope": "⌃⌘E",
        "Fix All in Scope": "⌃⌘F",
        "Show Issue": "not set",
        "Show All Issues": "⌃⌘M",
        "All Issues": "not set",
        "Errors Only": "not set",
        "Balance Delimiter": "not set",
        "Re-Indent": "not set",
        "Shift Right": "⌘]",
        "Shift Left": "⌘[",
        "Move Line Up": "⌥⌘[",
        "Move Line Down": "⌥⌘]",
        "Comment Selection": "⌘/",
        "Fold": "⌥⌘⇠",
        "Unfold": "⌥⌘⇢",
        "Unfold All": "not set",
        "Fold Methods & Functions": "⌥⇧⌘⇠",
        "Unfold Methods & Functions": "⌥⇧⌘⇢",
        "Fold Comment Blocks": "⌃⇧⌘⇠",
        "Unfold Comment Blocks": "⌃⇧⌘⇢",
        "Focus Follows Selection": "not set",
        "Show Invisibles": "not set",
        "Add Target…": "not set",
        "Overwrite Mode": "⌥⇧⌘O",
        "About Xcode": "not set",
        "Preferences…": "⌘,",
        "Hide Xcode": "⌘H",
        "Hide Others": "⌥⌘H",
        "Show All": "not set",
        "Quit Xcode": "⌘Q",
        "Minimize": "⌘M",
        "Zoom": "not set",
        "Select Next Tab": "⌘}",
        "Select Previous Tab": "⌘{",
        "Welcome to Xcode": "⇧⌘1",
        "Organizer": "⇧⌘2",
        "Bring All to Front": "not set",
        "Xcode Help": "not set",
        "Xcode 4 Transition Guide": "not set",
        "Quick Help": "⌃⌘?",
        "Search Documentation for Selected Text": "⌃⌥⌘/",
        "Developer Documentation": "⌥⌘?",
        "Run": "⌘R",
        "Run…": "⌥⌘R",
        "Test": "⌘T",
        "Test…": "⌥⌘T",
        "Profile": "⌘I",
        "Profile…": "⌥⌘I",
        "Analyze": "⌃⌘B",
        "Analyze…": "⌃⌥⌘B",
        "Archive": "not set",
        "Build For Running": "⇧⌘R",
        "Build For Testing": "⇧⌘U",
        "Build for Profiling": "⇧⌘I",
        "Build for Archiving": "not set",
        "Run Without Building": "⌃⌘R",
        "Test Without Building": "⌃⌘U",
        "Profile Without Building": "⌃⌘I",
        "Build": "⌘B",
        "Clean": "⇧⌘K",
        "Clean Build Folder…": "⌥⇧⌘K",
        "Stop": "⌘.",
        "Pause": "⌃⌘Y",
        "Step Into": "F7",
        "Step Over": "F6",
        "Step Out": "F8",
        "Step Into Thread": "⌃⇧F7",
        "Step Into Instruction": "⌃F7",
        "Step Over Thread": "⌃⇧F6",
        "Step Over Instruction": "⌃F6",
        "Add Breakpoint at Current Line": "⌘\"",
        "Activate/Deactivate Breakpoints": "⌘Y",
        "Shared Libraries...": "not set",
        "Clear Console": "⌘K",
        "Window Behavior: Normal": "not set",
        "Xcode Behind": "not set",
        "Xcode In Front": "not set",
        "Edit Scheme…": "⌘<",
        "New Scheme…": "not set",
        "Manage Schemes…": "not set",
    }
}
