# coding: utf8

shortcuts = {
    "Xcode Menu Commands": {
        "Preferences…": "⌘,",
        "Hide Xcode": "⌘H",
        "Hide Others": "⌥⌘H",
        "Quit Xcode": "⌘Q",
    },
    "File Menu Commands": {
        "New Tab": "⌘T",
        "New Window": "⇧⌘T",
        "New File…": "⌘N",
        "New Project…": "⇧⌘N",
        "New Workspace": "⌃⌘N",
        "New Group": "⌥⌘N",
        "Add Files…": "⌥⌘A",
        "Open…": "⌘O",
        "Open Quickly…": "⇧⌘O",
        "Close Window": "⌘W",
        "Close All Windows": "⌥⌘W",
        "Close Tab": "⇧⌘W",
        "Close Other Tabs": "⌥⇧⌘W",
        "Close Document": "⌃⌘W",
        "Save": "⌘S",
        "Save All": "⌥⌘S",
        "Save Multiple…": "⌥⇧⌘S",
        "Save As…": "⇧⌘S",
        "Commit…": "⌥⌘C",
        "Update…": "⌥⌘X",
        "Update All": "⌃⌥⌘X",
        "Create Snapshot…": "⌃⌘S",
        "Page Setup…": "⇧⌘P",
        "Print…": "⌘P",
    },
    "Edit Menu Commands": {
        "Undo": "⌘Z",
        "Redo": "⇧⌘Z",
        "Cut": "⌘X",
        "Copy": "⌘C",
        "Paste": "⌘V",
        "Paste Special": "⌥⌘V",
        "Paste and Match Style": "⌥⇧⌘V",
        "Duplicate": "⌘D",
        "Select All": "⌘A",
        "Find in Workspace…": "⇧⌘F",
        "Find and Replace in Workspace…": "⌥⇧⌘F",
        "Find…": "⌘F",
        "Find and Replace…": "⌥⌘F",
        "Find Next": "⌘G",
        "Find Previous": "⇧⌘G",
        "Use Selection for Find": "⌘E",
        "Use Selection for Replace": "⇧⌘E",
        "Filter in Navigator": "⌥⌘J",
        "Filter in Library": "⌥⌘L",
        "Show Fonts": "⌃⇧⌘T",
        "Show Spelling and Grammar": "⌘:",
    },
    "View Menu Commands": {
        "Project": "⌘1",
        "Symbol": "⌘2",
        "Search": "⌘3",
        "Issue": "⌘4",
        "Debug": "⌘5",
        "Breakpoint": "⌘6",
        "Log": "⌘7",
        "Show Navigator": "⌘0",
        "Standard": "⌘↩",
        "Assistant": "⌥⌘↩",
        "Version": "⌥⇧⌘↩",
        "Show Previous History": "⌃2",
        "Show Previous Files History": "⌃⌘2",
        "Show Next History": "⌃3",
        "Show Next Files History": "⌃⌘3",
        "Show Top Level Items": "⌃4",
        "Show Group Files": "⌃5",
        "Show Document Items": "⌃6",
        "Show Issues": "⌃7",
        "Remove Assistant Editor": "⌃⇧⌘W",
        "Reset Editor": "⌥⇧⌘Z",
        "Show Debug area": "⇧⌘Y",
    },
    "Navigate Menu Commands": {
        "Reveal in Project Navigator": "⌘L",
        "Open in Adjacent Editor": "⌘<",
        "Go Forward": "⌃⌘→",
        "Go Forward in Alternate Editor": "⌃⌥⌘→",
        "Go Back": "⌃⌘←",
        "Go Back in Alternate Editor": "⌃⌥⌘←",
        "Jump to Selection": "⌘J",
        "Jump to Definition": "⇧⌘D",
        "Move Focus To Next Area": "⌥⌘K",
        "Move Focus To Previous Area": "⌥⇧⌘K",
        "Jump To…": "⇧⌘J",
        "Jump to Next Issue": "⌘'",
        "Jump and Fix Next Issue": "⌃⌘'",
        "Jump to Previous Issue": "⌘\"",
        "Jump and Fix Previous Issue": "⌃⌘\"",
    },
    "Editor Menu Commands": {
        "Add Attribute": "⌃⌘A",
        "Add Relationship": "⌃⌘R",
        "Align Left Edges": "⌘[",
        "Align Right Edges": "⌘]",
        "Size to Fit": "⌘=",
        "Add Horizontal Guide": "⌘_",
        "Add Vertical Guide": "⌘|",
        "Next Page": "⌥⌘↓",
        "Previous Page": "⌥⌘↑",
        "Show Completions": "⌃\\",
        "Edit All in Scope": "⌃⌘E",
        "Fix All in Scope": "⌃⌘F",
        "Show All Issues": "⌃⌘M",
        "Shift Right": "⌘]",
        "Shift Left": "⌘[",
        "Move Line Up": "⌥⌘[",
        "Move Line Down": "⌥⌘]",
        "Comment Selection": "⌘/",
        "Fold": "⌥⌘←",
        "Unfold": "⌥⌘→",
        "Fold Methods & Functions": "⌥⇧⌘←",
        "Unfold Methods & Functions": "⌥⇧⌘→",
        "Fold Comment Blocks": "⌃⇧⌘←",
        "Unfold Comment Blocks": "⌃⇧⌘→",
        "Overwrite Mode": "⌥⇧⌘O",
    },
    "Product Menu Commands": {
        "Run": "⌘R",
        "Run…": "⌥⌘R",
        "Test": "⌘T",
        "Test…": "⌥⌘T",
        "Profile": "⌘I",
        "Profile…": "⌥⌘I",
        "Analyze": "⌃⌘B",
        "Analyze…": "⌃⌥⌘B",
        "Build For Running": "⇧⌘R",
        "Build For Testing": "⇧⌘U",
        "Build for Profiling": "⇧⌘I",
        "Run Without Building": "⌃⌘R",
        "Test Without Building": "⌃⌘U",
        "Profile Without Building": "⌃⌘I",
        "Build": "⌘B",
        "Clean": "⇧⌘K",
        "Clean Build Folder…": "⌥⇧⌘K",
        "Stop": "⌘.",
        "Pause": "⌃⌘Y",
        "Add Breakpoint at Current Line": "⌘\\",
        "Activate Breakpoints": None,
        "Deactivate Breakpoints": "⌘Y",
        "Clear Console": "⌘K",
        "Edit Scheme…": "⌘<",
        "New Scheme…": None,
    },
    "Window Menu Commands": {
        "Minimize": "⌘M",
        "Select Next Tab": "⌘}",
        "Select Previous Tab": "⌘{",
        "Welcome to Xcode": "⇧⌘1",
        "Organizer": "⇧⌘2",
    },
    "Help Menu Commands": {
        "Quick Help": "⌃⌘?",
        "Search Documentation for Selected Text": "⌃⌥⌘/",
        "Developer Documentation": "⌥⌘?",
    }
}

page_url = "https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/xcode_help-command_shortcuts/MenuCommands/MenuCommands014.html"