# coding: utf8


shortcuts = {
    "Google Chrome":{ #https://support.google.com/chrome/answer/157179?hl=en
        "Open a new window":"⌘n",
        "Open a new window in Incognito mode":"⌘t",
        "Open a new tab, and jump to it":"⌘t",
        "Reopen the last closed tab, and jump to it":"⌘⇧t",
        "Jump to the next open tab":"⌘⌥→",
        "Jump to the previous open tab":"⌘⌥←",
        "Jump to a specific tab (1-9)":"⌘[NUM]",
        "Jump to the last tab":"⌘9",
        "Open the previous page in your browsing history for the current tab":"⌘[ or ⌘←",
        "Open the next page in your browsing history for the current tab":"⌘] or ⌘→",
        "Close the current tab or pop-up":"⌘w",
        "Close all open tabs and the browser":"⌘⇧w",
        "Minimize the window":"⌘m",
        "Hide Google Chrome":"⌘h",
        "Quit Google Chrome":"⌘q",
        "Developer Tools":"⌘⌥i",
        "View Source":"⌘⌥U",
        "Always show toolbar in full screen":"⌘⇧F",
        "Show or hide the Bookmarks Bar":"⌘⇧b",
        "Open the Bookmark Manager:":"⌘⌥b",
        "Open the Settings page in a new tab":"⌘,",
        "Open the History page in a new tab":"⌘y",
        "Open the Downloads page in a new tab":"⌘⇧j",
        "Open the Find Bar to search the current page":"⌘f",
        "Jump to the next match to your Find Bar search":"⌘g",
        "Jump to the previous match to your Find Bar search":"⌘⇧g",
        "When Find Bar is open, search for selected text":"⌘e",
        "Open the Clear Browsing Data options":"⌘⇧⌫",
        "Log in as a different user or browse as a Guest":"⌘⇧m",
        "Search with your default search engine":"Type a search term + ↩",
        "Search using a different search engine":"Type a search engine name + Tab",
        "Add www. and .com to a site name, and open it in the current tab":"Type a site name + ⌃↩",
        "Add www. and .com to a site name, and open it in a new tab":"Type a site name + ⌃⇧↩",
        "Open the website in a new background tab":"Type a web address + ⌘↩",
        "Jump to the address bar":"⌘l",
        "Remove predictions from your address bar":"↓ to highlight + ⇧fn⌫",
        "Open options to print the current page":"⌘p",
        "Open options to save the current page":"⌘s",
        "Open the Page Setup dialog ":"⌘⌥p",
        "Email your current page":"⌘⇧i",
        "Reload your current page":"⌘r",
        "Reload your current page, ignoring cached content":"⌘⇧r",
        "Stop the page loading":"Esc",
        "Browse clickable items moving forward":"Tab",
        "Browse clickable items moving backward":"⇧Tab",
        "Open a file from your computer in Google Chrome":"⌘o + Select a file",
        "Display non-editable HTML source code for the current page":"⌘⌥u",
        "Open the JavaScript Console":"⌘⌥j",
        "Save your current webpage as a bookmark":"⌘d",
        "Save all open tabs as bookmarks in a new folder":"⌘⇧d",
        "Turn full-screen mode on or off":"⌘⌃f",
        "Make everything on the page bigger - zoom in":"⌘+",
        "Make everything on the page smaller - zoom out":"⌘-",
        "Return everything on the page to the default size":"⌘0",
        "Scroll down a webpage, a screen at a time":"Space",
        "Scroll up a webpage, a screen at a time":"⇧Space",
        "Search the web":"⌘⌥f",
        "Move your cursor to the front of the previous word in a text field ":"⌥←",
        "Move your cursor to the back of the next word in a text field":"⌥→",
        "Delete the previous word in a text field":"⌥⌫",
        "Open your home page in the current tab":"⌘⇧h",
        "Open a link in a current tab (mouse only)":"Drag a link to a tab",
        "Open a link in new background tab":"⌘ + Click a link",
        "Open a link, and jump to it":"⌘⇧ + Click a link",
        "Open a link, and jump to it (mouse only)":"Drag a link to a blank area of the tab strip",
        "Open a link in a new window":"⇧ + Click a link",
        "Open a tab in a new window (mouse only)":"Drag the tab out of the tab strip",
        "Move a tab to a current window (mouse only)":"Drag the tab into an existing window",
        "Return a tab to its original position":"Press Esc while dragging",
        "Save the current webpage as a bookmark":"Drag the web address to the Bookmarks Bar",
        "Download the target of a link":"⌥ + Click a link",
        "Display your browsing history":"Right-click Back ⇦ or Next ⇨, or click & hold Back ⇦ or Next ⇨",
        "Increase the window to full height":"Double-click a blank area of the tab strip"
    },
    "Reddit Enhancement Suite":{ #⇧/
        "Show help for keyboard shortcuts":"⇧/",
        "Launch RES command line":"/",
        "Launch filter command line":"H",
        "Move up to the previous link or comment in flat lists":"K",
        "Move down to the next link or comment in flat lists":"J",
        "Move to top of list (on link pages)":"⇧K",
        "Move to bottom of list (on link pages)":"⇧J",
        "Follow link (link pages only)":"↩",
        "Follow link in new tab (link pages only)":"⇧↩",
        "Toggle expando (image/text/video)":"X",
        "Increase the size of image(s) in the highlighted post area":"=",
        "Decrease the size of image(s) in the highlighted post area":"-",
        "Increase the size of image(s) in the highlighted post area (finer control)":"⇧=",
        "Decrease the size of image(s) in the highlighted post area (finer control)":"⇧-",
        "Removes the height restriction of image(s) in the highlighted post area":"⇧→",
        "Move the image(s) in the highlighted post area up":"⌃↑",
        "Move the image(s) in the highlighted post area down":"Move the image(s) in the highlighted post area down.",
        "Move the image(s) in the highlighted post area left":"⌃← ",
        "Move the image(s) in the highlighted post area right":"⌃→",
        "View the previous image of an inline gallery":"[",
        "View the next image of an inline gallery":"]",
        "Toggle 'show images' button":"⇧X",
        "View comments for link (⇧ opens them in a new tab)":"C",
        "View comments for link in a new tab":"⇧C",
        "View link and comments in new tabs.":"L",
        "View link and comments in new background tabs.":"⇧L",
        "Upvote selected link or comment (or remove the upvote).":"A",
        "Downvote selected link or comment (or remove the downvote).":"Z",
        "Upvote selected link or comment (but don't remove the upvote).":"⇧A",
        "Downvote selected link or comment (but don't remove the downvote).":"⇧Z",
        "Save the current post to your reddit account (not preserved if deleted or edited)":"S",
        "Save the current comment with RES (preserved locally)":"S",
        "Go to subreddit of selected link (link pages only)":"R",
        "Go to subreddit of selected link in a new tab (link pages only).":"⇧R ",
        "Enter 'goMode' (before using 'go to' shortcuts).":"G",
        "Go to inbox":"G then I",
        "Go to inbox in a new tab.":"G then ⇧I",
        "Go to modmail.":"G then M",
        "Go to modmail in a new tab.":"G then ⇧M",
        "Go to profile.":"G then U",
        "Go to profile in a new tab.":"G then ⇧U",
        "Go to front page.":"G then F ",
        "Go to /r/all.":"⌥A",
        "Go to subreddit front page.":"⇧F",
        "Go to a random subreddit.":"⌥Y",
        "Go to next page (link list pages only).":"G then N",
        "Go to previous page (link list pages only).":"G then P",
        "Focuses the cursor in the search box.":"⌥/",
    },
    "Sublime Text":{ #http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html
        "Command Pallete":"⌘⇧P",
        "Python Console":"⌃`",
        "Toggle Sidebar":"⌘K, ⌘B",
        "Toggle Full­scr­een":"⌃⌘F",
        "Toggle Dist­raction Free Mode":"⌃⇧⌘F",
        "Show scope in status bar":"⌃⇧P",
        "Cut line":"⌘X",
        "Insert line after":"⌘↩",
        "Insert line before":"⌘⇧↩",
        "Move line/selection up":"⌘⌃↑",
        "Move line/selection down":"⌘⌃↓",
        "Select line - Repeat to select next lines":"⌘L",
        "Select word - Repeat to select next occurrence":"⌘D",
        "Select all occurrences of current selection":"⌃⌘G",
        "Extra cursor on the line above":"⌃⇧↑",
        "Extra cursor on the line below":"⌃⇧↓",
        "Jump to closing parentheses Repeat to jump to opening parentheses":"⌃M",
        "Select all contents of the current parentheses":"⌃⇧M",
        "Move to beginning of line":"⌃A",
        "Move to beginning of text on line":"⌘Left",
        "Move to end of line":"⌃E, ⌘Right",
        "Delete from cursor to end of line":"⌘K, ⌘K",
        "Delete from cursor to start of line":"⌘K⌫",
        "Indent current line(s)":"⌘]",
        "Un-indent current line(s)":"⌘[",
        "Duplicate line(s)":"⌘⇧D",
        "Join line below to the end of the current line":"⌘J",
        "Comment/un-comment current line":"⌘/",
        "Block comment current selection":"⌘⌥/",
        "Redo, or repeat last keyboard shortcut command":"⌘Y",
        "Paste and indent correctly":"⌘⇧V",
        "Select next auto-complete suggestion":"⌃Space",
        "Soft undo; jumps to your last change before undoing change when repeated":"⌃U",
        "Column selection up":"⌃⇧↑",
        "Column selection down":"⌃⇧↓",
        "Wrap Selection in html tag":"⌃⇧W",
        "Delete current line of cursor":"⌃⇧K",
        "Quick-open files by name":"⌘P or ⌘T",
        "Goto symbol":"⌘R",
        "Goto line in current file":"⌃G",
        "Goto word in current file":"",
        "Find":"⌘F",
        "Replace":"⌘⌥F",
        "Find in files":"⌘⇧F",
        "Scroll down one page":"⌃V",
        "Center current line vertically in page":"⌃L",
        "Scroll to end of file":"⌘↓",
        "Scroll to start of file":"⌘↑",
        "Open last closed tab":"⌘⇧t",
        "Jump to tab in current group where num is 1-9":"⌘[NUM]",
        "Jump to 10th tab in current group":"⌘0",
        "Cycle left through tabs":"⌘⇧[",
        "Cycle right through tabs":"⌘⇧]",
        "Cycle up through recent tabs":"^Tab",
        "Cycle down through recent tabs":"⇧^Tab",
        "Revert view to single column":"⌘⌥1",
        "Split view into two columns":"⌘⌥2",
        "Split view into three columns":"⌘⌥3",
        "Split view into four columns":"⌘⌥4",
        "Set view to grid (4 groups)":"⌘⌥5",
        "Jump to group where num is 1-4":"⌃[NUM]",
        "Move file to specified group where num is 1-4":"⌃⇧[NUM]",
        "Toggle bookmark":"⌘F2",
        "Next bookmark":"F2",
        "Previous bookmark":"⇧F2",
        "Clear bookmarks":"⇧⌘F2",
        "Transform to Uppercase":"⌘K, ⌘U",
        "Clip text upwards / downwards":"⌘⌃↑, ⌘⌃↓",
    },
    "Vintage Sublime":{ #https://github.com/sublimehq/Vintage/blob/master/Default%20(OSX).sublime-keymap
        "Exit insert mode":"⌃c or Esc",
        "Exit visual mode":"⌃c or Esc",
        "Vi Cancel current action":"⌃c",
        "Move back to beginning of word":"⌥←",
        "Move back to end of word":"⌃←",
        "Move forward to beginning of word":"⌥→",
        "Move forward to end of word":"⌃→",
        "up":"k",
        "down":"j",
        "left":"h",
        "right":"l",
        "Move cursor to end of line":"⌘right",
        "Move cursor to first non-white space char":"⌘left",
        "Move to beginning of file":"⌘↑",
        "Move to end of file":"⌘↓",
        "page up":"⌃↑",
        "page down":"⌃↓",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "replace a single character":"r",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":"."
    },
    "Vim":{ #https://vim.rtorr.com/
        "open help for keyword":":help keyword",
        "open file":":o file",
        "save file as":":saveas file",
        "close current pane":":close",
        "open man page for word under the cursor":"K",
        "move cursor left":"h",
        "move cursor down":"j",
        "move cursor up":"k",
        "move cursor right":"l",
        "move to top of screen":"H",
        "move to middle of screen":"M",
        "move to bottom of screen":"L",
        "jump forwards to the start of a word":"w",
        "jump forwards to the start of a word (words can contain punctuation)":"W",
        "jump forwards to the end of a word":"e",
        "jump forwards to the end of a word (words can contain punctuation)":"E",
        "jump backwards to the start of a word":"b",
        "jump backwards to the start of a word (words can contain punctuation)":"B",
        "move to matching character (default supported pairs: '()', '{}', '[]')":"%",
        "jump to the start of the line":"0",
        "jump to the first non-blank character of the line":"^",
        "jump to the end of the line":"$",
        "jump to the end of the line":"$",
        "jump to the last non-blank character of the line":"g_",
        "go to the first line of the document":"gg",
        "go to the last line of the document":"G",
        "go to line 5":"5G",
        "jump to next occurrence of character x":"fx",
        "jump to before next occurrence of character x":"tx",
        "jump to previous occurence of character x":"Fx",
        "jump to after previous occurence of character x":"Tx",
        "repeat previous f, t, F or T movement":";",
        "repeat previous f, t, F or T movement, backwards":",",
        "jump to next paragraph (or function/block, when editing code)":"}",
        "jump to previous paragraph (or function/block, when editing code)":"{",
        "center cursor on screen":"zz",
        "move back one full screen":"⌃b",
        "move forward one full screen":"⌃f",
        "move forward 1/2 a screen":"⌃d",
        "move back 1/2 a screen":"⌃u",
        "insert before the cursor":"i",
        "insert at the beginning of the line":"I",
        "insert (append) after the cursor":"a",
        "insert (append) at the end of the line":"A",
        "append (open) a new line below the current line":"o",
        "append (open) a new line above the current line":"O",
        "insert (append) at the end of the word":"ea",
        "exit insert/visual mode":"Esc",
        "replace a single character":"r",
        "join line below to the current one":"J",
        "change (replace) entire line":"cc",
        "change (replace) to the end of the word":"cw",
        "change (replace) to the end of the line":"c$",
        "delete character and substitute text":"s",
        "delete line and substitute text (same as cc)":"S",
        "transpose two letters (delete and paste)":"xp",
        "undo":"u",
        "redo":"⌃r",
        "repeat last command":".",
        #Marking text (visual mode) stopped at
        "start visual mode, mark lines, then do a command (like y-yank)":"v",
        "start linewise visual mode":"V",
        "visual - move to other end of marked area":"o",
        "start visual block mode":"^v",
        "visual - move to other corner of block":"O",
        "visual - mark a word":"aw",
        "visual - a block with ()":"ab",
        "visual - inner block with ()":"ib",
        "visual - inner block with {}":"iB",
        "shift text right":">",
        "shift text left":"<",
        "yank (copy) marked text":"y",
        "delete marked text":"d",
        "switch case":"~",
        "show registers content":":reg",
        "yank into register x":"\"xy",
        "paste contents of register x":"\"xp",
        "list of marks":":marks",
        "set current position for mark A":"ma",
        "jump to position of mark A":"'a",
        "yank text to position of mark A":"y`a",
        "record macro a":"qa",
        "stop recording macro":"q",
        "run macro a":"@a",
        "rerun last run macro":"@@",
        "yank (copy) a line":"yy",
        "yank (copy) 2 lines":"2yy",
        "yank (copy) the characters of the word from the cursor position to the start of the next word":"yw",
        "yank (copy) to end of line":"y$",
        "put (paste) the clipboard after cursor":"p",
        "put (paste) before cursor":"P",
        "delete (cut) a line":"dd",
        "delete (cut) 2 lines":"2dd",
        "delete (cut) the characters of the word from the cursor position to the start of the next word":"dw",
        "delete (cut) to the end of the line":"D",
        "delete (cut) to the end of the line":"d$",
        "delete (cut) character":"x",
        "write (save) the file, but don't exit":":w",
        "write out the current file using sudo":":w !sudo tee %",
        "write (save) and quit":":wq or :x or ZZ",
        "quit (fails if there are unsaved changes)":":q",
        "quit and throw away unsaved changes":":q! or ZQ",
        "write (save) and quit on all tabs":":wqa",
        "search for pattern in multiple files":":vimgrep /pattern/ {file}",
        "search - jump to the next match":":cn",
        "search - jump to the previous match":":cp",
        "search - open a window containing the list of matches":":copen",
        "edit a file in a new buffer":":e file",
        "go to the next buffer":":bnext or :bn",
        "go to the previous buffer":":bprev or :bp",
        "delete a buffer (close a file)":":bd",
        "list all open buffers":":ls",
        "open a file in a new buffer and split window":":sp file",
        "open a file in a new buffer and vertically split window":":vsp file",
        "split window":"Ctrl + ws",
        "switch windows":"Ctrl + ww",
        "quit a window":"Ctrl + wq",
        "split window vertically":"Ctrl + wv",
        "move cursor to the left window (vertical split)":"Ctrl + wh",
        "move cursor to the right window (vertical split)":"Ctrl + wl",
        "move cursor to the window below (horizontal split)":"Ctrl + wj",
        "move cursor to the window above (horizontal split)":"Ctrl + wk",
        "open a file in a new tab":":tabnew or :tabnew file",
        "move the current split window into its own tab":"Ctrl + wT",
        "move to the next tab":"gt or :tabnext or :tabn",
        "move to the previous tab":"gT or :tabprev or :tabp",
        "move to tab number #":"#gt",
        "move current tab to the #th position (indexed from 0)":":tabmove #",
        "close the current tab and all its windows":":tabclose or :tabc",
        "close all tabs except for the current one":":tabonly or :tabo",
        "command - run the command on all tabs (e.g. :tabdo q - closes all opened tabs)":":tabdo"
    },
    "iTerm2":{
        #factory default key mappings in preferences
        #http://www.ifdattic.com/iterm-shortcut-keys/
        "New Tab":"⌘T",
        "Previous Tab":"⌘←",
        "Next Tab":"⌘→",
        "Close Tab":"⌘w",
        "Move Tab Right":"⇧⌘→",
        "Move Tab Left":"⇧⌘←",
        "Split Vertically with Current Profile":"⌘D",
        "Split Horizontally with Current Profile":"⇧⌘D",
        "Next Pane":"⌘]",
        "Previous Pane":"⌘[",
        "Select Pane Above":"⌥⌘↑",
        "Select Pane Below":"⌥⌘↓",
        "Select Pane Left":"⌥⌘←",
        "Select Pane Right":"⌥⌘→",
        "Clear Window":"^L",
        "Clear buffer":"⌘K",
        "Scroll One Line Up":"⌘↑",
        "Scroll One Line Down":"⌘↓",
        "Find":"⌘F",
        "Make Text Bigger":"⌘+",
        "Make Text Normal Size":"⌘0",
        "Make Text Smaller":"⌘-",
        "Go Left One Word":"⌥←",
        "Go Right One Word":"⌥→",
        "Clear line":"^u",
        "Highlight cursour":"⌘/",
        "Scroll To Top":"⌘Home",
        "Scroll To End":"⌘End",
        "Scroll One Page Up":"⌘Page Up or ⇧Page Up",
        "Scroll One Page Down":"⌘Page Down or ⇧Page Down",
    },
    "zshell":{
        #https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet
        "Create a new tab in the current directory (macOS - requires enabling access for assistive devices under System Preferences).":"tabs",
        "Create a new directory and change to it, will create intermediate directories as required.":"take",
        "Extract an archive (supported types: tar.{bz2,gz,xz,lzma}, bz2, rar, gz, tar, tbz2, tgz, zip, Z, 7z).":"x / extract",
        "Get a list of the top 20 commands and how many times they have been run.":"zsh_stats",
        "Uninstall Oh-my-zsh.":"uninstall_oh_my_zsh",
        "Upgrade Oh-my-zsh.":"upgrade_oh_my_zsh",
        "Uptake new changes":"source ~/.zshrc",
        "list all aliases":"alias",
        "cd ..":"..",
        "cd ../..":"...",
        "cd ../../..":"....",
        "cd ../../../..":".....",
        "cd /":"/",
        "cd ~":"~",
        "switch to directory number n (2-9)":"cd +n",
        "tab-completeion ls":"ls (tab)",
        "tab-completeion cap":"cap (tab)",
        "tab-completeion rake":"rake (tab)",
        "tab-completeion ssh":"ssh (tab)",
        "tab-completeion sudo unmount":"sudo unmount(tab)",
        "tab-completeion kill":"kill (tab)",
        "tab-completeion unrar":"unrar (tab)",
        "Dynamic access to current branch name with the current_branch function":"git pull origin $(current_branch)",
        "Dynamic access to current branch name with the current_branch function":"grb publish $(current_branch) origin",
        "git":"g",
        "git add":"ga",
        "git add --all":"gaa",
        "git add --patch":"gapa",
        "git branch":"gb",
        "git branch -a":"gba",
        "git branch -d":"gbd",
        "git blame -b -w":"gbl",
        "git branch --no-merged":"gbnm",
        "git branch --remote":"gbr",
        "git bisect":"gbs",
        "git bisect bad":"gbsb",
        "git bisect good":"gbsg",
        "git bisect reset":"gbsr",
        "git bisect start":"gbss",
        "git commit -v":"gc",
        "git commit -v --amend":"gc!",
        "git commit -v -a":"gca",
        "git commit -v -a --amend":"gca!",
        "git commit -v -a --no-edit --amend":"gcan!",
        "git commit -v -a -s --no-edit --amend":"gcans!",
        "git commit -a -m":"gcam",
        "git commit -s -m":"gcsm",
        "git checkout -b":"gcb",
        "git config --list":"gcf",
        "git clone --recursive":"gcl",
        "git clean -fd":"gclean",
        "git reset --hard ^^ git clean dfx":"gpristine",
        "git checkout master":"gcm",
        "git checkout develop":"gcd",
        "git commit -m":"gcmsg",
        "git checkout":"gco",
        "git shortlog -sn":"gcount",
        "git cherry-pick":"gcp",
        "git cherry-pick --abort":"gcpa",
        "git cherry-pick --continue":"gcpc",
        "git commit -S":"gcs",
        "git diff":"gd",
        "git diff --cached":"gdca",
        "git describe --tags `git rev-list --tags --max-count=1`":"gdct",
        "git diff-tree --no-commit-id --name-only -r":"gdt",
        "git diff --word-diff":"gdw",
        "git fetch":"gf",
        "git fetch --all --prune":"gfa",
        "git fetch origin":"gfo",
        "git gui citool":"gg",
        "git gui citool --amend":"gga",
        "git pull origin $(current_branch) && git push origin $(current_branch)":"ggpnp",
        "git pull origin $(current_branch)":"ggpull",
        "git pull origin $(current_branch)":"ggl",
        "git pull --rebase origin $(current_branch)":"ggpur",
        "git pull upstream master":"glum",
        "git push origin $(current_branch)":"ggpush",
        "git push origin $(current_branch)":"ggp",
        "git branch --set-upstream-to=origin/$(current_branch)":"ggsup",
        "git update-index --assume-unchanged":"gignore",
        "git ls-files -v | grep \"^[[:lower:]]\"":"gignored",
        "git svn dcommit && git push github master:svntrunk":"git-svn-dcommit-push",
        "gitk --all --branches":"gk",
        "git pull":"gl",
        "git log --stat --max-count = 10":"glg",
        "git log --graph --max-count = 10":"glgg",
        "git log --graph --decorate --all":"glgga",
        "git log --oneline --decorate --color":"glo",
        "git log --oneline --decorate --color --graph":"glog",
        "_git_log_prettily (git log --pretty=$1)":"glp",
        "git merge":"gm",
        "git mergetool --no-prompt":"gmt",
        "git push":"gp",
        "git push origin --all && git push origin --tags":"gpoat",
        "git remote":"gr",
        "git rebase --abort":"grba",
        "git rebase --continue":"grbc",
        "git rebase --skip":"grbs",
        "git rebase -i":"grbi",
        "git reset HEAD":"grh",
        "git reset HEAD --hard":"grhh",
        "git remote rename":"grmv",
        "git remote remove":"grrm",
        "git remote set-url":"grset",
        "cd $(git rev-parse --show-toplevel || echo \".\")":"grt",
        "git remote update":"grup",
        "git remote -v":"grv",
        "git svn dcommit":"gsd",
        "git show --pretty = short --show-signature":"gsps",
        "git svn rebase":"gsr",
        "git status -s":"gss",
        "git status":"gst",
        "git stash save":"gsta",
        "git stash apply":"gstaa",
        "git stash drop":"gstd",
        "git stash list":"gstl",
        "git stash pop":"gstp",
        "git stash show --text":"gsts",
        "git tag -s":"gts",
        "git update-index --no-assume-unchanged":"gunignore",
        "git log -n 1 | grep -q -c \"--wip--\" && git reset HEAD~1":"gunwip",
        "git pull --rebase":"gup",
        "git verify-tag":"gvt",
        "git whatchanged -p --abbrev-commit --pretty = medium":"gwch",
        "git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m \"--wip--\"":"gwip",
        "(When using sublime plugin) Open current directory in Sublime Text 2/3":"stt",
        "(When using vi-mode plugin) Edit current command line in Vim":"v",
        "Symfony2 - php ./app/console":"sf",
        "Symfony2 - php app/console cache:clear":"sfcl",
        "Symfony2 - sf debug:container":"sfcontainer",
        "Symfony2 - sf cache:warmup":"sfcw",
        "Symfony2 - sf generate:bundle":"sfgb",
        "Symfony2 - sf debug:router":"sfroute",
        "Symfony2 - sf server:run -vvv":"sfsr",
        "tmux attach -t":"ta",
        "tmux attach -d -t":'tad',
        "tmux new-session -s":"ts",
        "tmux list-sessions":"tl",
        "tmux kill-server":"tksv",
        "tmux kill-session -t":"tkss",
        "show the status of the NAME process":"sc-status NAME",
        "show the NAME systemd .service file" :"sc-show NAME",
        "start the NAME process" : "sc-start NAME",
        "stop the NAME process" : "sc-stop NAME",
        "restart the NAME process" : "sc-restart NAME",
        "enable the NAME process to start at boot" : "sc-enable NAME",
        "disable the NAME process at boot" : "sc-disable NAME",
    },
    "youtube.com":{
        #http://www.hongkiat.com/blog/useful-youtube-keyboard-shortcuts-to-know/
        #shift + /
        "Pause/Play video (player)":"Spacebar",
        "Pause/Play video":"k",
        "Keyboard shortcuts":"⇧/",
        "Previous video":"⇧p",
        "Next video":"⇧n",
        "Rewind 10 seconds":"j",
        "Fastfoward 10 seconds":"l",
        "Toggle Mute":"m",
        "Seek backwards by smallest amount possible, when video is paused":",",
        "Seek forwards by smallest amount possible, when video is paused":".",
        "Decrease playback rate":"< (^,)",
        "Increase playback rate":"> (^.)",
        "Toggle full screen":"f",
        "Seek backwards by 5 seconds (player)":"←",
        "Seek forwards by 5 seconds":"→",
        "Increase the volume by 5%":"UP",
        "Decrease the volume by 5%":"DOWN",
        "Close the current dialog or similar dialogs (share panel)":"ESCAPE",
        "Seek to the beginning of the video":"HOME",
        "Seek to the end of the video":"END",
        "If the video supports captions, toggle captions ON/OFF":"c",
        "Rotate through different text opacity levels":"o",
        "Rotate through different window opacity levels":"w",
        "Rotate through font sizes (increasing)":"+",
        "Rotate through font sizes (decreasing)":"-",
        "Seek to specific point in the video (7 advances to 70% of duration)":"0..9",
        "When viewing a spherical video, pan up":"w",
        "When viewing a spherical video, pan left":"a",
    },
    "AutoMute Chrome extension":{
        "Toggle mute current app":"⌥⇧m",
        "Mute all tabs":"⌥⇧l",
        "Mute other tabs":"⌥⇧o"
    },
    "github.com":{
    #https://help.github.com/articles/using-keyboard-shortcuts/
        "Focus the search bar":"s",
        "Go to your notifications":"g then n",
        "Go to the Code tab":"g then c",
        "Go to the Issues tab":"g then i",
        "Go to the Pull reuests tab":"g then p",
        "Go to the Projects tab":"g then b",
        "Go to the Wiki tab":"g then w",
        "Code editing - Start searching in file editor":"⌘f",
        "Code editing - Find next":"⌘g",
        "Code editing - Find previous":"⌘⇧g",
        "Code editing - Replace":"⌘⌥f",
        "Code editing - Replace All":"⇧⌘⌥f",
        "Code editing - Jump to line":"⌥g",
        "Code editing - Undo":"⌘z",
        "Code editing - Redo":"⌘y",
        "Code browsing - Activates the file finder":"t",
        "Code browsing - Jump to a line in your code":"l",
        "Code browsing - Switch to a new branch or tag":"w",
        "Code browsing - Expand a URL to its canonical form":"y",
        "Code browsing - Show or hide comments on diffs":"i",
        "Code browsing - Open blame view":"b",
        "Comments - Markdown to bold text":"⌘b",
        "Comments - Markdown to italicize text":"⌘i",
        "Comments - Markdown to create a link":"⌘k",
        "Comments - Toggles between the Write and Preview comment tabs":"⌘⇧p",
        "Comments - Submits a comment":"^⏎",
        "Issue/PR lists - Create an issue":"c",
        "Issue/PR lists - Focus the issues search bar":"/",
        "Issue/PR lists - Filter by author":"u",
        "Issue/PR lists - Filter by or edit labels":"l",
        "Issue/PR lists - Filter by or edit milestones":"m",
        "Issue/PR lists - Filter by or edit assignee":"a",
        "Issue/PR lists - Quote the selected text in your reply":"r",
        "Issue/PR lists - Open issue":"o or ⏎",
        "Issue/PR - Request a reviewer":"q",
        "Issue/PR - Set a milestone":"m",
        "Issue/PR - Apply a label":"l",
        "Issue/PR - Set an assignee":"a",
        "PR changes - Open the list of commits in the PR":"c",
        "PR changes - Open the list of changed files in the pull request":"t",
        "PR changes - Move selection down in the list":"j",
        "PR changes - Move selection up in the list":"k",
        "Notifications - Mark as read":"e or l or y",
        "Notifications - Mute thread":"⇧m",
        "Network Graph - Scroll left":"← or h",
        "Network Graph - Scroll right":"→ or l",
        "Network Graph - Scroll up":"↑ or k",
        "Network Graph - Scroll down":"↓ or j",
        "Network Graph - Scroll all the way left":"⇧← or ⇧h",
        "Network Graph - Scroll all the way right":"⇧→ or ⇧l",
        "Network Graph - Scroll all the way up":"⇧↑ or ⇧k",
        "Network Graph - Scroll all the way down":"⇧↓ or ⇧j",
        "Project boards - Moving a column - Start moving the focused column":"⏎ or Space",
        "Project boards - Moving a column - Cancel the move in progress":"Esc",
        "Project boards - Moving a column - Complete the move in progress":"⏎",
        "Project boards - Moving a column - Move column to the left":"← or h",
        "Project boards - Moving a column - Move column to the leftmost postition":"⌘← or ⌘h",
        "Project boards - Moving a column - Move column to the right":"→ or l",
        "Project boards - Moving a column - Move column to the rightmost postition":"⌘→ or ⌘l",
        "Project boards - Moving a card - Start moving the focused card":"⏎ or Space",
        "Project boards - Moving a card - Cancel the move in progress":"Esc",
        "Project boards - Moving a card - Complete the move in progress":"⏎",
        "Project boards - Moving a card - Move card down":"↓ or j",
        "Project boards - Moving a card - Move card to the bottom of the column":"⌘↓ or ⌘j",
        "Project boards - Moving a card - Move card up":"↑ or k",
        "Project boards - Moving a card - Move card to the top of the column":"⌘↑ or ⌘k",
        "Project boards - Moving a card - Move card to the bottom of the column on the left":"← or h",
        "Project boards - Moving a card - Move card to the top of the column on the left":"⇧← or ⇧h",
        "Project boards - Moving a card - Move card to the bottom of the leftmost column":"⌘← or ⌘h",
        "Project boards - Moving a card - Move card to the top of the leftmost column":"⌘⇧← or ⌘⇧h",
        "Project boards - Moving a card - Move card to the bottom of the column on the right":"→ or l",
        "Project boards - Moving a card - Move card to the top of the column on the right":"⇧→ or ⇧l",
        "Project boards - Moving a card - Move card to the bottom of the rightmost column":"⌘→ or ⌘l",
        "Project boards - Moving a card - Move card to the top of the rightmost column":"⌘⇧→ or ⌘⇧l"
    },
    "Outlook":{ #https://support.office.com/en-us/article/Keyboard-shortcuts-for-Outlook-for-Mac-07ae68c8-b7af-4010-b225-324c04ac7335?ui=en-US&rs=en-US&ad=US
        "Archive message":"^e",
        "Previous message":"^[",
        "Next message":"^]",
        "Save an item":"⌘S",
        "Print an item":"⌘P",
        "Undo the last action":"⌘Z",
        "Redo the last action":"⌘Y",
        "Minimize the active window":"⌘M",
        "Create a new folder in the navigation pane":"⌘⇧N",
        "Create new email (in Mail view)":"⌘N",
        "Hide the reading pane or show it on the right":"⌘\\",
        "Hide the reading pane or show it below":"⇧ ⌘\\ )",
        "Move the selected item to a different folder":"⇧ ⌘M",
        "Copy the selected item to a different folder":"⇧ ⌘C",
        "Select all items in the item list, if the item list is the active pane":"⌘A",
        "Minimize or expand the ribbon":"⌘⌥R",
        "Hide Outlook":"⌘H",
        "Quit Outlook":"⌘Q",
        "Start dictation":"FnFn",
        "Insert emoji":"⌘^Space",
        "Go to Mail view":"⌘1",
        "Go to Calendar view":"⌘2",
        "Go to Contacts view":"⌘3",
        "Go to Tasks view":"⌘4",
        "Go to Notes view":"⌘5",
        "Open the Sync Status window or make it the active window":"⌘7",
        "Open the Sync Errors or make it the active window":"⌘8",
        "Open the Contacts Search window":"⌘0",
        "Open the Outlook Preferences dialog box":"⌘,",
        "Cycle forward through open windows":"⌘~",
        "Cycle back through open windows":"⇧ ⌘~",
        "Close the active window":"⌘W",
        "Open the selected item":"⌘O",
        "Move forward through controls in a window":"Tab",
        "Move back through controls in a window":"⇧Tab",
        "Search current folder":"⌥ ⌘F",
        "Do an advanced search in Outlook (add Item Contains filter for searching)":"⇧ ⌘F",
        "Find text within an item - search":"⌘F",
        "Find the next instance of the text you searched for in an item":"⌘G",
        "Find the previous instance of the text you searched for in an item":"⌘⇧G",
        "Create a new message":"⌘N",
        "Send the open message":"⌘Return",
        "Send all messages in the Outbox and receive all incoming messages":"⌘K",
        "Send all the messages in the Outbox":"⇧ ⌘K",
        "Save the open message and store it in the Drafts folder":"⌘S",
        "Add an attachment to the open message":"⌘E",
        "Open the Spelling and Grammar dialog box":"⌘:",
        "Check recipient names in the open messages":"^ ⌘C",
        "Reply to the sender of the message or, if the message is from a mailing list, reply to the mailing list":"⌘R",
        "Reply to all":"⇧+  ⌘R",
        "Forward the message":"⌘J",
        "Open the selected message in a separate window":"⌘O",
        "Clear the flag for the selected message":"⌥ ⌘'",
        "Mark the selected message as junk mail":"⌘⇧J",
        "Mark the selected message as not junk mail":"⌘⇧⌥J",
        "Display the previous message":"[",
        "Display the next message":"]",
        "Navigate to the previous pane in the Mail view":"⇧[",
        "Navigate to the next pane in the Mail view":"⇧]",
        "Move the selected message to a folder":"⇧ ⌘M",
        "Decrease the display size of text in an open message or in the reading pane":"⌘-",
        "Increase the display size of text in an open message or in the reading pane":"⌘+",
        "Scroll down to the next screen of text or, if you are at the end of a message, display the next message":"Spacebar",
        "Scroll up to the previous screen of text or, if you are at the beginning of a message, display the previous message":"⇧+ Spacebar",
        "Delete the selected message":"Delete",
        "Permanently delete the selected message":"⇧Delete",
        "Delete the current message, and, if the message window is open, close it":"⌘Delete",
        "Mark selected messages as read":"⌘T",
        "Mark selected messages as unread":"⇧ ⌘T",
        "Mark all messages in a folder as read":"⌥ ⌘T",
        "Open the Calendar window":"⌘2",
        "Create a new appointment":"⌘N",
        "Open the selected calendar event":"⌘O",
        "Delete the calendar event":"Delete",
        "Switch the view to include today":"⌘T",
        "In Day view, move to the previous day. In Week and Work Week views, move to the previous week. In Month view, move to the previous month.":"⌘←",
        "In Day view, move to the next day. In Week and Work Week views, move to the next week. In Month view, move to the next month.":"⌘→",
        "Navigate to the previous pane in the Calendar view":"⇧[",
        "Navigate to the next pane in the Calendar view":"⇧]",
        "Create a new contact":"⌘N",
        "Open the selected contact":"⌘O",
        "Delete the contact":"Delete",
        "Close the current open contact and open the previous contact":"[",
        "Close the current open contact and open the next contact":"]",
        "Navigate to the previous pane in the People view":"⇧+ [",
        "Navigate to the next pane in the People view":"⇧]",
        "Move to the Task window":"⌘4",
        "Create a new task":"⌘N",
        "Open the selected task":"⌘O",
        "Delete the task":"Delete",
        "Close the current open task and open the previous task in the Tasks list":"[",
        "Close the current open task and open the next task in the Tasks list":"]",
        "Navigate to the previous pane in the Tasks view":"⇧[",
        "Navigate to the next pane in the Tasks view":"⇧]",
        "Move to the Notes window":"⌘5",
        "Create a new note":"⌘N",
        "Open the selected note":"⌘O",
        "Delete the note":"Delete",
        "Close the current open note and open the previous note in the Notes list":"[",
        "Close the current open note and open the next note in the Notes list":"]",
        "Navigate to the previous pane in the Notes view":"⇧[",
        "Navigate to the next pane in the Notes view":"⇧]",
        "Send a note as an email":"⌘J",
        "Send a note as an HTML attachment to an email":"^ ⌘J [First place the focus on the note in the list of notes]",
        "Cut the selected text to the clipboard":"⌘X",
        "Copy a selection to the clipboard":"⌘C",
        "Paste a selection from the clipboard":"⌘V",
        "Paste a selection from the clipboard and match the destination style":"⇧⌥ ⌘V",
        "Make the selected text bold":"⌘B",
        "Make the selected text italic":"⌘I",
        "Underline the selected text":"⌘U",
        "Strike through the selected text":"⇧ ⌘X",
        "Insert a hyperlink":"^ ⌘K",
        "Move the cursor left one character":"←",
        "Move the cursor right one character":"→",
        "Move the cursor up one line":"↑",
        "Move the cursor down one line":"↓",
        "Move the cursor to the beginning of the current paragraph":"⌥↑",
        "Move the cursor to the end of the current paragraph":"⌥↓",
        "Move the cursor to the beginning of the current word":"⌥←",
        "Move the cursor to the end of the current word":"⌥→",
        "Decrease indent":"{",
        "Increase indent":"}",
        "Delete the character to the left of the cursor, or delete the selected text":"Delete",
        "Delete the character to the right side of the cursor, or delete the selected text":"Delete [If your keyboard doesn't have a  Delete key, use FNDelete]",
        "Insert a tab stop":"Tab",
        "Move the cursor to the beginning of the line":"⌘←",
        "Move the cursor to the end of the line":"⌘→",
        "Move the cursor to the top of the message body":"⌘↑",
        "Move the cursor to the bottom of the message body":"⌘↓",
        "Move the cursor to the beginning of the selected text":"⌘Home",
        "Move the cursor to the end of the selected text":"⌘End",
        "Scroll up":"Page up",
        "Scroll down":"Page down",
        "Flag the selected item for follow up, with Today as Due Date":"^1",
        "Flag the selected item for follow up, with Tomorrow as Due Date":"^2",
        "Flag the selected item for follow up, with This Week as Due Date":"^3",
        "Flag the selected item for follow up, with Next Week as Due Date":"^4",
        "Flag the selected item for follow up, with No Due Date":"^5",
        "Flag the selected item for follow up, and add a custom Due Date":"^6",
        "Flag the selected item for follow up, and add a reminder":"^=",
        "Mark the selected item as Complete":"^0",
        "Clear the selected item's follow-up flag":"⌥⌘'"
    },
    "Video Speed Controller chrome extension":{
    #settings
        "Rewind":"Z",
        "Advance":"X",
        "Reset speed":"R",
        "Decrease speed":"S",
        "Increase speed":"D",
        "Preferred speed":"G",
        "Show/hide controller":"V"
    },
    "inbox.google.com":{
        #⇧?
        "Everywhere - Toggle and view keyboard shortcuts":"⇧?",
        "Everywhere - Compose":"c",
        "Everywhere - Search":"/",
        "Everywhere - Go to inbox":"i",
        "Everywhere - Open Hangouts and focus the conversation list":"h",
        "Everywhere - Open Hangouts and focus the search box":"q",
        "Everywhere - Create reminder":"t",
        "Everywhere - Focus on notification":"⇧b",
        "Everywhere - Open main menu":"⇧m",
        "Everywhere - Undo last action":"z",
        "Chat/compose - Focus latest chat or compose":"⇧Esc",
        "Chat/compose - Focus main window (while in chat or compose)":"⇧Esc",
        "Chat/compose - Advance to next chat or compose":"Ctrl .",
        "Chat/compose - Advance to previous chat or compose":"Ctrl ,",
        "Chat/compose - Bold":"⌘b",
        "Chat/compose - Italics":"⌘i",
        "Chat/compose - Underline":"⌘u",
        "Chat/compose - Insert link":"⌘k",
        "Chat/compose - Numbered list":"⌘⇧7",
        "Chat/compose - Bulleted list":"⌘⇧8",
        "Chat/compose - Remove formatting":"⌘\\",
        "Chat/compose - Send":"⌘⏎",
        "Chat/compose - Closes compose and deletes empty drafts":"Esc",
        "List - Open":"⏎ or o",
        "List - Close":"Esc or u",
        "List - Next item":"j or →",
        "List - Previous item":"k or ←",
        "List - First item":"Home",
        "List - Next message":"n",
        "List - Previous message":"p",
        "Focused item - Mark done":"e or y",
        "Focused item - Mark done and advance":"] or [",
        "Focused item - Snooze":"s",
        "Focused item - Pin":"⇧p",
        "Focused item - Reply all":"a",
        "Focused item - Reply all in a new window":"⇧a",
        "Focused item - Reply":"r",
        "Focused item - Reply in a new window":"⇧r",
        "Focused item - Forward":"f",
        "Focused item - Trash":"#",
        "Focused item - Report as spam":"!",
        "Focused item - Mute":"m",
        "Focused item - Toggle move-to menu":".",
        "Focused item - Select":"x",
        "Focused item - Select many items at once":"⇧x"
    },
    "trello.com":{
        "Navigate Cards":"← ↓/J ↑/K →",
        "Open Header Boards Menu":"B",
        "Focus Search Box":"/",
        "Archive Card":"C",
        "Due Date":"D",
        "Quick Edit Mode":"E",
        "Close Menu / Cancel Editing":"Esc",
        "Save Text":"⌘⏎",
        "Open Card":"⏎",
        "Open Card Filter Menu":"F",
        "Label":"L",
        "Black":"0",
        "Green":"1",
        "Yellow":"2",
        "Orange":"3",
        "Red":"4",
        "Purple":"5",
        "Blue":"6",
        "Sky":"7",
        "Lime":"8",
        "Pink":"9",
        "Toggle Label Names":";",
        "Add / Remove Members":"M",
        "Insert New Card":"N",
        "Move Card to Adjacent List":", , . < >",
        "My Cards Filter":"Q",
        "Subscribe":"S",
        "Assign Self":"Space",
        "Edit Title":"T",
        "Vote":"V",
        "Toggle Board Menu":"W",
        "Clear All Filters":"X",
        "Open Shortcuts Page":"?",
        "Autocomplete Members":"@",
        "Autocomplete Labels":"#",
        "Autocomplete Labels":"^"
    },
    "Alfred":{
    #https://www.alfredapp.com/help/getting-started/cheatsheet/
        "space Show Alfred":"⌥",
        "Select the next result in the list":"↓",
        "Select the previous item in the list":"↑",
        "Action the currently selected item":"↩",
        "Action the # item directly [1-9]":"⌘#",
        "Open file or application in default application":"⌘o",
        "Show the Preferences Window":"⌘,",
        "Search the currently typed query in Spotlight":"⌥↩",
        "Search the currently typed query in default web search":"⌃ ↩",
        "Reveal in Finder (if the result is a local file)":"⌘↩",
        "Show Alfred Preferences":"preferences",
        "To launch an application simply start typing its name, then hit Return":"app name",
        "Use predefined web search keywords":"google, wiki ...",
        "Follow keyword by query to open a file":"open",
        "Follow a space with your query to open a file":"spacebar",
        "Follow keyword by query to reveal file in Finder":"find",
        "Open the file":"⌘o",
        "Follow by a query to search for files that contain this query":"in",
        "Follow keyword by a word and get a definition":"define",
        "Follow keyword by a word and see results with suggested spelling":"spell",
        "Type a calculation into main window to get the result":"13*567",
        "Start an advanced calculation (enable this function in the Calculator Preferences)":"=",
        "Start Screen Saver":"screensaver",
        "Show Trash":"trash",
        "Empty Trash":"emptytrash",
        "Log Out":"logout",
        "Sleep your Mac":"sleep",
        "Sleep your Mac's displays":"sleepdisplays",
        "Lock your Mac":"lock",
        "Restart your Mac":"restart",
        "Shut Down your Mac":"shutdown",
        "Eject (removable media or all mounted volumes)":"eject",
        "Hide the running application":"hide",
        "Quit the running application":"quit",
        "Force Quit the running application":"forcequit",
        "Navigate to your home folder":"~",
        "Navigate to your root folder":"/",
        "Go to last browsed path in the File System Navigation":"⌥⌘/",
        "Go to last browsed path in the File System Navigation":"previous",
        "Show list of available Actions for selected item":"→",
        "Show list of available Actions for selected item":"fn",
        "Show list of available Actions for selected item":"⌃",
        "Show list of available Actions for selected Finder item":"⌥⌘\\",
        "Browse selected folder in File System Navigation":"⌘↓",
        "Enter a folder in File System Navigation":"↩",
        "Go up a folder":"backspace",
        "Autocomplete":"Tab",
        "Show hidden files in File System Navigation":".",
        "Open Clipboard History viewer":"⌥⌘c",
        "Copy selected clip to current Clipboard":"⌘c",
        "Access snippets from main Alfred window with this keyword":"snip",
        "Use keyword to clear Clipboard History":"clear",
        "While in the Clipboard Viewer, save current clip as a snippet":"⌘s",
        "Show the iTunes Mini Player":"⌃ ⌘↩",
        "Use keyword to show the iTunes Mini Player":"itunes",
        "Play / Pause":"⌃ ⌘↓  or  play/pause",
        "Next Track":"⌃ ⌘→  or next",
        "Back Track":"⌃ ⌘←  or back",
        "Previous Track":"previous",
        "Play Random Album":"⌃ ⌘↑ or random",
        "Maximum volume":"volmax",
        "Half volume":"volmid",
        "Mute volume":"mute",
        "Rate currently playing song from 0 to 5 stars":"⌃ ⌘[0-5]",
        "Go up a folder in iTunes Mini Player":"backspace",
        "Reindex iTunes library":"⌘r",
        "Use keyword followed by name or email address to send an email using your default email client":"email"
    },
    "Terminal":{
    #https://github.com/0nn0/terminal-mac-cheatsheet
        "Go to the beginning of the line you are currently typing on.":"Ctrl A ",
        "Go to the end of the line you are currently typing on.":"Ctrl E ",
        "Clears everything on current line":"Ctrl Q ",
        "Clears the Screen":"Ctrl L ",
        "Clears the Screen":"⌘K",
        "Cut everything backwards to beginning of line":"Ctrl U",
        "Cut everything forward to end of line":"Ctrl K",
        "Cut one word backwards using white space as delimiter":"Ctrl  W",
        "Paste whatever was cut by the last cut command":"Ctrl Y",
        "Same as backspace":"Ctrl H",
        "Kill whatever you are running":"Ctrl C",
        "Exit the current shell when no process is running, or send EOF to a the running process":"Ctrl D",
        "Puts whatever you are running into a suspended background process. fg restores it.":"Ctrl Z",
        "Undo the last command.":"Ctrl ⇧-",
        "Swap the last two characters before the cursor":"Ctrl T",
        "Move cursor one character forward":"Ctrl F",
        "Move cursor one character backward":"Ctrl B",
        "Move cursor one word forward":"⌥→",
        "Move cursor one word backward":"⌥←",
        "Swap the last two words before the cursor":"Esc T",
        "Auto-complete files and folder names":"Tab "
    },
    "Mac OSX":{
        #https://support.apple.com/en-jo/HT201236
        "Cut the selected item and copy it to the Clipboard.":"⌘X",
        "Copy the selected item to the Clipboard.":"⌘C",
        "Paste the contents of the Clipboard into the current document or app.":"⌘V",
        "Undo the previous command.":"⌘Z",
        "Redo, reversing the undo command.":"⌘⇧Z",
        "Select All items. ":"⌘A",
        "Find items in a document or open a Find window.":"⌘F",
        "Find Again: Find the next occurrence of the item previously found.":"⌘G",
        "Find Again: Find the previous occurrence of the item previously found":"⌘⇧G",
        "Hide the windows of the front app.":"⌘H",
        "view the front app but hide all other apps":"⌘⌥H",
        "Minimize the front window to the Dock.":"⌘M",
        "Minimize all windows of the front app":" ⌘⌥M",
        "New: Open an new document or window.":"⌘N",
        "Open the selected item, or open a dialog to select a file to open.":"⌘O",
        "Print the current document.":"⌘P",
        "Save the current document.":"⌘S",
        "Close the front window":"⌘W",
        "close all windows of the app":"⌘⌥W",
        "Quit the app.":"⌘Q",
        "Force Quit: choose app to quit and hold for 3 seconds to .":"⌥⌘Esc",
        "Force Quit: just the front app to quit":"press ⌘⇧⌥Esc and hold for 3 sec",
        "Spotlight":"⌘Space",
        "Quick Look: Use Quick Look to preview the selected item.":"Space",
        "Switch apps: Switch to the next most recently used app among your open apps. ":"⌘Tab",
        "Switch windows: Switch to the next most recently used window of the front app. ":"⇧⌘~",
        "Screenshot: Take a screenshot of the entire screen. ":"⇧⌘3",
        "Screenshot: Take a screenshot of part of the screen":"⇧⌘4",
        "Preferences: Open preferences for the front app.":"⌘,",
        "Press to turn on your Mac or wake your Mac from sleep.":"Power button",
        "Display a dialog asking if you want to sleep, restart, or shut down.":"Press and hold Power Button for 1.5 seconds or Ctrl Power button or Ctrl ⏏ ",
        "Force your Mac to turn off.":"Press and hold Power Button for 5 seconds ",
        "Force your Mac to restart.":"Ctrl ⌘ Power button    ",
        "Put your displays to sleep.*":"Ctrl ⇧ Power button or Ctrl ⇧⏏   ",
        "Quit all apps, then restart your Mac. ":"Ctrl ⌘⏏ ",
        "Quit all apps, then shut down your Mac. ":"Ctrl ⌥⌘ Power button or Ctrl ⌥⌘⏏",
        "Log out of your macOS user account. ":"⇧⌘Q ",
        "Log out of your macOS user account immediately, without being asked to confirm.":"⌥⇧⌘Q  "
    },
    "Finder":{
        #https://support.apple.com/en-jo/HT201236
        "Duplicate the selected files.":"⌘D   ",
        "Eject the selected disk or volume.":"⌘E   ",
        "Start a Spotlight search in the Finder window.":"⌘F   ",
        "Show the Get Info window for a selected file.":"⌘I   ",
        "Open the Computer window.":"⇧⌘C ",
        "Open the desktop folder.":"⇧⌘D ",
        "Open the All My Files window.":"⇧⌘F ",
        "Open a Go to Folder window.":"⇧⌘G ",
        "Open the Home folder of the current macOS user account.":"⇧⌘H ",
        "Open iCloud Drive.":"⇧⌘I ",
        "Open the Network window.":"⇧⌘K ",
        "Open the Downloads folder.":"⌥⌘L    ",
        "Open the Documents folder.":"⇧⌘O ",
        "Open the AirDrop window.":"⇧⌘R ",
        "Add selected Finder item to the Dock (OS X Mountain Lion or earlier)":"⇧⌘T ",
        "Add selected Finder item to the Dock (OS X Mavericks or later)":"Ctrl-⇧⌘T ",
        "Open the Utilities folder.":"⇧⌘U ",
        "Show or hide the Dock. This often works even when you're not in the Finder.":"⌥⌘D    ",
        "Add the selected item to the sidebar (OS X Mavericks or later).":"Ctrl-⌘T   ",
        "Hide or show the path bar in Finder windows.":"⌥⌘P    ",
        "Hide or show the Sidebar in Finder windows.":"⌥⌘S    ",
        "Hide or show the status bar in Finder windows.":"/",
        "Show View Options.":"⌘J   ",
        "Open the Connect to Server window.":"⌘K   ",
        "Make an alias of the selected item.":"⌘L   ",
        "Open a new Finder window.":"⌘N   ",
        "Create a new folder.":"⇧⌘N ",
        "Create a new Smart Folder.":"⌥⌘N    ",
        "Show the original file for the selected alias.":"⌘R   ",
        "Show or hide the tab bar when a single tab is open in the current Finder window.":"⌘T   ",
        "Show or hide a Finder tab.":"⇧⌘T ",
        "Show or hide the toolbar when a single tab is open in the current Finder window.":"⌥⌘T    ",
        "Move: Move the files in the Clipboard from their original location to the current location.":"⌥⌘V    ",
        "View a Quick Look slideshow of the selected files.":"⌥⌘Y    ",
        "Use Quick Look to preview the selected files.":"⌘Y   ",
        "View the items in the Finder window as icons.":"⌘1   ",
        "View the items in a Finder window as a list.":"⌘2   ",
        "View the items in a Finder window in columns. ":"⌘3   ",
        "View the items in a Finder window with Cover Flow.":"⌘4   ",
        "Go to the previous folder.":"[    ",
        "Go to the next folder.":"]   ",
        "Open the folder that contains the current folder.":"⌘↑    ",
        "Open the folder that contains the current folder in a new window.":"⌘Ctrl ↑    ",
        "Open the selected item.":"⌘↓",
        "Show the desktop. This works even when you're not in the Finder.":"⌘ Mission Control",
        "Turn Target Display Mode on or off.":"⌘ Brightness Up   ",
        "Turn display mirroring on or off when your Mac is connected to more than one display.":"⌘ Brightness Down ",
        "Open the selected folder. This works only when in list view.":"→     ",
        "Close the selected folder. This works only when in list view.":"←",
        "Open a folder in a separate window and close the current window.":"⌥ double-click ",
        "Open a folder in a separate tab or window.":"⌘ double-click    ",
        "Move the selected item to the Trash.":"⌘ Delete  ",
        "Empty the Trash.":"⇧⌘ Delete    ",
        "Empty the Trash without confirmation dialog.":"⌥⇧⌘ Delete ",
        "Use Quick Look to preview the files.":"⌘Y   ",
        "Open Displays preferences. This works with either Brightness key.":"⌥ Brightness Up    ",
        "Open Mission Control preferences.":"⌥ Mission Control",
        "Open Sound preferences. ":"⌥ Volume Up or any volume key",
        "Move the dragged item to another volume or location. ":"⌘ while dragging  ",
        "Copy the dragged item. ":"⌥ while dragging",
        "Make an alias of the dragged item. ":"⌥Command while dragging   ",
        "Open all folders within the selected folder.  [list view].":"⌥ click a disclosure triangle  ",
        "See the folders that contain the current folder.":"⌘ click a window title    "
    },
    "Firefox":{
        #https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
        #https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/Keyboard_shortcuts
        "Navigation - Back    ":"command + ← or command + [ or Delete",
        "Navigation - Forward ":"command + → or command + ] or Shift + Delete",
        "Navigation - Home   ":"option + home",
        "Navigation - Open File   ":"command + O",
        "Navigation - Reload  ":"F5 or command + R",
        "Navigation - Reload (override cache) ":"command + shift + R",
        "Navigation - Stop    ":"Esc  or command + .",
        "Current Page - Go Down a Screen    ":"fn + ↓",
        "Current Page - Go Up a Screen  ":"fn + ↑ or Shift + Space bar",
        "Current Page - Go to Bottom of Page    ":"End or command + ↓",
        "Current Page - Go to Top of Page   ":"Home or command + ↑",
        "Current Page - Move to Next Frame  ":"F6",
        "Current Page - Move to Previous Frame  ":"Shift + F6",
        "Current Page - Print   ":"command + P",
        "Current Page - Save Page As    ":"command + S",
        "Current Page - Zoom In ":"command + +",
        "Current Page - Zoom Out    ":"command + -",
        "Current Page - Zoom Reset  ":"command + 0",
        "Editing - Copy    ":"command + C",
        "Editing - Cut ":"command + X",
        "Editing - Delete  ":"delete",
        "Editing - Paste  ":"command + V",
        "Editing - Paste (as plain text)   ":"command + shift + V",
        "Editing - Redo    ":"command + shift + Z",
        "Editing - Select All  ":"command + A",
        "Editing - Undo    ":"command + Z",
        "Search - Find    ":"command + F ",
        "Search - Find Again  ":"F3 or command + G ",
        "Search - Find Previous   ":"Shift + F3 or command + shift + G ",
        "Search - Quick Find within link-text only    ":"'   ",
        "Search - Quick Find  ":"/   ",
        "Search - Close the Find or Quick Find bar    ":"Esc - when the Find or Quick Find bar is focused",
        "Search - Focus Search bar    ":"command + K or command + option + F    ",
        "Search - Quickly switch between search engines   ":"command + ↑ or command + ↓ - when Search Bar is focused",
        "Search - View menu to switch, add or manage search engines":"option + ↑ or option + ↓  - when Search Bar is focused",
        "Windows/tabs - Close Tab   ":"command + W - except for App Tabs",
        "Windows/tabs - Close Window    ":"command + shift + W ",
        "Windows/tabs - Move Tab in focus Left  ":"Ctrl + Shift + Page Up  ",
        "Windows/tabs - Move Tab in focus ":"Right Ctrl + Shift + Page Down    ",
        "Windows/tabs - Move Tab in focus to start  ":"command + home  ",
        "Windows/tabs - Move Tab in focus to end    ":"command + end   ",
        "Windows/tabs - Mute/Unmute Audio   ":"Ctrl + M    ",
        "Windows/tabs - New Tab ":"command + T ",
        "Windows/tabs - New Window  ":"command + N ",
        "Windows/tabs - New Private Window  ":"command + shift + P ",
        "Windows/tabs - Next Tab    ":"control + tab or control + page down or command + option + →    ",
        "Windows/tabs - Open Address in New Tab ":"option + return - from Location Bar or Search Bar",
        "Windows/tabs - Previous Tab    ":"control + shift + tab or control + page up or command + option + ←    ",
        "Windows/tabs - Undo Close Tab  ":"command + shift + T ",
        "Windows/tabs - Undo Close Window   ":"command + shift + N ",
        "Windows/tabs - Select Tab 1 to 8   ":"command + 1to8  ",
        "Windows/tabs - Select Last Tab ":"command + 9",
        "History - History sidebar ":"command + shift + H",
        "History - Clear Recent History    ":"command + shift + delete",
        "Bookmarks - Bookmark All Tabs   ":"command + shift + D",
        "Bookmarks - Bookmark This Page  ":"command + D",
        "Bookmarks - Bookmarks sidebar   ":"command + B",
        "Bookmarks - Library window  ":"command + shift + B",
        "Tools - Downloads   ":"command + J",
        "Tools - Add-ons ":"command + shift + A",
        "Tools - Toggle Developer Tools  ":"F12 or command + alt + I",
        "Tools - Web Console ":"command + alt + K",
        "Tools - Inspector   ":"command + alt + C",
        "Tools - Debugger    ":"command + alt + S",
        "Tools - Style Editor    ":"Shift + F7",
        "Tools - Profiler    ":"Shift + F5",
        "Tools - Network ":"command + alt + Q",
        "Tools - Developer Toolbar   ":"Shift + F2",
        "Tools - Responsive Design View  ":"command + alt + M",
        "Tools - Scratchpad  ":"Shift + F4",
        "Tools - Page Source ":"command + U",
        "Tools - Browser Console ":"command + shift + J",
        "Tools - Page Info   ":"command + I",
        "PDF Viewer - Next page   ":"N or J or →",
        "PDF Viewer - Previous page   ":"P or K or ←",
        "PDF Viewer - Zoom in ":"command + +",
        "PDF Viewer - Zoom out    ":"command + -",
        "PDF Viewer - Automatic Zoom  ":"command + 0",
        "PDF Viewer - Rotate the document clockwise   ":"R",
        "PDF Viewer - Rotate counterclockwise ":"Shift + R",
        "PDF Viewer - Switch to Presentation Mode ":"command + Alt + P",
        "PDF Viewer - Toggle Hand Tool    ":"H",
        "PDF Viewer - Focus the Page Number input box ":"command + Alt + G",
        "Complete .com Address   ":"command + return",
        "Complete .net Address   ":"shift + return",
        "Complete .org Address   ":"command + shift + return",
        "Delete Selected Autocomplete Entry  ":"shift + delete",
        "Toggle Full Screen  ":"command+Shift+F",
        "Toggle Reader Mode  ":"command+option+R",
        "Caret Browsing  ":"F7",
        "Select Location Bar ":"F6 or command + L",
        "Media - Toggle Play / Pause ":"Space bar",
        "Media - Decrease volume ":"↓",
        "Media - Increase volume ":"↑",
        "Media - Mute audio  ":"command + ↓",
        "Media - Unmute audio    ":"command + ↑",
        "Media - Seek back 15 seconds    ":"←",
        "Media - Seek back 10 %  ":"command + ←",
        "Media - Seek forward 15 seconds ":"→",
        "Media - Seek forward 10 %   ":"command + →",
        "Media - Seek to the beginning   ":"Home",
        "Media - Seek to the end ":"End",
        "Inspect Element":"Cmd + Opt + C",
        "Node picker - Select the element under the mouse and cancel picker mode   ":"Click",
        "Node picker - Select the element under the mouse and stay in picker mode   ":"Shift+Click ",
        "HTML pane - Delete the selected node    ":"Delete",
        "HTML pane - Undo delete of a node   ":"Cmd + Z",
        "HTML pane - Redo delete of a node   ":"Cmd + Shift + Z / Cmd + Y",
        "HTML pane - Move to next node (expanded nodes only) ":"Down arrow",
        "HTML pane - Move to previous node   ":"Up arrow",
        "HTML pane - Expand currently selected node  ":"Right arrow",
        "HTML pane - Collapse currently selected node    ":"Right arrow",
        "HTML pane - Step forward through the attributes of a node   ":"Tab",
        "HTML pane - Step backward through the attributes of a node  ":"Shift + Tab",
        "HTML pane - Start editing the selected attribute    ":"Enter",
        "HTML pane - Hide/show the selected node ":"H   ",
        "HTML pane - Focus on the search box in the HTML pane    ":"Cmd + F",
        "HTML pane - Edit as HTML    ":"F2",
        "HTML pane - Stop editing HTML   ":"F2 / Ctrl +Enter",
        "HTML pane - Copy the selected node's outer HTML  ":"Cmd + C",
        "HTML pane - Scroll the selected node into view   ":"S",
        "HTML pane - Find the next match in the markup, when searching is active ":"Enter",
        "HTML pane - Find the previous match in the markup, when searching is active  ":"Shift + Enter",
        "Breadcrumbs bar - Move to the previous element in the breadcrumbs bar     ":"Left arrow",
        "Breadcrumbs bar - Move to the next element in the breadcrumbs bar     ":"Right arrow",
        "Breadcrumbs bar - Focus the HTML pane ":"Shift + Tab",
        "Focus the CSS pane  ":"Tab",
        "CSS pane - Focus on the search box in the CSS pane ":"Cmd + F",
        "CSS pane - Clear search box content (only when the search box is focused, and content has been entered)    ":"Esc",
        "CSS pane - Step forward through properties and values  ":"Tab",
        "CSS pane - Step backward through properties and values ":"Shift + Tab",
        "CSS pane - Start editing property or value (Rules view only, when a property or value is selected, but not already being edited)   ":"Enter or Space",
        "CSS pane - Cycle up and down through auto-complete suggestions (Rules view only, when a property or value is being edited) ":"Up arrow , Down arrow",
        "CSS pane - Choose current auto-complete suggestion (Rules view only, when a property or value is being edited) ":"Enter or Tab",
        "CSS pane - Increment selected value by 1   ":"Up arrow",
        "CSS pane - Decrement selected value by 1   ":"Down arrow",
        "CSS pane - Increment selected value by 100 ":"Shift + Page Up",
        "CSS pane - Decrement selected value by 100 ":"Shift + Page Down",
        "CSS pane - Increment selected value by 10  ":"Shift + Up arrow",
        "CSS pane - Decrement selected value by 10  ":"Shift + Down arrow",
        "CSS pane - Increment selected value by 0.1 ":"Opt + Up arrow",
        "CSS pane - Decrement selected value by 0.1 ":"Opt + Down arrow",
        "CSS pane - Show/hide more information about current property (Computed view only, when a property is selected)  ":"Return or Space",
        "CSS pane - Open MDN reference page about current property (Computed view only, when a property is selected) ":"F1",
        "CSS pane - Open current CSS file in Style Editor (Computed view only, when more information is shown for a property and a CSS file reference is focused)    ":"Enter",
        "Increase font size  ":"Cmd +",
        "Decrease font size  ":"Cmd + -",
        "Reset font size ":"Cmd + 0"
    },
    "Microsoft Word":{
        # https://support.office.com/en-us/article/Keyboard-shortcuts-in-Word-for-Mac-3256d48a-7967-475d-be81-a6e3e1284b25
        "Undo the last action":"COMMAND + Z or Control + Z",
        "Cut selected text or graphics":"COMMAND + X or Control + X",
        "Copy selected text or graphics to the Clipboard":"COMMAND + C or Control + C",
        "Paste the Clipboard contents":"COMMAND + V or Control + V",
        "Choose the Go To command (Edit menu)":"Option +  COMMAND + G",
        "Open the Spelling and Grammar dialog box":"Option +  COMMAND + L",
        "Extend a selection":"F8",
        "Go to the next window":"COMMAND + Grave accent ( ` )",
        "Choose the Save As command (File menu).":"COMMAND + Shift + S",
        "Copy selected text":"Shift + F2",
        "Change letters to uppercase, lowercase, or mixed case":"Shift + F3",
        "Find":"Control+F; places the focus in the Search box",
        "Find and Replace":"Control+H",
        "Print a document":"COMMAND + P or Control + P",
        "Move to the previous insertion point":"Shift + F5",
        "Go to the previous window":"COMMAND + Shift + `",
        "Open the Thesaurus pane":"Shift+ F7",
        "Shrink a selection":"Shift+ F8",
        "Switch between a field code and its result":"Shift + F9",
        "Cut the selection to the Spike":"COMMAND + F3",
        "Close the window":"COMMAND + F4",
        "Expand or minimize the ribbon":"Option +  COMMAND + R",
        "Edit a bookmark":"COMMAND + Shift + F5",
        "Find the next misspelling or grammatical error. The Check spelling as you type check box must be selected (Word menu, Preferences command, Spelling and Grammar).":"Option + F7",
        "Look up selected text on the Internet":"COMMAND + Shift + L",
        "Cursor - Move one character to the left":"Left arrow",
        "Cursor - Move one character to the right":"Right arrow",
        "Cursor - Move one word to the left":"Option + Left arrow",
        "Cursor - Move one word to the right":"Option + Right arrow",
        "Cursor - Move one paragraph up":"COMMAND + Up arrow",
        "Cursor - Move one paragraph down":"COMMAND + Down arrow",
        "Cursor - Move one cell to the left (in a table)":"Shift + Tab",
        "Cursor - Move one cell to the right (in a table)":"Tab",
        "Cursor - Move up one line":"Up arrow",
        "Cursor - Move down one line":"Down arrow",
        "Cursor - Move to the end of a line":"COMMAND + Right arrow or End",
        "Cursor - Move to the beginning of a line":"COMMAND + Left arrow or Home",
        "Cursor - Move up one screen (scrolling)":"Page Up",
        "Cursor - Move down one screen (scrolling)":"Page Down",
        "Cursor - Move to the top of the next page":"COMMAND + Page Down",
        "Cursor - Move to the top of the previous page":"COMMAND + Page Up",
        "Cursor - To the end of a document":"COMMAND + End",
        "Cursor - On a MacBook keyboard:":"COMMAND + FN + Right arrow",
        "Cursor - To the beginning of a document":"COMMAND + Home",
        "Cursor - On a MacBook keyboard:":"COMMAND + FN + Left arrow",
        "Cursor - To the previous insertion point":"Shift + F5",
        "Select multiple items not next to each other":"Select the first item that you want, hold down  COMMAND , and then select any additional items",
        "Select one character to the right":"Shift + Right arrow",
        "Select one character to the left":"Shift + Left arrow",
        "Select one word to the right":"Shift + Option + Right arrow",
        "Select one word to the left":"Shift + Option + Left arrow",
        "Select to the end of a line":"COMMAND + Shift + Right arrow or Shift + End",
        "Select to the beginning of a line":"COMMAND + Shift + Left arrow or Shift + Home",
        "Select one line down":"Shift + Down arrow",
        "Select one line up":"Shift + Up arrow",
        "Select to the end of a paragraph":"COMMAND + Shift + Down arrow",
        "Select to the beginning of a paragraph":"COMMAND + Shift + Up arrow",
        "Select one screen down":"Shift + Page Down",
        "Select one screen up":"Shift + Page Up",
        "Select to the beginning of a document":"COMMAND + Shift + Home",
        "Select to the end of a document":"COMMAND + Shift + End",
        "Select to the end of a window":"Option +  COMMAND + Shift + Page Down",
        "Select to select the entire document":"COMMAND + A",
        "Select to a vertical block of text":"COMMAND + Shift + F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Select to a specific location in a document":"F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Select the next cell's contents":"Tab",
        "Select the preceding cell's contents":"Shift + Tab",
        "Extend a selection to adjacent cells":"Hold down Shift and press an arrow key repeatedly",
        "Select a column":"Click in the column's top or bottom cell. Hold down Shift and press the Up arrow or Down arrow key repeatedly",
        "Extend a selection (or block)":"COMMAND + Shift + F8 , and then use the arrow keys; press Esc to cancel selection mode",
        "Reduce the selection size":"Shift + F8",
        "Select multiple cells, columns, or rows that are not next to each other":"Select the first item that you want, hold down  COMMAND , and then select any additional items",
        "Extend select - Turn on extend mode":"F8",
        "Extend select - Select the nearest character to the left":"F8, Left arrow",
        "Extend select - Select the nearest character to the right":"F8, Right arrow",
        "Extend select - Expand a selection":"Press F8 repeatedly to expand the selection to the entire word, sentence, paragraph, section, and document.",
        "Extend select - Reduce the size of a selection":"Shift + F8",
        "Extend select - Turn off extend mode":"Esc",
        "Edit - Copy text or graphics":"COMMAND + C or F3",
        "Edit - Copy a style":"COMMAND + Shift + C",
        "Edit - Paste a style":"COMMAND + Shift + V",
        "Edit - Copy text or graphics to the Scrapbook":"Control + Option + C",
        "Edit - Cut selected text to the clipboard":"COMMAND + X or F2",
        "Edit - Move text or graphics":"COMMAND + X or F2 (then move the cursor and press  COMMAND + V or F4 )",
        "Edit - Create AutoText":"Option + F3",
        "Edit - Insert AutoText":"COMMAND + Option + Shift + V",
        "Edit - Paste the Clipboard contents":"COMMAND + V or F4",
        "Edit - Paste special":"COMMAND + Control + V",
        "Edit - Paste and match the formatting of the surrounding text":"COMMAND + Option + Shift + V",
        "Edit - Paste the Spike  contents":"COMMAND + Shift + F3",
        "Edit - Delete one character to the left":"Delete",
        "Edit - Delete one word to the left":"COMMAND + Delete",
        "Edit - Delete one character to the right":"COMMAND or Clear",
        "Edit - Delete one word to the right":"COMMAND +  COMMAND",
        "Edit - Cut selected text to the Clipboard":"COMMAND + X or F2",
        "Edit - Undo the last action":"COMMAND + Z",
        "Edit - Redo the last action":"COMMAND + Y",
        "Edit - Cut to the Spike":"COMMAND + F3",
        "Center a paragraph":"COMMAND + E",
        "Justify a paragraph":"COMMAND + J",
        "Left-align a paragraph":"COMMAND + L",
        "Right-align a paragraph":"COMMAND + R",
        "Indent a paragraph from the left":"Control + Shift + M",
        "Remove a paragraph indent from the left":"COMMAND + Shift + M",
        "Create a hanging indent":"COMMAND + T",
        "Remove a hanging indent":"COMMAND + Shift + T",
        "Start AutoFormat":"COMMAND + Option + K",
        "Apply the Normal style":"COMMAND + Shift + N",
        "Apply the Heading 1 style":"COMMAND + Option + 1",
        "Apply the Heading 2 style":"COMMAND + Option + 2",
        "Apply the Heading 3 style":"COMMAND + Option + 3",
        "Apply the List style when the cursor is at the beginning of a line":"COMMAND + Shift + L",
        "Insert a nonbreaking space":"Option + Spacebar",
        "Set lines as single-spaced":"COMMAND + 1",
        "Set lines as double-spaced":"COMMAND + 2",
        "Set lines as 1.5-line spacing":"COMMAND + 5",
        "Add or remove one line of space directly preceding a paragraph":"COMMAND + 0 (zero)",
        "Format - Change the font":"COMMAND + Shift + F",
        "Format - Increase the font size":"COMMAND + Shift + >",
        "Format - Decrease the font size":"COMMAND + Shift + <",
        "Format - Increase the font size by 1 point":"COMMAND + ]",
        "Format - Decrease the font size by 1 point":"COMMAND + [",
        "Format - Change the formatting of characters (Font command, Format menu)":"COMMAND + D",
        "Format - Change the case of letters":"Shift + F3",
        "Format - Format in all capital letters":"COMMAND + Shift + A",
        "Format - Apply bold formatting":"COMMAND + B",
        "Format - Apply an underline":"COMMAND + U",
        "Format - Underline words but not spaces":"COMMAND + Shift + W",
        "Format - Double-underline text":"COMMAND + Shift + D",
        "Format - Apply italic formatting":"COMMAND + I",
        "Format - Format in all small capital letters":"COMMAND + Shift + K",
        "Format - Apply subscript formatting (automatic spacing)":"COMMAND + Equal sign",
        "Format - Apply superscript formatting (automatic spacing)":"COMMAND + Shift + Plus sign",
        "Format - Apply strike-through formatting":"COMMAND + Shift + X",
        "Insert an empty field":"COMMAND + F9",
        "Special Chars - Insert a line break":"Shift + Return",
        "Special Chars - Insert a page break":"COMMAND + Enter",
        "Special Chars - Insert a column break":"COMMAND + Shift + Return",
        "Special Chars - Insert a nonbreaking hyphen":"COMMAND + Shift + Hyphen",
        "Special Chars - Insert the copyright symbol":"Option + G",
        "Special Chars - Insert the registered trademark symbol":"Option + R",
        "Special Chars - Insert the trademark symbol":"Option + 2",
        "Special Chars - Insert an ellipsis":"Option + Semicolon",
        "Special Chars - Insert a DATE field":"Control + Shift + D",
        "Special Chars - Insert a LISTNUM field":"COMMAND + Option + Shift + L",
        "Special Chars - Insert a PAGE field":"Control + Shift + P",
        "Special Chars - Insert a TIME field":"Control + Shift + T",
        "Special Chars - Insert an empty field":"COMMAND + F9",
        "Fields - Update selected fields":"F9",
        "Fields - Unlink a field":"COMMAND + Shift + F9",
        "Fields - Switch between a field code and its result":"Shift + F9",
        "Fields - Switch between all field codes and their results":"Option + F9",
        "Fields - Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"Option + Shift + F9",
        "Fields - Go to the next field":"F11",
        "Fields - Go to the previous field":"Shift + F11",
        "Fields - Lock a field":"COMMAND + F11",
        "Fields - Unlock a field":"COMMAND + Shift + F11",
        "Outline - Promote a paragraph":"Control + Shift + Left arrow",
        "Outline - Demote a paragraph":"Control + Shift + Right arrow",
        "Outline - Demote to body text":"COMMAND + Shift + N",
        "Outline - Move selected paragraphs up":"This keyboard shortcut conflicts with a default Mission Control key. To use this Office keyboard shortcut, you must first change the Mission Control shortcut for this key. On the Apple menu, click System Preferences > Mission Control. Under Keyboard and Mouse, choose another shortcut for Mission Control, or choose – (minus sign) to turn it off.",
        "Outline - Control + Shift + Up arrow":"Move selected paragraphs down",
        "Outline - This keyboard shortcut conflicts with a default Mission Control key. To use this Office keyboard shortcut, you must first change the Application windows shortcut for this key. On the Apple menu, click System Preferences > Mission Control. Under Keyboard and Mouse, choose another shortcut for Application windows, or choose – (minus sign) to turn it off.":"Control + Shift + Down arrow",
        "Outline - Expand text under a heading":"Control + Shift + Plus sign",
        "Outline - Collapse text under a heading":"Control + Shift + Minus sign",
        "Outline - Expand all body text and headings or collapse all body text":"Control + Shift + A",
        "Outline - Show the first line of body text or all body text":"Control + Shift + L",
        "Outline - Show all headings with the specified heading level":"Control + Shift +<Heading level>",
        "Review - Insert a comment":"COMMAND + Option + A",
        "Review - Turn track changes on or off":"COMMAND + Shift + E",
        "Review - Go to the beginning of a comment":"Home",
        "Review - Go to the end of a comment":"End  (The End key is not available on all keyboards)",
        "Review - Go to the beginning of the list of comments when in the Reviewing Pane":"COMMAND + Home",
        "Review - Go to the end of the list of comments when in the Reviewing Pane":"COMMAND + End",
        "Print a document":"COMMAND + P",
        "Table - Move to the next cell":"Tab (If the cursor is in the last cell of a table, pressing Tab adds a new row)",
        "Table - Move to the preceding cell":"Shift + Tab",
        "Table - Move to the preceding or next row":"Up arrow or Down arrow",
        "Table - Move to the first cell in the row":"Control + Home",
        "Table - Move to the last cell in the row":"Control + End",
        "Table - Move to the first cell in the column":"Control + Page Up",
        "Table - Move to the last cell in the column":"Control + Page Down",
        "Table - Start a new paragraph":"Return",
        "Table - Add a new row at the bottom of the table":"Tab at the end of the last row",
        "Table - Add text before a table at the beginning of a document":"Return at the beginning of the first cell",
        "Table - Insert a row":"COMMAND + Control + I",
        "Table Resize by ruler - Move a single column line":"Shift",
        "Table Resize by ruler - Equally resize all columns to the right":"COMMAND + Shift",
        "Table Resize by ruler - Proportionally resize all columns to the right":"COMMAND",
        "Table Resize directly - Move a single column line":"",
        "Table Resize directly - Retain column sizes to the right":"Shift",
        "Table Resize directly - Equally resize all columns to the right":"COMMAND + Shift",
        "Table Resize directly - Proportionally resize all columns to the right":"COMMAND",
        "Table - Insert a new paragraph in a cell":"Return",
        "Table - Insert a Tab character in a cell":"Option + Tab",
        "Insert a footnote":"COMMAND + Option + F",
        "Insert an endnote":"COMMAND + Option + E",
        "Paragraph direction to right to left":"Control +  COMMAND + Left arrow",
        "Paragraph direction to left to right":"Control +  COMMAND + Right arrow",
        "Undo the last action":"F1",
        "Cut selected text or graphics":"F2",
        "Copy selected text or graphics to the clipboard":"F3",
        "Paste the Clipboard contents":"F4",
        "Choose the Go To command (Edit menu)":"F5",
        "Open the Spelling and Grammar dialog box":"F7",
        "Extend a selection":"F8",
        "Update selected fields.":"F9",
        "Go to the next window":"COMMAND + F6",
        "Copy selected text":"Shift + F2",
        "Change letters to uppercase, lowercase, or mixed case":"Shift + F3",
        "Repeat a Find or Go To action":"Shift + F4 or COMMAND + Shift + F4",
        "Move to the previous insertion point":"Shift + F5",
        "Open the Thesaurus pane":"Shift+ F7",
        "Shrink a selection":"Shift+ F8",
        "Switch between a field code and its result.":"Shift + F9",
        "Go to the previous field":"Shift + F11 (confilcts with default Mission Control key)",
        "Cut the selection to the Spike":"COMMAND + F3",
        "Close the window":"COMMAND + F4",
        "Go to the next window":"COMMAND + F6",
        "Insert an empty field":"COMMAND + F9",
        "Lock a field":"COMMAND + F11",
        "Insert the contents of the Spike":"COMMAND + Shift + F3",
        "Edit a bookmark":"COMMAND + Shift + F5",
        "Update linked information in a Word source document":"COMMAND + Shift + F7",
        "Extend a selection as a block selection":"COMMAND + Shift + F8, an arrow key",
        "Unlink a field":"COMMAND + Shift + F9",
        "Unlock a field":"COMMAND + Shift + F11",
        "Create an AutoText entry":"Option + F3",
        "Find the next misspelling or grammatical error":"Option + F7",
        "Run a macro":"Option + F8",
        "Switch between all field codes and their results":"Option + F9",
        "Look up selected text on the Internet":"COMMAND + Shift + L",
        "Run GOTOBUTTON or MACROBUTTON from the field that displays the field results":"Option + Shift + F9"
    },
    "Safari":{
        #https://support.apple.com/en-jo/guide/safari/keyboard-and-other-shortcuts-cpsh003
        #https://www.lifewire.com/keyboard-shortcuts-for-safari-in-mac-446554
        #https://support.apple.com/en-jo/guide/safari-developer/keyboard-shortcuts-reference-dev654e5967f
        "Scroll up, down, left, or right":"Press the arrow keys",
        "Scroll in larger increments":"Press Option while you press an arrow key",
        "Scroll down a screen":"Page Down or Space bar",
        "Scroll up a screen":"Page Up or Shift–Space bar",
        "Scroll to the top-left corner of the page":"Command–Up Arrow or Home",
        "Scroll to the bottom-left corner of the page":"Command–Down Arrow or End",
        "Highlight the next item on a webpage":"Tab ",
        "Highlight the same items as Tab plus all other clickable items":"Option-tab",
        "Show all tabs":"Shift-Command-\\",
        "Open a page in a new tab":"Command-click a link ",
        "Open a bookmark in a new tab":"Command-click a bookmark ",
        "Open a page in a new tab in Smart Search field":"Command-Return after typing",
        "Open a page in a new tab, and make that tab the active tab":"Shift-Command-click a link",
        "Open a bookmark in a new tab, and make that tab the active tab":"Shift-Command-click a bookmark",
        "Open a page in a new tabn Smart Search field, and make that tab the active tab":"Shift-Command-Return after typing in the Smart Search field",
        "Make the next tab the active tab":"Control-Tab or Shift-Command-]",
        "Make the previous tab the active tab":"Control-Shift-Tab or Shift-Command -[",
        "Select one of your first nine tabs":"Command-1 to Command-9",
        "Close all tabs except for one":"Option-click the close button  on the tab you want to leave open",
        "Reopen the last tab or window you closed":"Shift-Command-T",
        "See a list of your recently visited pages by name":"Hold down the Back or Forward button until the list appears",
        "See a list of your recently visited pages by web address (URL)":"Press Option and hold down the Back or Forward button until the list appears",
        "Go to your homepage":"Command-Home key",
        "While typing in the Smart Search field, restore the current webpage address":"Esc",
        "Close Reader":"Esc",
        "Exit full-screen view":"Esc",
        "Download a linked file":"Option-click a link to the file",
        "Open a downloaded file":"Double-click the file in the downloads list",
        "Zoom website content":"Press Command-Plus Sign (+) or Command-Minus Sign (-)",
        "Zoom website text":"Press Option while you choose View > Make Text Bigger or View > Make Text Smaller",
        "Show or Hide the Reading List sidebar":"Control-Command-2",
        "Add the current page":"Shift-Command-D",
        "Add a linked page":"Shift-click a link to the page",
        "Remove a page":"Control-click the page summary in the sidebar, then choose Remove Item",
        "Add a bookmark to the Favorites bar":"Click the Smart Search field to show the page’s full address and its icon, then drag the icon to the Favorites bar",
        "Open all bookmarks from a folder in the Favorites bar":"Command-click the folder in the Favorites bar",
        "Move a bookmark on the Favorites bar":"Drag the bookmark left or right",
        "Remove a bookmark from the Favorites bar":"Drag the bookmark off the top of the bar",
        "Show or Hide the Bookmarks sidebar":"Control-Command-1",
        "Select bookmarks and folders in the sidebar":"Command-click each bookmark and folder",
        "Extend selection of bookmarks and folders in the sidebar":"Shift-click",
        "Select the next bookmark or folder":"Up Arrow or Down Arrow",
        "Open the selected bookmark":"Space bar",
        "Open the selected folder":"Space bar or Right Arrow",
        "Close the selected folder":"Space bar or Left Arrow",
        "Change the name or address of a bookmark":"Select the bookmark, then press Return",
        "Cancel editing a bookmark name in the sidebar":"Esc",
        "Finish editing a bookmark name":"Return",
        "Create a folder containing the selected bookmarks and folders in bookmarks view":"Option-click the New Folder button near the top-right corner",
        "Delete a bookmark":"Select the bookmark, then press Delete",
        "Go back":"COMMAND + [ ",
        "Go forward":"COMMAND + ] ",
        "Download a file":"OPTION + Link on a web page ",
        "Select all":"COMMAND + A ",
        "Show/Hide Favorites":"COMMAND + SHIFT + B ",
        "Copy":"COMMAND + C ",
        "Add a Bookmark":"COMMAND + D ",
        "Find":"COMMAND + F ",
        "Hide Safari":"COMMAND + H ",
        "Advance to selection":"COMMAND + J ",
        "Open location":"COMMAND + L ",
        "Minimize":"COMMAND + M ",
        "Open new window":"COMMAND + N ",
        "Open file":"COMMAND + O ",
        "Print":"COMMAND + P ",
        "Quit Safari":"COMMAND + Q ",
        "Reload page":"COMMAND + R ",
        "Save As":"COMMAND + S ",
        "Open a new tab":"COMMAND + T ",
        "Paste":"COMMAND + V ",
        "Close":"COMMAND + W ",
        "Undo":"COMMAND + Z ",
        "Add To Reading List":"COMMAND + SHIFT + D ",
        "Redo":"COMMAND + SHIFT + Z ",
        "Resources":"COMMAND + OPTION + A ",
        "Show all Bookmarks":"COMMAND + OPTION + B ",
        "Google Search":"COMMAND + OPTION + F ",
        "Downloads":"COMMAND + OPTION + L ",
        "Load the nth bookmark in Bookmarks Toolbar":"COMMAND + NUM [1-9]",
        "Load Safari Help":"COMMAND + ? ",
        "Load Preferences":"COMMAND + , ",
        "Local search within the currently selected resource in the tab":"Command-F",
        "Select next in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"Shift-Command-] or Ctrl-Tab",
        "Select previous tab in Web Inspector. Make sure Web Inspector is undocked for this feature to work":"Shift-Command-[ or Ctrl-Shift-Tab",
        "Find Next":"Command-G",
        "Find Previous":"Command-Shift-G",
        "Puts the selected text in the system search pasteboard, which is used by the Find dialog as the default search text":"Command-E",
        "Brings up the “Go To Line Number” dialog":"Control-G (in text editor)",
        "Brings up the Quick Open dialog, a feature that allows you to quickly search for a file in Web Inspector":"Command-Shift-O",
        "Zoom-in, makes Web Inspector’s interface larger":"Command-+",
        "Zoom-out, makes Web Inspector’s interface smaller":"Command- -",
        "Open Settings":"Command- ,",
        "Reset changes to Web Inspector’s interface size":"Command-0",
        "Save all console messages to a text file in the Console tab. Save current web content into a .webarchive file in the Elements tab. When showing a resource, it saves the resource to disk":"Command-S",
        "Forces the Save As… dialog":"Shift-Command-S",
        "Toggle between previous Web Inspector position, detached and docked":"Shift-Command-D",
        "Shifts focus to the search bar":"Shift-Command-F",
        "Enter element selection mode":"Shift-Command-C",
        "Focus the Split Console at the bottom of the tabs. Click again to enlarge the console":"Escape",
        "Focus on the console prompt. Unlike Esc, it does the same thing regardless of the context":"Control-~",
        "Show/Close Web Inspector":"Command-Option-I",
        "Show Error Console":"Command-Option-C",
        "Start Profiling JavaScript":"Shift-Command-Option-P",
        "Next Console Suggestion":"Tab",
        "Previous Console Suggestion":"Shift-Tab",
        "Accept Console Suggestion":"Right",
        "Previous Command/Line in Console":"Up",
        "Next Command/Line in Console":"Down",
        "Clear Console History":"Command-K (when in Console tab)",
        "Clear Network Items":"Command-K (when in Network tab)",
        "Execute Console Command in Console tab. Edit attribute in Elements Panel when element is selected":"Return",
        "Continue in Debugger":"Command-/",
        "Step Over in Debugger":"Command-’",
        "Step Into in Debugger":"Command-;",
        "Step Out in Debugger":"Shift-Command-;",
        "Show/hide status bar":"Command-/",
        "Show/hide sidebar":"Command-shift-L",
        "Enter full-screen":"Command-ctrl-f",
        "Open profiles":"Command-O",
        "Show toolbelt":"Command-shift-B",
        "Save work arrangement":"Command-shift-S",
        "Password manager":"Command-option-F",
        "Expose All Tabs":"Command-option-E",
        "Move tab right":"Command-shift-option-]",
        "Move tab left":"Command-shift-option-[",
        "Empty Caches":"Command-option-E",
        "Go to home page":"Command-shift-H",
        "Show history":"Command-Y",
        "Autofill form":"Command-shift-A",
        "Toggle page source":"Command-Shift-U",
        "Toggle web insepector":"Command-Shift-I",
        "Toggle JavaScript console":"Command-Shift-C",
        "Start/stop time line recording":"Command-shift-option-T",
        "Start/stop element selction":"Command-shift-C",
        "Open first-ninth tab":"Command-[1-9]"
    }
}

import collections

def convert(data):
    if isinstance(data, basestring):
        return data.decode('utf-8').strip()
    elif isinstance(data, collections.Mapping):
        return dict(map(convert, data.iteritems()))
    elif isinstance(data, collections.Iterable):
        return type(data)(map(convert, data))
    else:
        return data

shortcuts = convert(shortcuts)

import cPickle
output = open('default_cheatsheet.pkl', 'wb')
cPickle.dump(shortcuts, output)
output.close()

